>gnl|BL_ORD_ID|14505 @F.cylindrus_GMF2@jgi|Fracy1|163202|gw1.2.1698.1
-----------RMLFL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------DGILQSESSSEREYHEALVHAGMFS--HAD
PKR--VAIVGGAEGATLREVLKHKTVESVTMVEIDQELIDITKTYMPFMSDCIDYVGRSD
NCFDDPVLDLVVEDAKEWFMDRSNKADKQEKFDVVIVDAMEPEASSAIS----KDLYDTA
HLEA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------ILNTLTD------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------EGIMI-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------IQIGRA----------------------------------
-----------------------
>gnl|BL_ORD_ID|1453 @P.tricornutum@gi|219115513|ref|XP_002178552.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MLP---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------DGPLSVIDLA--
-------------------------------------------EILEEKP----------
------------------------------------------------------------
--VSVIKFLMTDLGVMASMTQNLDSA---------------TCVAVAEGFGKIGLEESAL
ATGVVFDE----------------------------------------------------
-------------------DDPADLKP----------RAPVVTIMGHVD--HGKTSLL--
-----DTIRKTQ---VTAGEAGGITQHIAAYQVTRNDQTITFVDTPGHAAFTD-------
-MRERGANITDIIVLVVAADDGVKQQTADSIACA--------------------------
-------------RQAGVPLIVAINKCDLETADPTK--VMTELTSYDV-LTEEFGGDVLS
SQISAKKGTNIDDL----------------LDKIM---LQAEIQDIKANP-DRD----AE
CIVVEANVEKGLGTVATT------------LVQKGTLRVGDVFVAGETHGKVRA--LLST
SNN--D----------------RMKEVGP-------STPVRVV-----------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GFEGVPCAGDVLIVA
KDEQTA--REMAENRQ-------------RIAREKSSSSYQAGLMDSVAMTFGAVKESRE
M-------------------------------------------CVVVKADVQ-------
---GSAEALTRALRDLKREDDQAIVTVKVLVSEAGEVSKSDIAIA----SVTPDTTVI--
--AFNIPASFAAMED-----SRVTGVPIEYYN--------IIYDAIESVE----SRMQEV
LSPTPEGEYVGS------------------------------------------------
-------------------------------------AKVQEVFNIGGTGNIAGSRCTNG
FLKKGANVRVMRGDKILIESRIKTL--RNFKAETDSIEEGNECGIGLLDFEAFEPDDVIE
-------------------CYVE
>gnl|BL_ORD_ID|24856 @T.oceanica@gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------FGIRRLVVGGSVRHGGHARGR-
-----PLPC---------------------------------------------------
------------------------------------------------------------
----------------------------------------PACPTG--------------
-----------------------------------------------------------P
DISSSASSLLSRTMTSYFDGGPSAP-----------ETSRPKQQRR--LDIAIVGAPNAG
KSQLLNSLVGSKVAAVSRKRHTTRSGILGARTFGDTQLVFIDTPGFLHHSKGAREGVRNL
LSEASAE-----MMNADFALLVVDAAKTIDQDLKRTLVTLMMLALRSTGREEGSRVFSDQ
RHLGRFSVVLNKVDLVKPKEKLLATAAE---------------VGSLAESCVRRLLQQHR
APVRVKM----GELVDSVLERHEDE------EGFAGVHEEDYETFASVVPEFLFTSAIDP
EDEGA---DDLLNVLLSRATPSTEFVMDPSS--NLEQVEEIIREKIYRCLHREVPHHVQQ
TNRVFKLKQDQPPDHDVRADMGDLLQIHQDLIVRTKSHHRLVLGSGGKTLQ---RIQTTA
SKDLRELFGCEVDLLLSVKLKKTNQGVLLDPEEEGA-------RITTLHD----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|14494 @T.oceanica@gi|397643422|gb|EJK75853.1| hypothetical protein THAOC_02405 [Thalassiosira oceanica]
M-------------------KGSIRMAHVGALMMFATTACRGFRRSS-------------
------------------------------------QSATPKSTNRHITVLSQYCGIRD-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------EVRRRNLIVGPSLQTVASRRRRA
TARLGPLHTPLQSTLYDLEEKESTASTSDEDTVFALSSGSGVTAVAVIRISGRNAFDALK
QLLSPYS-LEAGAEPPKLPTPRMASLRILYDPLSSSDHLNRMRDPLD---------SALV
LIFPGPRSFTGEDIVELHCHGSRAVTSGVLKALSSLDSVRPADPGEFTQRAYGNGKLGLV
EVEALADLIVADTSLQRKQALQQFDGRLSRLYLGWRKELIKGLAHAEAVIDFGDDEALGE
EDSSFDSSENDGGMSVWADVRPRISSLREAMDRHLEDASRG-ELLRDGLRIAIVGRPNAG
KSSLLNLLAGRDAAIVSSTPGTTRDVVEVVLDLDGVRCSLLDTA-------GVREEIEDG
VDEIEIEGMKRARLAAQEAHLIVGVVDCSDQ--KRGLEAVQEL-IRADGHSDSARSSPHN
NLL----YVLNKRDLFEGEMEPCGVDSETFAISCTTNQGVDIFLAALSKRALAMISQEGD
SSGDLSVVGTEGAVITRARHRRHVEAASDALQRFEVLSSQGYMALDMAAEELRLASSELG
RVTGAIDVEDVLDVLF--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------ADFCIGK------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|410 @T.pseudonana@gi|224010381|ref|XP_002294148.1| predicted protein [Thalassiosira pseudonana CCMP1335]
MKRASLKKIFSKKGAMSPKTPNDDNDSPGGVWGELVTQGSGRNSLTPVKSPGSVGSRGSS
SIGGGGNKTPLASNVGGSHRRNLKSPSLPPLSSHQSSSSFNSLSNYNDGNDTSDMDKLSS
LHFSSSTSNNTSYHSTNTTNDKKGK-GKSRRFPLQHYSSASAVDLDAPIESYTGPVDLDE
SLVSDNDSLGGSLSGDTADGGGSKCEVGGSSALGDVPRSWSEEESSPPLKPPANAATSTN
TAHVSDLPLTNP-----------YTNDETMNEDSHDEYDDDDDDDDSTHSGISIEQMKS-
GESSIMAMSVDESEVGGNNYIHGSIGRWNRYNPDN---------------------NSSS
SNGIRNNSSNSLSESRSSKHGSSFNRIETDDSALDDEDYYKQ------DYYLPSTSKSLS
ERVLMNDGTTRRLTSREVLE-----MTEPTLPVGEEGGVKILGED---LEEGGDYGDF--
---------YNDTEFPVVGVSGDGEEGVHQYERSDDDGDSTADVDDVVMDDGNDEQPSQD
IIEQPVPVLPDDEEFEEVDNNDAGGDVVENANMAEASAAGTNDDVLVETGSDIGD-----
IMLSDDEADSVVKESVAEDFDVAEEENSIAVGASAEEVKVDHITNDSEHEAEQYDLSESE
DVTN--------NILDDKEEFSIDREQPDDSISVESQHVVPESVNDEPDETEKFSLDGVQ
SDDNDSLPSATR--EVR--------EADDARIPSVAEGPDASEEFSLDGEPSDGD--GGN
IVQIDDNERD--------GSNEDCKSPTIELVRSSSDIDS-PPHMTSPDGLSPRRHSLGS
MYVNHNVQPEPTPKKTPHKEVTDNLMAMGVMSLFMGGG----------------------
--GLGRSSKKKTPMKT-RPSESDGEMSAN-----------TMKPLTEEHVLKEESPGLWS
VPSLASP-------SSPSPAVNKA-------SSALSTRDDAAVTPEAG------------
--------KSMLAQFDEEMSEEKEVEVDESTVEQLQQFTKAEAIKSFSSQLSVGLKAEIG
QSNERNT-------------DETTQPLAIETTVNE---SFAAEPTPRTSHKTASDDKE-K
GSSRNGT---CSPLPLLFCRSDSDEHEDPTSPLSLVSRSADLFEGVARLPQLDETNVTDQ
PPQSPRSPMKDYMTLNLPVS-----PTNSKAESIESMFPDFPHDVN--------------
-KIIRENRRLRVKRQQLCESLSSMAQQ---FAAHESTSSEKIFSLEQK------IQALVA
EKEQSVIAPASYDGETVRRLSSGVLNQEKQLESKDMQISQLKLRCEVLKRTLHDKEEDHH
QNKKLWDDERKRLVERLHNHISSPERQGHLT---LRRELLEAKMECARYKKDLDNAISDI
NALTEALETNNEALDKSVAELEKLRKWKSEHD---NATTDDAIDEPPTISRTSLPTLSYS
PSKMSSSSLPNSPYDANWEQSDHRDESTDTQSVLMHEKDEEIAQLQRDLESSLNELDALR
ELAVPATQREYHDL-QNEVQLLQNEAKASRLEAKLANDRIAQILEKKRDEPDAGIHESKG
IDNDESTMQKARRLELEMASTASSSKIAQLESELEAKRAEIDQLRATVASKDSDIAGLRI
AAETVSVFTSIEDEKVASEKTKSLEDKIASLEQKLTEYERGGEDKEDPEV---------L
ASDDNPVPDD----GNDNDEDKGPKDNIASILSPKSKNDETEVAQDGELTSNSTGESSKV
AASPLQGRRLFQLHRGWKTSPPLNRNTNSEPSGDLLREHEAKIAELDATVKANIEVMEKL
KRDIVRIQSEREEADFVSAKKIETLLEENTTYALQVSELEKLF-------MTLNAERISD
ASAVNDPVDDDEKEKYMVVADDGDLSDDGSAAVSAADVSQSAQSEKTAATQENANLRTKN
MALQRTVEELENSRSFQEDQIEQLKIELVKLRVSFQQEKDLALEDLQNEVAIVTSQRSAL
ENQLVEINKSAGLLRQSLADQSPNSYKRTDPSGSNELSTPKSPGNDGVAGDDPVLVAQVV
MLENANRVLESQVNSLRSDMQQKLAPLLERIALLEEEKRISEDEMNAKLECREMTITNLE
NSLQQMTSSRLSGSAKKKRQSKMSSPLKKSISKGDPNKDSAEER
>gnl|BL_ORD_ID|11386 @F.cylindrus_GMF1@jgi|Fracy1|187133|e_gw1.7.947.1
----------MFKNAVLFPQRRARTWLWNNSNTTTDACRANLSY----------------
------------------------AIERCCSSSSSSSSSQSQSQSQSQSQSTLQQSPSTI
GRKRLDVAIVGAPNAGKSQLVNILT-QSPVAAV---SRKRHTTRSDILGARTIGNTQIVF
KDTPGF---------------------MRIENAKEERLDRDLIA-TAASEMQDVDFTLLV
IDSA---------RALSENYRHAD-------------------------------DDANP
NSNDGRGKFAIVLNKVDLVKPKSTLIDLAME------------IGAIADTCLEDHFTEHG
KTID---FEAMLE---HSPIVFYVSALKEDGTDDLLDHLINLATPCKE------------
-------------------WAVQSGQSTNMTELEQVQEIIREKIYRTCHREV-------P
HSVQ----QVNRMFRKIPKKGVIIHQDLVVF----TKSHQKLVLGAGGRTLERIRESAQT
------DLRKMFKCE-VSLHLHVKKKIG---------------RRGDSGTEYKLGEASQT
IL---
>gnl|BL_ORD_ID|17946 @F.cylindrus_GMF1@jgi|Fracy1|190835|e_gw1.11.594.1
----------------MNTNTTTITNVNNDDHQQQHRCG----Y----------------
------------------------------------------------------------
------AGIVGAPNMGKSTLLNSLL-KEDLCIA---TRRPQTTRHAILGVLSSPTKQCCL
LDTPGV---------------------LQGDGAYQ----------LQANMMEAVKGALTD
SDMI---------VVVTDLFSTPI-------------------------------PDD--
-------------NVFRRLSETTKPVLVVVN---------------------KIDLEGRA
KRPD----EATIQ---RRPI---PG-MFRNGVKSLTNDDVKQLLPIGPPLYDDD------
------------------FLSDRSVRFFC-------SELIREALLESRYLKKEL-----P
YCC-----EVQITDYKEPRDDNITRIEATIF--VERDGQKAIIIGKNGDVVKQVGIIARE
------KIERFLDGEKVFLQLRVKINKD---------------WRKREDQLAKFGYSN--
-----
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3128 _gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
-----MDSETPTKNEAEQRASPDRTGQVTQRPVSLFRKNGTFAY----------------
------------------------PLEDSDVYEEQVLALEDVPEPTAQAILRLALAAERQ
GVPRLRFLVVGAPGVGKSSLINTLL-NENLCSV---SAWERGTKNAQVCARQVDSVVIEF
IDTPGIAPCRRSGLEASRRQVQRLRKLLDARGADEHPYLRSFHAILYVMRLDDTRPDLVD
YHNW---------KVLMEFFGAEVL----------------RHMMVVFTHGQSLPPDSLS
YPEYVRGRRDYVYLLIERLTGPLKAVRFPVF------------VAENSSKCPVIEETGER
KLPDDTPWITQLYDGIRRFVFPLEADLFGMETGPEDTQVLVYIYDKRRSRADER------
------YPRSPLQALIRNPWFLRAVQFCG-------AMLLRSYMIRQEHERFNPKPHHPE
PIIR----DANNAFAVASRRANDHRLFTPSI---DEDEESFFRMNGNDDFVSRLRNRPGE
VDLDELDVERIESPDGRFVEYWYTEKDNPEMVRMYRLEIRDDPNEERESRQDRIPISKDQ
H----
>gnl|BL_ORD_ID|25599 @F.cylindrus_GMF1@jgi|Fracy1|214794|estExt_Genewise1Plus.C_700009
----------MSEDIVAEFSS---------------KAGGGYNR----------------
------------------------PGVQWYP-----------------------------
----------GHIAKAERQLSETLK-AVDVVVEVRDARACKATSHPRVGEWCAGRPRIVV
LTHLDMIP-------------------KAAANSWRKAYEK-----FGAEDMDDAPIN---
-RQV---------LFVNAKQGQGI--------------------------------HALH
RAIFKAGSHVQERRERRGLNP--RALRVGIIGYPNVGKSALINKILGRKRAKTANTPGVT
RSLQ---WIREFE------LLDSPGIIPAKMVDQSDALLLAACNCIGQAAYDNQAVAAYL
YEWLKAVYLMDKQALTAPNWRDKCIDRYGFDPLEKVQRDEDDIVQDEYLTGEDMLFKVAD
DLCRGDAEDAARKMLQDFRQGRMGPISLQMAPESEEDGGMLSVSVGDGTILGRQSMRGSE
NGGFDAEYQQQIQDERARIALETAKERG-----LELPPIVDDPERAKEEAEADVGKGMFD
GW---
>gnl|BL_ORD_ID|22594 @F.cylindrus_GMF1@jgi|Fracy1|214636|estExt_Genewise1Plus.C_650061
MAPKYQNKTKRRENAIPRTGASSKIGKGRDNAKGGHRSAETIKRLNLYKSRAIRNKKGTI
IGGDFMMGDRAGDRDITGETGRIAPDRRWFGNTRVVDPKQLDTFRQEMTEKVADPYSVVL
KRKKLPMGLLREAAEREAPPSQALLGQEPFSQVFGSKSRRKKVKLDQLMLARSDVDPNKD
EDEDGAPIKKGGRAE------------VKADLFNKGQSKRIWGEFFKVVDCSDVVLHIID
ARNVPGTRCNMIERHIRDNASHKHLVFVLNKIDLVPNWVAKRWMGELAKDRPTIAFHASM
THAFGKGALISLLRQFGKLHGDKKQISVGVIGYPNVGKSSVINTLISQKSCKVAPIPGET
KIWQ---YITLFK---RISLIDCPGVVVDTAGDTETESVLKGVVRAERLETPED------
----------FIQPIVDMVKREHIAGQYKFTKEESNKWTTPTELLETIATKAGRLLKGGE
PCLR----SASITMINDFQRGRLPHFVAPPELKEDDVEENQGNMGGSTAVIEGVKPEAQE
LD----KIGEENTKSDGTVDGESDQKEG--------------KETGSSGVVADEPVAIAE
GEWDD
>gnl|BL_ORD_ID|12642 @F.cylindrus_GMF2@jgi|Fracy1|187133|e_gw1.7.947.1
MFK---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------NAVLFPQRRARTWLWNNSNTTT----
------------------DACRANLSYAIERCCSSSSSSSSSQSQSQSQSQSQSTLQQSP
STIGR-KRLDVAIVGAPNAGKSQLVNILTQSPVAAVSRKRHTTRSDILGARTIGNTQIV-
------FKDTPGFMRIENA-----KEERLDRDLIATAASEMQDVDF-----------TLL
VIDSARALSENYRH----------------------------------------------
---------------ADDDANPNSNDGRGKFAIVLN--KVDLVKPKSTLI--DLAMEIGA
IADTCLEDHFTEHGKTIDFEAMLEHS----PIVFYVSALKEDGTDDLLDHLINLATPCKE
WAVQSGQSTNMTELEQVQEII---REKIYRTCHREVPHSVQQVNRMFRKIPKKGVIIHQD
--------------------------LVVFTKSHQKLVLGAGGRTLERIRESAQTDLRKM
FKCEVS-------------------------LHLHVKKKIGRRGDSGTEYKLGEASQTIL
>gnl|BL_ORD_ID|12349 @F.cylindrus_GMF2@jgi|Fracy1|189577|e_gw1.9.1105.1
MNT---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------NTTTITNVNND
DHQQQHRCGYAGIVGAPNMGKSTLLNSLLKEDLCIATRRPQTTRHAILGVLSSPTKQCC-
------LLDTPGVLQGDGA-------YQLQANMMEAVKGALTDSD------------VIV
VVTDLFSTPIPDDN----------------------------------------------
-------------------VFRRLSETTKPVLVVVN--KIDL---EGRAKRPDEATIQRK
KDDEEEEEDEFEKTYTVSLTNDDVKQ------------------------LLPIGPPLYD
DDFLSDRSVRFFCSELIREAL---LESRYL---KKELPYCCEVQITDYKEPRDDNITRIE
AT------------------------IFVERDGQKAIIIGKNGDVVKQVGIIAREKIERF
LDGEKV------------F------------LQLRVKINKDWRKREDQLAKFGYSN----
>gnl|BL_ORD_ID|3483 @F.cylindrus_GMF2@jgi|Fracy1|196010|e_gw1.26.139.1
MPTPISTQPIRRYRSLKKEPLVAILGRPNVGKSAFVNRIC--------GTQNGGAIVADE
EGITRDRTYRDANFLGENFQVVDTGGL---------------------------------
------------------------------------------------------------
-----------------------------VFADDESTLFAREIREQAMVAIDESSGVVLV
VDGKIGMTAMDQQIAEFLRKDVLSRNLPVILAVNKCE-------------SETVGALNAA
EFWNLGLGEPIPVSALHGVGTAEVLERLFEEIKQKQSAALPGFGTKDALAAFDELERP--
------EEINVAIVGRPNVGKSSLLNALFGDQRAIVSKMAGTTRDSIDAVMERPGDNEGD
LPTIYRFVDTAGIRRRAKV------EYGPEFFMVNRALRAIRRADV-----------VLL
VMDATAGVTEQDRI----------------------------------------------
------------------LAQKIADDGRA-CAIICN--KWDAVVDKDSST----------
---------YDKSVKYIRAEMPQIRW----APILFISAETGQRVGKI---YNVVDDAI--
-----GAHRKRISTSVLNEVL---RDAILW---QPPPARRNGAQAKIYYCN---------
--QVSTRPPTIVVFCNDPKLVNDNYKRYLDRKFRESLDGFEATPVRWIFRGRRARDIMRA
KDMNGNPGDGGKGVSYPFPHAD--------------------------------------
>gnl|BL_ORD_ID|13890 @F.cylindrus_GMF2@jgi|Fracy1|147902|gw1.4.359.1
SNF-----------------TVSILGPPNAGKSTLFNRLQCKERNRAKHTSKGNAIVSSI
AGTTRDRRECWGRIGGTEFTLMDTAGI---------------------------------
------------------------------------------------------------
--------------------DGDRIQALAGKSKSEKHALERAMMEQTLEAAKKSDLVLLL
WDARIGVSQDLLITARWLRK--LGKHSNVSLIANKLE------GDSWAHDEDSIVMENLR
DVLRLGLGNAIPISALQG-DGLADIAILIEKLKTEKEAKYNQENYSTDTTTANEISENNS
GKDGDQKPLQIAIIGRQNVGKSTLVNRLLKSDRVLTGSTPGLTRDAIAVEWDWDGQLVQ-
------LVDTAGIRKLTKR--MQMDDDSIEDQSVADALRAMKVAEV-----------AVL
VLDAKELFIQRQEL----------------------------------------------
-----------------AICNAVLNEGRA-LVIAAN--KMDLIEMSSTYT----------
-----SRDFANSVREQIESRIPILRN----IPIVPMSCISGKGIEHV---LPAALDAR--
-----NRWARTISTGLLNRWL---AEVVTG----LQPPYVAGVRAKLKYII---------
--QTKGRPPTFIIFSNVKSFPEPYL-RYLTRQFQDSFELYGMPVRL--------------
------------------------------------------------------------
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3128 _gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
MDS---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------ETPTKNEAEQRA
SPDRTGQVTQRPVSLFRK---NGTFAYPLEDSDVYEEQVLALEDVPEPTAQAILRLALAA
ERQGV-PRLRFLVVGAPGVGKSSLINTLLNENLCSVSAWERGTKNAQVCARQVDSVVIE-
------FIDTPGIAPCRRS----GLEASRRQVQRLRKLLDARGADEHPYLRSFHAILYVM
RLDDTRPDLVDYHNWKVLMEFFGAEVLRHMMVVFTHGQSLPPDSLSYPEYVRGRRDYVYL
LIERLTGPLKAVRFP---------------VFVAENSSKCPVIEETGERKLPDDTPWITQ
LYDGIRRFVFPLEADLFGMETGPEDT----QVLVYIYDKRRSRADER---YPRSPLQALI
RNPWFLRAVQFCGAMLLRSYMIRQEHERFNPKPHHPEPIIRDANNAFAVASRRANDHRLF
T-------------------------PSIDEDEESFFRMNGNDDFVSRLRNRPGEVDLDE
LDVERIESPDGRFVEYWYTEKDNPEMVRMYRLEIRDDPNEERESRQDRIPISKDQH----
>gnl|BL_ORD_ID|14675 @F.cylindrus_GMF2@jgi|Fracy1|209263|estExt_Genewise1Plus.C_71245
MSE---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------DIVAEFSSKAGGGYNRPGVQWYPGHIAKAERQLSETLKAVDVVVEV
RDARACKATSHPRVGEWCAG------RPRIVVLTHLDMIPKAAANSWRKAYEKFGAEDMD
DAPIN--RQVLFVNAKQGQGIHALHRAIFK--------------------AGSHVQERRE
RRGLNPRALRVGIIGYPNVGKSALINKILGRKRAKTANTPGVTRSLQWIREFE-------
------LLDSPGIIPAKMV------DQSDALLLAACNCIGQAAYDNQAVAAYLYEWLKAV
YLMDKQALTAPNWRDKC-------------------------------------------
---------------------------------------------IDRYGFDPLEKVQRD
EDDIVQDEYLTGEDMLFKVADDLCRGDAEDAARKMLQDFRQGRMGPI----------SLQ
MAPESEEDGGMLSVSVGDGTI---LG----------------------------------
--------------------------RQSMRGSENGGFDAEYQQQIQDERARIALETAKE
RG-----------------------------LELPPIVDDPERAKEEAEADVGKGMFDGW
>gnl|BL_ORD_ID|3946 @F.cylindrus_GMF2@jgi|Fracy1|211867|estExt_Genewise1Plus.C_210148
MAP--------------KYQNKTKRRENAIPRTGASSKIGKGRDNAKGGHRSAETIKRLN
LYKSRAIRNKKGTIIGGDFMMGDRAGDRDITGETGRIAPDRRWFGNTRVVDPKQLDTFRQ
EMTEKVADPYSVVLKRKKLPMGLLREAAEREAPPSQALLGQEPFSQVFGSKSRRKKVKLD
QLMLARSDVDPNKDEDEDGAPIKKGGRAEVKADLFNKGQSKRIWGEFFKVVDCSDVVLHI
IDARNVPGTRCNMIERHIRD--NASHKHLVFVLNKIDLVPNWVAKRWMGELAKDRPT---
------------------IAFHASMTHAFGK------------------GALISLLRQFG
KLHGDKKQISVGVIGYPNVGKSSVINTLISQKSCKVAPIPGETKIWQYITLFKRIS----
------LIDCPGVVVDTAG------DTETESVLKGVVRAE--------------------
RLETPEDFIQP-------------------------------------------------
------------------------------IVDMVKREHI-----AGQYKFTKEESNKWT
TPTELLETIATKAGRLLKGGEPCLRS----ASITMINDFQRGRLPHF-----VAPPELKE
DDVEENQGNMGGSTAVIEGVK---PEAQELDKIGEENTKSDGT-----------------
--------------------------VDGESDQKEGKETGSSGVVADEPVAIAEGEWDD-
------------------------------------------------------------
>gnl|BL_ORD_ID|13155 @F.cylindrus_GMF2@jgi|Fracy1|162596|gw1.1.2020.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------EVAFLGRSNVGKSSLINAIMRKNLCITSKSPGRTQLPYYYGNPSGQPQGF-
------IVDLPGYGFAKKPMSITEDWQKDTQDLLLHRRHEAKVLKR-----------LFL
LMDARRGVQGPNEH----------------------------------------------
----------------DRIVMRWLEDAEIPFTVVLT--KADRVS----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>gnl|BL_ORD_ID|696 @P.tricornutum@gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GAPNMGKSTLLNALL--EED-------LCIATARPQTTR
HAILGLMSTDKCQ--------VCLVDTPG--------VIEDPAYELQEGM----MEAVTG
AVATSDVLLVVTDV--FS--TPIPDDELFL--------KVQ-------------------
---RTRKPVLVAINKIDLAKKVN-KAAEENRDKTVTVEEAV----------------AFW
RAQL---------PNALCILPLSASQGINNVGVVAMRRILTELLPISPPLYDPETLTDRP
E---RFIASEIVRSAL--------------------------------------------
---------------FQVLKKELPYCCEVRIREFKEPKEEGEVIRIAADVL-------VE
RDSQKVIVIGKNGAQVKEI--GVIAREKLEAFFRHQIFLNLSVKVDKDWRKNTRKLTEYG
YMKPKR------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>gnl|BL_ORD_ID|6794 @P.tricornutum@gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
----------------------------------------------RPTFIRTALVTFRW
SGGPKISRSDRVRLSSTTIG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----STPSLEDRKRLDVAIVGLPNAGKSQLLNVLT--QST-------VAAVSRKRHTTR
DGILGARTVDDTQ--------LYFVDTPG--------FLRQSQAKKE-GLNRDLVVTASS
EMENVDFSLLVVDA--AR--RMTDDYEETLVALMLAALRSQGRLEFDVHSAEEVQSIRTP
KGGTNPAKFAVVLNKVDLVHPKS-NLMDLAVNIGTLAEQCIKFDAKESGKEELFLDSAYL
QESL---------PMFFYISALKQRGVQDLLEFLLERATPSTSWEVEAGEATPMTMKERI
E--------EVIREKI--------------------------------------------
---------------YRCLHKEVPHSIRQ--ENRVLQQGKDEDGNIVLVIHQDLI---VR
SKSHQELVHGGGGRTLERI--RETAARGLEKIFFCNVVLHLHVKLPRSKNQRWSI-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>gnl|BL_ORD_ID|5109 @P.tricornutum@gi|219124383|ref|XP_002182484.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
S-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------RIVVSILGPPNAGKSTLFNRLL
DKAANRAGTAIVSNVPGTTRDRRECVGRIGGTLFRLVDTAGV--DGERLELLAQSRRNQN
GEGILMKFMMGQTLEAARQADLVFLMFDARVGV--------------------------T
ADLLETARWLRKISQREQDPAAQTALPDRQIFLLANKLEGDF----------WNFDGSIV
LDHLTEATRLGFGEAIPISAHHGEGLADIAVLIEQAAVAKRQSLG--------ILDDDTD
LASNDSDKD----KPLQLAILGRQNVGKSTLVNALL--KQD-------RVIVGATPGLTR
DAIAVEWTWKNRP--------VQIVDTAG--------IRKRSQRNHEDAIEDLSVEDALR
AMKVADVAVLVLDA--EA--RKLQRQELAI------ADAVL-------------------
---KEGRALVVAANKMDLIVERGYSKKDFA---------------------------EDV
RAQLEARYPILRKTPIVPMSSLTGDSVHKLMPVVF-RARERWSRKISTGELNRWIA----
---------EVMDGK---------------------------------------------
-----------PPPPVSGRKARIKYVMQTKGRPPTFL-----LFCNVASLPENYLRFLTR
NFQDTFEMFGMEVRM---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>gnl|BL_ORD_ID|5109 @P.tricornutum@gi|219124383|ref|XP_002182484.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
S-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------RIVVSILGPPNAGKSTLFNRLL
DKAANRAGTAIVSNVPGTTRDRRECVGRIGGTLFRLVDTAGV--DGERLELLAQSRRNQN
GEGILMKFMMGQTLEAARQADLVFLMFDARVGV--------------------------T
ADLLETARWLRKISQREQDPAAQTALPDRQIFLLANKLEGDF----------WNFDGSIV
LDHLTEATRLGFGEAIPISAHHGEGLADIAVLIEQAAVAKRQSLG--------ILDDDTD
LASNDSDKD----KPLQLAILGRQNVGKSTLVNALL--KQD-------RVIVGATPGLTR
DAIAVEWTWKNRP--------VQIVDTAG--------IRKRSQRNHEDAIEDLSVEDALR
AMKVADVAVLVLDA--EA--RKLQRQELAI------ADAVL-------------------
---KEGRALVVAANKMDLIVERGYSKKDFA---------------------------EDV
RAQLEARYPILRKTPIVPMSSLTGDSVHKLMPVVF-RARERWSRKISTGELNRWIA----
---------EVMDGK---------------------------------------------
-----------PPPPVSGRKARIKYVMQTKGRPPTFL-----LFCNVASLPENYLRFLTR
NFQDTFEMFGMEVRM---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>gnl|BL_ORD_ID|7302 @P.tricornutum@gi|219109543|ref|XP_002176526.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------KSVLCGVTLACGGIWQAN
SFTFRPLPVTRPVIGLLA------------------------------------------
-------TLDRVNEKSTVEPSSGDPQLQPIRRLRQNKKEPLIAIVGRPNVGKSALVN---
RIAGSQSGGAIVADESGITRDRTYRPAEFLGERFMIVDTGGLVFDDDESTLFAKEIRE--
-----------QAMVAIEESAAVIMVVDGQTGL--------------------------T
GMDLMIAEFLRK----EVDIPVHVAVNKCESEKTGAMSAADF------------------
-------WGLGLGEPFPVSALHGVGTAEIMETIFDSIAEKK-------------------
-TFDAEDRP----EEINIAIIGRPNVGKSSLLNSIF--GDT-------RAIVSEMAGTTR
DSIDAVMERPPPPGSDDLSTIYRFVDTAG--------IRRKGKVDF--GPEFFMVNRALR
AIRRADVVLLILDA--TS---GVAEQDRVL------AQKIA-------------------
---DDGRACVIVCNKWDAVVDKDSTTYDKSV--------------------------QYF
REEL----PMIRWAPILFISAATGQRVGKIYSAID-GAIEAHRKRISTAILN--------
---------EVLRDAILWQP----------------------------------------
-----------PPTRRNGSQAKIYYCNQVSTRPPTV----------------------VV
FCNDPKLVNDNYRRYLDRK-----FRESLDGFEATPIRWIFRGRRVRDVMRNRSMNGDPG
DGGTGVSFPFPHAD----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>gnl|BL_ORD_ID|9918 @P.tricornutum@gi|219114453|ref|XP_002176397.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M---------------------------------------------RMTTQRCYSTQHSR
HFSFQSIRIPHVLLAMVVSAWFGSQPTRTVRAFPLTQWRCHSVRRNTNCRHVSHLSFQRN
TVFKEHTRTKRVLIPSTTRRYSSVNDVDMTTTVATTSSQDTIFALSSGAATGQATAVAVI
RLSGPQAGV---------------------------------------------ILQRLT
PGRPLPKPRTAALRKLHDLDDPKVVLDQALVLYFSGPNSFTGDDVVELQVHGSRAVVTAV
LETLGTAARLAEPGEFTQRAWLAGKLDALQVEALADLLTADTATQRQQALAQLDGQLSAV
YDTWRDMLVAGLAHAEAVIDFGDDERLDDALLDEEDQQLAQDNVWGGVVGNMEVLERSMR
RQLQDARRGELVRQGLQIAIVGPPNAGKSSLFNILA--DRD-------AAIVSPTAGTTR
DVLELSLNLGGVK--------CVLQDTAG--------VR----TFTDDAIEMEGIARATR
AAAQADLVLAMVDS--SDVESGLEILTTIL------QNSPN-------------------
---LDRQHVLLLLNKSDLREEKH-QTIEVPGKDVV-------------------------
----------ELIGGQYEISCATQNGVDTFLESLT-RICVARVSNTDASDRDKTSIVDRE
TSEGTLITRARHR-----------------------------------------------
--------------------QHVQAAVEALERFQTLSQQG------------------TM
SVDLAAEELRLAASELGRITGAVDVEDVLDKLFADFCIGK--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3128 _gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
M-----------------------------------------------------------
-------------------------------------------------DSETPTKNEAE
QRASPDRTGQVTQRPVSLFRKNGTFAYPLEDSDVYEEQVLALEDVPEPTAQAI-------
------------------------------------------------------------
---------------------LRLALAAERQGV---------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------PRLRFLVVGAPGVGKSSLINTLL--NEN-------LCSVSAWERGTK
NAQVCARQVDSVV--------IEFIDTPG--------IA---------PCRRSGLEASRR
QVQR---LRKLLDARGADEHPYLRSFHAILYVMRLDDTRP--------------------
----------------DLVDYHNWKVLMEFFGAEVLRHMMVVFTHGQSLPPDSLSYPEYV
RG--------------------RRDYVYLLIERLT-GPLKAVRFPVFVAENSSKCPVIEE
TGERKLPD----------------------------------------------------
-------------------------------DTPWITQLYDGIRRFVFPLEADLFGMETG
PEDTQVLVYIYDKRRSRAD--ERYPRSPLQALIRNPWFLRAVQFCGAMLLRSYMIRQEHE
RFNPKPHHPEPIIRDAN---------NAFAVASRRANDHRLFTPSIDEDEESFFRMNGND
DFVSRLRNRPGEVDLDELDVERIESPDGRFVEYWYTEKDNPEMVRMYRLEIRDDPNEERE
SRQDRIPISKDQH-----------------------------------------------
>gnl|BL_ORD_ID|6857 @P.tricornutum@gi|219112187|ref|XP_002177845.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MAKTGWKSGISNTSSAGKTNRTPKGNASSKLTQGRRRDKQPGSERSAETIQRLKMYSNGK
AIRNKAGKIVAGTFMMQDRAGDRKIEASTGRIQPDRRWFGNTRVVGATELDRFRQEMTEK
VADPYSVVLKRKKLPMGLLQ-DAAEYKAGNQKAALLEQEPFDQAFGKNSRRK--------
RVKLDQLFVQRAAESADSKEDIKTGEGEAIRSEGEGIDWRHEKKDDLFLKGQSKRI----
---------WGEFFKVVDCSDVVLHIIDARN-----------------------------
-----------VPGTRCTMIERHIAKNASHKHLVFVLNKIDL-----------------V
PNWVAKRWMGELAAVRPTIAFHASLTNAFGKGALISLLRQFGKL----------------
---------HEDKKQISVGVIGYPNVGKSSVINTLI--SKK-------SCKVAPIPGETK
I---WQYVTLFKR--------ISLIDCPG--------VVVDTAGDTEEDSVLKGVVRAER
LENPEDFIDAIMGK--VKREHIAAQYKLP-------------------------------
---KDGEETWSSSGELMEMIARRSGRL---------------------------------
---LKGGDPCIRTAALMIINDFQRGRLPHFI-----------------------------
------------------------------------------------------------
-----------PPPELKVEEDQKTVATEQ--AIQIEEQNLDDVVVVEKEMEQDEEGVETK
TNDHAAIADTETVIDTSSI-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------LIGDGKWDE
>gnl|BL_ORD_ID|9646 @P.tricornutum@gi|219116036|ref|XP_002178813.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-------------------------------------------------------PRSQ
GTSRKGKPGKKDRDAGMGKSLQRAQVQRYRPRADGKSRRGDGGMHMQAGVDSIGLEEAQQ
DQLKTRSVLEMQDLDDFLLQADMANREFVSEKEGLVVVDQTGQAYRPPAVQWA-------
DQKSSFLFTELSVPRRPAWDDTTTAVELDMNERKSFLEWRRAIAIKEEELARTSSLAAAT
PFEK-NLEVWRQLWRVLERSACLLQLVDARNPMFYLSDDLRDYASTLGKPMMVLVNKSDY
LSPSQRASWREYLMEKGWDPVFFSAVKEQQ-------------------------KLDAM
ANRKRIQVQLGTGHDNSLDHLGEETDVSIDAHDQIEEPEDERGVSVPLSRERLMETMLSF
ARQHNCQPDPRYDNRIQFGMVGFPNVGKSSVINVLF--GSSKHEHGVVRVAVASQPGKTK
H-FQTLMLPDAEE--------MMLCDCPG--------LVFPSFVSNTADLIAAGVYPIAQ
MRDHWPVTNLICQR--IPREVINAHYGIVL------------------------------
-----PKPSQLEMNERGLTKLPP-------------------------------------
-----------------------PSGEEFLGTFCIARGMLAASSGVPDYTRAARTIIK--
------------------------------------------------------------
DYADGKLLYCHPPPS---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>gnl|BL_ORD_ID|10132 @P.tricornutum@gi|219112105|ref|XP_002177804.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
-------KLGRKQLP---------------------------------------------
------------------------------------------------------RRRKAT
GPLRLDWPAVGASQDLVGTKDLVSFSLEESAFV---------------------------
------------PVRRKQKRPRKNAVSHTGGDTSSHDNALWI------------------
-----------------------------------------DRYNPQCIADVCVAPKKVQ
EVRQWIQSAMKDHVHKLLILVGSPGIGKSTMIRCLA--KEN-------RWSISEWNETFS
NQYSALNSA------------MHSVDQQSSLSSFQEFLRQAGTGYHSLTFESSSNSSTKQ
DGSQISGSIILLES--LP--TQHESTQMRLRELFTEHVRTT-------------------
-------SVPTVLIFSDVLEGKHKR--------------------------------EDL
ESLVDPNLLYSDLCLILQIQPCTKQNMKRVLSLIV----RAERLSVPSSIYE-----DLH
ERSNGDLRSAITTFQYEAMGQSMTVKNTDTTNRDRRL--SPFHALGKLLYAKRVTGAHKD
PLSWWKWKDDRPPIDFNPENVLEHSGIEQFGTLSFLEHHSPDFFSDISELSDT-----LA
TFSDSALLMDCSSISGSQNAAASLAGRAVAAFNRHPRANKFRQLSAPKIFEVNRNRRENE
VHLRHLHHSLSTNRSNELSLHSALGATSHFVSDSLSFLRRIIPESIDLSLNTMHSRFRLI
DKSISSSNDAKTGLLKEQQQVLLDDDIGDFDSE---------------------------
------------------------------------------------------------
>gnl|BL_ORD_ID|7791 @P.tricornutum@gi|219128028|ref|XP_002184225.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--PVYNFKGMKPVPTAPELVDIVLMRTQRRTPT--------------------------V
VHPGYKITRIRSFYMRKIKFTQQTISERLSGMLTDFPRLNDIHPFYADLCNTLYDRDHYK
LALGQINTARSLVDSIARDMIRMVKYGDSLYRCKCLKRAALGRMCTVLKRQKASLAYLEE
VRKHLSRLPALDPNTRTLLMCGLPNVGKSSFMNKIT--RGN--------VDVQPYAFTTK
SLFVGHCDYKYLR--------WQVIDTPG--------ILDHPLEERN-TIEMQAIIALAH
LTCS---VLYFVDI--SEQCGYTIDQQCSL----FRSIKPL-------------------
---FANKQLIVVVNKVD---QQPWESLEEAKRAMV-------------------------
-----QGLADDANCSLMTMSNLSEHGVSDVKAAAC-DKLLATRVDARVSGKKIEGVMNRL
QVFNPAPRDGVTRGAFIPDSDGVTDGDVDMDGGNIRKTARELMWEGGGPGVWAPDYRDQY
DLADDSWKFDKIPEIIDGKNIADFVDADILDRLEALEREEEQL---------------VA
ESDAARMGEEPESDLESEEEAAVEAIRARKKIIKEKKLATNTQ-----------------
---NKPMLPLSIRGKSK---------DKHDAGTLLATEIRKTMDSIGVDSSKMLERGRLL
ERGRKRERSLSRSRRGADDEDAAMDVDVSGLSKAALKKIKKEKGEKARRDLSQARSHSRP
REPSQMGLKDSESVKSAQKLDRLGRKGWMGASGEGDTRKSVHLVKWMNTGKKRNGTHYQR
>gnl|BL_ORD_ID|9505 @P.tricornutum@gi|219116829|ref|XP_002179209.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
--------------------------------------------------SSERAATKRP
EMPSNRPRSRFANLPQTTIRKAITPYLPPPVIQAIERIDPKLEPFVEPEATLT-------
------------------------------------------------------------
---------LTVTFLLAWTVFLLLRFVTSRITG---------------------------
------------------------------------------------------------
-------------------------------------------------SGRAIADEDED
NVLSPKQTETTQHYEETVLLCGPPGAGKTRLFYQLCFGESN-------LPTVQSIKANVG
I---TLQNEHGPS--------IRYMDWPG--------HA---------PLSDDALQPILK
DKPR---IVLVLDS--TQPVASAADTLFNLLAYVHRQGRRQ-------------------
---MQKPLIFVACHKSDISKAKNSKRVKIQIRSELERLLKVHSSDTPATPLWWPSGEPLE
LDEL------SFCDLHFTATNCEGEGSPELVAFTCTGNVPDVA-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>gnl|BL_ORD_ID|138163 @Pn.multiseries@jgi|Psemu1|186266|e_gw1.57.139.1
MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLSSQASSRVKFLSSSSPSSTRR--
------------------------------QSPPASRPQA----AATAQNRTRKRLDVAI
VGPPNAGKSQLVNVLTKSPIAAVSRKRHTTRSDLLGARTVGNTQIVFKDTPGF-------
LRIENAKEERLDRDLIATAASE---------------MQDVDFTLLVLDSARTLSDNYRH
ALVQLMVGAINSGGRIEDCDDDDDNNDRKTTRQSREDINPSSKCDTAIPSDKSKFAIVLN
KVDLVKPKTDLISLAMDVGTMADTCLLDQFQKQGREFDFDAQ-----MEQSP----IVFY
VSALKEDGTDDLLEHLLGLATPSREWPVEPGKA--TNMTTLEQVQ----EVIREKIYRST
HKEVPHAVQQVNRLFRRIPNKGVVIHQ---DLVVFTKS----HQKLVLGSGGGKTLKRIQ
ESARH-DLQKLFGCDVA---------------------------LQLHVKYRKSKQQRGD
SGAQYNLGEVSQSVY
>gnl|BL_ORD_ID|24856 @T.oceanica@gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
-----------------FGIRRLVVGGSVRHGGHARGRPLPCPACPTGPDI---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----SSSASSLLSRTMTSYFDGGP------------------------------------
--------------------------------------------------------SAPE
TSRPKQQ-----------------------------------------------------
----------------------------------------------RRLDIA------IV
GAPNAGKSQLLNS----LVGSKVAAVSRK-RHTTRSGILGARTFGDTQL-----------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------VFI
DT-------------------------PG-------------------------------
--FLHHSKGAREGV----RNLLSEASAEM-------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----MNADFALLVVDAAKTIDQDLKRTLVTLMML-ALRSTGREEGSRVFSDQRHLGRFS
VV----------------------------------------------------------
--------------LNKVDLVKPKEKLLAT------------------------------
------------------------------------------------------------
----------------------------AAEVGSLAESCVRR------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------L
LQQHRA------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------P
VRVKMGELVDSVLERHEDEEGFAGVH----------------------------------
------------------------------------------------------------
-----------------EEDYETFASVVPEFL----------------------------
-FTSAIDPEDEGADDLLNVLLSRATPSTEF-------------VM---------------
--------DPSSNLEQV-----------EEIIREKIYRCLHREVPHHVQQTN-RVFKLKQ
DQPPDHD-----------------------------------------------------
------------------------------------------------------------
----------------------------VRADMGDLLQIHQDLIVRTKSHHRLVLGSGGK
TLQRIQTTASKDLRELFGCEVDLLLSVKLKKTNQGVLLDPEEEGARITTLHD--------
-----------------
>gnl|BL_ORD_ID|14494 @T.oceanica@gi|397643422|gb|EJK75853.1| hypothetical protein THAOC_02405 [Thalassiosira oceanica]
M---------------------------------KGSIRMAHVGALMMFA----------
------------------------------------------------------------
-----------------TTACRGFRRSSQSATPKSTNRHITVLSQYCGIRDEVRRRNL--
-----IVGPSLQTVASRRRRATARLGPLHTPLQSTLYDLEEKESTASTSDEDTVFALSSG
SGVTAVAVIRISGRNAFDALKQLLSPYSLEAGAEPPKLP---------------------
--------TPRMASLRILYDPLSSSD---HLNRMRDPLDSALVLIFPGPRSFTGEDIVEL
HCHGSRAVTSGVLKALSSLDSVRPADPGEFTQRAYGNGKLGLVEVEAL------------
--ADLIVADTSLQRKQALQQFDGRLSRLYLGWRKELIKGLAHAEAVIDFGDDEA-LGEED
SSFDSSENDGGMSVWADVRPRI--SSLREAMDRH--------------------------
-LEDASRGE----------------------------------LLRDGLRIA------IV
GRPNAGKSSLLNL----LAGRDAAIVSST-PGTTRDVVEVVLDLDGVRC-----------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------SLL
DTAGVREEIEDGVDEIEI---------EG-------------------------------
--MKRARLAAQEA-----HLIVGVVDCSD-------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------QKRGLEAVQE----------LIRADGHSDSARSSPHNNLLYV--
------------------------------------------------------------
--------------LNKRDLFEGE------------------------------------
------------------------------------------------------------
----------------------------MEPCGVDSETFAISC-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------TTNQGVDI
FLAALSKRALAMISQEGDSSGDLSVV----------------------------------
------------------------------------------------------------
-----------------------------------------------GTEGAVITRARHR
RHVEAASDALQRFEVLSSQGYMALDMAAEELRLASSELGRVTGAI---------------
--------DVEDVLDVLFADFCIGK-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>gnl|BL_ORD_ID|1577 @T.oceanica@gi|397642458|gb|EJK75246.1| hypothetical protein THAOC_03037 [Thalassiosira oceanica]
M--------------------VKTGYKFTKQQPNKGSRNMLKNSAASSRPNRTAPKRGDN
GNMRSNQTIARLKMYNNGKAIRNKEGKVVGGQFMMGDRAGDTKITAATGRIAPDRRWFGN
TRVVNPTELDRFREEMTSSMADPYSVVVKRKQLPMGLLRDAAELEKAG------RNNSGL
LANEPFEHTFGGKSRRKRVKMEQYMVGRTSKIDDVEDKDEEDDQKPYRGGEAET------
--VNDMPSDDKSGYAALLAAAQKSQDTYSKVNNRVGIVPWGKDSNLTKTSGEGVDWVHSK
KDDLFLKGQSKR-IWGEFYKVVDCSDVILHVIDARNVP----------------------
-----GTRCTMIEKHIAKNAPHKH-----------------LVFVLNK------------
--IDLVPNWVAKRWIGEL------------------------------------------
-----AQIRPTIAFHASMTHAFGKGALISLLRQF-------------------------G
KLNSDK----------------------------------------KQISVG------VI
GYPNVGKSSVINT----LISKKSCKVAPI-PGETKIWQYITLFRNI--------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------YLI
DC-------------------------PG-------------------------------
--VVVDTAGDSETD----SVLKGVVRSER-------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------LETPEDYVDAIQDAVKREHIAAMYGLPRSGEDTWKSSEELCEKIA--
------------------------------------------------------------
--------------IKCGRLRKG-------------------------------------
------------------------------------------------------------
----------------------------GEPCLRSAAIMIIN------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------D
FQRGRL------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------PHYVAPPE
LKEE------------DSGEGAAAVA----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-DTANIEGVELAAQNLDEVTRDRAEDSAEG------------------------------
--------QRSDTKEETSEKIEKKD----------------------------GIAEDAG
DVEADED-----------------------------------------------------
------------------------------------------------------------
---------------------------------------------AGSDDDEVVIGDGDW
E-----------------------------------------------------------
-----------------
>gnl|BL_ORD_ID|33149 @T.oceanica@gi|397569214|gb|EJK46603.1| hypothetical protein THAOC_34725 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
--------VKKKGKSKRITLKDKYKIQRRVVETHRKNRKQAKRDAKAGIVRHDKKKDPGI
PNSWPFKQELLQSIQREKERAE-------------NRKLEEKERRVNKNGAANLEELVKQ
ANQKKSEFDAKTGSSSAASDDGIKIVTTSHGQ----------------------------
--------QSRRAYLRSLKTVIESSDVILQVLDARDPL----------------------
----GTRISSGIEASILSHFDKRM------------------VLVMNK------------
--IDLIPKKNVSEWLTYLR--------------------RSHPTVALKAGTTQSRSNEGG
RSSGVGQTKGENALSSSMAVGV--DGLLQLLKNY-------------------------A
RANGEKKSK-------------------------------------TSITVG------II
GYPNVGKSSILNS----LKRFRAVGVSSR-PGFTTTLQEVVLDKNI--------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------RLI
DS-------------------------PG-------------------------------
--VVFDDDASRDGAN---AMLRNGVDADS-------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------VSDPLPAIAELLGRCTSESLMMTYSVPAFPPGPEGVLTFLAMVA---
------------------------------------------------------------
--------------RSKGRVLKG-------------------------------------
------------------------------------------------------------
----------------------------GIPDKMMAARLVMR------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------D
WNQGKI------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------PYFSTPPV
TEVEMG------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-DTSAGSTHAKIVSKFSEEFDVSKIMAAHDKELMNGLEDV--------------------
--------DEMDFVQMTSSSRPRGEGSADKVV---------------------KYLHEGG
DQNSDSE-----------------------------------------------------
------------------------------------------------------------
---------------------------------------------MEGDDDAVALNTRME
EAEDFFGE----------------------------------------------------
-----------------
>gnl|BL_ORD_ID|10226 @T.oceanica@gi|397601583|gb|EJK57948.1| hypothetical protein THAOC_21972 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------EDPNSFSLSGYQ
RPKVNWYPGHIAKAERQLAETLKSVDVVIEVRDSRAPK----------------------
---------ATAHPSVGKWAAGRP-----------------RVVVLTR------------
--VDTVTTRSRETWRQAYER-------------------LGADRWQEKLAGDERNRNAQF
ETERRKYVDGEDGDSVKLRGA---DGVEEVLFVD-------AKRGQGTHAITRAVYRAGR
HVNERRKRR---------------------------------GLNDRSLRVG------II
GFPNVGKSALINR----LLGRKRAKTANT-PGITRSLQWMRVAADKSTSASGSGSANAKK
GF----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------ELL
DS-------------------------PG-------------------------------
--IIPSDMLDQND-----ALLLAACNSVG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------VGAKIAARWG-------------SESTDGSARSWLDFA------
------------------------------------------------------------
--------------AKNADRMPSGEDMLFIVADNTCKGDP--------------------
------------------------------------------------------------
---------------------------------ENAARKILQ------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------D
FRNGRM------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GPVSLQLAPESETDEGQVHVE----------------------------------
------------------------------------------------------------
-----------------NMRSDGLDVRIVASPTNL-------------------------
-KRATEEHEKRQKEEIQQRAKAAMVAAKQK-------------GL---------------
--------DLPPVVESI-----------------------------DVDDTEQVAAGGGA
DSKPSESEIGKGLFDGW-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>gnl|BL_ORD_ID|10627 @T.pseudonana@gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
MAFFRR------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------ALLQGSL-----------------------------------------------
-----------AVNNLTHDTWHQTP-----------------------------------
----------RAITSLLNHQQSCSLHSTPIT-----------------LNNPTSSSAATT
QSDKPAPQKRLDVAIVGAPNA--GKSQLL-------------------------------
-----------------NSLIGSKV-----------------------------------
-AAVSRKR----------------------------------------------------
-----------------------------HTTRTGILGARTFDD-------TQLVFIDTP
GFLHHEMSVKEG-VRKLLGEASSEMESADF------VLLVVDAARKM-------------
---------------------------------------------------EDDLRRTLV
TLMFLALR----------------------------------------------------
---------------------------SKGRNEFAVVLNKVDLVSP--------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------KEKLLMTAADVGSMAESCIRQFLNQ---------
--------------------------------------RRSPSKVKF-------------
------------------------------------GELVD-------------------
----------------------TVLKNYANEDGFDGVHDDDIELFATLAPEFFFTSAIVK
DDEGVDDVLGL----------LLERATLSDQWI---VDAGSATGMTPVEQVEEIIREKIY
RCLHREVPHSVQQQNRMFQLYKPNES----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------KTKSTDGSDVDEDIKILRIRQDLIVRTKSHQRLVLGSGGKTLE
RIRSTALKDLEESFDCIVDLDLTVRVTKSNQHEAILDPESVGAVSLTPLE----------
---------------------------N
>gnl|BL_ORD_ID|4381 @T.pseudonana@gi|224003191|ref|XP_002291267.1| predicted protein [Thalassiosira pseudonana CCMP1335]
KADSNMRSSATIARLKMYNNGKAIRNKEGKVVGGQFMMADRAGDSKITAATGRIAPDRRW
FGNTRVVAPTELDAFREEMTQSMADPYSVVIKRKQLPMGLLKDAAE---LQAKHGGTNSS
AGLLLNEPFEHAFGTKSRRKRVKVEQFMVGN-----------------------------
--AETLANLPDDDATGYKSLLAAAQKTSGEGVDWRTEKKDDLFLKGQSKRIWGEFYKVLD
CSDVILHIIDARNVPGTRCTMIEK----------------HIAKNAPHKHLVFVLNKIDL
VPN------------WVAKRWIGELA-QIRPTIAFHASM--------------------T
HAFGK-----GALISLLRQFGKLASDKKQIS-----------------------------
------------VGVIGYPNV--GKSSVI-------------------------------
-----------------NTLISKKS-----------------------------------
-CKVAPVP----------------------------------------------------
-----------------------------GETKIWQYITLF----------RNIYLIDCP
GVVVDTAGDTEI---DSVLKGDVRAERLEC------------------------------
---------------------------------------------------PEDFIDAIQ
AAV---------------------------------------------------------
---------------------------KREHIAAMYGVPKSGDDTW--------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------STSIELLEKISIKCGR------------------
--------------------------------------LKKGGEPCLRSSAIT-------
--------------------------------------LIN-------------------
----------------------DFQRGRLPHYVAPP------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------E
>gnl|BL_ORD_ID|2716 @T.pseudonana@gi|223994459|ref|XP_002286913.1| predicted protein [Thalassiosira pseudonana CCMP1335]
-------------------------------------------------------PKVN-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------WYPGHIAKAERQLSETLK
SVDVVIEVRDSRAPKATAHPSVGKWTA--------------------GRPRVVVLTRMDT
VTSRSRDSWREAYERLGADRWEDSLVEEILFVDAKRGQG--------------------T
HAISRAVYKAGRHVNERRKRRGL--NDRPLR-----------------------------
------------VGIIGFPNV--GKSALI-------------------------------
-----------------NRLLGKKR-----------------------------------
-ARTANTP----------------------------------------------------
-----------------------------GITRSLQWIR------------SGFELLDSP
GIIPSDMLDQSD--------ALLLAACNSI------GVGAYDNQAV--------------
---------------------------------------------------AAYLCERIQ
SLVIM-------------------------------------------------------
---------------------------EKDYIAAPLWRNRCIERYG--------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------FDPLDMLFIVADNTCK------------------
------------------------------------------GDP---------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------ENAA
RKILQD------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------FRMGRMGPISLQL
>gnl|BL_ORD_ID|7596 @T.pseudonana@gi|224013676|ref|XP_002296502.1| predicted protein [Thalassiosira pseudonana CCMP1335]
LPNARMASLRTL------------------------------------------------
------------------------YDPTADAKGTSDDEEEMQQQKRDPLDSALVLTFEGP
NSFTGEDIVELHCHGSR-------------------------------------------
------------------------------------------------------------
------AVVHGVL---SALSSLSSRAIPLQLRPADPGEFTQRAYAHGKLGLVEVEALADL
IVADTSLQRKQALQQFDGRLSRLYGGWREEL----------------------------I
KGLAHAEAVIDFGDDEA--LDAHDEFDDGLNANDGGMSIWGTIAPRIRSLRQAMNRHLAD
ASRGELLRDGLRIAIVGRPNA--GKSSLL-------------------------------
-----------------NLLAGRDA-----------------------------------
-AIVSSSP----------------------------------------------------
-----------------------------GTTRDVVEVMLDLGG-------VRCTLLDTA
GVREEKEEGVNEIEVEGMKRARRAARDAHI------IVGVVDATDL--------------
---------------------------------------------------SRGL-EAVD
ELIRV-------------------------------------------------------
---------------------------ESESDESSSLLNRDNVLYV--------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------LNKLDLVEGNENSINS------------------
--------------------------------------KEQSNSPKFGISCTT-------
------------------------------------SEGVD-------------------
----------------------DFLSSLTQQALSLVSGDRDEGAVITRARHRRHVEAASD
ALERFEELSGQ---GYMALDMAAEELRLASSELGRVTGAIDVEDVLDVLFADFCIG----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------K
>gnl|BL_ORD_ID|192 @T.pseudonana@gi|224012297|ref|XP_002294801.1| predicted protein [Thalassiosira pseudonana CCMP1335]
LPNARMASLRTL------------------------------------------------
------------------------YDPTADAKGTSDDEEEMQQQKRDPLDSALVLTFEGP
NSFTGEDIVELHCHGSR-------------------------------------------
------------------------------------------------------------
------AVVHGVL---SALSSLSSRAIPLQLRPADPGEFTQRAYAHGKLGLVEVEALADL
IVADTSLQRKQALQQFDGRLSRLYGGWREEL----------------------------I
KGLAHAEAVIDFGDDEA--LDAHDEFDDGLNANDGGMSIWGTIAPRIRSLRQAMNRHLAD
ASRGELLRDGLRIAIVGRPNA--GKSSLL-------------------------------
-----------------NLLAGRDA-----------------------------------
-AIVSSSP----------------------------------------------------
-----------------------------GTTRDVVEVMLDLGG-------VRCTLLDTA
GVREEKEEGVNEIEVEGMKRARRAARDAHI------IVGVVDATDL--------------
---------------------------------------------------SRGL-EAVD
ELIRV-------------------------------------------------------
---------------------------ESESDESSSLLNRDNVLYV--------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------LNKLDLVEGNENSINS------------------
--------------------------------------KEQSNSPKFGISCTT-------
------------------------------------SEGVD-------------------
----------------------DFLSSLTQQALSLVSGDRDEGAVITRARHRRHVEAASD
ALERFEELSGQ---GYMALDMAAEELRLASSELGRVTGAIDVEDVLDVLFADFCIG----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------K
>gnl|BL_ORD_ID|5653 @T.pseudonana@gi|223994975|ref|XP_002287171.1| predicted protein [Thalassiosira pseudonana CCMP1335]
-------------------------PLIAVVGRPNVGKSALVNRLAGTQSGGAIVADEEG
ITRDRTYRNAEFLGEAFQLVDTGGLVFDDNDALFA-------------------------
------------------------------------------------------------
------------------------------------------------KEIREQAMIAIE
ESAGVILVVDGQM---GPTSMDEQLAIFLRK---------------------EVLKKMPV
ILAVNKCESDKNGAYLASQFWNLGLG-EPFAVSALHGVG--------------------T
AEVME-----KMFDDIAKPLDGEDDTDEEIN-----------------------------
------------VAIIGRPNV--GKSSLI-------------------------------
-----------------NTIFGSNR-----------------------------------
-AIVSDVA----------------------------------------------------
-----------------------------GTTRDSIDAIMERPSSDPEGLPTIYRFVDTA
GIRRKGKIEFGP-EFFMVNRALRAIRRADV------VLLVLDATAGVTEQ----------
---------------------------------------------------DRVLAQKI-
------------------------------------------------------------
---------------------------SDDGRACVILCNKWDAVID--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------KDSSTY-------
------------------------------------DQSV--------------------
------------------------------------------------------------
--KYFREELPQ-------------------------------IRWAPILFVSAATGQRVG
K-IYEAVDSAVNAHRRRISTSVLNE-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------VLRDATLWQPPPARRNGAQAK
IYYGSQVSTRPPTIVVFVNDPNLINDNYKRYLDRKMRESLDGFESTPIRWM---------
------------------------------------------------------------
---------------FRGRRVRDVTRNM
