>cmToc34
MDSETPTKNEAEQRASPDRTGQVTQRPVSLFRKNGT---------------FAYPLEDSD
VYEEQVLALEDVPEPTAQAILRLALA-------------------AERQGVPRLRFLVVG
APGVGKSSLINTLLNENLCSVSAWERGT--------KNAQVCARQV-DSVVIEFIDTPGI
APCRRS---GLEASRRQVQRLR----KLLDA------RGADEHPYLRSFHAILYVMRLDD
TRPDLVDYHNWKVLMEFFGAEVLRH-----------------------MMVVFTHGQS-L
PPDSL-----SYPEYVRGRRDYVYLLI---ERLTG----PLKAV----------------
--------------RFPVFVAENSSKCPVIEETGERKLPD-------DTPWITQLYDGIR
RFVFPL------------------------------------------EADLF---GMET
GPEDTQVLVYIYDKRRSRADERYPRSPLQALIRNPWFLRAVQFCGAMLLRSYMIRQEHER
FNPKPHHPEPIIRDANNAFAVASRRANDHRLFTPSIDEDEESFFRMNGNDDFVSRLRNRP
GEVDLDELDVERIESPDGRFVEYWYTEKDNPEMVRMYRLEIRDDPNEERESRQDRIPISK
DQH
>acToc34	
M----------------------------------S------------------------
FLTREWVGIQQFPAATQTKLHEILGK-------------------LKQENVNTMTILVMG
KGGVGKSSTVNSILGERVATVSAFQSEG--------LRPIMCSRTR-AGFTLNVIDTPGI
V----E---GGYVNEQALEIIK----RFLLD------KTID---------VLLYVDRLDS
YRVDNLDKQVVKAITDFLGKEIWQR-----------------------GVVVLTHAQL-S
PPDGL-----NYDDYLEKRSDALLKYV---RLGAGIKKKELQGK----------------
--------------GIPVALVENSGRCK-TNEDGEKILPN-------GTAWIPNLVQQSQ
T-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>vvtoc34	
M---------------------------------AS------------------------
QLIREWTGIQQFPPVTQTKLIELLGK-------------------LKQENVSTLTILVMG
KGGVGKSSTVNSIIGERAVAVSAFQSEG--------PRPVMVSRSR-AGFTLNIIDTPGL
V----E---GGYVNDQALEIIK----RFLLN------KTID---------VLLYVDRLDA
YRVDNLDRQVVKAITDSFGKEIWRR-----------------------GVVVLTHAQL-S
PPDGL-----NYEDFFSKRSEALMKVV---RSGARLRKQDIQDS----------------
--------------GIPVVLVENSGRCH-KNESDEKILPN-------GTAWIPNLVKTIT
DAVSNG------------------------------------------SKGILVDKKLIE
GPNPNE--------------------------RGKLLIPFILAFQYFFIVKRIQRA----
-------------------------------------------------------IKSDM
AK-ER--KAPWESREANRYEP---------------------------------------
---
>stToc34-2
M---------------------------------AS------------------------
QIIREWAGIQQFPAATQSKLLELLGK-------------------LKQENVSTLTILVMG
KGGVGKSSTVNSIIWERAVAVSAFQSET--------PRPVMVSRSR-AGFTLNIIDTPGL
V----E---GGYVNDQALDLIK----KFLLN------KTID---------VLLYVDRLDA
YRVDNLDKQIVKAITDSFGKEIWRR-----------------------GIVVLTHAQL-S
PPDGL-----TYDEFTSRRSEALLKIV---RMGARIRKQDIQAA----------------
--------------SIPVVLVENSGRCN-KNESDEKILPS-------GTAWIPNLVQTIT
DAVLSG------------------------------------------SKGILVDQKLIE
GPNPNN--------------------------RGKVLIPFILAFQYFFVVKRIQKS----
-------------------------------------------------------IKNDI
AR-ES--RPAWA------------------------------------------------
---
>leToc34-2
M---------------------------------AS------------------------
QIIREWAGIQQFPAATQSKLLELLGK-------------------LKQENVSTLTILVMG
KGGVGKSSTVNSIIGERAVAVSAFQSET--------PRPVMVSRSR-AGFTLNIIDTPGL
V----E---GGYVNDQALDLIK----KFLLN------KTID---------VLLYVDRLDA
YRVDNLDKQIVKAITDIFGKEMWCR-----------------------GIVVLTHAQL-S
PPDGL-----TYEEFTSRRSEALLKIV---RMGARIRKQDIQAA----------------
--------------SIPVVLVENSGRCN-KNESDEKILPS-------GIAWIPNLVQTIT
DAVLSG------------------------------------------SKGILVDQKLIE
GPNPNN--------------------------RGKVLIPFILAFQYFFVVKRIQRS----
-------------------------------------------------------IKNDI
AR-ET--RPSWA------------------------------------------------
---
>leToc34-1
M---------------------------------AS------------------------
QVIREWVGFQQFPSATQSKLIELIRK-------------------LKQESVSTVTILVMG
KGGVGKSSTVNSILGERAVAVSAFQSET--------PRPVMVSRSW-AEFTLNIIDTPGL
V----E---GGYVNDQALDLIK----RFLLN------KTID---------VLLYVDRLDT
YRVDNLDRQIVKAITDSFGKGIWRR-----------------------GLVVLTHAQV-S
PPDGL-----SYDEFTSRRSEALLKIV---RLGARMKKQEIKAA----------------
--------------SIPLVCVENSGRCN-KNELDEKILPN-------GTAWIPSILQTIT
EVVVSQ------------------------------------------SKGILIDQKLIE
GPNPNN--------------------------KGKLLIPLIATFQYFFVVKRIQTW----
-------------------------------------------------------IKNDI
SR-EN--RPSWA------------------------------------------------
---
>stToc34-1
M---------------------------------AS------------------------
QVIREWVGFQQFPSATQSKLIELIRK-------------------LKQESVSTLTILVMG
KGGVGKSSTVNSILGERAVAVSAFQSET--------PRPVMVSRSW-AEFTLNIIDTPGL
V----E---GGYVNDQALDLIK----RFLLN------KTID---------VLLYVDRLDT
YRVDNLDRQIVKAITDSFGKEIWHR-----------------------GLVVLTHAQV-S
PPDGL-----SYDEFTSRRSEALSKIV---RLGARIRKQEVKAS----------------
--------------SVPIVCVENSGRCN-KNELDEKILPN-------GTAWIPNLLQTIT
EVVASE------------------------------------------SKGILVDQKLIE
GPNPNN--------------------------KGKLLIPLIAAFQYFFVVKRIQKW----
-------------------------------------------------------IKNDI
AR-ET--RPSWA------------------------------------------------
---
>mtToc34-1
M---------------------------------ASQ----------------------Q
QQVREWSGINTFAPATQTKLLELLGK-------------------LKQEDVNSLTILVMG
KGGVGKSSTVNSIIGERVVAISPFQSEG--------PRPVMVSRAR-AGFTLNIIDTPGL
I----E---GGYINDMALDIIK----RFLLD------KTID---------VLLYVDRLDA
YRVDNLDKLVAKAITDSFGKGIWNK-----------------------AIVALTHAQF-S
PPDAL-----AYDEFFSKRSESLLQII---KSGASLKKDDAQAS----------------
--------------AIPVVLIENSGRCN-KNETDEKVLPN-------GIAWIPHLVHTIT
EIALNK------------------------------------------SESIFVDKNLIE
GPNPNQ--------------------------RGKLWIPVLFALEFLLIMKPIEGL----
-------------------------------------------------------IKNDV
AN-EK--KPSWETRDVGVKKE----------------------TREVGQKDMRKERRGGA
VRR
>psToc34	
M---------------------------------ASQ----------------------Q
QTVREWSGINTFAPATQTKLLELLGN-------------------LKQEDVNSLTILVMG
KGGVGKSSTVNSIIGERVVSISPFQSEG--------PRPVMVSRSR-AGFTLNIIDTPGL
I----E---GGYINDMALNIIK----SFLLD------KTID---------VLLYVDRLDA
YRVDNLDKLVAKAITDSFGKGIWNK-----------------------AIVALTHAQF-S
PPDGL-----PYDEFFSKRSEALLQVV---RSGASLKK-DAQAS----------------
--------------DIPVVLIENSGRCN-KNDSDEKVLPN-------GIAWIPHLVQTIT
EVALNK------------------------------------------SESIFVDKNLID
GPNPNQ--------------------------RGKLWIPLIFALQYLFLAKPIEAL----
-------------------------------------------------------IRRDI
AT-ET--KPAWETRDVGDRK----------------------------------------
---
>pcToc34	
M---------------------------------AS------------------------
QIIREWSGINTFAPATQTKLLELLGK-------------------LKQENVNSLTILVMG
KGGVGKSSTVNSIIGERVVSISPLQSEG--------PRPVMVSRSR-AGFTLNIIDTPGL
I----E---GGYINDMALDIIK----RFLLN------KTID---------VLLYVDRLDV
YRVDNLDKLVAKAITDSFGKGIWNK-----------------------AIVALTHAQF-S
PPDGL-----PYEDFFSQRSEALLRVL---RSGAKIKKEVFQAA----------------
--------------SMP-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>asToc34	
------------------------------------------------------------
------------------------------------------------------------
---------------------SAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGL
I----E---GGYINEQAVEIIK----RFLLE------KTID---------VLLYVDRLDT
YRMDTLDEQVIRAITTSFGKAIWRR-----------------------TLVVLTHAQL-S
PPDGL-----DYNDFLTRRSESLLRYI---RSGAGIGKRESADY----------------
--------------PLPLALVENSGRCK-TNENGAKILPD-------GTPWIPNLMKEIT
MVVSNG------------------------------------------SKPIHVDQKLID
GPNPNN--------------------------RWKKYIPLILAVQYFFVVKGIRRA----
-------------------------------------------------------IHSDI
AN-GK--LDDWEQRYRDLVGS----------------------GNPVDQKVSSSRNPRPE
AGQ
>osToc34	
M--------------------------------SAA------------------------
PIPREWVGLQQFPAATQTKLHELLGK-------------------LKEENVSTLTILVMG
KGGVGKSSTVNSIVGERVATVSAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGL
I----E---GGYINEQAVEIIK----RFLLG------KTID---------VLLYVDRLDA
YRMDTLDDQVIRAVTNSFGKAIWRR-----------------------TLVVLTHAQL-S
PPDGL-----DYNDFFTKRSESLLRYI---RAGAGVSKRELGDF----------------
--------------PLPIALVENSGRCK-TNENGEKVLPD-------GTPWIPNLMKEIT
TVVSNG------------------------------------------SKSIHVDQKLID
GPNPNN--------------------------RWKMFIPLILMVEYFLVVKGIRRA----
-------------------------------------------------------IHADI
SN-GK--LDDWEQRYRDLVGS----------------------KDPVDQKGSSSGNRK--
--A
>sbToc34	
M---------------------------------AS------------------------
PIPREWAGLQQFPAATQTKLHELLGK-------------------LKEEDVSTLTILVMG
KGGVGKSSTVNSIVGERVTTVSAFQSEG--------LRPTMCSRTR-AGFTLNIIDTPGL
I----E---GGYINEQAVDIIK----RFLLG------KTID---------VLLYVDRLDA
YRMDTLDEQVIRAITNSFGKDIWRR-----------------------SLVVLTHAQL-S
PPDGI-----DYNDFFTRRSEALLRYI---RSGAGINKREYGDF----------------
--------------PLPIALVENSGRCK-ANEHGEKILPD-------GTPWVPNLM----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>zmToc34-1
M---------------------------------AS------------------------
PIPREWVGLQQFPPATQTELHELLGK-------------------LKEEDVSTLTILVMG
KGGVGKSSTVNSIVGERIATVSAFQSEG--------LRPMMWSRTR-AGFTLNIIDTPGL
I----E---GGYINEQAVDIIK----RFLLG------KTID---------VLLYVDRLDA
YRMDTLDGQVIRAITNSFGKDIWRR-----------------------SLVVLTHAQL-S
PPDGI-----EYNDFFTRRSEALLRYI---HSGAGIKKREYGDF----------------
--------------PLPIALVENSGRCK-TNEHGEKILPD-------GTPWVPKLMKEIT
VVISNG------------------------------------------SKPIHVDQKLID
GPNPNN--------------------------RWKMFIPIILAVEYFLVVKGIRRA----
-------------------------------------------------------IHADI
AN-GK--VDDWEQRYRDLVGS----------------------RDPVEQKGSTTRNRK--
--A
>zmToc34-2
M---------------------------------AS------------------------
PIPREWVGLQQFPAATQTKLHELLGK-------------------LKEEDVSTLTILVMG
KGGVGKSSTVNSIVGERVASVSAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGL
I----E---GGYINEQAVDIIK----RFLLG------KTID---------VLLYVDRLDA
YRMDTLDEQVIRAITNSFGKDIWRR-----------------------SLVVLTHAQL-S
PPDGI-----DYNDFFTRRSEALLRYI---HSGAGINKREYGDF----------------
--------------PLPIALVENSGRCK-TNEHGEKILPD-------GTLWVPNLMKEIT
VVISNG------------------------------------------SSPIHVDQKLID
GPNPNN--------------------------RRKLFIPLILAVEYFLVVKGIRRA----
-------------------------------------------------------IHADI
AN-GK--VDDWEQRYRDLVGS----------------------RDLVEQKGSTSRNRK--
--A
>soToc34	
M---------------------------------AS------------------------
PIPREWVGLQQFPAATQTKLHELLGK-------------------LKEEDVSTLTILVMG
KGGVGKSSTVNSIVGERVTTVSAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGL
I----E---GGYINEQAVDIIK----RFLLG------KTID---------VLLYVDRLDA
YRMDTLDEQVIRAITNSFGKDIWRR-----------------------SLVVLTHAQL-S
PPDGI-----DYNDFFTRRSKALLPYI---RSGAGIQPTRIWGF----------------
--------------P----------PCQ--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>hvToc34	
M---------------------------------AA------------------------
PIPREWVGLQQFPAATQTKLHELLGK-------------------LKEENVSTLTILVMG
KGGVGKSSTVNSIVGERVANVSAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGL
I----E---GGYINEQAVEIIK----RFLLE------KTID---------VLLYVDRLDT
YRMDTLDEQVIRAITSSLGKAIWRR-----------------------TLVVLTHAQL-S
PPDGI-----DYNDFLARRSESLVRYI---RSGAGIGKREYADF----------------
--------------PLPIALAEDSGKGR-TNENGA--ILD-------GNSWDSKLE----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>brToc34	
M--------------------------------AAL------------------------
QMSREWIGIQQFPPATQSKLIEILNK-------------------FKEEDVSSLTVLVMG
KGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGL
I----E---GGYVNDQAVNLIK--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>rrToc34	
M--------------------------------AAL------------------------
QMSREWIGIQQFPPATQSKLLEILGK-------------------FEEEDVSSLTVLVMG
KGGVGKSSTVNSVIGERAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGL
I----E---GGYVNDQAVNLIK----GFLPN------KTID---------VLLYVDRLDV
YRVDDLDKQVVTAITDAFGKEIWKK-----------------------SALVLSHAQF-S
PPDGL-----NYDLFVSRRSDALLKLI---YASAQLK-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>bnToc34	
M--------------------------------AAL------------------------
QMSREWIGIQQFPPATQSKLLEILGK-------------------FKEEDVSSLTVLVMG
KGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGL
I----E---GGYVNDQAVNLIK----RFLLN------MTID---------VLLYVDRLDV
YRVDDLDKQVVTAITDAFGKEIWKK-----------------------SALVLSHAQF-S
PPDGL-----NYDLFVSRRSDALLKLI---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>boToc34	
M--------------------------------AAL------------------------
QVSREWIGIQQFPPATQSKLLEILGK-------------------FKEEDVSSLTVLVMG
KGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGL
I----E---GGYVNGQAVNLIK----RFLLN------MTID---------VLLYVDRLDV
YRVDDLDKQVVTAITDAFGKEIWKK-----------------------SALVLSHAQF-S
PRDG--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>atToc34	
M--------------------------------AAL------------------------
QTLREWIGIQQFPPATQSKLLEILGK-------------------YKEEDVSSLTVLVMG
KGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPTLVSRTR-SGFTLNIIDTPGL
I----E---GGYVNDQAINIIK----RFLLN------MTID---------VLLYVDRLDV
YRVDDLDRQVVGAITDAFGKEIWKK-----------------------SALVLTHAQF-S
PPDGL-----NYNHFVSKRSNALLKVI---QTGAQLKKQDLQGF----------------
--------------SIPVILVENSGRCH-KNESDEKILPC-------GTSWIPNLFNKIT
EISFNG------------------------------------------NKAIHVDKKLVE
GPNPNE--------------------------RGKKLIPLMFAFQYLLVMKPLVRA----
-------------------------------------------------------IKSDV
SR-ES--KLAWELRDSGLASR----------------------RS---------------
---
>tsToc34	
P-----------------------------------------------------------
---------------------------------------------TRPEDVSSLTVLVRG
KGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGL
I----E---GGYVNDGAVNLIK----GFLLN------KTID---------VLLYVDRLDV
YRVDDLDRQVVTAITDAFGKEIWKK-----------------------SALVLSHAQF-S
PPDGL------YDLFVSRRSDS--SVI---CAGAQLKKQDLQGS----------------
--------------SIPVILVENSGRC---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>lsToc34	
------------------------------------------------------------
------------------------------------------------------------
--------------GERAVTVSAFQSEA--------LRPTMVSRER-SGFTLNIIDTPGI
V----E---GGYVNDQALEIIK----RFLLN------KTID---------VLLYVDRLDA
YRVDTLDGQIVKAISNSFGQQIWRK-----------------------AIVVLTHAQL-S
PPDCL-----SYDEFLAKRSEALLKVV---YRGARFRKLDIENF----------------
--------------PIPIGLVENSSRCN-KNEKDEKILPN-------GSAWIPSIVETIT
EVSLTE------------------------------------------SKSILVDQKLID
GPNPN---------------------------RGKLFIPFIIAFQYFFV-----------
------------------------------------------------------------
------------------------------------------------------------
---
>ptToc34-1
M---------------------------------GS------------------------
-VLREWIGFQQFPTATQSKLVELFAK-------------------LKEEGVDKLTILVMG
KGGVGKSSTVNSLFGERAVNVSSFQSEG--------FRPVMVSRNR-AGFTLNIIDTPGL
V----E---GGYVSYQALDMIK----RFLLN------KTIH---------VLLYVDRLDA
YRVDDLDKQIIGAISDSFGKEIWSK-----------------------SLLVLTHAQL-S
PPDDL-----SYDVFCARRSEAVLKTI---RMGARIRKRDFEDS----------------
--------------AIPVGLVENSGRCN-KNENDEKILPN-------GDAWIPSLVKEII
LVATNG------------------------------------------KKLLLMRSWLVG
LSQMTG---------------------------GKIFIPLILGI----------------
------------------------------------------------------------
------------------------------------------------------------
---
>ptToc34-3
M---------------------------------GS------------------------
-VLREWIGFQQFPTATQSKLVELFAK-------------------LKEEGVDKLTILVMG
KGGVGKSSTVNSLFGERAVNVSSFQSEG--------FRPVMVSRNR-AGFTLNIIDTPGL
V----E---GGYVSYQALDMIK----RFLLN------KTIH---------VLLYVDRLDA
YRVDDLDKQIIGAISDSFGKEIWSK-----------------------SLLVLTHAQL-C
PPDDL-----SYDVFCARRSEAVLKTI---RMGARIRKRDFEDS----------------
--------------AIPVGLVENSGRCN-KNENDEKILPS-------GDAWIPSLVKEII
LVATNG------------------------------------------KKALVVDEKLVN
GSESND--------------------------RGKIFIPLILGIQW-LLVKWIQRE----
-------------------------------------------------------IKKDI
AK-GG--KYL--------------------------------------------------
---
>ptToc34-2
G-----------------------------------------------------------
---------------------------------------------------NKMTILVMG
KGGVGKSSTVNSLLGERVVNVSSFQSEG--------LRPVMVSRDR-AGFTLNIIDTPGL
V----E---GGYVNYQSLELIK----RFLLN------KTIN---------VLLYVDRLDA
YRVDDLDKQIISAITDSFGKEIWNK-----------------------SLLVLTHAQL-C
PPDDL-----SYDVFCGRRSEAVLKTI---RMGAQI-KRDFEDS----------------
--------------AIP-GLVENSGGCN-KSENDEKILPN-------GDAWIPTLVK-IV
GVATNG------------------------------------------KKSLLDQ-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>atToc33	
M---------------------------------GS------------------------
-LVREWVGFQQFPAATQEKLIEFFGK-------------------LKQKDMNSMTVLVLG
KGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGL
V----E---AGYVNHQALELIK----GFLVN------RTID---------VLLYVDRLDV
YRVDELDKQVVIAITQTFGKEIWCK-----------------------TLLVLTHAQF-S
PPDEL-----SYETFSSKRSDSLLKTI---RAGSKMRKQEFEDS----------------
--------------AIAVVYAENSGRCS-KNDKDEKALPN-------GEAWIPNLVKAIT
DVATNQ------------------------------------------RKAIHVDKKMVD
GSYSDD--------------------------KGKKLIPLIIGAQY-LIVKMIQGA----
-------------------------------------------------------IRNDI
KT-SG--KPL--------------------------------------------------
---
>bnToc33	
M---------------------------------GS------------------------
-LVREWVGFQQFPAATQEKLIEFFAK-------------------LKQKDMNSLTVVVMG
KGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGL
V----E---AGYVNHQALELIK----GFLVN------RTID---------VLLYVDRLDV
YRVDELDKQVVQAITQTFGKEIWCK-----------------------TLLVLTHAQF-S
PPDDL-----SYETFSSKRSDSLLKTI---RAGSKMGKQQFEDS----------------
--------------AIEVVYAENSGRCS-KNDKEEKALPN-------GEAWIPNLVKAIT
DVATNQ------------------------------------------KKAIHVDKKMVD
GSYSDD--------------------------KGKKLIPLIIAAQY-FVVKMIQGA----
-------------------------------------------------------IRSDI
KT-SG--KPL--------------------------------------------------
---
>ovToc33	
M---------------------------------GS------------------------
-LVREWVGFQQFPAATQEKLIGFFGK-------------------LKQKDMNSLTVLVLG
KGGVGKSSTANSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGL
V----E---AGYVNHQALELIK----GFLVN------RTID---------VFLYVDRLDV
YRVDELDKQVVQAITQTFGKEIWCK-----------------------TLLVLTHAQF-S
PPDEL-----SYETFSSKRSDSLFKTI---RAGSKMRKQQFEDS----------------
--------------AIEVVYAENSGRCS-KNEKEEKALPN-------GEAWIPSLVKAIT
YVATNQ------------------------------------------RKAIHVDKKMVD
GSYSDD--------------------------RGKKLIPLIIGAQW-FIVKMIQGA----
-------------------------------------------------------IRNDI
KT-SG--KPL--------------------------------------------------
---
>ovToc33like
M---------------------------------GS------------------------
-LVREWVGFQQFPAATQEKLIGFFGK-------------------LKQKDMNSLTVLVLG
KGGVGKSSTANSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGL
V----E---AGYVNHQALELIK----GFLVN------RTID---------VLLYVDRLDV
YRVDELDRQVVQAITQTFGKEIWCK-----------------------TLLVLTHAQF-S
PPDEL-----SYGTFSSKRSDSFLKTI---RTGSKMRKQQFEDS----------------
--------------AIEVVYAENSGRCS-KNEKEEKALPN-------GEAWIPGLVKAIT
DVATNQ------------------------------------------RKAIHVDKKMVD
GSYSDD--------------------------RGKKLIPLIMAAQY-FIVEMIQGA----
-------------------------------------------------------IRNDI
KT-SG--KPL--------------------------------------------------
---
>rrToc33	
M---------------------------------GS------------------------
-LVREWVGFQQFPAATQEKLIEFFSK-------------------LKQKDMNSLTVVVMG
KGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPDL
V----E---AGYVNHQALELIK----GFLVN------RTID---------VFLYVDRLDV
YRVDELDKQVVQAITQTFGKEIWCK-----------------------TLLVLTHAQF-S
PPDDL-----SYETFSSKRSDSLLKTI---RAGSKMRKQQFEDS----------------
--------------AIEVVYAENSGRCS-KNDKDEKALPN-------GEAWIPNLVKAIT
DVATIQ------------------------------------------KKAIHV------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>boToc33	
M---------------------------------GS------------------------
-IVREWVGFQQFPAATQEKLIEFFAK-------------------LKQKDMNSLTVVVMG
KGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGL
V----E---AGYVNHQALELIK----GFLVN------RTID---------VLLYVDRLDV
YRVDELDKQVVQAITQTFGKEIWCK-----------------------TLLVLTHAQF-S
PPDDL-----SYETFSSKRSDSLLKTI---RAGSKMGKQQFEDS----------------
--------------AIEVVYAENSGRCS-KNDK---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>thToc33	
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------LDLIK----GFLVN------RTID---------VLLYVDRLDV
YRVDELDKQVVQAITQTFGKEIWCK-----------------------TLLVLTHAQF-S
PPDEL-----SYETFSSKRSDSLLTTI---RAGAKMRKQQFEDS----------------
--------------AIAVVYAENSGRCS-KNEKEEKALPN-------GEAWIPNLVKSIT
DVATNQ------------------------------------------KKAIHVDNKMVD
GSQSDD--------------------------KGKKLIPLIIGAQY-FIVKMIQGA----
-------------------------------------------------------IRNDI
KI-SG--KPV--------------------------------------------------
---
>brToc33	
M---------------------------------GS------------------------
-LVREWVGFQQFPAATQEKLIEFFTK-------------------LKQKDMNSLTLVVMG
KGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGL
V----E---AGYVNHQALELIK----GFLVN------RTID---------VLLYVDRLDV
YRVDELDKQVVQAITQTFGKEIWCK-----------------------TLLVLTHAQF-S
PPDDL-----SYETFSSKRSDSLLRTI---RAGSKMGETTV-------------------
------------------------GFCN--------------------------------
--------------------------------------------------------GCVC
GETVED------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>grToc34	
M---------------------------------GT------------------------
PLPREWLGLQQFPAATQTKLFELLGK-------------------LKQENVNTLTIVVMG
KGGVGKSSTINSLIGEQVVRVTAFQSEG--------LRPVMVSRSW-AGFTLNVIDTPGL
V----E---AGYVNHQALELIK----GFLLN------KTID---------VLLYVDRLDV
YRVDNLDKQIIRAITNSFGKEIWRK-----------------------SLLVLTHAQL-C
PPDGL-----NYDVFSSKRSEGVLKAI---RMGARIRKMDLEDS----------------
--------------VIPVVLVENTGRCN-KNDIDEKILPN-------GEAWVPNFGKSH-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>amToc34	
M---------------------------------AA------------------------
QLIKEWSAIQQFPAATQEKLVDLLGK-------------------LKNQDVNTLTILVMG
KGGVGKSSTINSIIGERVVTVSAFQSET--------PRPVMVSRSR-SGFTLNVIDTPGL
V----E---GGYVNDQVLETIKSFLGRFLMN------KTID---------VLLYVDRLDA
YRVDNLDKQIVKAITESFGKEIWHK-----------------------AVVVLTHAQL-S
PPDAL-----SYEEFFSRRSDSLLKFV---CQGAGINKKDLKNF----------------
--------------DIPVALVEN-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>laToc34	
M---------------------------------TS------------------------
PITREWAGFNTFPPETQTKLLELLGR-------------------LKEKNVNKLTILVMG
KCGVGKSSTVNSIIGERAVVINPFQSEG--------LRPVMVSRSR-TEFTLNIIDTPGI
I----E---GGCINNQALELIK----HFLLN------KTID---------ILLYVDRLDT
YRVDELDKMVVRAITNSFGKEIWNR-----------------------ALIVLTHAQL-S
PPDGL-----PYDEFVSKRSEALLKVV---HQGARLKKGDLASS----------------
---------------IPSV-----SRCN-KNDSGEK-GPN-------GTA----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>peToc34	
------------------------------------------------------------
------------------------------------------------------------
------------IVGERVAIVSAFQSEA--------MRPLICSRSR-AGFTLNIIDTPGL
I----E---GGFVNDHALDLIK----RFLIN------KTID---------ILLYVDRLDG
YRVDDLDMQVTKAISKSFGQQIWRR-----------------------GLVVLTHAQL-S
PPDEL-----RYADFVDRRSAILQAVV---RKAAGFKKSETQ------------------
---------------IPVVLVENSGRCN-TNSGGEKVLSD-------GTVWLPYLVEKIV
EVATNG------------------------------------------SKPILIDKKLIE
GPDANQ--------------------------WGKRWIPLFLAFQYFFIVKPIRRG----
-------------------------------------------------------IQKDI
QR-EKSERPAWEIYDET-----------------------------------------GD
KTI
>ppToc34-1
M---------------------------------AA------------------------
TPAREWTGLQQFPVATQTALHNILGT-------------------LRQQNKESLTVLVVG
KGGVGKSSTVNSIVGERVTIVSAFQSET--------LRPLQCARSR-AGFTLNIIDTPGL
V----E---GGCINDQALDIIK----RFLLS------KTID---------VVLYVDRLDG
YRVDNLDRQVIRGLARSFGPNFWRL-----------------------AVIVLTHAQF-S
PSDGV-----NYTEFVEKRSAALQAAI---RQEAGLKKDEKE------------------
---------------VPYALVENSGRCN-TNDGGEKILPN-------GTVWLPALVERIV
EVATGT------------------------------------------TDSVFVDKKLID
GPNANE--------------------------WGKWWIPVLAVAQYFLVVMPIRKA----
-------------------------------------------------------IEKDL
AE-EKNQRPQWEIRAEEFRRN-TSLYDDDQVDEQAISQALEQDDGLSGQPSSFVDEDDDD
DEF
>ppToc34-3
M---------------------------------AA------------------------
TQAREWTGLLQFPVATQTALHNILGK-------------------LRQQKKESLTVLVVG
KGGVGKSSTVNSIIGERVTVVSAFQSET--------LRPLQCARTR-AGFTLNVIDTPGL
I----E---GGCINDQALDIIK----RFLLN------KTID---------VVLYVDRLDG
YRVDNLDKQVIRALARSFGPNFWRI-----------------------AIIALTHAQL-S
PPDGV-----DYTEFVNNRSAALRAAI---RQEAGFKKSEGE------------------
---------------ISYMLVENSGRCN-TNSEGEKVLPN-------GSVWLPALVDRIA
EVATGA------------------------------------------TPSIHVDQKLID
GPNANG--------------------------KGKWWIPLIILAQYFLIVRPIRSA----
-------------------------------------------------------IEKDL
IE-EEKQRPQWQIRAEEFVRPIASLYEDDQVDEQAIRQALKQ-GALNDQMDSFVEDDEDD
DEY
>ppToc34-2
M---------------------------------AT------------------------
VSEKEWTGFQGLPAATQIILHTLLAK-------------------LRKQKVDKITIVLLG
KGGVGKSSIVNSLFSERVAAVSAFRSET--------LRPRQYSRSK-DGFKLTVIDTPGF
V----E---AGRV-DAALNSIR----RYLLG------KTIN---------VVLYVDRLDG
PREDKVDVKISRAISQAFGPQIWPH-----------------------VIVVFTHAEI-H
LED-V-----TYSEFVSRRSAALRNII---LKESRFKTVNTK------------------
---------------VPFVLVENCSRCS-ENGEHEKILPD-------GTVWLPVLFEALV
DLVLGS------------------------------------------KKPILIDEKMIG
IPKGNP--------------------------LGSIWMPLVLLAQFVLIWRPIRKA----
-------------------------------------------------------IDRDL
VE-EAQRHSP--------------------------------------------------
---
>olToc34
MSEEEYSEDEDYVSSEGEGVEGTEEGGEGQPAQAAAP----------------------V
LGPKEWVGLSSMPAATQSALLETLGK-------------------LRERNVNEMTVIFIG
KQGVGKSSTVNTLLNERVAPSSPFQPEN--------VRPLLAGRVA-AGFTLNVLDTPGL
L----E---GDSVSARGLMALR----AALNG------RKVD---------AFVFTDRLDT
WRVDNADKAIFTSLAENFGAELWER-----------------------TVLGFSHAQT-T
PTDGR-----PYEEFVNARVEQYRKAI---RSTLNM-----PNL----------------
--------------ALPFALIENGSRCK-TNGNGEKVV-N-------DRPWLSDMVSTMV
EMACSK------------------------------------------DGYEYDHGKAGK
KLDPNN--------------------------KHKIWILPLFLFQAFVLRPLVIGQ----
-------------------------------------------------------IRRDI
KK-ADEKKQRAAAAKH--------------------------------------------
---
>otToc34
MSDEEYSEDE-YVSSEGEGAEGRDVEPQ---AQQAAP----------------------V
LGPKEWVGLSSMPAATQQALLETLGK-------------------LRERNVNEMTVIFIG
KQGVGKSSTVNTLLNERVAPSSPFQPEN--------ARPLLAGRVA-AGFTLNVLDTPGL
L----D---GDSISARGLMALR----AALNG------RKVD---------AFIFTDRLDT
WRVDNSDRAIFTALAENFGAELWER-----------------------TVLGFSHAQT-T
PPDGK-----PYEEFVNARVEQYRKAI---RQTLGM-----PNL----------------
--------------TLPFALIENGSRCK-ANAAGEKVV-N-------ERPWLTDMVGTMV
EMACAK------------------------------------------ESYEYDHKKAGK
KLDPNN--------------------------KYKIWMLPLFLFQAFVLRPLMIGQ----
-------------------------------------------------------IRRDI
RK-SDEDKKKKSARPAPKK-----------------------------------------
---
>crToc34
MAQPPRPAEEYDDDVQEDEDELKEGELDDDESHEAASEGGEAAAGDEEAEDDEQDEEDGD
EDSQPWAGLNRLP--ERDDMLDILNE-------------------LRAEGRKQLTVLLLG
KSSVGKSSLINSLLGEAVVRVQAFKLQADTDITTTVVRQVAVGNSEVDGFRLKLIDTCGL
E----DPEAGDTVNLGALSKIA----EDVRG------VGID---------VVLYCDRLDL
YRVDPLDKAIIDAISSTFGRGIWRR-----------------------TVVALTHANLVQ
TPPGT-----DYDSFVNGRVRLIRGAV---RGPLFFR------P----------------
--------------SLPVALVENSETCPVSSESGFRVLPD-------GEPWLVALVSQLV
DMAAAR------------------------------------------RRPYKYHPRLSS
KP--SH--------------------------RFRWLLPVAIAAEVLFYRRFLHPR----
-------------------------------------------------------LDDNQ
RRVEREEERVWALRGQQRRALGLHRPHRPDKDAAWRLEQMYDDD----------------
---
>pwToc34
V-----------------------------------------------------------
-----------------LALAECSGD---------------------RQRTGASRCCCWE
REAWARVATVNSLLGERAAVVSSFQATG--------LGVHMHTRTLPGGFALNLIDTPSL
L----D---QDSVSTSRLEQIG----SAIKG------VKID---------AVLFLDRLDV
YSTDTLDEQVVDGVTAYFGEDMWDH-----------------------AVLGLTRATSSA
PPLST-----DFGEWVVERSLQLQSLIAKARAQYAPRRRRGEAP----------------
--------------PLTPAGCRESQECP-RKLRGSGSSPA-------TAPGSPTCMPRWR
SAATGA------------------------------------------GQAWLHDAARR-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>Thalassiosira_pseudonana gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335] >gi|220973246|gb|EED91577.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
M-------------------------------------------AFFRRALLQGSLAVNN
LTHDTWHQTPRAITSLLNHQQSCSLHSTPITLNNPTSSSAATTQSDKPAPQKRLDVAIVG
APNAGKSQLLNSLIGSKVAAVSRKRHTT--------RTGILGARTF-DDTQLVFIDTPGF
L----H---HEMSVKEGV--------RKLLGEASSEMESAD---------FVLLVVDAAR
KMEDDLRRTLVTLMFLALRSKGRNE-----------------------FAVVLNKVDLVS
PKEKLLMTAADVGSMAESCIRQFLNQR---RSPSKVKFGELVDTVLKNYANEDGFDGVHD
DDIELFATLAPEFFFTSAIVKDDEGVDDVLGLLLERATLSDQWIVDAGSATGMTPVEQVE
EIIREKIYRCLHREVPHSVQQQNRMFQLYKPNESKTKSTDGSDVDEDI-KILRIRQDLIV
RTKSHQRLVL--------------------------------------------------
------------------------------------------------------------
---GSGGKTLERIRSTALKDLEESFDCIVDLDLTVRVTKS-NQHEAILDPESVGAVSLTP
LEN
>Thalassiosira_oceanica gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M-------------------------------------------FGIRRLVVGGSVRHGG
HARGRPLPCPACPTGPDISSSASSLLSRTMTSYFDGGPSAPET--SRPKQQRRLDIAIVG
APNAGKSQLLNSLVGSKVAAVSRKRHTT--------RSGILGARTF-GDTQLVFIDTPGF
L----H---HSKGAREGV--------RNLLSEASAEMMNAD---------FALLVVDAAK
TIDQDLKRTLVTLMMLALRSTGREE----------GSRVFSDQRHLGRFSVVLNKVDLVK
PKEKLLATAAEVGSLAESCVRRLLQQH---RAPVRVKMGELVDSVLERHEDEEGFAGVHE
EDYETFASVVPEFLFTSAIDPEDEGADDLLNVLLSRATPSTEFVMDPSSN-----LEQVE
EIIREKIYRCLHREVPHHVQQTNRVFKL------KQDQPPDHDVRADMGDLLQIHQDLIV
RTKSHHRLVL--------------------------------------------------
------------------------------------------------------------
---GSGGKTLQRIQTTASKDLRELFGCEVDLLLSVKLKKT-NQ-GVLLDPEEEGA-RITT
LHD
>Phaeodactylumgi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217410895|gb|EEC50824.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M---------------------------------------------------RPTFIRTA
LVTFRWSGGPKISRSDRVRLSSTTIGST-----------------PSLEDRKRLDVAIVG
LPNAGKSQLLNVLTQSTVAAVSRKRHTT--------RDGILGARTV-DDTQLYFVDTPGF
L----R---QSQAKKEGLN-------RDLVVTASSEMENVD---------FSLLVVDAAR
RMTDDYEETLVALMLAALRSQGRLEFDVHSAEEVQSIRTPKGGTNPAKFAVVLNKVDLVH
PKSNLMDLAVNIGTLAEQCIKF--------------------------DAKESGKEELFL
DSAYLQESL-PMFFYISAL--KQRGVQDLLEFLLERATPSTSWEVEAGEATPMTMKERIE
EVIREKIYRCLHKEVPHSIRQENRVLQQ------------GKDEDGNI--VLVIHQDLIV
RSKSHQELVH--------------------------------------------------
------------------------------------------------------------
---GGGGRTLERIRETAARGLEKIFFCNVVLHLHVKLPRSKNQRWSI-------------
---
>Phaeodactylum_2 gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217406280|gb|EEC46220.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
-----------------------------------------------------------G
APNMGKSTLLNALLEEDLCIATARPQTT--------RHAILGLMST-DKCQVCLVDTPGV
I----E---DPAYELQ----------EGMMEAVTGAVATSD---------VLLVVT--DV
FSTPIPDDELFLKVQRTRKP----------------------------VLVAINKIDLAK
KVNKAAEENRDKTVTVEEAVAFWRAQL-----PNALCILPLSAS-----------QGINN
VGVVAMRRILTELLPISPPLYDPETLTD----RPERFIAS--------------------
EIVRSALFQVLKKELPYCCEVRIREFKEPKEE----------------GEVIRIAADVLV
ERDSQKVIVI--------------------------------------------------
------------------------------------------------------------
---GKNGAQVKEIGVIAREKLEAFFRHQIFLNLSVKVDKDWRKNTRKLTEYGYMKPKR--
---
