>cmToc34
M---------------------------------------------DSETPTKNEAEQRA
SPDRTGQVTQRPVSLFRKNGT---------------FAYPLEDSDVYEEQVLALEDVPEP
TAQAILRLALA--AERQGVPRLRFLVVGAPGVGKSSLINTLLNENLCSVSAWERGT----
----KNAQVCARQVD-SVVIEFIDTPGIAPCRRS---GLE--ASRRQVQRLR----KLLD
ARGADEHPYLRSFHAILYVMRLDDTRPDLVDYHNWKVLMEFFGA----------------
--------------------------EVLRHMMVVFTHGQS-LPPDSLSYPEYV------
------RGRRDYVYLLI---ERLTG-----------------------------------
PLKAVRFPVFVAENSSKCPVIEETGERKLPDDTPWITQLYDGIRRFVFPLEADLF---GM
ETGPEDTQVLVYIYDKRRSRADERYPRSPLQALIRNPWFLRAVQFCGAMLLRSYMIRQEH
ERFNP-KPHHPEPIIRDANNAFAVASRRANDHRLFTPSIDEDEESFFRMNGNDDFVSRLR
NRPGEVDLDELDVERIESPDGRFVEYWYT-EKDNPEMVRMYRLEIRDDPNEERESRQDRI
PISKDQH
>acToc34	
M-----------------------------------------------------------
------------------------------------------S--FLTREWVGIQQFPAA
TQTKLHEILGK--LKQENVNTMTILVMGKGGVGKSSTVNSILGERVATVSAFQSEG----
----LRPIMCSRTRA-GFTLNVIDTPGIV----E---GGY--VNEQALEIIK----RFLL
DKTID---------VLLYVDRLDSYRVDNLDKQVVKAITDFLGK----------------
--------------------------EIWQRGVVVLTHAQL-SPPDGLNYDDYL------
------EKRSDALLKYV---RLGAGIKKK-------------------------------
ELQGKGIPVALVENSGRCK-TNEDGEKILPNGTAWIPNLVQQSQT---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>vvtoc34	
M-----------------------------------------------------------
-----------------------------------------AS--QLIREWTGIQQFPPV
TQTKLIELLGK--LKQENVSTLTILVMGKGGVGKSSTVNSIIGERAVAVSAFQSEG----
----PRPVMVSRSRA-GFTLNIIDTPGLV----E---GGY--VNDQALEIIK----RFLL
NKTID---------VLLYVDRLDAYRVDNLDRQVVKAITDSFGK----------------
--------------------------EIWRRGVVVLTHAQL-SPPDGLNYEDFF------
------SKRSEALMKVV---RSGARLRKQ-------------------------------
DIQDSGIPVVLVENSGRCH-KNESDEKILPNGTAWIPNLVKTITDAVSNGSKGILVDKKL
IEGPNPNE--------------------------RGKLLIPFILAFQYFFIVKRIQRAIK
SDMAK-ER--KAPWESREANRYEP------------------------------------
------------------------------------------------------------
-------
>stToc34-2
M-----------------------------------------------------------
-----------------------------------------AS--QIIREWAGIQQFPAA
TQSKLLELLGK--LKQENVSTLTILVMGKGGVGKSSTVNSIIWERAVAVSAFQSET----
----PRPVMVSRSRA-GFTLNIIDTPGLV----E---GGY--VNDQALDLIK----KFLL
NKTID---------VLLYVDRLDAYRVDNLDKQIVKAITDSFGK----------------
--------------------------EIWRRGIVVLTHAQL-SPPDGLTYDEFT------
------SRRSEALLKIV---RMGARIRKQ-------------------------------
DIQAASIPVVLVENSGRCN-KNESDEKILPSGTAWIPNLVQTITDAVLSGSKGILVDQKL
IEGPNPNN--------------------------RGKVLIPFILAFQYFFVVKRIQKSIK
NDIAR-ES--RPAWA---------------------------------------------
------------------------------------------------------------
-------
>leToc34-2
M-----------------------------------------------------------
-----------------------------------------AS--QIIREWAGIQQFPAA
TQSKLLELLGK--LKQENVSTLTILVMGKGGVGKSSTVNSIIGERAVAVSAFQSET----
----PRPVMVSRSRA-GFTLNIIDTPGLV----E---GGY--VNDQALDLIK----KFLL
NKTID---------VLLYVDRLDAYRVDNLDKQIVKAITDIFGK----------------
--------------------------EMWCRGIVVLTHAQL-SPPDGLTYEEFT------
------SRRSEALLKIV---RMGARIRKQ-------------------------------
DIQAASIPVVLVENSGRCN-KNESDEKILPSGIAWIPNLVQTITDAVLSGSKGILVDQKL
IEGPNPNN--------------------------RGKVLIPFILAFQYFFVVKRIQRSIK
NDIAR-ET--RPSWA---------------------------------------------
------------------------------------------------------------
-------
>leToc34-1
M-----------------------------------------------------------
-----------------------------------------AS--QVIREWVGFQQFPSA
TQSKLIELIRK--LKQESVSTVTILVMGKGGVGKSSTVNSILGERAVAVSAFQSET----
----PRPVMVSRSWA-EFTLNIIDTPGLV----E---GGY--VNDQALDLIK----RFLL
NKTID---------VLLYVDRLDTYRVDNLDRQIVKAITDSFGK----------------
--------------------------GIWRRGLVVLTHAQV-SPPDGLSYDEFT------
------SRRSEALLKIV---RLGARMKKQ-------------------------------
EIKAASIPLVCVENSGRCN-KNELDEKILPNGTAWIPSILQTITEVVVSQSKGILIDQKL
IEGPNPNN--------------------------KGKLLIPLIATFQYFFVVKRIQTWIK
NDISR-EN--RPSWA---------------------------------------------
------------------------------------------------------------
-------
>stToc34-1
M-----------------------------------------------------------
-----------------------------------------AS--QVIREWVGFQQFPSA
TQSKLIELIRK--LKQESVSTLTILVMGKGGVGKSSTVNSILGERAVAVSAFQSET----
----PRPVMVSRSWA-EFTLNIIDTPGLV----E---GGY--VNDQALDLIK----RFLL
NKTID---------VLLYVDRLDTYRVDNLDRQIVKAITDSFGK----------------
--------------------------EIWHRGLVVLTHAQV-SPPDGLSYDEFT------
------SRRSEALSKIV---RLGARIRKQ-------------------------------
EVKASSVPIVCVENSGRCN-KNELDEKILPNGTAWIPNLLQTITEVVASESKGILVDQKL
IEGPNPNN--------------------------KGKLLIPLIAAFQYFFVVKRIQKWIK
NDIAR-ET--RPSWA---------------------------------------------
------------------------------------------------------------
-------
>mtToc34-1
M-----------------------------------------------------------
-----------------------------------------ASQQQQVREWSGINTFAPA
TQTKLLELLGK--LKQEDVNSLTILVMGKGGVGKSSTVNSIIGERVVAISPFQSEG----
----PRPVMVSRARA-GFTLNIIDTPGLI----E---GGY--INDMALDIIK----RFLL
DKTID---------VLLYVDRLDAYRVDNLDKLVAKAITDSFGK----------------
--------------------------GIWNKAIVALTHAQF-SPPDALAYDEFF------
------SKRSESLLQII---KSGASLKKD-------------------------------
DAQASAIPVVLIENSGRCN-KNETDEKVLPNGIAWIPHLVHTITEIALNKSESIFVDKNL
IEGPNPNQ--------------------------RGKLWIPVLFALEFLLIMKPIEGLIK
NDVAN-EK--KPSWETRDVGVKKE------------------------------------
-----------------------------------------------TREVGQKDMRKER
RGGAVRR
>psToc34	
M-----------------------------------------------------------
-----------------------------------------ASQQQTVREWSGINTFAPA
TQTKLLELLGN--LKQEDVNSLTILVMGKGGVGKSSTVNSIIGERVVSISPFQSEG----
----PRPVMVSRSRA-GFTLNIIDTPGLI----E---GGY--INDMALNIIK----SFLL
DKTID---------VLLYVDRLDAYRVDNLDKLVAKAITDSFGK----------------
--------------------------GIWNKAIVALTHAQF-SPPDGLPYDEFF------
------SKRSEALLQVV---RSGASLKK--------------------------------
DAQASDIPVVLIENSGRCN-KNDSDEKVLPNGIAWIPHLVQTITEVALNKSESIFVDKNL
IDGPNPNQ--------------------------RGKLWIPLIFALQYLFLAKPIEALIR
RDIAT-ET--KPAWETRDVGDRK-------------------------------------
------------------------------------------------------------
-------
>pcToc34	
M-----------------------------------------------------------
-----------------------------------------AS--QIIREWSGINTFAPA
TQTKLLELLGK--LKQENVNSLTILVMGKGGVGKSSTVNSIIGERVVSISPLQSEG----
----PRPVMVSRSRA-GFTLNIIDTPGLI----E---GGY--INDMALDIIK----RFLL
NKTID---------VLLYVDRLDVYRVDNLDKLVAKAITDSFGK----------------
--------------------------GIWNKAIVALTHAQF-SPPDGLPYEDFF------
------SQRSEALLRVL---RSGAKIKKE-------------------------------
VFQAASMP----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>asToc34	
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------SAFQSEG----
----LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--INEQAVEIIK----RFLL
EKTID---------VLLYVDRLDTYRMDTLDEQVIRAITTSFGK----------------
--------------------------AIWRRTLVVLTHAQL-SPPDGLDYNDFL------
------TRRSESLLRYI---RSGAGIGKR-------------------------------
ESADYPLPLALVENSGRCK-TNENGAKILPDGTPWIPNLMKEITMVVSNGSKPIHVDQKL
IDGPNPNN--------------------------RWKKYIPLILAVQYFFVVKGIRRAIH
SDIAN-GK--LDDWEQRYRDLVGS------------------------------------
-----------------------------------------------GNPVDQKVSSSRN
PRPEAGQ
>osToc34	
M-----------------------------------------------------------
----------------------------------------SAA--PIPREWVGLQQFPAA
TQTKLHELLGK--LKEENVSTLTILVMGKGGVGKSSTVNSIVGERVATVSAFQSEG----
----LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--INEQAVEIIK----RFLL
GKTID---------VLLYVDRLDAYRMDTLDDQVIRAVTNSFGK----------------
--------------------------AIWRRTLVVLTHAQL-SPPDGLDYNDFF------
------TKRSESLLRYI---RAGAGVSKR-------------------------------
ELGDFPLPIALVENSGRCK-TNENGEKVLPDGTPWIPNLMKEITTVVSNGSKSIHVDQKL
IDGPNPNN--------------------------RWKMFIPLILMVEYFLVVKGIRRAIH
ADISN-GK--LDDWEQRYRDLVGS------------------------------------
-----------------------------------------------KDPVDQKGSSSGN
RK----A
>sbToc34	
M-----------------------------------------------------------
-----------------------------------------AS--PIPREWAGLQQFPAA
TQTKLHELLGK--LKEEDVSTLTILVMGKGGVGKSSTVNSIVGERVTTVSAFQSEG----
----LRPTMCSRTRA-GFTLNIIDTPGLI----E---GGY--INEQAVDIIK----RFLL
GKTID---------VLLYVDRLDAYRMDTLDEQVIRAITNSFGK----------------
--------------------------DIWRRSLVVLTHAQL-SPPDGIDYNDFF------
------TRRSEALLRYI---RSGAGINKR-------------------------------
EYGDFPLPIALVENSGRCK-ANEHGEKILPDGTPWVPNLM--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>zmToc34-1
M-----------------------------------------------------------
-----------------------------------------AS--PIPREWVGLQQFPPA
TQTELHELLGK--LKEEDVSTLTILVMGKGGVGKSSTVNSIVGERIATVSAFQSEG----
----LRPMMWSRTRA-GFTLNIIDTPGLI----E---GGY--INEQAVDIIK----RFLL
GKTID---------VLLYVDRLDAYRMDTLDGQVIRAITNSFGK----------------
--------------------------DIWRRSLVVLTHAQL-SPPDGIEYNDFF------
------TRRSEALLRYI---HSGAGIKKR-------------------------------
EYGDFPLPIALVENSGRCK-TNEHGEKILPDGTPWVPKLMKEITVVISNGSKPIHVDQKL
IDGPNPNN--------------------------RWKMFIPIILAVEYFLVVKGIRRAIH
ADIAN-GK--VDDWEQRYRDLVGS------------------------------------
-----------------------------------------------RDPVEQKGSTTRN
RK----A
>zmToc34-2
M-----------------------------------------------------------
-----------------------------------------AS--PIPREWVGLQQFPAA
TQTKLHELLGK--LKEEDVSTLTILVMGKGGVGKSSTVNSIVGERVASVSAFQSEG----
----LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--INEQAVDIIK----RFLL
GKTID---------VLLYVDRLDAYRMDTLDEQVIRAITNSFGK----------------
--------------------------DIWRRSLVVLTHAQL-SPPDGIDYNDFF------
------TRRSEALLRYI---HSGAGINKR-------------------------------
EYGDFPLPIALVENSGRCK-TNEHGEKILPDGTLWVPNLMKEITVVISNGSSPIHVDQKL
IDGPNPNN--------------------------RRKLFIPLILAVEYFLVVKGIRRAIH
ADIAN-GK--VDDWEQRYRDLVGS------------------------------------
-----------------------------------------------RDLVEQKGSTSRN
RK----A
>soToc34	
M-----------------------------------------------------------
-----------------------------------------AS--PIPREWVGLQQFPAA
TQTKLHELLGK--LKEEDVSTLTILVMGKGGVGKSSTVNSIVGERVTTVSAFQSEG----
----LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--INEQAVDIIK----RFLL
GKTID---------VLLYVDRLDAYRMDTLDEQVIRAITNSFGK----------------
--------------------------DIWRRSLVVLTHAQL-SPPDGIDYNDFF------
------TRRSKALLPYI---RSGAGIQPT-------------------------------
RIWGFP----------PCQ-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>hvToc34	
M-----------------------------------------------------------
-----------------------------------------AA--PIPREWVGLQQFPAA
TQTKLHELLGK--LKEENVSTLTILVMGKGGVGKSSTVNSIVGERVANVSAFQSEG----
----LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--INEQAVEIIK----RFLL
EKTID---------VLLYVDRLDTYRMDTLDEQVIRAITSSLGK----------------
--------------------------AIWRRTLVVLTHAQL-SPPDGIDYNDFL------
------ARRSESLVRYI---RSGAGIGKR-------------------------------
EYADFPLPIALAEDSGKGR-TNENGA--ILDGNSWDSKLE--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>brToc34	
M-----------------------------------------------------------
----------------------------------------AAL--QMSREWIGIQQFPPA
TQSKLIEILNK--FKEEDVSSLTVLVMGKGGVGKSSTVNSVIGEKAAAVSTFQSEG----
----LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--VNDQAVNLIK--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>rrToc34	
M-----------------------------------------------------------
----------------------------------------AAL--QMSREWIGIQQFPPA
TQSKLLEILGK--FEEEDVSSLTVLVMGKGGVGKSSTVNSVIGERAAAVSTFQSEG----
----LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--VNDQAVNLIK----GFLP
NKTID---------VLLYVDRLDVYRVDDLDKQVVTAITDAFGK----------------
--------------------------EIWKKSALVLSHAQF-SPPDGLNYDLFV------
------SRRSDALLKLI---YASAQLK---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>bnToc34	
M-----------------------------------------------------------
----------------------------------------AAL--QMSREWIGIQQFPPA
TQSKLLEILGK--FKEEDVSSLTVLVMGKGGVGKSSTVNSVIGEKAAAVSTFQSEG----
----LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--VNDQAVNLIK----RFLL
NMTID---------VLLYVDRLDVYRVDDLDKQVVTAITDAFGK----------------
--------------------------EIWKKSALVLSHAQF-SPPDGLNYDLFV------
------SRRSDALLKLI-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>boToc34	
M-----------------------------------------------------------
----------------------------------------AAL--QVSREWIGIQQFPPA
TQSKLLEILGK--FKEEDVSSLTVLVMGKGGVGKSSTVNSVIGEKAAAVSTFQSEG----
----LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--VNGQAVNLIK----RFLL
NMTID---------VLLYVDRLDVYRVDDLDKQVVTAITDAFGK----------------
--------------------------EIWKKSALVLSHAQF-SPRDG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>atToc34	
M-----------------------------------------------------------
----------------------------------------AAL--QTLREWIGIQQFPPA
TQSKLLEILGK--YKEEDVSSLTVLVMGKGGVGKSSTVNSVIGEKAAAVSTFQSEG----
----LRPTLVSRTRS-GFTLNIIDTPGLI----E---GGY--VNDQAINIIK----RFLL
NMTID---------VLLYVDRLDVYRVDDLDRQVVGAITDAFGK----------------
--------------------------EIWKKSALVLTHAQF-SPPDGLNYNHFV------
------SKRSNALLKVI---QTGAQLKKQ-------------------------------
DLQGFSIPVILVENSGRCH-KNESDEKILPCGTSWIPNLFNKITEISFNGNKAIHVDKKL
VEGPNPNE--------------------------RGKKLIPLMFAFQYLLVMKPLVRAIK
SDVSR-ES--KLAWELRDSGLASR------------------------------------
-----------------------------------------------RS-----------
-------
>tsToc34	
P-----------------------------------------------------------
------------------------------------------------------------
-------------TRPEDVSSLTVLVRGKGGVGKSSTVNSVIGEKAAAVSTFQSEG----
----LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--VNDGAVNLIK----GFLL
NKTID---------VLLYVDRLDVYRVDDLDRQVVTAITDAFGK----------------
--------------------------EIWKKSALVLSHAQF-SPPDGL-YDLFV------
------SRRSDS--SVI---CAGAQLKKQ-------------------------------
DLQGSSIPVILVENSGRC------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>lsToc34	
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GERAVTVSAFQSEA----
----LRPTMVSRERS-GFTLNIIDTPGIV----E---GGY--VNDQALEIIK----RFLL
NKTID---------VLLYVDRLDAYRVDTLDGQIVKAISNSFGQ----------------
--------------------------QIWRKAIVVLTHAQL-SPPDCLSYDEFL------
------AKRSEALLKVV---YRGARFRKL-------------------------------
DIENFPIPIGLVENSSRCN-KNEKDEKILPNGSAWIPSIVETITEVSLTESKSILVDQKL
IDGPNPN---------------------------RGKLFIPFIIAFQYFFV---------
------------------------------------------------------------
------------------------------------------------------------
-------
>ptToc34-1
M-----------------------------------------------------------
-----------------------------------------GS---VLREWIGFQQFPTA
TQSKLVELFAK--LKEEGVDKLTILVMGKGGVGKSSTVNSLFGERAVNVSSFQSEG----
----FRPVMVSRNRA-GFTLNIIDTPGLV----E---GGY--VSYQALDMIK----RFLL
NKTIH---------VLLYVDRLDAYRVDDLDKQIIGAISDSFGK----------------
--------------------------EIWSKSLLVLTHAQL-SPPDDLSYDVFC------
------ARRSEAVLKTI---RMGARIRKR-------------------------------
DFEDSAIPVGLVENSGRCN-KNENDEKILPNGDAWIPSLVKEIILVATNGKKLLLMRSWL
VGLSQMTG---------------------------GKIFIPLILGI--------------
------------------------------------------------------------
------------------------------------------------------------
-------
>ptToc34-3
M-----------------------------------------------------------
-----------------------------------------GS---VLREWIGFQQFPTA
TQSKLVELFAK--LKEEGVDKLTILVMGKGGVGKSSTVNSLFGERAVNVSSFQSEG----
----FRPVMVSRNRA-GFTLNIIDTPGLV----E---GGY--VSYQALDMIK----RFLL
NKTIH---------VLLYVDRLDAYRVDDLDKQIIGAISDSFGK----------------
--------------------------EIWSKSLLVLTHAQL-CPPDDLSYDVFC------
------ARRSEAVLKTI---RMGARIRKR-------------------------------
DFEDSAIPVGLVENSGRCN-KNENDEKILPSGDAWIPSLVKEIILVATNGKKALVVDEKL
VNGSESND--------------------------RGKIFIPLILGIQW-LLVKWIQREIK
KDIAK-GG--KYL-----------------------------------------------
------------------------------------------------------------
-------
>ptToc34-2
G-----------------------------------------------------------
------------------------------------------------------------
-------------------NKMTILVMGKGGVGKSSTVNSLLGERVVNVSSFQSEG----
----LRPVMVSRDRA-GFTLNIIDTPGLV----E---GGY--VNYQSLELIK----RFLL
NKTIN---------VLLYVDRLDAYRVDDLDKQIISAITDSFGK----------------
--------------------------EIWNKSLLVLTHAQL-CPPDDLSYDVFC------
------GRRSEAVLKTI---RMGAQI-KR-------------------------------
DFEDSAIP-GLVENSGGCN-KSENDEKILPNGDAWIPTLVK-IVGVATNGKKSLLDQ---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>atToc33	
M-----------------------------------------------------------
-----------------------------------------GS---LVREWVGFQQFPAA
TQEKLIEFFGK--LKQKDMNSMTVLVLGKGGVGKSSTVNSLIGEQVVRVSPFQAEG----
----LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--VNHQALELIK----GFLV
NRTID---------VLLYVDRLDVYRVDELDKQVVIAITQTFGK----------------
--------------------------EIWCKTLLVLTHAQF-SPPDELSYETFS------
------SKRSDSLLKTI---RAGSKMRKQ-------------------------------
EFEDSAIAVVYAENSGRCS-KNDKDEKALPNGEAWIPNLVKAITDVATNQRKAIHVDKKM
VDGSYSDD--------------------------KGKKLIPLIIGAQY-LIVKMIQGAIR
NDIKT-SG--KPL-----------------------------------------------
------------------------------------------------------------
-------
>bnToc33	
M-----------------------------------------------------------
-----------------------------------------GS---LVREWVGFQQFPAA
TQEKLIEFFAK--LKQKDMNSLTVVVMGKGGVGKSSTVNSLIGEQVVRVSPFQAEG----
----LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--VNHQALELIK----GFLV
NRTID---------VLLYVDRLDVYRVDELDKQVVQAITQTFGK----------------
--------------------------EIWCKTLLVLTHAQF-SPPDDLSYETFS------
------SKRSDSLLKTI---RAGSKMGKQ-------------------------------
QFEDSAIEVVYAENSGRCS-KNDKEEKALPNGEAWIPNLVKAITDVATNQKKAIHVDKKM
VDGSYSDD--------------------------KGKKLIPLIIAAQY-FVVKMIQGAIR
SDIKT-SG--KPL-----------------------------------------------
------------------------------------------------------------
-------
>ovToc33	
M-----------------------------------------------------------
-----------------------------------------GS---LVREWVGFQQFPAA
TQEKLIGFFGK--LKQKDMNSLTVLVLGKGGVGKSSTANSLIGEQVVRVSPFQAEG----
----LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--VNHQALELIK----GFLV
NRTID---------VFLYVDRLDVYRVDELDKQVVQAITQTFGK----------------
--------------------------EIWCKTLLVLTHAQF-SPPDELSYETFS------
------SKRSDSLFKTI---RAGSKMRKQ-------------------------------
QFEDSAIEVVYAENSGRCS-KNEKEEKALPNGEAWIPSLVKAITYVATNQRKAIHVDKKM
VDGSYSDD--------------------------RGKKLIPLIIGAQW-FIVKMIQGAIR
NDIKT-SG--KPL-----------------------------------------------
------------------------------------------------------------
-------
>ovToc33like
M-----------------------------------------------------------
-----------------------------------------GS---LVREWVGFQQFPAA
TQEKLIGFFGK--LKQKDMNSLTVLVLGKGGVGKSSTANSLIGEQVVRVSPFQAEG----
----LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--VNHQALELIK----GFLV
NRTID---------VLLYVDRLDVYRVDELDRQVVQAITQTFGK----------------
--------------------------EIWCKTLLVLTHAQF-SPPDELSYGTFS------
------SKRSDSFLKTI---RTGSKMRKQ-------------------------------
QFEDSAIEVVYAENSGRCS-KNEKEEKALPNGEAWIPGLVKAITDVATNQRKAIHVDKKM
VDGSYSDD--------------------------RGKKLIPLIMAAQY-FIVEMIQGAIR
NDIKT-SG--KPL-----------------------------------------------
------------------------------------------------------------
-------
>rrToc33	
M-----------------------------------------------------------
-----------------------------------------GS---LVREWVGFQQFPAA
TQEKLIEFFSK--LKQKDMNSLTVVVMGKGGVGKSSTVNSLIGEQVVRVSPFQAEG----
----LRPVMVSRTMG-GFTINIIDTPDLV----E---AGY--VNHQALELIK----GFLV
NRTID---------VFLYVDRLDVYRVDELDKQVVQAITQTFGK----------------
--------------------------EIWCKTLLVLTHAQF-SPPDDLSYETFS------
------SKRSDSLLKTI---RAGSKMRKQ-------------------------------
QFEDSAIEVVYAENSGRCS-KNDKDEKALPNGEAWIPNLVKAITDVATIQKKAIHV----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>boToc33	
M-----------------------------------------------------------
-----------------------------------------GS---IVREWVGFQQFPAA
TQEKLIEFFAK--LKQKDMNSLTVVVMGKGGVGKSSTVNSLIGEQVVRVSPFQAEG----
----LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--VNHQALELIK----GFLV
NRTID---------VLLYVDRLDVYRVDELDKQVVQAITQTFGK----------------
--------------------------EIWCKTLLVLTHAQF-SPPDDLSYETFS------
------SKRSDSLLKTI---RAGSKMGKQ-------------------------------
QFEDSAIEVVYAENSGRCS-KNDK------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>thToc33	
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------LDLIK----GFLV
NRTID---------VLLYVDRLDVYRVDELDKQVVQAITQTFGK----------------
--------------------------EIWCKTLLVLTHAQF-SPPDELSYETFS------
------SKRSDSLLTTI---RAGAKMRKQ-------------------------------
QFEDSAIAVVYAENSGRCS-KNEKEEKALPNGEAWIPNLVKSITDVATNQKKAIHVDNKM
VDGSQSDD--------------------------KGKKLIPLIIGAQY-FIVKMIQGAIR
NDIKI-SG--KPV-----------------------------------------------
------------------------------------------------------------
-------
>brToc33	
M-----------------------------------------------------------
-----------------------------------------GS---LVREWVGFQQFPAA
TQEKLIEFFTK--LKQKDMNSLTLVVMGKGGVGKSSTVNSLIGEQVVRVSPFQAEG----
----LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--VNHQALELIK----GFLV
NRTID---------VLLYVDRLDVYRVDELDKQVVQAITQTFGK----------------
--------------------------EIWCKTLLVLTHAQF-SPPDDLSYETFS------
------SKRSDSLLRTI---RAGSKMGET-------------------------------
TV-------------GFC---------------------------------------NGC
VCGETVED----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>grToc34	
M-----------------------------------------------------------
-----------------------------------------GT--PLPREWLGLQQFPAA
TQTKLFELLGK--LKQENVNTLTIVVMGKGGVGKSSTINSLIGEQVVRVTAFQSEG----
----LRPVMVSRSWA-GFTLNVIDTPGLV----E---AGY--VNHQALELIK----GFLL
NKTID---------VLLYVDRLDVYRVDNLDKQIIRAITNSFGK----------------
--------------------------EIWRKSLLVLTHAQL-CPPDGLNYDVFS------
------SKRSEGVLKAI---RMGARIRKM-------------------------------
DLEDSVIPVVLVENTGRCN-KNDIDEKILPNGEAWVPNFGKSH-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>amToc34	
M-----------------------------------------------------------
-----------------------------------------AA--QLIKEWSAIQQFPAA
TQEKLVDLLGK--LKNQDVNTLTILVMGKGGVGKSSTINSIIGERVVTVSAFQSET----
----PRPVMVSRSRS-GFTLNVIDTPGLV----E---GGY--VNDQVLETIKSFLGRFLM
NKTID---------VLLYVDRLDAYRVDNLDKQIVKAITESFGK----------------
--------------------------EIWHKAVVVLTHAQL-SPPDALSYEEFF------
------SRRSDSLLKFV---CQGAGINKK-------------------------------
DLKNFDIPVALVEN----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>laToc34	
M-----------------------------------------------------------
-----------------------------------------TS--PITREWAGFNTFPPE
TQTKLLELLGR--LKEKNVNKLTILVMGKCGVGKSSTVNSIIGERAVVINPFQSEG----
----LRPVMVSRSRT-EFTLNIIDTPGII----E---GGC--INNQALELIK----HFLL
NKTID---------ILLYVDRLDTYRVDELDKMVVRAITNSFGK----------------
--------------------------EIWNRALIVLTHAQL-SPPDGLPYDEFV------
------SKRSEALLKVV---HQGARLKKG-------------------------------
DLASS-IPSV-----SRCN-KNDSGEK-GPNGTA--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>peToc34	
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------IVGERVAIVSAFQSEA----
----MRPLICSRSRA-GFTLNIIDTPGLI----E---GGF--VNDHALDLIK----RFLI
NKTID---------ILLYVDRLDGYRVDDLDMQVTKAISKSFGQ----------------
--------------------------QIWRRGLVVLTHAQL-SPPDELRYADFV------
------DRRSAILQAVV---RKAAGFKKS-------------------------------
ETQ---IPVVLVENSGRCN-TNSGGEKVLSDGTVWLPYLVEKIVEVATNGSKPILIDKKL
IEGPDANQ--------------------------WGKRWIPLFLAFQYFFIVKPIRRGIQ
KDIQR-EKSERPAWEIYDET----------------------------------------
------------------------------------------------------------
--GDKTI
>ppToc34-1
M-----------------------------------------------------------
-----------------------------------------AA--TPAREWTGLQQFPVA
TQTALHNILGT--LRQQNKESLTVLVVGKGGVGKSSTVNSIVGERVTIVSAFQSET----
----LRPLQCARSRA-GFTLNIIDTPGLV----E---GGC--INDQALDIIK----RFLL
SKTID---------VVLYVDRLDGYRVDNLDRQVIRGLARSFGP----------------
--------------------------NFWRLAVIVLTHAQF-SPSDGVNYTEFV------
------EKRSAALQAAI---RQEAGLKKD-------------------------------
EKE---VPYALVENSGRCN-TNDGGEKILPNGTVWLPALVERIVEVATGTTDSVFVDKKL
IDGPNANE--------------------------WGKWWIPVLAVAQYFLVVMPIRKAIE
KDLAE-EKNQRPQWEIRAEEFRRN-TSLY-------------------------------
------------------------------DDDQVDEQAISQALEQDDGLSGQPSSFVDE
DDDDDEF
>ppToc34-3
M-----------------------------------------------------------
-----------------------------------------AA--TQAREWTGLLQFPVA
TQTALHNILGK--LRQQKKESLTVLVVGKGGVGKSSTVNSIIGERVTVVSAFQSET----
----LRPLQCARTRA-GFTLNVIDTPGLI----E---GGC--INDQALDIIK----RFLL
NKTID---------VVLYVDRLDGYRVDNLDKQVIRALARSFGP----------------
--------------------------NFWRIAIIALTHAQL-SPPDGVDYTEFV------
------NNRSAALRAAI---RQEAGFKKS-------------------------------
EGE---ISYMLVENSGRCN-TNSEGEKVLPNGSVWLPALVDRIAEVATGATPSIHVDQKL
IDGPNANG--------------------------KGKWWIPLIILAQYFLIVRPIRSAIE
KDLIE-EEKQRPQWQIRAEEFVRPIASLY-------------------------------
------------------------------EDDQVDEQAIRQALKQ-GALNDQMDSFVED
DEDDDEY
>ppToc34-2
M-----------------------------------------------------------
-----------------------------------------AT--VSEKEWTGFQGLPAA
TQIILHTLLAK--LRKQKVDKITIVLLGKGGVGKSSIVNSLFSERVAAVSAFRSET----
----LRPRQYSRSKD-GFKLTVIDTPGFV----E---AGR--V-DAALNSIR----RYLL
GKTIN---------VVLYVDRLDGPREDKVDVKISRAISQAFGP----------------
--------------------------QIWPHVIVVFTHAEI-HLED-VTYSEFV------
------SRRSAALRNII---LKESRFKTV-------------------------------
NTK---VPFVLVENCSRCS-ENGEHEKILPDGTVWLPVLFEALVDLVLGSKKPILIDEKM
IGIPKGNP--------------------------LGSIWMPLVLLAQFVLIWRPIRKAID
RDLVE-EAQRHSP-----------------------------------------------
------------------------------------------------------------
-------
>olToc34
M-----------------------------------------------------------
--------SEEEYSEDEDYVSSEGEGVEGTEEGGEGQPAQAAAPVLGPKEWVGLSSMPAA
TQSALLETLGK--LRERNVNEMTVIFIGKQGVGKSSTVNTLLNERVAPSSPFQPEN----
----VRPLLAGRVAA-GFTLNVLDTPGLL----E---GDS--VSARGLMALR----AALN
GRKVD---------AFVFTDRLDTWRVDNADKAIFTSLAENFGA----------------
--------------------------ELWERTVLGFSHAQT-TPTDGRPYEEFV------
------NARVEQYRKAI---RSTLNM----------------------------------
--PNLALPFALIENGSRCK-TNGNGEKVV-NDRPWLSDMVSTMVEMACSKDGYEYDHGKA
GKKLDPNN--------------------------KHKIWILPLFLFQAFVLRPLVIGQIR
RDIKK-ADEKKQRAAAAKH-----------------------------------------
------------------------------------------------------------
-------
>otToc34
M-----------------------------------------------------------
--------SDEEYSEDE-YVSSEGEGAEGRDVEPQ---AQQAAPVLGPKEWVGLSSMPAA
TQQALLETLGK--LRERNVNEMTVIFIGKQGVGKSSTVNTLLNERVAPSSPFQPEN----
----ARPLLAGRVAA-GFTLNVLDTPGLL----D---GDS--ISARGLMALR----AALN
GRKVD---------AFIFTDRLDTWRVDNSDRAIFTALAENFGA----------------
--------------------------ELWERTVLGFSHAQT-TPPDGKPYEEFV------
------NARVEQYRKAI---RQTLGM----------------------------------
--PNLTLPFALIENGSRCK-ANAAGEKVV-NERPWLTDMVGTMVEMACAKESYEYDHKKA
GKKLDPNN--------------------------KYKIWMLPLFLFQAFVLRPLMIGQIR
RDIRK-SDEDKKKKSARPAPKK--------------------------------------
------------------------------------------------------------
-------
>crToc34
M---------------------------------------------AQPPRPAEEYDDDV
QEDEDELKEGELDDDESHEAASEGGEAAAGDEEAEDDEQDEEDGDEDSQPWAGLNRLP--
ERDDMLDILNE--LRAEGRKQLTVLLLGKSSVGKSSLINSLLGEAVVRVQAFKLQADTDI
TTTVVRQVAVGNSEVDGFRLKLIDTCGLE----DPEAGDT--VNLGALSKIA----EDVR
GVGID---------VVLYCDRLDLYRVDPLDKAIIDAISSTFGR----------------
--------------------------GIWRRTVVALTHANLVQTPPGTDYDSFV------
------NGRVRLIRGAV---RGPLFFRPS-------------------------------
------LPVALVENSETCPVSSESGFRVLPDGEPWLVALVSQLVDMAAARRRPYKYHPRL
SSKPSH----------------------------RFRWLLPVAIAAEVLFYRRFLHPRLD
DNQRRVEREEERVWALRGQQRRAL------------------------------------
--------GLHRPHRPDKDAAWRLEQMYDDD-----------------------------
-------
>pwToc34
V-----------------------------------------------------------
------------------------------------------------------------
------LALAECSGDRQRTGASRCCCWEREAWARVATVNSLLGERAAVVSSFQATG----
----LGVHMHTRTLPGGFALNLIDTPSLL----D---QDS--VSTSRLEQIG----SAIK
GVKID---------AVLFLDRLDVYSTDTLDEQVVDGVTAYFGE----------------
--------------------------DMWDHAVLGLTRATSSAPPLSTDFGEWV------
------VERSLQLQSLIAKARAQYAPRRR-------------------------------
RGEAPPLTPAGCRESQECP-RKLRGSGSSPATAPGSPTCMPRWRSAATGAGQAWLHDAAR
R-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------
>jgi|Fracy1|190984|jgi|Fracy1|190984|e_gw1.11.73.1:28-347
M-----------------------------------------------------------
----------------------------------------------------------NT
NTTTITNVNND--DHQQQHRCGYAGIVGAPNMGKSTLLNSLLKEDLCIATRRPQTT----
----RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--LQANMMEAVK----GALT
DSDM----------IVVVTDLFSTPIPD---DNVFRRLS---------------------
--------------------------ETTKPVLVVVNKIDLEGRAKRPDEATIQRKKDDE
EEEEDEFEKTYTVVEAV-------------------------------------------
EKWRLLLPNALAIIPLTAPIPGMFRNGVKSLTNDDVKQLL--------PIGPPLYDDDFL
SDRSVR------------------------------------------FFCSELIREALL
ESRYL-KKELPYCCEVQITDYKEPR-----------------DDNITRIEATIFVERDGQ
KAIIIGK-NGDVVKQVGIIAREKIERFLDGEKVFLQLRVKINKDWRKREDQLAKFGYSN-
-------
>jgi|Psemu1|253210|jgi|Psemu1|253210|estExt_Genewise1Plus.C_650095:87-387
M---------------------------------------------------------SP
SQNENSKKQRSGKSKSKKNIEKKRPADTLLILKQLDEKINSYEGRLPSKMPANLDTDNDR
SSTGFADTNNI--QH-EQHRCGFVGIVGAPNMGKSTLLNGLLKEDLCIATRRPQTT----
----RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--LQANMMEAVK----GALK
DSDV----------LLVVTDMFSTPIPN---DEIFRRLS---------------------
--------------------------LTNKPVLVVVNKIDLEGRAQRPTETDGEEKKND-
EDDEDEVEKTYTVAEAV-------------------------------------------
AKWRMLLPDALAIIPMTAT-------------------LL--------PVGPPLYDDDFL
SDRSVR------------------------------------------FFCSELIREALL
ESRYL-KKELPYCCEVQITEYKEPR----------------KEKDLTRIEATIFVERDGQ
KAIVVGK-NGSVIKQVGIVAREKIERFLDGEKIFLKLQVKVDKDWRKKDDALTKFGYTNK
-------
>gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217406280|gb|EEC46220.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
--------------------------MGAPNMGKSTLLNALLEEDLCIATARPQTT----
----RHAILGLMSTD-KCQVCLVDTPGVI----E-DPAYE--LQEGMMEAVT----GAVA
TSDV----------LLVVTDVFSTPIPD---DELFLKVQ---------------------
--------------------------RTRKPVLVAINKIDL---AKKVNKAA--------
---EENRDKTVTVEEAV-------------------------------------------
AFWRAQLPNALCILPLSAS-QGINNVGVVAM-RRILTELL--------PISPPLYDPETL
TDRPER------------------------------------------FIASEIVRSALF
Q--VL-KKELPYCCEVRIREFKEPK----------------EEGEVIRIAADVLVERDSQ
KVIVIGK-NGAQVKEIGVIAREKLEAFFR-HQIFLNLSVKVDKDWRKNTRKLTEYGYMKP
KR-----
>gi|224012853|ref|XP_002295079.1| predicted protein [Thalassiosira pseudonana CCMP1335] >gi|220969518|gb|EED87859.1| predicted protein [Thalassiosira pseudonana CCMP1335]
M------------------LLPITFNGFVLIGCAVLRSTHLASSTNTVAFVPSASSIRST
SSTHHQHTVLFAESGNKYAKEDKQTQQELL---QTLESKFDYEGRIASKV-----GDGDN
SSTDTSTTN-------PSHRCALVTILGKPNMGKSTLLNSLLSDNLAIATSRPQTT----
----RHAILGVMTSD-HNQLCLTDTPGII----D-KTAYK--LQDGMMDVVK----GAVK
SADL----------FLVVTDEEDPYLGI--GEDTVKMIK---------------------
--------------------------QMEKPVIVCVNKVDLAS----VDKSSVY------
------VNTPPLAVQTI-------------------------------------------
GKWRALLPNAFAIIPTCAA----------------NVDLL--------PIGPPLYHPDFF
TDRTDR------------------------------------------FCASELIRETLF
E--TL-GKELPYCCEVRVETFDESK-----RYLDEDSVGSGKNKSMIRIGATILVERDSQ
KGIVVGK-GGQQIKDLGMNARKKLQVFFD-TKIFLDLRVKVDKNWRNNAEKLKKYGYMQ-
-------
>jgi|Fracy1|187133|jgi|Fracy1|187133|e_gw1.7.947.1:43-377
M-------FKNAVLFPQRRARTWLWNNS--NTTT--------DACRANLSYAIE-RCCSS
SSSSSSSQSQ-----------------------------------------------SQS
QSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILTQSPVAAVSRKRHTT----
----RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEERLDRDLIATAA----SEMQ
DVDF----------TLLVIDSARAL-SENYRHA---------------------------
-----------DDDANPNSN------DGRGKFAIVLNKVDLVKPKSTLIDLA--------
------MEIGAIADTCL---EDHFTEHGK---------------------------TIDF
EAMLEHSPIVFYVSA-------LKEDGT--------DDLLDHLINLATPCKEWAVQSGQS
TNMTELEQ------------------------------------------VQEIIREKIY
R--TC-HREVPHSVQQVNRMFRKIP------------------KKGVIIHQDLVVFTKSH
QKLVLGA-GGRTLERIRESAQTDLRKMFK-CEVSLHLHVK--KKIGRRGDSGTEYKLGEA
SQTIL--
>jgi|Fracy1|226249|jgi|Fracy1|226249|fgenesh2_pm.7_#_308:48-420
M-------------QLEPVQRSIVQNQSLLLSIAADVMCFIARSIIAHTEYCIQYRCCSS
SSSSSSSQSQ-----------------------------------------------SQS
QSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILTQSPVAAVSRKRHTT----
----RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEERLDRDLIATAA----SEMQ
DVDF----------TLLVIDSARAL-SENYRHAFVQLMTGAINSKGRIEESFGDDNEIDD
KSSIHNNNKSSDDDANPNSN------DGRGKFAIVLNKVDLVKPKSTLIDLA--------
------MEIGAIADTCL---EDHFTEHGK---------------------------TIDF
EAMLEHSPIVFYVSA-------LKEDGT--------DDLLDHLINLATPCKEWAVQSGQS
TNMTELEQ------------------------------------------VQEIIREKIY
R--TC-HREVPHSVQQVNRMFRKIP------------------KKGVIIHQDLVVFTKSH
QKLVLGA-GGRTLERIRESAQTDLRKMFK-CEVSLHLHVK--KKIGRRGDSGTEYKLGEA
SQTIL--
>jgi|Psemu1|8240|jgi|Psemu1|8240|gm1.8240_g:60-428
MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNT--------GWLSSQASSRVK-FLSSS
SPSSTRRQSP-----------------------------------------------PAS
RPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLTKSPIAAVSRKRHTT----
----RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEERLDRDLIATAA----SEMQ
DVDF----------TLLVLDSARTL-SDNYRHALVQLMVGAINSGGRIEDCDDDDDNNDR
KTT-----RQSREDINPSSKCDTAIPSDKSKFAIVLNKVDLVKPKTDLISLA--------
------MDVGTMADTCL---LDQFQKQGR---------------------------EFDF
DAQMEQSPIVFYVSA-------LKEDGT--------DDLLEHLLGLATPSREWPVEPGKA
TNMTTLEQ------------------------------------------VQEVIREKIY
R--ST-HKEVPHAVQQVNRLFRRIP------------------NKGVVIHQDLVVFTKSH
QKLVLGSGGGKTLKRIQESARHDLQKLFG-CDVALQLHVKYRKSKQQRGDSGAQYNLGEV
SQSVY--
>jgi|Psemu1|252849|jgi|Psemu1|252849|estExt_Genewise1Plus.C_570066:60-394
MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNT--------GWLSSQASSRVK-FLSSS
SPSSTRRQSP-----------------------------------------------PAS
RPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLTKSPIAAVSRKRHTT----
----RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEERLDRDLIATAA----SEMQ
DVDF----------TLLVLDSARTL-SDNYRHAL--------------------------
-------------DINPSSKCDTAIPSDKSKFAIVLNKVDLVKPKTDLISLA--------
------MDVGTMADTCL---LDQFQKQGR---------------------------EFDF
DAQMEQSPIVFYVSA-------LKEDGT--------DDLLEHLLGLATPSREWPVEPGKA
TNMTTLEQ------------------------------------------VQEVIREKIY
R--ST-HKEVPHAVQQVNRLFRRIP------------------NKGVVIHQDLVVFTKSH
QKLVLGSGGGKTLKRIQESARHDLQKLFG-CDVALQLHVKYRKSKQQRGDSGAQYNLGEV
SQSVY--
>gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217410895|gb|EEC50824.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------RPTFIRTALVTF
RWSGGPKISR-----------------------------------------------SDR
VRLSSTTIGST--PSLEDRKRLDVAIVGLPNAGKSQLLNVLTQSTVAAVSRKRHTT----
----RDGILGARTVD-DTQLYFVDTPGFL----RQSQAKKEGLNRDLVVTAS----SEME
NVDF----------SLLVVDAARRM-TDDYEETLVALMLAALRSQGRLEFDVHSAEEVQS
IRTPKGG-------------------TNPAKFAVVLNKVDLVHPKSNLMDLA--------
------VNIGTLAEQCI---KFDAKESGK------------------------EELFLDS
AYLQESLPMFFYISA-------LKQRGV--------QDLLEFLLERATPSTSWEVEAGEA
TPMTMKER------------------------------------------IEEVIREKIY
R--CL-HKEVPHSIRQENRVLQQGK--------------DEDGNIVLVIHQDLIVRSKSH
QELVHGG-GGRTLERIRETAARGLEKIFF-CNVVLHLHVKLPRSKNQRWSI---------
-------
>gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335] >gi|220973246|gb|EED91577.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
M---------------AFFRRALLQGSLAVNNLT--------HDTWHQTPRAIT-SLLNH
QQSCSLHSTP-----------------------------------------------ITL
NNPTSSSAATTQSDKPAPQKRLDVAIVGAPNAGKSQLLNSLIGSKVAAVSRKRHTT----
----RTGILGARTFD-DTQLVFIDTPGFL----HHEMSVKEGV-RKLLGEAS----SEME
SADF----------VLLVVDAARKM-EDDLRRTLVTLMFLALRSKGRNE-----------
-------------------------------FAVVLNKVDLVSPKEKLLMTA--------
------ADVGSMAESCI---RQFLNQRRSPSKVKFGELVDTVLKNYANEDGFDGVHDDDI
ELFATLAPEFFFTSA-----IVKDDEGV--------DDVLGLLLERATLSDQWIVDAGSA
TGMTPVEQ------------------------------------------VEEIIREKIY
R--CL-HREVPHSVQQQNRMFQLYKPNESKTKSTDGSDVDED-IKILRIRQDLIVRTKSH
QRLVLGS-GGKTLERIRSTALKDLEESFD-CIVDLDLTVRVTKS-NQHEAILDPESVGAV
SLTPLEN
>gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M---------------FGIRRLVVGGSVRHGGHA--------RGRPLPCPACPT-GPDIS
SSASSLLSRT-----------------------------------------------MTS
YFDGGPSAPET--SRPKQQRRLDIAIVGAPNAGKSQLLNSLVGSKVAAVSRKRHTT----
----RSGILGARTFG-DTQLVFIDTPGFL----HHSKGAREGV-RNLLSEAS----AEMM
NADF----------ALLVVDAAKTI-DQDLKRTLVTLMMLALRSTGREEGSRVFSDQ---
--------------------------RHLGRFSVVLNKVDLVKPKEKLLATA--------
------AEVGSLAESCV---RRLLQQHRAPVRVKMGELVDSVLERHEDEEGFAGVHEEDY
ETFASVVPEFLFTSA-----IDPEDEGA--------DDLLNVLLSRATPSTEFVMDPS--
---SNLEQ------------------------------------------VEEIIREKIY
R--CL-HREVPHHVQQTNRVFKLKQ------DQPPDHDVRADMGDLLQIHQDLIVRTKSH
HRLVLGS-GGKTLQRIQTTASKDLRELFG-CEVDLLLSVKLKKT--NQGVLLDPEEEGA-
RITTLHD
