>cmToc34
------------------------------------------------------------
-----MDSETPTKNEAEQRASPDRTGQVTQRPVSLFRKNGT---------------FAYP
LEDSDVYEEQVLALEDVPEPTAQAILRLALAAERQGVPRLRFLVVGAPGVGKSSLINTLL
NENLCSVSAWERGT--------KNAQVCARQVD-SVVIEFIDTPGIAPCRRS---GLE--
ASRRQVQRLR----KLLDARGADEHPYLRSFHAILYVMRLDDTR-P-DLVDYHNWKVLME
FFGA------------------------------------------EVLRHMMVVFTHGQ
S-LP--------------------------------------------------------
-------------------------PDSLSYPEYVRGR----------------------
------------------------------------------------------------
-----------RDYVYLLI---ERLTG----PLKAVRFPVFVAENSSKCPVIEETGERKL
PDDTPWITQLYDGIRRFVFPLEADLF---GMETGPEDTQVLVYIYDKRRSRADERYPRSP
LQALIRNPWFLRAVQFCGAMLLRSYMIRQEHERFNPKPHHPEPIIRDANNAFAVASRRAN
DHRLFTPSIDEDEESFFRMNGNDDFVSRLRNRPGEVDLDELDVERIESPDGRFVEYWYTE
KDNPEMVRMYRLEIRDDPNEERESRQDRIPISKDQH
>acToc34	
------------------------------------------------------------
---------------------------------------MS-------------------
-----FLTREWVGIQQFPAATQTKLHEILGKLKQENVNTMTILVMGKGGVGKSSTVNSIL
GERVATVSAFQSEG--------LRPIMCSRTRA-GFTLNVIDTPGIV----E---GGY--
VNEQALEIIK----RFLLDKTID---------VLLYVDRLDSYR-V-DNLDKQVVKAITD
FLGK------------------------------------------EIWQRGVVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGLNYDDYLEKR----------------------
------------------------------------------------------------
-----------SDALLKYV---RLGAGIKKKELQGKGIPVALVENSGRCK-TNEDGEKIL
PNGTAWIPNLVQQSQT--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>vvtoc34	
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----QLIREWTGIQQFPPVTQTKLIELLGKLKQENVSTLTILVMGKGGVGKSSTVNSII
GERAVAVSAFQSEG--------PRPVMVSRSRA-GFTLNIIDTPGLV----E---GGY--
VNDQALEIIK----RFLLNKTID---------VLLYVDRLDAYR-V-DNLDRQVVKAITD
SFGK------------------------------------------EIWRRGVVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGLNYEDFFSKR----------------------
------------------------------------------------------------
-----------SEALMKVV---RSGARLRKQDIQDSGIPVVLVENSGRCH-KNESDEKIL
PNGTAWIPNLVKTITDAVSNGSKGILVDKKLIEGPNPNE---------------------
-----RGKLLIPFILAFQYFFIVKRIQRA-------------------------------
----------------------------IKSDMAK-ER--KAPWESREANRYEP------
------------------------------------
>stToc34-2
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----QIIREWAGIQQFPAATQSKLLELLGKLKQENVSTLTILVMGKGGVGKSSTVNSII
WERAVAVSAFQSET--------PRPVMVSRSRA-GFTLNIIDTPGLV----E---GGY--
VNDQALDLIK----KFLLNKTID---------VLLYVDRLDAYR-V-DNLDKQIVKAITD
SFGK------------------------------------------EIWRRGIVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGLTYDEFTSRR----------------------
------------------------------------------------------------
-----------SEALLKIV---RMGARIRKQDIQAASIPVVLVENSGRCN-KNESDEKIL
PSGTAWIPNLVQTITDAVLSGSKGILVDQKLIEGPNPNN---------------------
-----RGKVLIPFILAFQYFFVVKRIQKS-------------------------------
----------------------------IKNDIAR-ES--RPAWA---------------
------------------------------------
>leToc34-2
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----QIIREWAGIQQFPAATQSKLLELLGKLKQENVSTLTILVMGKGGVGKSSTVNSII
GERAVAVSAFQSET--------PRPVMVSRSRA-GFTLNIIDTPGLV----E---GGY--
VNDQALDLIK----KFLLNKTID---------VLLYVDRLDAYR-V-DNLDKQIVKAITD
IFGK------------------------------------------EMWCRGIVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGLTYEEFTSRR----------------------
------------------------------------------------------------
-----------SEALLKIV---RMGARIRKQDIQAASIPVVLVENSGRCN-KNESDEKIL
PSGIAWIPNLVQTITDAVLSGSKGILVDQKLIEGPNPNN---------------------
-----RGKVLIPFILAFQYFFVVKRIQRS-------------------------------
----------------------------IKNDIAR-ET--RPSWA---------------
------------------------------------
>leToc34-1
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----QVIREWVGFQQFPSATQSKLIELIRKLKQESVSTVTILVMGKGGVGKSSTVNSIL
GERAVAVSAFQSET--------PRPVMVSRSWA-EFTLNIIDTPGLV----E---GGY--
VNDQALDLIK----RFLLNKTID---------VLLYVDRLDTYR-V-DNLDRQIVKAITD
SFGK------------------------------------------GIWRRGLVVLTHAQ
V-SP--------------------------------------------------------
-------------------------PDGLSYDEFTSRR----------------------
------------------------------------------------------------
-----------SEALLKIV---RLGARMKKQEIKAASIPLVCVENSGRCN-KNELDEKIL
PNGTAWIPSILQTITEVVVSQSKGILIDQKLIEGPNPNN---------------------
-----KGKLLIPLIATFQYFFVVKRIQTW-------------------------------
----------------------------IKNDISR-EN--RPSWA---------------
------------------------------------
>stToc34-1
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----QVIREWVGFQQFPSATQSKLIELIRKLKQESVSTLTILVMGKGGVGKSSTVNSIL
GERAVAVSAFQSET--------PRPVMVSRSWA-EFTLNIIDTPGLV----E---GGY--
VNDQALDLIK----RFLLNKTID---------VLLYVDRLDTYR-V-DNLDRQIVKAITD
SFGK------------------------------------------EIWHRGLVVLTHAQ
V-SP--------------------------------------------------------
-------------------------PDGLSYDEFTSRR----------------------
------------------------------------------------------------
-----------SEALSKIV---RLGARIRKQEVKASSVPIVCVENSGRCN-KNELDEKIL
PNGTAWIPNLLQTITEVVASESKGILVDQKLIEGPNPNN---------------------
-----KGKLLIPLIAAFQYFFVVKRIQKW-------------------------------
----------------------------IKNDIAR-ET--RPSWA---------------
------------------------------------
>mtToc34-1
------------------------------------------------------------
-----M---------------------------------ASQ------------------
----QQQVREWSGINTFAPATQTKLLELLGKLKQEDVNSLTILVMGKGGVGKSSTVNSII
GERVVAISPFQSEG--------PRPVMVSRARA-GFTLNIIDTPGLI----E---GGY--
INDMALDIIK----RFLLDKTID---------VLLYVDRLDAYR-V-DNLDKLVAKAITD
SFGK------------------------------------------GIWNKAIVALTHAQ
F-SP--------------------------------------------------------
-------------------------PDALAYDEFFSKR----------------------
------------------------------------------------------------
-----------SESLLQII---KSGASLKKDDAQASAIPVVLIENSGRCN-KNETDEKVL
PNGIAWIPHLVHTITEIALNKSESIFVDKNLIEGPNPNQ---------------------
-----RGKLWIPVLFALEFLLIMKPIEGL-------------------------------
----------------------------IKNDVAN-EK--KPSWETRDVGVKKE------
----------------TREVGQKDMRKERRGGAVRR
>psToc34	
------------------------------------------------------------
-----M---------------------------------ASQ------------------
----QQTVREWSGINTFAPATQTKLLELLGNLKQEDVNSLTILVMGKGGVGKSSTVNSII
GERVVSISPFQSEG--------PRPVMVSRSRA-GFTLNIIDTPGLI----E---GGY--
INDMALNIIK----SFLLDKTID---------VLLYVDRLDAYR-V-DNLDKLVAKAITD
SFGK------------------------------------------GIWNKAIVALTHAQ
F-SP--------------------------------------------------------
-------------------------PDGLPYDEFFSKR----------------------
------------------------------------------------------------
-----------SEALLQVV---RSGASLKK-DAQASDIPVVLIENSGRCN-KNDSDEKVL
PNGIAWIPHLVQTITEVALNKSESIFVDKNLIDGPNPNQ---------------------
-----RGKLWIPLIFALQYLFLAKPIEAL-------------------------------
----------------------------IRRDIAT-ET--KPAWETRDVGDRK-------
------------------------------------
>pcToc34	
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----QIIREWSGINTFAPATQTKLLELLGKLKQENVNSLTILVMGKGGVGKSSTVNSII
GERVVSISPLQSEG--------PRPVMVSRSRA-GFTLNIIDTPGLI----E---GGY--
INDMALDIIK----RFLLNKTID---------VLLYVDRLDVYR-V-DNLDKLVAKAITD
SFGK------------------------------------------GIWNKAIVALTHAQ
F-SP--------------------------------------------------------
-------------------------PDGLPYEDFFSQR----------------------
------------------------------------------------------------
-----------SEALLRVL---RSGAKIKKEVFQAASMP---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>asToc34	
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------SAFQSEG--------LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--
INEQAVEIIK----RFLLEKTID---------VLLYVDRLDTYR-M-DTLDEQVIRAITT
SFGK------------------------------------------AIWRRTLVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGLDYNDFLTRR----------------------
------------------------------------------------------------
-----------SESLLRYI---RSGAGIGKRESADYPLPLALVENSGRCK-TNENGAKIL
PDGTPWIPNLMKEITMVVSNGSKPIHVDQKLIDGPNPNN---------------------
-----RWKKYIPLILAVQYFFVVKGIRRA-------------------------------
----------------------------IHSDIAN-GK--LDDWEQRYRDLVGS------
----------------GNPVDQKVSSSRNPRPEAGQ
>osToc34	
------------------------------------------------------------
-----M--------------------------------SAA-------------------
-----PIPREWVGLQQFPAATQTKLHELLGKLKEENVSTLTILVMGKGGVGKSSTVNSIV
GERVATVSAFQSEG--------LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--
INEQAVEIIK----RFLLGKTID---------VLLYVDRLDAYR-M-DTLDDQVIRAVTN
SFGK------------------------------------------AIWRRTLVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGLDYNDFFTKR----------------------
------------------------------------------------------------
-----------SESLLRYI---RAGAGVSKRELGDFPLPIALVENSGRCK-TNENGEKVL
PDGTPWIPNLMKEITTVVSNGSKSIHVDQKLIDGPNPNN---------------------
-----RWKMFIPLILMVEYFLVVKGIRRA-------------------------------
----------------------------IHADISN-GK--LDDWEQRYRDLVGS------
----------------KDPVDQKGSSSGNRK----A
>sbToc34	
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----PIPREWAGLQQFPAATQTKLHELLGKLKEEDVSTLTILVMGKGGVGKSSTVNSIV
GERVTTVSAFQSEG--------LRPTMCSRTRA-GFTLNIIDTPGLI----E---GGY--
INEQAVDIIK----RFLLGKTID---------VLLYVDRLDAYR-M-DTLDEQVIRAITN
SFGK------------------------------------------DIWRRSLVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGIDYNDFFTRR----------------------
------------------------------------------------------------
-----------SEALLRYI---RSGAGINKREYGDFPLPIALVENSGRCK-ANEHGEKIL
PDGTPWVPNLM-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>zmToc34-1
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----PIPREWVGLQQFPPATQTELHELLGKLKEEDVSTLTILVMGKGGVGKSSTVNSIV
GERIATVSAFQSEG--------LRPMMWSRTRA-GFTLNIIDTPGLI----E---GGY--
INEQAVDIIK----RFLLGKTID---------VLLYVDRLDAYR-M-DTLDGQVIRAITN
SFGK------------------------------------------DIWRRSLVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGIEYNDFFTRR----------------------
------------------------------------------------------------
-----------SEALLRYI---HSGAGIKKREYGDFPLPIALVENSGRCK-TNEHGEKIL
PDGTPWVPKLMKEITVVISNGSKPIHVDQKLIDGPNPNN---------------------
-----RWKMFIPIILAVEYFLVVKGIRRA-------------------------------
----------------------------IHADIAN-GK--VDDWEQRYRDLVGS------
----------------RDPVEQKGSTTRNRK----A
>zmToc34-2
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----PIPREWVGLQQFPAATQTKLHELLGKLKEEDVSTLTILVMGKGGVGKSSTVNSIV
GERVASVSAFQSEG--------LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--
INEQAVDIIK----RFLLGKTID---------VLLYVDRLDAYR-M-DTLDEQVIRAITN
SFGK------------------------------------------DIWRRSLVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGIDYNDFFTRR----------------------
------------------------------------------------------------
-----------SEALLRYI---HSGAGINKREYGDFPLPIALVENSGRCK-TNEHGEKIL
PDGTLWVPNLMKEITVVISNGSSPIHVDQKLIDGPNPNN---------------------
-----RRKLFIPLILAVEYFLVVKGIRRA-------------------------------
----------------------------IHADIAN-GK--VDDWEQRYRDLVGS------
----------------RDLVEQKGSTSRNRK----A
>soToc34	
------------------------------------------------------------
-----M---------------------------------AS-------------------
-----PIPREWVGLQQFPAATQTKLHELLGKLKEEDVSTLTILVMGKGGVGKSSTVNSIV
GERVTTVSAFQSEG--------LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--
INEQAVDIIK----RFLLGKTID---------VLLYVDRLDAYR-M-DTLDEQVIRAITN
SFGK------------------------------------------DIWRRSLVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGIDYNDFFTRR----------------------
------------------------------------------------------------
-----------SKALLPYI---RSGAGIQPTRIWGFP----------PCQ----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>hvToc34	
------------------------------------------------------------
-----M---------------------------------AA-------------------
-----PIPREWVGLQQFPAATQTKLHELLGKLKEENVSTLTILVMGKGGVGKSSTVNSIV
GERVANVSAFQSEG--------LRPMMCSRTRA-GFTLNIIDTPGLI----E---GGY--
INEQAVEIIK----RFLLEKTID---------VLLYVDRLDTYR-M-DTLDEQVIRAITS
SLGK------------------------------------------AIWRRTLVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGIDYNDFLARR----------------------
------------------------------------------------------------
-----------SESLVRYI---RSGAGIGKREYADFPLPIALAEDSGKGR-TNENGA--I
LDGNSWDSKLE-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>brToc34	
------------------------------------------------------------
-----M--------------------------------AAL-------------------
-----QMSREWIGIQQFPPATQSKLIEILNKFKEEDVSSLTVLVMGKGGVGKSSTVNSVI
GEKAAAVSTFQSEG--------LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--
VNDQAVNLIK--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>rrToc34	
------------------------------------------------------------
-----M--------------------------------AAL-------------------
-----QMSREWIGIQQFPPATQSKLLEILGKFEEEDVSSLTVLVMGKGGVGKSSTVNSVI
GERAAAVSTFQSEG--------LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--
VNDQAVNLIK----GFLPNKTID---------VLLYVDRLDVYR-V-DDLDKQVVTAITD
AFGK------------------------------------------EIWKKSALVLSHAQ
F-SP--------------------------------------------------------
-------------------------PDGLNYDLFVSRR----------------------
------------------------------------------------------------
-----------SDALLKLI---YASAQLK-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>bnToc34	
------------------------------------------------------------
-----M--------------------------------AAL-------------------
-----QMSREWIGIQQFPPATQSKLLEILGKFKEEDVSSLTVLVMGKGGVGKSSTVNSVI
GEKAAAVSTFQSEG--------LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--
VNDQAVNLIK----RFLLNMTID---------VLLYVDRLDVYR-V-DDLDKQVVTAITD
AFGK------------------------------------------EIWKKSALVLSHAQ
F-SP--------------------------------------------------------
-------------------------PDGLNYDLFVSRR----------------------
------------------------------------------------------------
-----------SDALLKLI-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>boToc34	
------------------------------------------------------------
-----M--------------------------------AAL-------------------
-----QVSREWIGIQQFPPATQSKLLEILGKFKEEDVSSLTVLVMGKGGVGKSSTVNSVI
GEKAAAVSTFQSEG--------LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--
VNGQAVNLIK----RFLLNMTID---------VLLYVDRLDVYR-V-DDLDKQVVTAITD
AFGK------------------------------------------EIWKKSALVLSHAQ
F-SP--------------------------------------------------------
-------------------------RDG--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>atToc34	
------------------------------------------------------------
-----M--------------------------------AAL-------------------
-----QTLREWIGIQQFPPATQSKLLEILGKYKEEDVSSLTVLVMGKGGVGKSSTVNSVI
GEKAAAVSTFQSEG--------LRPTLVSRTRS-GFTLNIIDTPGLI----E---GGY--
VNDQAINIIK----RFLLNMTID---------VLLYVDRLDVYR-V-DDLDRQVVGAITD
AFGK------------------------------------------EIWKKSALVLTHAQ
F-SP--------------------------------------------------------
-------------------------PDGLNYNHFVSKR----------------------
------------------------------------------------------------
-----------SNALLKVI---QTGAQLKKQDLQGFSIPVILVENSGRCH-KNESDEKIL
PCGTSWIPNLFNKITEISFNGNKAIHVDKKLVEGPNPNE---------------------
-----RGKKLIPLMFAFQYLLVMKPLVRA-------------------------------
----------------------------IKSDVSR-ES--KLAWELRDSGLASR------
----------------RS------------------
>tsToc34	
------------------------------------------------------------
------------------------------------------------------------
------------------------------PTRPEDVSSLTVLVRGKGGVGKSSTVNSVI
GEKAAAVSTFQSEG--------LRPSLVSRSRS-GFTLNIIDTPGLI----E---GGY--
VNDGAVNLIK----GFLLNKTID---------VLLYVDRLDVYR-V-DDLDRQVVTAITD
AFGK------------------------------------------EIWKKSALVLSHAQ
F-SP--------------------------------------------------------
-------------------------PDGL-YDLFVSRR----------------------
------------------------------------------------------------
-----------SDS--SVI---CAGAQLKKQDLQGSSIPVILVENSGRC-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>lsToc34	
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GERAVTVSAFQSEA--------LRPTMVSRERS-GFTLNIIDTPGIV----E---GGY--
VNDQALEIIK----RFLLNKTID---------VLLYVDRLDAYR-V-DTLDGQIVKAISN
SFGQ------------------------------------------QIWRKAIVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDCLSYDEFLAKR----------------------
------------------------------------------------------------
-----------SEALLKVV---YRGARFRKLDIENFPIPIGLVENSSRCN-KNEKDEKIL
PNGSAWIPSIVETITEVSLTESKSILVDQKLIDGPNPN----------------------
-----RGKLFIPFIIAFQYFFV--------------------------------------
------------------------------------------------------------
------------------------------------
>ptToc34-1
------------------------------------------------------------
-----M---------------------------------GS-------------------
------VLREWIGFQQFPTATQSKLVELFAKLKEEGVDKLTILVMGKGGVGKSSTVNSLF
GERAVNVSSFQSEG--------FRPVMVSRNRA-GFTLNIIDTPGLV----E---GGY--
VSYQALDMIK----RFLLNKTIH---------VLLYVDRLDAYR-V-DDLDKQIIGAISD
SFGK------------------------------------------EIWSKSLLVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDDLSYDVFCARR----------------------
------------------------------------------------------------
-----------SEAVLKTI---RMGARIRKRDFEDSAIPVGLVENSGRCN-KNENDEKIL
PNGDAWIPSLVKEIILVATNGKKLLLMRSWLVGLSQMTG---------------------
------GKIFIPLILGI-------------------------------------------
------------------------------------------------------------
------------------------------------
>ptToc34-3
------------------------------------------------------------
-----M---------------------------------GS-------------------
------VLREWIGFQQFPTATQSKLVELFAKLKEEGVDKLTILVMGKGGVGKSSTVNSLF
GERAVNVSSFQSEG--------FRPVMVSRNRA-GFTLNIIDTPGLV----E---GGY--
VSYQALDMIK----RFLLNKTIH---------VLLYVDRLDAYR-V-DDLDKQIIGAISD
SFGK------------------------------------------EIWSKSLLVLTHAQ
L-CP--------------------------------------------------------
-------------------------PDDLSYDVFCARR----------------------
------------------------------------------------------------
-----------SEAVLKTI---RMGARIRKRDFEDSAIPVGLVENSGRCN-KNENDEKIL
PSGDAWIPSLVKEIILVATNGKKALVVDEKLVNGSESND---------------------
-----RGKIFIPLILGIQW-LLVKWIQRE-------------------------------
----------------------------IKKDIAK-GG--KYL-----------------
------------------------------------
>ptToc34-2
------------------------------------------------------------
------------------------------------------------------------
------------------------------------GNKMTILVMGKGGVGKSSTVNSLL
GERVVNVSSFQSEG--------LRPVMVSRDRA-GFTLNIIDTPGLV----E---GGY--
VNYQSLELIK----RFLLNKTIN---------VLLYVDRLDAYR-V-DDLDKQIISAITD
SFGK------------------------------------------EIWNKSLLVLTHAQ
L-CP--------------------------------------------------------
-------------------------PDDLSYDVFCGRR----------------------
------------------------------------------------------------
-----------SEAVLKTI---RMGAQI-KRDFEDSAIP-GLVENSGGCN-KSENDEKIL
PNGDAWIPTLVK-IVGVATNGKKSLLDQ--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>atToc33	
------------------------------------------------------------
-----M---------------------------------GS-------------------
------LVREWVGFQQFPAATQEKLIEFFGKLKQKDMNSMTVLVLGKGGVGKSSTVNSLI
GEQVVRVSPFQAEG--------LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--
VNHQALELIK----GFLVNRTID---------VLLYVDRLDVYR-V-DELDKQVVIAITQ
TFGK------------------------------------------EIWCKTLLVLTHAQ
F-SP--------------------------------------------------------
-------------------------PDELSYETFSSKR----------------------
------------------------------------------------------------
-----------SDSLLKTI---RAGSKMRKQEFEDSAIAVVYAENSGRCS-KNDKDEKAL
PNGEAWIPNLVKAITDVATNQRKAIHVDKKMVDGSYSDD---------------------
-----KGKKLIPLIIGAQY-LIVKMIQGA-------------------------------
----------------------------IRNDIKT-SG--KPL-----------------
------------------------------------
>bnToc33	
------------------------------------------------------------
-----M---------------------------------GS-------------------
------LVREWVGFQQFPAATQEKLIEFFAKLKQKDMNSLTVVVMGKGGVGKSSTVNSLI
GEQVVRVSPFQAEG--------LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--
VNHQALELIK----GFLVNRTID---------VLLYVDRLDVYR-V-DELDKQVVQAITQ
TFGK------------------------------------------EIWCKTLLVLTHAQ
F-SP--------------------------------------------------------
-------------------------PDDLSYETFSSKR----------------------
------------------------------------------------------------
-----------SDSLLKTI---RAGSKMGKQQFEDSAIEVVYAENSGRCS-KNDKEEKAL
PNGEAWIPNLVKAITDVATNQKKAIHVDKKMVDGSYSDD---------------------
-----KGKKLIPLIIAAQY-FVVKMIQGA-------------------------------
----------------------------IRSDIKT-SG--KPL-----------------
------------------------------------
>ovToc33	
------------------------------------------------------------
-----M---------------------------------GS-------------------
------LVREWVGFQQFPAATQEKLIGFFGKLKQKDMNSLTVLVLGKGGVGKSSTANSLI
GEQVVRVSPFQAEG--------LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--
VNHQALELIK----GFLVNRTID---------VFLYVDRLDVYR-V-DELDKQVVQAITQ
TFGK------------------------------------------EIWCKTLLVLTHAQ
F-SP--------------------------------------------------------
-------------------------PDELSYETFSSKR----------------------
------------------------------------------------------------
-----------SDSLFKTI---RAGSKMRKQQFEDSAIEVVYAENSGRCS-KNEKEEKAL
PNGEAWIPSLVKAITYVATNQRKAIHVDKKMVDGSYSDD---------------------
-----RGKKLIPLIIGAQW-FIVKMIQGA-------------------------------
----------------------------IRNDIKT-SG--KPL-----------------
------------------------------------
>ovToc33like
------------------------------------------------------------
-----M---------------------------------GS-------------------
------LVREWVGFQQFPAATQEKLIGFFGKLKQKDMNSLTVLVLGKGGVGKSSTANSLI
GEQVVRVSPFQAEG--------LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--
VNHQALELIK----GFLVNRTID---------VLLYVDRLDVYR-V-DELDRQVVQAITQ
TFGK------------------------------------------EIWCKTLLVLTHAQ
F-SP--------------------------------------------------------
-------------------------PDELSYGTFSSKR----------------------
------------------------------------------------------------
-----------SDSFLKTI---RTGSKMRKQQFEDSAIEVVYAENSGRCS-KNEKEEKAL
PNGEAWIPGLVKAITDVATNQRKAIHVDKKMVDGSYSDD---------------------
-----RGKKLIPLIMAAQY-FIVEMIQGA-------------------------------
----------------------------IRNDIKT-SG--KPL-----------------
------------------------------------
>rrToc33	
------------------------------------------------------------
-----M---------------------------------GS-------------------
------LVREWVGFQQFPAATQEKLIEFFSKLKQKDMNSLTVVVMGKGGVGKSSTVNSLI
GEQVVRVSPFQAEG--------LRPVMVSRTMG-GFTINIIDTPDLV----E---AGY--
VNHQALELIK----GFLVNRTID---------VFLYVDRLDVYR-V-DELDKQVVQAITQ
TFGK------------------------------------------EIWCKTLLVLTHAQ
F-SP--------------------------------------------------------
-------------------------PDDLSYETFSSKR----------------------
------------------------------------------------------------
-----------SDSLLKTI---RAGSKMRKQQFEDSAIEVVYAENSGRCS-KNDKDEKAL
PNGEAWIPNLVKAITDVATIQKKAIHV---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>boToc33	
------------------------------------------------------------
-----M---------------------------------GS-------------------
------IVREWVGFQQFPAATQEKLIEFFAKLKQKDMNSLTVVVMGKGGVGKSSTVNSLI
GEQVVRVSPFQAEG--------LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--
VNHQALELIK----GFLVNRTID---------VLLYVDRLDVYR-V-DELDKQVVQAITQ
TFGK------------------------------------------EIWCKTLLVLTHAQ
F-SP--------------------------------------------------------
-------------------------PDDLSYETFSSKR----------------------
------------------------------------------------------------
-----------SDSLLKTI---RAGSKMGKQQFEDSAIEVVYAENSGRCS-KNDK-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>thToc33	
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----LDLIK----GFLVNRTID---------VLLYVDRLDVYR-V-DELDKQVVQAITQ
TFGK------------------------------------------EIWCKTLLVLTHAQ
F-SP--------------------------------------------------------
-------------------------PDELSYETFSSKR----------------------
------------------------------------------------------------
-----------SDSLLTTI---RAGAKMRKQQFEDSAIAVVYAENSGRCS-KNEKEEKAL
PNGEAWIPNLVKSITDVATNQKKAIHVDNKMVDGSQSDD---------------------
-----KGKKLIPLIIGAQY-FIVKMIQGA-------------------------------
----------------------------IRNDIKI-SG--KPV-----------------
------------------------------------
>brToc33	
------------------------------------------------------------
-----M---------------------------------GS-------------------
------LVREWVGFQQFPAATQEKLIEFFTKLKQKDMNSLTLVVMGKGGVGKSSTVNSLI
GEQVVRVSPFQAEG--------LRPVMVSRTMG-GFTINIIDTPGLV----E---AGY--
VNHQALELIK----GFLVNRTID---------VLLYVDRLDVYR-V-DELDKQVVQAITQ
TFGK------------------------------------------EIWCKTLLVLTHAQ
F-SP--------------------------------------------------------
-------------------------PDDLSYETFSSKR----------------------
------------------------------------------------------------
-----------SDSLLRTI---RAGSKMGETTV-------------GFCN----------
-----------------------------GCVCGETVED---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>grToc34	
------------------------------------------------------------
-----M---------------------------------GT-------------------
-----PLPREWLGLQQFPAATQTKLFELLGKLKQENVNTLTIVVMGKGGVGKSSTINSLI
GEQVVRVTAFQSEG--------LRPVMVSRSWA-GFTLNVIDTPGLV----E---AGY--
VNHQALELIK----GFLLNKTID---------VLLYVDRLDVYR-V-DNLDKQIIRAITN
SFGK------------------------------------------EIWRKSLLVLTHAQ
L-CP--------------------------------------------------------
-------------------------PDGLNYDVFSSKR----------------------
------------------------------------------------------------
-----------SEGVLKAI---RMGARIRKMDLEDSVIPVVLVENTGRCN-KNDIDEKIL
PNGEAWVPNFGKSH----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>amToc34	
------------------------------------------------------------
-----M---------------------------------AA-------------------
-----QLIKEWSAIQQFPAATQEKLVDLLGKLKNQDVNTLTILVMGKGGVGKSSTINSII
GERVVTVSAFQSET--------PRPVMVSRSRS-GFTLNVIDTPGLV----E---GGY--
VNDQVLETIKSFLGRFLMNKTID---------VLLYVDRLDAYR-V-DNLDKQIVKAITE
SFGK------------------------------------------EIWHKAVVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDALSYEEFFSRR----------------------
------------------------------------------------------------
-----------SDSLLKFV---CQGAGINKKDLKNFDIPVALVEN---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>laToc34	
------------------------------------------------------------
-----M---------------------------------TS-------------------
-----PITREWAGFNTFPPETQTKLLELLGRLKEKNVNKLTILVMGKCGVGKSSTVNSII
GERAVVINPFQSEG--------LRPVMVSRSRT-EFTLNIIDTPGII----E---GGC--
INNQALELIK----HFLLNKTID---------ILLYVDRLDTYR-V-DELDKMVVRAITN
SFGK------------------------------------------EIWNRALIVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDGLPYDEFVSKR----------------------
------------------------------------------------------------
-----------SEALLKVV---HQGARLKKGDLASS-IPSV-----SRCN-KNDSGEK-G
PNGTA-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>peToc34	
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------IV
GERVAIVSAFQSEA--------MRPLICSRSRA-GFTLNIIDTPGLI----E---GGF--
VNDHALDLIK----RFLINKTID---------ILLYVDRLDGYR-V-DDLDMQVTKAISK
SFGQ------------------------------------------QIWRRGLVVLTHAQ
L-SP--------------------------------------------------------
-------------------------PDELRYADFVDRR----------------------
------------------------------------------------------------
-----------SAILQAVV---RKAAGFKKSETQ---IPVVLVENSGRCN-TNSGGEKVL
SDGTVWLPYLVEKIVEVATNGSKPILIDKKLIEGPDANQ---------------------
-----WGKRWIPLFLAFQYFFIVKPIRRG-------------------------------
----------------------------IQKDIQR-EKSERPAWEIYDET----------
-------------------------------GDKTI
>ppToc34-1
------------------------------------------------------------
-----M---------------------------------AA-------------------
-----TPAREWTGLQQFPVATQTALHNILGTLRQQNKESLTVLVVGKGGVGKSSTVNSIV
GERVTIVSAFQSET--------LRPLQCARSRA-GFTLNIIDTPGLV----E---GGC--
INDQALDIIK----RFLLSKTID---------VVLYVDRLDGYR-V-DNLDRQVIRGLAR
SFGP------------------------------------------NFWRLAVIVLTHAQ
F-SP--------------------------------------------------------
-------------------------SDGVNYTEFVEKR----------------------
------------------------------------------------------------
-----------SAALQAAI---RQEAGLKKDEKE---VPYALVENSGRCN-TNDGGEKIL
PNGTVWLPALVERIVEVATGTTDSVFVDKKLIDGPNANE---------------------
-----WGKWWIPVLAVAQYFLVVMPIRKA-------------------------------
----------------------------IEKDLAE-EKNQRPQWEIRAEEFRRN-TSLYD
DDQVDEQAISQALEQDDGLSGQPSSFVDEDDDDDEF
>ppToc34-3
------------------------------------------------------------
-----M---------------------------------AA-------------------
-----TQAREWTGLLQFPVATQTALHNILGKLRQQKKESLTVLVVGKGGVGKSSTVNSII
GERVTVVSAFQSET--------LRPLQCARTRA-GFTLNVIDTPGLI----E---GGC--
INDQALDIIK----RFLLNKTID---------VVLYVDRLDGYR-V-DNLDKQVIRALAR
SFGP------------------------------------------NFWRIAIIALTHAQ
L-SP--------------------------------------------------------
-------------------------PDGVDYTEFVNNR----------------------
------------------------------------------------------------
-----------SAALRAAI---RQEAGFKKSEGE---ISYMLVENSGRCN-TNSEGEKVL
PNGSVWLPALVDRIAEVATGATPSIHVDQKLIDGPNANG---------------------
-----KGKWWIPLIILAQYFLIVRPIRSA-------------------------------
----------------------------IEKDLIE-EEKQRPQWQIRAEEFVRPIASLYE
DDQVDEQAIRQALKQ-GALNDQMDSFVEDDEDDDEY
>ppToc34-2
------------------------------------------------------------
-----M---------------------------------AT-------------------
-----VSEKEWTGFQGLPAATQIILHTLLAKLRKQKVDKITIVLLGKGGVGKSSIVNSLF
SERVAAVSAFRSET--------LRPRQYSRSKD-GFKLTVIDTPGFV----E---AGR--
V-DAALNSIR----RYLLGKTIN---------VVLYVDRLDGPR-E-DKVDVKISRAISQ
AFGP------------------------------------------QIWPHVIVVFTHAE
I-HL--------------------------------------------------------
-------------------------ED-VTYSEFVSRR----------------------
------------------------------------------------------------
-----------SAALRNII---LKESRFKTVNTK---VPFVLVENCSRCS-ENGEHEKIL
PDGTVWLPVLFEALVDLVLGSKKPILIDEKMIGIPKGNP---------------------
-----LGSIWMPLVLLAQFVLIWRPIRKA-------------------------------
----------------------------IDRDLVE-EAQRHSP-----------------
------------------------------------
>olToc34
------------------------------------------------------------
-----MSEEEYSEDEDYVSSEGEGVEGTEEGGEGQPAQAAAP------------------
----VLGPKEWVGLSSMPAATQSALLETLGKLRERNVNEMTVIFIGKQGVGKSSTVNTLL
NERVAPSSPFQPEN--------VRPLLAGRVAA-GFTLNVLDTPGLL----E---GDS--
VSARGLMALR----AALNGRKVD---------AFVFTDRLDTWR-V-DNADKAIFTSLAE
NFGA------------------------------------------ELWERTVLGFSHAQ
T-TP--------------------------------------------------------
-------------------------TDGRPYEEFVNAR----------------------
------------------------------------------------------------
-----------VEQYRKAI---RSTLNM-----PNLALPFALIENGSRCK-TNGNGEKVV
-NDRPWLSDMVSTMVEMACSKDGYEYDHGKAGKKLDPNN---------------------
-----KHKIWILPLFLFQAFVLRPLVIGQ-------------------------------
----------------------------IRRDIKK-ADEKKQRAAAAKH-----------
------------------------------------
>otToc34
------------------------------------------------------------
-----MSDEEYSEDE-YVSSEGEGAEGRDVEPQ---AQQAAP------------------
----VLGPKEWVGLSSMPAATQQALLETLGKLRERNVNEMTVIFIGKQGVGKSSTVNTLL
NERVAPSSPFQPEN--------ARPLLAGRVAA-GFTLNVLDTPGLL----D---GDS--
ISARGLMALR----AALNGRKVD---------AFIFTDRLDTWR-V-DNSDRAIFTALAE
NFGA------------------------------------------ELWERTVLGFSHAQ
T-TP--------------------------------------------------------
-------------------------PDGKPYEEFVNAR----------------------
------------------------------------------------------------
-----------VEQYRKAI---RQTLGM-----PNLTLPFALIENGSRCK-ANAAGEKVV
-NERPWLTDMVGTMVEMACAKESYEYDHKKAGKKLDPNN---------------------
-----KYKIWMLPLFLFQAFVLRPLMIGQ-------------------------------
----------------------------IRRDIRK-SDEDKKKKSARPAPKK--------
------------------------------------
>crToc34
------------------------------------------------------------
-----MAQPPRPAEEYDDDVQEDEDELKEGELDDDESHEAASEGGEAAAGDEEAEDDEQD
EEDGDEDSQPWAGLNRLP--ERDDMLDILNELRAEGRKQLTVLLLGKSSVGKSSLINSLL
GEAVVRVQAFKLQADTDITTTVVRQVAVGNSEVDGFRLKLIDTCGLE----DPEAGDT--
VNLGALSKIA----EDVRGVGID---------VVLYCDRLDLYR-V-DPLDKAIIDAISS
TFGR------------------------------------------GIWRRTVVALTHAN
LVQT--------------------------------------------------------
-------------------------PPGTDYDSFVNGR----------------------
------------------------------------------------------------
-----------VRLIRGAV---RGPLFFR------PSLPVALVENSETCPVSSESGFRVL
PDGEPWLVALVSQLVDMAAARRRPYKYHPRLSSKPSH-----------------------
-----RFRWLLPVAIAAEVLFYRRFLHPR-------------------------------
----------------------------LDDNQRRVEREEERVWALRGQQRRAL------
-------------GLHRPHRPDKDAAWRLEQMYDDD
>pwToc34
------------------------------------------------------------
------------------------------------------------------------
-----------------------VLALAECSGDRQRTGASRCCCWEREAWARVATVNSLL
GERAAVVSSFQATG--------LGVHMHTRTLPGGFALNLIDTPSLL----D---QDS--
VSTSRLEQIG----SAIKGVKID---------AVLFLDRLDVYS-T-DTLDEQVVDGVTA
YFGE------------------------------------------DMWDHAVLGLTRAT
SSAP--------------------------------------------------------
-------------------------PLSTDFGEWVVER----------------------
------------------------------------------------------------
-----------SLQLQSLIAKARAQYAPRRRRGEAPPLTPAGCRESQECP-RKLRGSGSS
PATAPGSPTCMPRWRSAATGAGQAWLHDAARR----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>jgi|Fracy1|149019|jgi|Fracy1|149019|gw1.11.270.1:9-303
------------------------------------------------------------
------------------------------------------------------------
------------------------------------HRCGYAGIVGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDM----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LE---------------DDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTAS-----------------------
------------------------------SLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GY-----
>jgi|Fracy1|149020|jgi|Fracy1|149020|gw1.9.619.1:9-303
------------------------------------------------------------
------------------------------------------------------------
------------------------------------HRCGYAGIVGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDV----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LE---------------DDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTAS-----------------------
------------------------------SLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GY-----
>jgi|Fracy1|190544|jgi|Fracy1|190544|e_gw1.11.270.1:28-322
------------------------------------------------------------
------------------------------------------------------------
-----------------MNTNTTTITNVNNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDM----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LE---------------DDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTAS-----------------------
------------------------------SLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GYSN---
>jgi|Fracy1|188959|jgi|Fracy1|188959|e_gw1.9.619.1:28-322
------------------------------------------------------------
------------------------------------------------------------
-----------------MNTNTTTITNVNNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDV----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LE---------------DDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTAS-----------------------
------------------------------SLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GYSN---
>jgi|Fracy1|140885|jgi|Fracy1|140885|gw1.11.73.1:1-320
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------VGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDM----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LEGRAKRPDEATIQRKKDDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTA------------------------
-------------------PIPGMFRNGVKSLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GY-----
>jgi|Fracy1|140886|jgi|Fracy1|140886|gw1.9.255.1:1-320
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------VGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDV----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LEGRAKRPDEATIQRKKDDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTA------------------------
-------------------PIPGMFRNGVKSLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GY-----
>jgi|Fracy1|190984|jgi|Fracy1|190984|e_gw1.11.73.1:28-347
------------------------------------------------------------
------------------------------------------------------------
-----------------MNTNTTTITNVNNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDM----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LEGRAKRPDEATIQRKKDDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTA------------------------
-------------------PIPGMFRNGVKSLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GYSN---
>jgi|Fracy1|190984|jgi|Fracy1|190984|e_gw1.11.73.1:1-81
------------------------------------------------------------
------------------------------------------------------------
-----------------MNTNTTTITNVNNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDM----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LEGRAKRPDEATIQRKKDDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTA------------------------
-------------------PIPGMFRNGVKSLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GYSN---
>jgi|Fracy1|189349|jgi|Fracy1|189349|e_gw1.9.255.1:28-347
------------------------------------------------------------
------------------------------------------------------------
-----------------MNTNTTTITNVNNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDV----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LEGRAKRPDEATIQRKKDDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTA------------------------
-------------------PIPGMFRNGVKSLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GYSN---
>jgi|Fracy1|243114|jgi|Fracy1|243114|fgenesh2_pg.11_#_8:162-524
MTVSILLALLSSTTKSSVVTVTAFRTTKIRTHRSNIRHDGDGARISHVPSYDSVINPLTM
LLASSPPSSS---SESTSESRPAKKKMKTKKKTAADTFLLLEKLDEQIDSYEGRLPSKMT
AVQKTIDGNIDTEGNNDMNTNTTTITNVNNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDM----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LEGRAKRPDEATIQRKKDDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTASVSNNDESDTDEHPGISLLRQILI
GCSSNDDHDIPAMVRALGRPIPGMFRNGVKSLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GYSN---
>jgi|Fracy1|242114|jgi|Fracy1|242114|fgenesh2_pg.9_#_588:165-527
MTVSILLALLSPTTISSVVTVTAFRTSKIRTHRSNIRHDGDGARISHVPSYDSIINPLTM
LLASSPPSSSESTSESTSESRPAKKKMKTKKKTAADTFLLLEKLDEQIDSYEGRLPSKMT
AAQKTTDGNIDTEGNNDMNTNTTTITNVNNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TKQCCLLDTPGVL----QGDGAYQ--
LQANMMEAVK----GALTDSDV----------IVVVTDLFSTPIPD-DNVFRRLS-----
----------------------------------------------ETTKPVLVVVNKID
LEGRAKRPDEATIQRKKDDEEEEEDEFEKTYTVVEAVEKWRLLL----------------
-------------------------PNALAIIPLTASVSNNDESDTDEHPGISLLRQILI
GCSSNDDHDIPAMVRALGRPIPGMFRNGVKSLTNDDVK-----QLLPIGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITDYKEPR-------------
----DDNITRIEATIFVERDGQKAIIIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGDVVKQVGIIAREKIERFLDG
EKVFLQLRVKINKDWRKREDQLAKF----GYSN---
>jgi|Psemu1|253210|jgi|Psemu1|253210|estExt_Genewise1Plus.C_650095:87-387
------------------------------------------------------------
------MSPSQNENSKKQRSGKSKSKKNIEKKRPADTLLILKQLDEKINSYEGRLPSKMP
ANLDTD-----------NDRSSTGFADTNNIQH-EQHRCGFVGIVGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRMLL----------------
-------------------------PDALAIIPMTA------------------------
-------------------------------------------TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GYTN--K
>jgi|Psemu1|187164|jgi|Psemu1|187164|e_gw1.65.149.1:87-387
------------------------------------------------------------
------MSPSQNENSKKQRSGKSKSKKNIEKKRPADTLLILKQLDEKINSYEGRLPSKMP
ANLDTD-----------NDRSSTGFADTNNIQH-EQHRCGFVGIVGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRMLL----------------
-------------------------PDALAIIPMTA------------------------
-------------------------------------------TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GYTN--K
>jgi|Psemu1|237240|jgi|Psemu1|237240|estExt_Genewise1.C_650108:35-335
------------------------------------------------------------
----------------------------------------------------------MP
ANLDTD-----------NDRSSTGFADTNNIQH-EQHRCGFVGIVGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRMLL----------------
-------------------------PDALAIIPMTA------------------------
-------------------------------------------TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GYTN--K
>jgi|Psemu1|253211|jgi|Psemu1|253211|estExt_Genewise1Plus.C_650096:35-322
------------------------------------------------------------
----------------------------------------------------------MP
ANLDTD-----------NDRSSTGFADTNNIQH-EQHRCGFVGIVGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRM------------------
------------------------------------------------------------
-------------------------------------------TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GYTN--K
>jgi|Psemu1|187190|jgi|Psemu1|187190|e_gw1.65.36.1:35-322
------------------------------------------------------------
----------------------------------------------------------MP
ANLDTD-----------NDRSSTGFADTNNIQH-EQHRCGFVGIVGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRM------------------
------------------------------------------------------------
-------------------------------------------TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GYTN--K
>jgi|Psemu1|253212|jgi|Psemu1|253212|estExt_Genewise1Plus.C_650097:35-348
------------------------------------------------------------
----------------------------------------------------------MP
ANLDTD-----------NDRSSTGFADTNNIQH-EQHRCGFVGIVGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRMLL----------------
-------------------------PDALAIIPMTAA-----------------------
------------------------------SYSGDVPKRRKM-TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GYTN--K
>jgi|Psemu1|187218|jgi|Psemu1|187218|e_gw1.65.138.1:35-348
------------------------------------------------------------
----------------------------------------------------------MP
ANLDTD-----------NDRSSTGFADTNNIQH-EQHRCGFVGIVGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRMLL----------------
-------------------------PDALAIIPMTAA-----------------------
------------------------------SYSGDVPKRRKM-TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GYTN--K
>jgi|Psemu1|117035|jgi|Psemu1|117035|gw1.65.36.1:24-311
------------------------------------------------------------
------------------------------------------------------------
--------------------SSTGFADTNNIQH-EQHRCGFVGIVGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRM------------------
------------------------------------------------------------
-------------------------------------------TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GYTN---
>jgi|Psemu1|154356|jgi|Psemu1|154356|gw1.65.149.1:54-354
------------------------------------------------------------
---------------------------------------ILKQLDEKINSYEGRLPSKMP
ANLDTD-----------NDRSSTGFADTNNIQH-EQHRCGFVGIVGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRMLL----------------
-------------------------PDALAIIPMTA------------------------
-------------------------------------------TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GY-----
>jgi|Psemu1|151549|jgi|Psemu1|151549|gw1.65.138.1:1-314
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------VGAPNMGKSTLLNGLL
KEDLCIATRRPQTT--------RHAILGVLSSP-TRQCCLLDTPGVL----QGDGAYK--
LQANMMEAVK----GALKDSDV----------LLVVTDMFSTPIPN-DEIFRRLS-----
----------------------------------------------LTNKPVLVVVNKID
LEGRAQRPTETDGEEKKND-EDDEDEVEKTYTVAEAVAKWRMLL----------------
-------------------------PDALAIIPMTAA-----------------------
------------------------------SYSGDVPKRRKM-TLLPVGPP----LYDDD
FLSDRSVRFFCSELIREAL---LESRYLKKELPYCCEVQITEYKEPR-------------
---KEKDLTRIEATIFVERDGQKAIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-NGSVIKQVGIVAREKIERFLDG
EKIFLKLQVKVDKDWRKKDDALTKF----GY-----
>gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217406280|gb|EEC46220.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MGAPNMGKSTLLNALL
EEDLCIATARPQTT--------RHAILGLMSTD-KCQVCLVDTPGVI----E-DPAYE--
LQEGMMEAVT----GAVATSDV----------LLVVTDVFSTPIPD-DELFLKVQ-----
----------------------------------------------RTRKPVLVAINKID
LAKKVN--------------KAAEENRDKTVTVEEAVAFWRAQL----------------
-------------------------PNALCILPLSASQ----------------------
----------------------------GINNVGVVAMRRILTELLPISPP----LYDPE
TLTDRPERFIASEIVRSAL---FQ--VLKKELPYCCEVRIREFKEPK-------------
---EEGEVIRIAADVLVERDSQKVIVIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGAQVKEIGVIAREKLEAFFR-
HQIFLNLSVKVDKDWRKNTRKLTEY----GYMKPKR
>gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217406280|gb|EEC46220.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MGAPNMGKSTLLNALL
EEDLCIATARPQTT--------RHAILGLMSTD-KCQVCLVDTPGVI----E-DPAYE--
LQEGMMEAVT----GAVATSDV----------LLVVTDVFSTPIPD-DELFLKVQ-----
----------------------------------------------RTRKPVLVAINKID
LAKKVN--------------KAAEENRDKTVTVEEAVAFWRAQL----------------
-------------------------PNALCILPLSASQ----------------------
----------------------------GINNVGVVAMRRILTELLPISPP----LYDPE
TLTDRPERFIASEIVRSAL---FQ--VLKKELPYCCEVRIREFKEPK-------------
---EEGEVIRIAADVLVERDSQKVIVIG--------------------------------
------------------------------------------------------------
------------------------------------K-NGAQVKEIGVIAREKLEAFFR-
HQIFLNLSVKVDKDWRKNTRKLTEY----GYMKPKR
>gi|224012853|ref|XP_002295079.1| predicted protein [Thalassiosira pseudonana CCMP1335] >gi|220969518|gb|EED87859.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------MLLPITFNGFVLIGCAVLRSTHLASSTNTV
AFVPSASSIRSTSSTHHQHTVLFAESGNKYAKEDKQTQQELLQTLESKFDYEGRIASKVG
D----------------GDNSSTDTSTTN-----PSHRCALVTILGKPNMGKSTLLNSLL
SDNLAIATSRPQTT--------RHAILGVMTSD-HNQLCLTDTPGII----D-KTAYK--
LQDGMMDVVK----GAVKSADL----------FLVVTDEEDPYLGIGEDTVKMIK-----
----------------------------------------------QMEKPVIVCVNKVD
LASV----------------DKSSVYVNTPPLAVQTIGKWRALL----------------
-------------------------PNAFAIIPTCAAN----------------------
------------------------------------------VDLLPIGPP----LYHPD
FFTDRTDRFCASELIRETL---FE--TLGKELPYCCEVRVETFDESK-----RYLDEDSV
GSGKNKSMIRIGATILVERDSQKGIVVG--------------------------------
------------------------------------------------------------
------------------------------------K-GGQQIKDLGMNARKKLQVFFD-
TKIFLDLRVKVDKNWRNNAEKLKKY----GYMQ---
>jgi|Fracy1|186584|jgi|Fracy1|186584|e_gw1.7.131.1:43-415
-------------------------MFKNAVLFPQRRARTWLWNNS--NTTTDACRANLS
YAIE-RCCSSSSSSSSSQSQSQ--------------------------------------
-----------------SQSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILT
QSPVAAVSRKRHTT--------RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVIDSARAL--S-ENYRHAFVQLMTG
AINSKGRIEESFGDDNEIDDKSSIHNNNKSSDDDANPNSN------DGRGKFAIVLNKVD
LVKPKS--------------TLIDLAMEIGAIADTCLEDHFTEH----------------
---GKT--I------DFEAMLEHS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLDHLINLATPCKEWAVQSG
QSTNMTELEQVQEIIREKI---YR--TCHREVPHSVQQVNRMFRKIP-------------
-KKG----VIIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------A-GGRTLERIRESAQTDLRKMFK-
CEVSLHLHVKKKIGR--RGDSGTEYKLG-EASQTIL
>jgi|Fracy1|240292|jgi|Fracy1|240292|fgenesh2_pg.7_#_630:43-415
-------------------------MFKNAVLFPQRRARTWLWNNS--NTTTDACRANLS
YAIE-RCCSSSSSSSSSQSQSQ--------------------------------------
-----------------SQSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILT
QSPVAAVSRKRHTT--------RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVIDSARAL--S-ENYRHAFVQLMTG
AINSKGRIEESFGDDNEIDDKSSIHNNNKSSDDDANPNSN------DGRGKFAIVLNKVD
LVKPKS--------------TLIDLAMEIGAIADTCLEDHFTEH----------------
---GKT--I------DFEAMLEHS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLDHLINLATPCKEWAVQSG
QSTNMTELEQVQEIIREKI---YR--TCHREVPHSVQQVNRMFRKIP-------------
-KKG----VIIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------A-GGRTLERIRESAQTDLRKMFK-
CEVSLHLHVKKKIGR--RGDSGTEYKLG-EASQTIL
>jgi|Fracy1|187133|jgi|Fracy1|187133|e_gw1.7.947.1:43-377
-------------------------MFKNAVLFPQRRARTWLWNNS--NTTTDACRANLS
YAIE-RCCSSSSSSSSSQSQSQ--------------------------------------
-----------------SQSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILT
QSPVAAVSRKRHTT--------RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVIDSARAL--S-ENYRHA-------
-------------------------------DDDANPNSN------DGRGKFAIVLNKVD
LVKPKS--------------TLIDLAMEIGAIADTCLEDHFTEH----------------
---GKT--I------DFEAMLEHS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLDHLINLATPCKEWAVQSG
QSTNMTELEQVQEIIREKI---YR--TCHREVPHSVQQVNRMFRKIP-------------
-KKG----VIIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------A-GGRTLERIRESAQTDLRKMFK-
CEVSLHLHVKKKIGR--RGDSGTEYKLG-EASQTIL
>jgi|Fracy1|158143|jgi|Fracy1|158143|gw1.7.947.1:1-321
------------------------------------------------------------
------------------------------------------------------------
-------------------SQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILT
QSPVAAVSRKRHTT--------RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVIDSARAL--S-ENYRHA-------
-------------------------------DDDANPNSN------DGRGKFAIVLNKVD
LVKPKS--------------TLIDLAMEIGAIADTCLEDHFTEH----------------
---GKT--I------DFEAMLEHS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLDHLINLATPCKEWAVQSG
QSTNMTELEQVQEIIREKI---YR--TCHREVPHSVQQVNRMFRKIP-------------
-KKG----VIIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------A-GGRTLERIRESAQTDLRKMFK-
CEVSLHLHVK--------------------------
>jgi|Fracy1|226249|jgi|Fracy1|226249|fgenesh2_pm.7_#_308:48-420
----------------MQLEPVQRSIVQNQSLLLSIAADVMCFIAR-------SIIAHTE
YCIQYRCCSSSSSSSSSQSQSQ--------------------------------------
-----------------SQSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILT
QSPVAAVSRKRHTT--------RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVIDSARAL--S-ENYRHAFVQLMTG
AINSKGRIEESFGDDNEIDDKSSIHNNNKSSDDDANPNSN------DGRGKFAIVLNKVD
LVKPKS--------------TLIDLAMEIGAIADTCLEDHFTEH----------------
---GKT--I------DFEAMLEHS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLDHLINLATPCKEWAVQSG
QSTNMTELEQVQEIIREKI---YR--TCHREVPHSVQQVNRMFRKIP-------------
-KKG----VIIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------A-GGRTLERIRESAQTDLRKMFK-
CEVSLHLHVKKKIGR--RGDSGTEYKLG-EASQTIL
>jgi|Fracy1|139406|jgi|Fracy1|139406|gw1.7.131.1:7-365
------------------------------------------------------------
------------------SQSQ--------------------------------------
-----------------SQSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILT
QSPVAAVSRKRHTT--------RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVIDSARAL--S-ENYRHAFVQLMTG
AINSKGRIEESFGDDNEIDDKSSIHNNNKSSDDDANPNSN------DGRGKFAIVLNKVD
LVKPKS--------------TLIDLAMEIGAIADTCLEDHFTEH----------------
---GKT--I------DFEAMLEHS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLDHLINLATPCKEWAVQSG
QSTNMTELEQVQEIIREKI---YR--TCHREVPHSVQQVNRMFRKIP-------------
-KKG----VIIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------A-GGRTLERIRESAQTDLRKMFK-
CEVSLHLHVK--------------------------
>jgi|Fracy1|186460|jgi|Fracy1|186460|e_gw1.7.1091.1:43-169
-------------------------MFKNAVLFPQRRARTWLWNNS--NTTTDACRANLS
YAIE-RCCSSSSSSSSSQSQSQ--------------------------------------
-----------------SQSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILT
QSPVAAVSRKRHTT--------RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVIDSAR-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>jgi|Fracy1|160081|jgi|Fracy1|160081|gw1.7.1091.1:1-93
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------VAIVGAPNAGKSQLVNILT
QSPVAAVSRKRHTT--------RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVIDSAR-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>jgi|Fracy1|254023|jgi|Fracy1|254023|fgenesh2_pg.52_#_25:26-133
-------------------------MFKNAVLFPQRRARTWLWNNS--------------
------------------------------------------------------------
-----------------------------------NTTTLDVAIVGAPNAGKSQLVNILT
QSPVAAVSRKRHTT--------RSDILGARTIG-NTQIVFKDTPGFM----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVIDSARAL--S-ENYRHAFVELK--
------------------------------------------------------------
--------------------NLLGMIRD--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>jgi|Psemu1|163870|jgi|Psemu1|163870|gw1.57.139.1:16-384
------------------------------------------------------------
--VK-FLSSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHALVQLMVG
AINSGGRIEDCDDDDDNNDRKTT-----RQSREDINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQR------------------
>jgi|Psemu1|252850|jgi|Psemu1|252850|estExt_Genewise1Plus.C_570067:60-428
------------------MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLSSQAS
SRVK-FLSSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHALVQLMVG
AINSGGRIEDCDDDDDNNDRKTT-----RQSREDINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
>jgi|Psemu1|186266|jgi|Psemu1|186266|e_gw1.57.139.1:60-428
------------------MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLSSQAS
SRVK-FLSSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHALVQLMVG
AINSGGRIEDCDDDDDNNDRKTT-----RQSREDINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
>jgi|Psemu1|64246|jgi|Psemu1|64246|estExt_Genemark1.C_570046:60-428
------------------MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLSSQAS
SRVK-FLSSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHALVQLMVG
AINSGGRIEDCDDDDDNNDRKTT-----RQSREDINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
>jgi|Psemu1|8240|jgi|Psemu1|8240|gm1.8240_g:60-428
------------------MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLSSQAS
SRVK-FLSSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHALVQLMVG
AINSGGRIEDCDDDDDNNDRKTT-----RQSREDINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
>jgi|Psemu1|102320|jgi|Psemu1|102320|gw1.57.18.1:12-346
------------------------------------------------------------
-------SSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHAL------
---------------------------------DINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSV-
>jgi|Psemu1|252849|jgi|Psemu1|252849|estExt_Genewise1Plus.C_570066:60-394
------------------MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLSSQAS
SRVK-FLSSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHAL------
---------------------------------DINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
>jgi|Psemu1|186359|jgi|Psemu1|186359|e_gw1.57.18.1:60-394
------------------MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLSSQAS
SRVK-FLSSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHAL------
---------------------------------DINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
>jgi|Psemu1|252848|jgi|Psemu1|252848|estExt_Genewise1Plus.C_570065:60-398
------------------MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLSSQAS
SRVK-FLSSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHALVQLM--
---------------------------------DINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
>jgi|Psemu1|186337|jgi|Psemu1|186337|e_gw1.57.145.1:60-398
------------------MRKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLSSQAS
SRVK-FLSSSSPSSTRRQSPPA--------------------------------------
-----------------SRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLT
KSPIAAVSRKRHTT--------RSDLLGARTVG-NTQIVFKDTPGFL----RIENAKEER
LDRDLIATAA----SEMQDVDF----------TLLVLDSARTL--S-DNYRHALVQLM--
---------------------------------DINPSSKCDTAIPSDKSKFAIVLNKVD
LVKPKT--------------DLISLAMDVGTMADTCLLDQFQKQ----------------
---GRE--F------DFDAQMEQS-PIVFYVSAL--KE----------------------
-----------------------------------DGTDDLLEHLLGLATPSREWPVEPG
KATNMTTLEQVQEVIREKI---YR--STHKEVPHAVQQVNRLFRRIP-------------
-NKG----VVIHQDLVVFTKSHQKLVLG--------------------------------
------------------------------------------------------------
------------------------------------SGGGKTLKRIQESARHDLQKLFG-
CDVALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
>gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217410895|gb|EEC50824.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------MRPTFIR----------------------------------T
ALVT-FRWSGGPKISRSDRVRL--------------------------------------
-----------------S----STTIGST--PSLEDRKRLDVAIVGLPNAGKSQLLNVLT
QSTVAAVSRKRHTT--------RDGILGARTVD-DTQLYFVDTPGFL----RQSQAKKEG
LNRDLVVTAS----SEMENVDF----------SLLVVDAARRM--T-DDYEETLVALMLA
ALRSQGRLEFDVHSAEEVQSIRT-------------PKGG------TNPAKFAVVLNKVD
LVHPKS--------------NLMDLAVNIGTLAEQCIKFDAKES----------------
---GKEELF------LDSAYLQESLPMFFYISAL--KQ----------------------
-----------------------------------RGVQDLLEFLLERATPSTSWEVEAG
EATPMTMKERIEEVIREKI---YR--CLHKEVPHSIRQENRVLQQGK-------------
-DEDGNIVLVIHQDLIVRSKSHQELVHG--------------------------------
------------------------------------------------------------
------------------------------------G-GGRTLERIRETAARGLEKIFF-
CNVVLHLHVKLPRSKNQRWSI---------------
>gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217410895|gb|EEC50824.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------MRPTFIR----------------------------------T
ALVT-FRWSGGPKISRSDRVRL--------------------------------------
-----------------S----STTIGST--PSLEDRKRLDVAIVGLPNAGKSQLLNVLT
QSTVAAVSRKRHTT--------RDGILGARTVD-DTQLYFVDTPGFL----RQSQAKKEG
LNRDLVVTAS----SEMENVDF----------SLLVVDAARRM--T-DDYEETLVALMLA
ALRSQGRLEFDVHSAEEVQSIRT-------------PKGG------TNPAKFAVVLNKVD
LVHPKS--------------NLMDLAVNIGTLAEQCIKFDAKES----------------
---GKEELF------LDSAYLQESLPMFFYISAL--KQ----------------------
-----------------------------------RGVQDLLEFLLERATPSTSWEVEAG
EATPMTMKERIEEVIREKI---YR--CLHKEVPHSIRQENRVLQQGK-------------
-DEDGNIVLVIHQDLIVRSKSHQELVHG--------------------------------
------------------------------------------------------------
------------------------------------G-GGRTLERIRETAARGLEKIFF-
CNVVLHLHVKLPRSKNQRWSI---------------
>gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335] >gi|220973246|gb|EED91577.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
------------------MAFF---------------RRALLQGSLAVNNLTHDTWHQTP
RAIT-SLLNHQQSCSLHSTPIT--------------------------------------
-----------------LNNPTSSSAATTQSDKPAPQKRLDVAIVGAPNAGKSQLLNSLI
GSKVAAVSRKRHTT--------RTGILGARTFD-DTQLVFIDTPGFL----HHEMSVKEG
V-RKLLGEAS----SEMESADF----------VLLVVDAARKM--E-DDLRRTLVTLMFL
ALRSKGRNE------------------------------------------FAVVLNKVD
LVSPKE--------------KLLMTAADVGSMAESCIRQFLNQRRSPSKVKFGELVDTVL
KNYANEDGFDGVHDDDIELFATLA-PEFFFTSAIVKDD----------------------
-----------------------------------EGVDDVLGLLLERATLSDQWIVDAG
SATGMTPVEQVEEIIREKI---YR--CLHREVPHSVQQQNRMFQLYKPNESKTKSTDGSD
VDEDI-KILRIRQDLIVRTKSHQRLVLG--------------------------------
------------------------------------------------------------
------------------------------------S-GGKTLERIRSTALKDLEESFD-
CIVDLDLTVRVTKSNQHEAILDPESVGAVSLTPLEN
>gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335] >gi|220973246|gb|EED91577.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
------------------MAFF---------------RRALLQGSLAVNNLTHDTWHQTP
RAIT-SLLNHQQSCSLHSTPIT--------------------------------------
-----------------LNNPTSSSAATTQSDKPAPQKRLDVAIVGAPNAGKSQLLNSLI
GSKVAAVSRKRHTT--------RTGILGARTFD-DTQLVFIDTPGFL----HHEMSVKEG
V-RKLLGEAS----SEMESADF----------VLLVVDAARKM--E-DDLRRTLVTLMFL
ALRSKGRNE------------------------------------------FAVVLNKVD
LVSPKE--------------KLLMTAADVGSMAESCIRQFLNQRRSPSKVKFGELVDTVL
KNYANEDGFDGVHDDDIELFATLA-PEFFFTSAIVKDD----------------------
-----------------------------------EGVDDVLGLLLERATLSDQWIVDAG
SATGMTPVEQVEEIIREKI---YR--CLHREVPHSVQQQNRMFQLYKPNESKTKSTDGSD
VDEDI-KILRIRQDLIVRTKSHQRLVLG--------------------------------
------------------------------------------------------------
------------------------------------S-GGKTLERIRSTALKDLEESFD-
CIVDLDLTVRVTKSNQHEAILDPESVGAVSLTPLEN
>gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
------------------MFGI---------------RRLVVGGSVRHGGHARGRPLPCP
ACPT-GPDISSSASSLLSRTMT--------------------------------------
-----------------SYFDGGPSAPET--SRPKQQRRLDIAIVGAPNAGKSQLLNSLV
GSKVAAVSRKRHTT--------RSGILGARTFG-DTQLVFIDTPGFL----HHSKGAREG
V-RNLLSEAS----AEMMNADF----------ALLVVDAAKTI--D-QDLKRTLVTLMML
ALRSTGREEGSRVFSDQ-----------------------------RHLGRFSVVLNKVD
LVKPKE--------------KLLATAAEVGSLAESCVRRLLQQHRAPVRVKMGELVDSVL
ERHEDEEGFAGVHEEDYETFASVV-PEFLFTSAIDPED----------------------
-----------------------------------EGADDLLNVLLSRATPSTEFVMDPS
SN-----LEQVEEIIREKI---YR--CLHREVPHHVQQTNRVFKL------KQDQPPDHD
VRADMGDLLQIHQDLIVRTKSHHRLVLG--------------------------------
------------------------------------------------------------
------------------------------------S-GGKTLQRIQTTASKDLRELFG-
CEVDLLLSVKLKKTNQ-GVLLDPEEEGA-RITTLHD
>gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
------------------MFGI---------------RRLVVGGSVRHGGHARGRPLPCP
ACPT-GPDISSSASSLLSRTMT--------------------------------------
-----------------SYFDGGPSAPET--SRPKQQRRLDIAIVGAPNAGKSQLLNSLV
GSKVAAVSRKRHTT--------RSGILGARTFG-DTQLVFIDTPGFL----HHSKGAREG
V-RNLLSEAS----AEMMNADF----------ALLVVDAAKTI--D-QDLKRTLVTLMML
ALRSTGREEGSRVFSDQ-----------------------------RHLGRFSVVLNKVD
LVKPKE--------------KLLATAAEVGSLAESCVRRLLQQHRAPVRVKMGELVDSVL
ERHEDEEGFAGVHEEDYETFASVV-PEFLFTSAIDPED----------------------
-----------------------------------EGADDLLNVLLSRATPSTEFVMDPS
SN-----LEQVEEIIREKI---YR--CLHREVPHHVQQTNRVFKL------KQDQPPDHD
VRADMGDLLQIHQDLIVRTKSHHRLVLG--------------------------------
------------------------------------------------------------
------------------------------------S-GGKTLQRIQTTASKDLRELFG-
CEVDLLLSVKLKKTNQ-GVLLDPEEEGA-RITTLHD
