>jgi|Fracy1|190984|jgi|Fracy1|190984|e_gw1.11.73.1:28-347
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
------------------------------------------------------------
--------------------------------NTNTTTITNVNNDDHQQQHRCGYAGIVG
APNMGKSTLLNSLLKEDLCIATRRPQTTRHAILGVLSS-----PTKQCCLLDTPGVLQGD
GAYQ--LQANMMEAVKGALTDSDMIVVVTDLFSTP---IPDD------------------
-------------------------------N-VFRRLSETTKPVLVVVNKIDLEGRAKR
PDEAT--------------------------IQRKKDDEEEEEDEFEKTYTVVEAVEKWR
LLLP---------NALAIIPLTAPIPGMFRNGVKSLTNDDVKQLLPIGPPLYDDDFLSDR
SVRFFCSELIREALLESRYLKKELPYCCEVQITDYKEPR-----------------DDNI
TRIEATIFVERDGQKAIIIGK-NGDVVKQVGIIAREKIERFLDGEKVFLQLRVKINKDWR
KREDQLAKFGYSN--------
>jgi|Psemu1|253210|jgi|Psemu1|253210|estExt_Genewise1Plus.C_650095:87-387
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
--------------------------------SPSQNENSKKQRSGKSKSKKNIEKKRPA
DTLLILKQLDEKINSYEGRLPSKMPANLDTDNDRSSTGFADTNNIQH-EQHRCGFVGIVG
APNMGKSTLLNGLLKEDLCIATRRPQTTRHAILGVLSS-----PTRQCCLLDTPGVLQGD
GAYK--LQANMMEAVKGALKDSDVLLVVTDMFSTP---IPND------------------
-------------------------------E-IFRRLSLTNKPVLVVVNKIDLEGRAQR
PTETD--------------------------GEEKKND-EDDEDEVEKTYTVAEAVAKWR
MLLP---------DALAIIPMTA-------------------TLLPVGPPLYDDDFLSDR
SVRFFCSELIREALLESRYLKKELPYCCEVQITEYKEPR----------------KEKDL
TRIEATIFVERDGQKAIVVGK-NGSVIKQVGIVAREKIERFLDGEKIFLKLQVKVDKDWR
KKDDALTKFGYTN--K-----
>gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217406280|gb|EEC46220.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
------------------------------------------------------------
-----------------------------------------------------------G
APNMGKSTLLNALLEEDLCIATARPQTTRHAILGLMST-----DKCQVCLVDTPGVIE-D
PAYE--LQEGMMEAVTGAVATSDVLLVVTDVFSTP---IPDD------------------
-------------------------------E-LFLKVQRTRKPVLVAINKIDL------
---------------------------------AKKVN-KAAEENRDKTVTVEEAVAFWR
AQLP---------NALCILPLSA-SQGINNVGVVAM-RRILTELLPISPPLYDPETLTDR
PERFIASEIVRSALFQ--VLKKELPYCCEVRIREFKEPK----------------EEGEV
IRIAADVLVERDSQKVIVIGK-NGAQVKEIGVIAREKLEAFFR-HQIFLNLSVKVDKDWR
KNTRKLTEYGYMKPKR-----
>gi|224012853|ref|XP_002295079.1| predicted protein [Thalassiosira pseudonana CCMP1335] >gi|220969518|gb|EED87859.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MLLPITFN
GFVLIGCAVLRSTHLASSTNTVAFVPSASSIRSTSSTHHQHTVLFAESGNKYAKEDKQTQ
QELL---QTLESKFDYEGRIASKVGDGDNSSTDTSTTN----------PSHRCALVTILG
KPNMGKSTLLNSLLSDNLAIATSRPQTTRHAILGVMTS-----DHNQLCLTDTPGIID-K
TAYK--LQDGMMDVVKGAVKSADLFLVVTDE-EDPYLGIGED------------------
-------------------------------T-V-KMIKQMEKPVIVCVNKVDLASV---
---------------------------------------DKSSVYVNTPPLAVQTIGKWR
ALLP---------NAFAIIPTCA----------------ANVDLLPIGPPLYHPDFFTDR
TDRFCASELIRETLFE--TLGKELPYCCEVRVETFDESKRYLDEDSVG-----SGKNKSM
IRIGATILVERDSQKGIVVGK-GGQQIKDLGMNARKKLQVFFD-TKIFLDLRVKVDKNWR
NNAEKLKKYGYMQ--------
>NODE_3830936_27 [157 - 1101] length_3162_cov_13.956673
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------A-------
------------------------------------------------------------
--------------------------------GCRRTGVEKTGAGMSIDKSYCGFIAIVG
RPNVGKSTLLNKLLGQKISITSRKAQTTRHRIVGIHTE-----GAYQAIYVDTPGLHM-E
EKRA--INRLMNKAASSSIGDVELVIFVVE--GTRW--TPDD------------------
-------------------------------EMVLNKLREGKAPVILAVNKVD-------
-------------------------------------NVQEKAD----------------
-LLPHLQFLASQMNFLDIVPISA-ETGLNVDTIAAIVR----KHLPEATHHFPEDYITDR
SQRFMASEIIREKLMR--FLGAELPYSVTVEIERFVS------------------NERGG
YDINGLILVEREGQKKMVIGN-KGAKIKTIGIEARKDMQEMFE-APVHLELWVKVKSGWA
DDERALRSLGYVD-DL-----
>jgi|Fracy1|187133|jgi|Fracy1|187133|e_gw1.7.947.1:43-377
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
---------------------------FKNAVLFPQRRARTWLWNNSNT--TTDACR---
-------ANLSYAIE-RCCSSSSSSSSSQSQSQSQSQSQSTLQQSPSTIGRKRLDVAIVG
APNAGKSQLVNILTQSPVAAVSRKRHTTRSDILGARTI-----GNTQIVFKDTPGFMRIE
NAKEERLDRDLIATAASEMQDVDFTLLVIDSARA----LSENYRHA--------------
------------------------DDDANPNSN------DGRGKFAIVLNKVDLVKPKST
LIDLAMEIGAIADTCLEDHFTEH--------GKTIDF--EAMLEHS--------------
---P---------IVFYVSAL-------KEDGTDDLLDHLINLATPCKEWAVQSGQSTNM
TELEQVQEIIREKIYR--TCHREVPHSVQQVNRMFRKIP--------------KKG----
VIIHQDLVVFTKSHQKLVLGA-GGRTLERIRESAQTDLRKMFK-CEVSLHLHVK--KKIG
RRGDSGTEYKLGEASQTIL--
>jgi|Fracy1|226249|jgi|Fracy1|226249|fgenesh2_pm.7_#_308:48-420
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
---------------------------QLEPV------QRSIVQNQSLL--LSIAADVMC
FIARSIIAHTEYCIQYRCCSSSSSSSSSQSQSQSQSQSQSTLQQSPSTIGRKRLDVAIVG
APNAGKSQLVNILTQSPVAAVSRKRHTTRSDILGARTI-----GNTQIVFKDTPGFMRIE
NAKEERLDRDLIATAASEMQDVDFTLLVIDSARA----LSENYRHAFVQLMTGAINSKGR
IEESFGDDNEIDDKSSIHNNNKSSDDDANPNSN------DGRGKFAIVLNKVDLVKPKST
LIDLAMEIGAIADTCLEDHFTEH--------GKTIDF--EAMLEHS--------------
---P---------IVFYVSAL-------KEDGTDDLLDHLINLATPCKEWAVQSGQSTNM
TELEQVQEIIREKIYR--TCHREVPHSVQQVNRMFRKIP--------------KKG----
VIIHQDLVVFTKSHQKLVLGA-GGRTLERIRESAQTDLRKMFK-CEVSLHLHVK--KKIG
RRGDSGTEYKLGEASQTIL--
>jgi|Psemu1|8240|jgi|Psemu1|8240|gm1.8240_g:60-428
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
--------------------RKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLS---
-------SQASSRVK-FLSSSSPSSTRRQSPPASRPQAAATAQNR----TRKRLDVAIVG
PPNAGKSQLVNVLTKSPIAAVSRKRHTTRSDLLGARTV-----GNTQIVFKDTPGFLRIE
NAKEERLDRDLIATAASEMQDVDFTLLVLDSART----LSDNYRHALVQLMVGAINSGGR
IEDCDDDDDNNDRKTTRQS-----REDINPSSKCDTAIPSDKSKFAIVLNKVDLVKPKTD
LISLAMDVGTMADTCLLDQFQKQ--------GREFDF--DAQMEQS--------------
---P---------IVFYVSAL-------KEDGTDDLLEHLLGLATPSREWPVEPGKATNM
TTLEQVQEVIREKIYR--STHKEVPHAVQQVNRLFRRIP--------------NKG----
VVIHQDLVVFTKSHQKLVLGSGGGKTLKRIQESARHDLQKLFG-CDVALQLHVKYRKSKQ
QRGDSGAQYNLGEVSQSVY--
>jgi|Psemu1|252849|jgi|Psemu1|252849|estExt_Genewise1Plus.C_570066:60-394
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
--------------------RKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGWLS---
-------SQASSRVK-FLSSSSPSSTRRQSPPASRPQAAATAQNR----TRKRLDVAIVG
PPNAGKSQLVNVLTKSPIAAVSRKRHTTRSDLLGARTV-----GNTQIVFKDTPGFLRIE
NAKEERLDRDLIATAASEMQDVDFTLLVLDSART----LSDNYRHAL-------------
--------------------------DINPSSKCDTAIPSDKSKFAIVLNKVDLVKPKTD
LISLAMDVGTMADTCLLDQFQKQ--------GREFDF--DAQMEQS--------------
---P---------IVFYVSAL-------KEDGTDDLLEHLLGLATPSREWPVEPGKATNM
TTLEQVQEVIREKIYR--STHKEVPHAVQQVNRLFRRIP--------------NKG----
VVIHQDLVVFTKSHQKLVLGSGGGKTLKRIQESARHDLQKLFG-CDVALQLHVKYRKSKQ
QRGDSGAQYNLGEVSQSVY--
>gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217410895|gb|EEC50824.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
---------------------------------------RPTFIRTALV-----------
-------------------TFRWSGGPKISRSDRVRLSSTTIGSTPSLEDRKRLDVAIVG
LPNAGKSQLLNVLTQSTVAAVSRKRHTTRDGILGARTV-----DDTQLYFVDTPGFLRQS
QAKKEGLNRDLVVTASSEMENVDFSLLVVDAARR----MTDDYEETLVALMLAALRSQGR
LEFDVHSAEEVQSIRT-------------PKGG------TNPAKFAVVLNKVDLVHPKSN
LMDLAVNIGTLAEQCIKFDAKES--------GKEELFLDSAYLQES--------------
--LP---------MFFYISAL-------KQRGVQDLLEFLLERATPSTSWEVEAGEATPM
TMKERIEEVIREKIYR--CLHKEVPHSIRQENRVLQQGK--------------DEDGNIV
LVIHQDLIVRSKSHQELVHGG-GGRTLERIRETAARGLEKIFF-CNVVLHLHVKLPRSKN
QRWS--------------I--
>gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335] >gi|220973246|gb|EED91577.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
-----------------------------------AFFRRALLQGSLAVNNLTHDTWHQT
PRAITSLLNHQQ-------SCSLHSTPITLNNPTSSSAATTQSDKPA--PQKRLDVAIVG
APNAGKSQLLNSLIGSKVAAVSRKRHTTRTGILGARTF-----DDTQLVFIDTPGFLHHE
MSVKEGV-RKLLGEASSEMESADFVLLVVDAARK----MEDDLRRTLVTLMFLALRSKGR
NE------------------------------------------FAVVLNKVDLVSPKEK
LLMTAADVGSMAESCIRQFLNQRRSPSKVKFGELVDTVLKNYANEDGFDGVHDDDIELFA
TLAP---------EFFFTSAIVK-----DDEGVDDVLGLLLERATLSDQWIVDAGSATGM
TPVEQVEEIIREKIYR--CLHREVPHSVQQQNRMFQLYKPNESKTKSTDGSDVDEDI-KI
LRIRQDLIVRTKSHQRLVLGS-GGKTLERIRSTALKDLEESFD-CIVDLDLTVRVTKS-N
QHEAILDPESVGAVSLTPLEN
>gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------M-------
-----------------------------------FGIRRLVVGGSVRHGGHARGRPLPC
PACPTGPDISSS-------ASSLLSRTMTSYFDGGPSAPET--SRPK--QQRRLDIAIVG
APNAGKSQLLNSLVGSKVAAVSRKRHTTRSGILGARTF-----GDTQLVFIDTPGFLHHS
KGAREGV-RNLLSEASAEMMNADFALLVVDAAKT----IDQDLKRTLVTLMMLALRSTGR
EEGSRVFSDQ-----------------------------RHLGRFSVVLNKVDLVKPKEK
LLATAAEVGSLAESCVRRLLQQHRAPVRVKMGELVDSVLERHEDEEGFAGVHEEDYETFA
SVVP---------EFLFTSAIDP-----EDEGADDLLNVLLSRATPSTEFVMDPSSN---
--LEQVEEIIREKIYR--CLHREVPHHVQQTNRVFKL------KQDQPPDHDVRADMGDL
LQIHQDLIVRTKSHHRLVLGS-GGKTLQRIQTTASKDLRELFG-CEVDLLLSVKLKKT-N
Q-GVLLDPEEEGA-RITTLHD
>NODE_3217431_10 [208 - 2] (REVERSE SENSE) length_180_cov_17.744444
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------DARSGEGVADIIGHLGAMATPSQHWPVPAGLATNQ
SMEERIQEMIREKIYRCLHREVPYAVDQQNRLLK--------------------------
------------------------------------------------------------
---------------------
>NODE_5633892_22 [421 - 2] (REVERSE SENSE) length_391_cov_5.074169
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------RQSISTEINLQDARSKQALPRPDAELMESITTKKRLDVAIVG
LPNAGKSQLLNVLTESTVSAVSRKRHTTREGILGARTIFPEPGEGIQFVFVDTPGFLKHD
PKNPERLERKLVVSATVAMRTVDYTLIVVDAARNLGNE----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
