>cmToc34
M----------------DSETPTKNEAEQRASPDRTGQVTQRPVSLFRKNGT--------
---------------FAYPLEDSDVYEEQVLALEDVPEPTAQAILRLALAAERQGVPRLR
FLVVGAPGVGKSSLINTLLNENLCSVSAWERGT--------KNAQVCARQV-----D-SV
VIEFIDTPGIAPCRRSGLEASRRQVQRLR----KLLDA------RGADEHPYLRSFHAIL
YVMRLDDTRPDLVDYHNWKVLMEFFGA---------------------------------
---------EVLRHMMVVFTHGQS-LPPDSLSYPEYVRGRRDYVYLLI---ERLTG----
PLKAVRFPVF---------VAENSSKCPVIEETGERKLPDDTP-------WITQLYDGIR
RFVFPLEADLF---GMETGPEDTQVLVYIYDKRRSRADERYPRSPLQALIRNPWFLRAVQ
FCGAMLLRSYMIRQEHERFNP-KPHHPEPIIRDANNAFAVASRRANDHRLFTPSIDEDEE
SFFRMNGNDDFVSRLRNRPGEVDLDELDVERIESPDGRFVEYWYT-EKDNPEMVRMYRLE
IRDDPNEERESRQDRIPISKDQH
>acToc34	
M-----------------------------------------------------------
---------------------S--FLTREWVGIQQFPAATQTKLHEILGKLKQENVNTMT
ILVMGKGGVGKSSTVNSILGERVATVSAFQSEG--------LRPIMCSRTR-----A-GF
TLNVIDTPGIV----EGGYVNEQALEIIK----RFLLD------KTID---------VLL
YVDRLDSYRVDNLDKQVVKAITDFLGK---------------------------------
---------EIWQRGVVVLTHAQL-SPPDGLNYDDYLEKRSDALLKYV---RLGAGIKKK
ELQGKGIPVA---------LVENSGRCK-TNEDGEKILPNGTA-------WIPNLVQQSQ
T-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>vvtoc34	
M-----------------------------------------------------------
--------------------AS--QLIREWTGIQQFPPVTQTKLIELLGKLKQENVSTLT
ILVMGKGGVGKSSTVNSIIGERAVAVSAFQSEG--------PRPVMVSRSR-----A-GF
TLNIIDTPGLV----EGGYVNDQALEIIK----RFLLN------KTID---------VLL
YVDRLDAYRVDNLDRQVVKAITDSFGK---------------------------------
---------EIWRRGVVVLTHAQL-SPPDGLNYEDFFSKRSEALMKVV---RSGARLRKQ
DIQDSGIPVV---------LVENSGRCH-KNESDEKILPNGTA-------WIPNLVKTIT
DAVSNGSKGILVDKKLIEGPNPNE--------------------------RGKLLIPFIL
AFQYFFIVKRIQRAIKSDMAK-ER--KAPWESREANRYEP--------------------
------------------------------------------------------------
-----------------------
>stToc34-2
M-----------------------------------------------------------
--------------------AS--QIIREWAGIQQFPAATQSKLLELLGKLKQENVSTLT
ILVMGKGGVGKSSTVNSIIWERAVAVSAFQSET--------PRPVMVSRSR-----A-GF
TLNIIDTPGLV----EGGYVNDQALDLIK----KFLLN------KTID---------VLL
YVDRLDAYRVDNLDKQIVKAITDSFGK---------------------------------
---------EIWRRGIVVLTHAQL-SPPDGLTYDEFTSRRSEALLKIV---RMGARIRKQ
DIQAASIPVV---------LVENSGRCN-KNESDEKILPSGTA-------WIPNLVQTIT
DAVLSGSKGILVDQKLIEGPNPNN--------------------------RGKVLIPFIL
AFQYFFVVKRIQKSIKNDIAR-ES--RPAWA-----------------------------
------------------------------------------------------------
-----------------------
>leToc34-2
M-----------------------------------------------------------
--------------------AS--QIIREWAGIQQFPAATQSKLLELLGKLKQENVSTLT
ILVMGKGGVGKSSTVNSIIGERAVAVSAFQSET--------PRPVMVSRSR-----A-GF
TLNIIDTPGLV----EGGYVNDQALDLIK----KFLLN------KTID---------VLL
YVDRLDAYRVDNLDKQIVKAITDIFGK---------------------------------
---------EMWCRGIVVLTHAQL-SPPDGLTYEEFTSRRSEALLKIV---RMGARIRKQ
DIQAASIPVV---------LVENSGRCN-KNESDEKILPSGIA-------WIPNLVQTIT
DAVLSGSKGILVDQKLIEGPNPNN--------------------------RGKVLIPFIL
AFQYFFVVKRIQRSIKNDIAR-ET--RPSWA-----------------------------
------------------------------------------------------------
-----------------------
>leToc34-1
M-----------------------------------------------------------
--------------------AS--QVIREWVGFQQFPSATQSKLIELIRKLKQESVSTVT
ILVMGKGGVGKSSTVNSILGERAVAVSAFQSET--------PRPVMVSRSW-----A-EF
TLNIIDTPGLV----EGGYVNDQALDLIK----RFLLN------KTID---------VLL
YVDRLDTYRVDNLDRQIVKAITDSFGK---------------------------------
---------GIWRRGLVVLTHAQV-SPPDGLSYDEFTSRRSEALLKIV---RLGARMKKQ
EIKAASIPLV---------CVENSGRCN-KNELDEKILPNGTA-------WIPSILQTIT
EVVVSQSKGILIDQKLIEGPNPNN--------------------------KGKLLIPLIA
TFQYFFVVKRIQTWIKNDISR-EN--RPSWA-----------------------------
------------------------------------------------------------
-----------------------
>stToc34-1
M-----------------------------------------------------------
--------------------AS--QVIREWVGFQQFPSATQSKLIELIRKLKQESVSTLT
ILVMGKGGVGKSSTVNSILGERAVAVSAFQSET--------PRPVMVSRSW-----A-EF
TLNIIDTPGLV----EGGYVNDQALDLIK----RFLLN------KTID---------VLL
YVDRLDTYRVDNLDRQIVKAITDSFGK---------------------------------
---------EIWHRGLVVLTHAQV-SPPDGLSYDEFTSRRSEALSKIV---RLGARIRKQ
EVKASSVPIV---------CVENSGRCN-KNELDEKILPNGTA-------WIPNLLQTIT
EVVASESKGILVDQKLIEGPNPNN--------------------------KGKLLIPLIA
AFQYFFVVKRIQKWIKNDIAR-ET--RPSWA-----------------------------
------------------------------------------------------------
-----------------------
>mtToc34-1
M-----------------------------------------------------------
--------------------ASQQQQVREWSGINTFAPATQTKLLELLGKLKQEDVNSLT
ILVMGKGGVGKSSTVNSIIGERVVAISPFQSEG--------PRPVMVSRAR-----A-GF
TLNIIDTPGLI----EGGYINDMALDIIK----RFLLD------KTID---------VLL
YVDRLDAYRVDNLDKLVAKAITDSFGK---------------------------------
---------GIWNKAIVALTHAQF-SPPDALAYDEFFSKRSESLLQII---KSGASLKKD
DAQASAIPVV---------LIENSGRCN-KNETDEKVLPNGIA-------WIPHLVHTIT
EIALNKSESIFVDKNLIEGPNPNQ--------------------------RGKLWIPVLF
ALEFLLIMKPIEGLIKNDVAN-EK--KPSWETRDVGVKKE--------------------
--TREVGQKDMRKERRGGAVRR--------------------------------------
-----------------------
>psToc34	
M-----------------------------------------------------------
--------------------ASQQQTVREWSGINTFAPATQTKLLELLGNLKQEDVNSLT
ILVMGKGGVGKSSTVNSIIGERVVSISPFQSEG--------PRPVMVSRSR-----A-GF
TLNIIDTPGLI----EGGYINDMALNIIK----SFLLD------KTID---------VLL
YVDRLDAYRVDNLDKLVAKAITDSFGK---------------------------------
---------GIWNKAIVALTHAQF-SPPDGLPYDEFFSKRSEALLQVV---RSGASLKK-
DAQASDIPVV---------LIENSGRCN-KNDSDEKVLPNGIA-------WIPHLVQTIT
EVALNKSESIFVDKNLIDGPNPNQ--------------------------RGKLWIPLIF
ALQYLFLAKPIEALIRRDIAT-ET--KPAWETRDVGDRK---------------------
------------------------------------------------------------
-----------------------
>pcToc34	
M-----------------------------------------------------------
--------------------AS--QIIREWSGINTFAPATQTKLLELLGKLKQENVNSLT
ILVMGKGGVGKSSTVNSIIGERVVSISPLQSEG--------PRPVMVSRSR-----A-GF
TLNIIDTPGLI----EGGYINDMALDIIK----RFLLN------KTID---------VLL
YVDRLDVYRVDNLDKLVAKAITDSFGK---------------------------------
---------GIWNKAIVALTHAQF-SPPDGLPYEDFFSQRSEALLRVL---RSGAKIKKE
VFQAASMP----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>asToc34	
------------------------------------------------------------
------------------------------------------------------------
--------------------------SAFQSEG--------LRPMMCSRTR-----A-GF
TLNIIDTPGLI----EGGYINEQAVEIIK----RFLLE------KTID---------VLL
YVDRLDTYRMDTLDEQVIRAITTSFGK---------------------------------
---------AIWRRTLVVLTHAQL-SPPDGLDYNDFLTRRSESLLRYI---RSGAGIGKR
ESADYPLPLA---------LVENSGRCK-TNENGAKILPDGTP-------WIPNLMKEIT
MVVSNGSKPIHVDQKLIDGPNPNN--------------------------RWKKYIPLIL
AVQYFFVVKGIRRAIHSDIAN-GK--LDDWEQRYRDLVGS--------------------
--GNPVDQKVSSSRNPRPEAGQ--------------------------------------
-----------------------
>osToc34	
M-----------------------------------------------------------
-------------------SAA--PIPREWVGLQQFPAATQTKLHELLGKLKEENVSTLT
ILVMGKGGVGKSSTVNSIVGERVATVSAFQSEG--------LRPMMCSRTR-----A-GF
TLNIIDTPGLI----EGGYINEQAVEIIK----RFLLG------KTID---------VLL
YVDRLDAYRMDTLDDQVIRAVTNSFGK---------------------------------
---------AIWRRTLVVLTHAQL-SPPDGLDYNDFFTKRSESLLRYI---RAGAGVSKR
ELGDFPLPIA---------LVENSGRCK-TNENGEKVLPDGTP-------WIPNLMKEIT
TVVSNGSKSIHVDQKLIDGPNPNN--------------------------RWKMFIPLIL
MVEYFLVVKGIRRAIHADISN-GK--LDDWEQRYRDLVGS--------------------
--KDPVDQKGSSSGNRK----A--------------------------------------
-----------------------
>sbToc34	
M-----------------------------------------------------------
--------------------AS--PIPREWAGLQQFPAATQTKLHELLGKLKEEDVSTLT
ILVMGKGGVGKSSTVNSIVGERVTTVSAFQSEG--------LRPTMCSRTR-----A-GF
TLNIIDTPGLI----EGGYINEQAVDIIK----RFLLG------KTID---------VLL
YVDRLDAYRMDTLDEQVIRAITNSFGK---------------------------------
---------DIWRRSLVVLTHAQL-SPPDGIDYNDFFTRRSEALLRYI---RSGAGINKR
EYGDFPLPIA---------LVENSGRCK-ANEHGEKILPDGTP-------WVPNLM----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>zmToc34-1
M-----------------------------------------------------------
--------------------AS--PIPREWVGLQQFPPATQTELHELLGKLKEEDVSTLT
ILVMGKGGVGKSSTVNSIVGERIATVSAFQSEG--------LRPMMWSRTR-----A-GF
TLNIIDTPGLI----EGGYINEQAVDIIK----RFLLG------KTID---------VLL
YVDRLDAYRMDTLDGQVIRAITNSFGK---------------------------------
---------DIWRRSLVVLTHAQL-SPPDGIEYNDFFTRRSEALLRYI---HSGAGIKKR
EYGDFPLPIA---------LVENSGRCK-TNEHGEKILPDGTP-------WVPKLMKEIT
VVISNGSKPIHVDQKLIDGPNPNN--------------------------RWKMFIPIIL
AVEYFLVVKGIRRAIHADIAN-GK--VDDWEQRYRDLVGS--------------------
--RDPVEQKGSTTRNRK----A--------------------------------------
-----------------------
>zmToc34-2
M-----------------------------------------------------------
--------------------AS--PIPREWVGLQQFPAATQTKLHELLGKLKEEDVSTLT
ILVMGKGGVGKSSTVNSIVGERVASVSAFQSEG--------LRPMMCSRTR-----A-GF
TLNIIDTPGLI----EGGYINEQAVDIIK----RFLLG------KTID---------VLL
YVDRLDAYRMDTLDEQVIRAITNSFGK---------------------------------
---------DIWRRSLVVLTHAQL-SPPDGIDYNDFFTRRSEALLRYI---HSGAGINKR
EYGDFPLPIA---------LVENSGRCK-TNEHGEKILPDGTL-------WVPNLMKEIT
VVISNGSSPIHVDQKLIDGPNPNN--------------------------RRKLFIPLIL
AVEYFLVVKGIRRAIHADIAN-GK--VDDWEQRYRDLVGS--------------------
--RDLVEQKGSTSRNRK----A--------------------------------------
-----------------------
>soToc34	
M-----------------------------------------------------------
--------------------AS--PIPREWVGLQQFPAATQTKLHELLGKLKEEDVSTLT
ILVMGKGGVGKSSTVNSIVGERVTTVSAFQSEG--------LRPMMCSRTR-----A-GF
TLNIIDTPGLI----EGGYINEQAVDIIK----RFLLG------KTID---------VLL
YVDRLDAYRMDTLDEQVIRAITNSFGK---------------------------------
---------DIWRRSLVVLTHAQL-SPPDGIDYNDFFTRRSKALLPYI---RSGAGIQPT
RIWGFP-------------------PCQ--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>hvToc34	
M-----------------------------------------------------------
--------------------AA--PIPREWVGLQQFPAATQTKLHELLGKLKEENVSTLT
ILVMGKGGVGKSSTVNSIVGERVANVSAFQSEG--------LRPMMCSRTR-----A-GF
TLNIIDTPGLI----EGGYINEQAVEIIK----RFLLE------KTID---------VLL
YVDRLDTYRMDTLDEQVIRAITSSLGK---------------------------------
---------AIWRRTLVVLTHAQL-SPPDGIDYNDFLARRSESLVRYI---RSGAGIGKR
EYADFPLPIA---------LAEDSGKGR-TNENGA--ILDGNS-------WDSKLE----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>brToc34	
M-----------------------------------------------------------
-------------------AAL--QMSREWIGIQQFPPATQSKLIEILNKFKEEDVSSLT
VLVMGKGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPSLVSRSR-----S-GF
TLNIIDTPGLI----EGGYVNDQAVNLIK-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>rrToc34	
M-----------------------------------------------------------
-------------------AAL--QMSREWIGIQQFPPATQSKLLEILGKFEEEDVSSLT
VLVMGKGGVGKSSTVNSVIGERAAAVSTFQSEG--------LRPSLVSRSR-----S-GF
TLNIIDTPGLI----EGGYVNDQAVNLIK----GFLPN------KTID---------VLL
YVDRLDVYRVDDLDKQVVTAITDAFGK---------------------------------
---------EIWKKSALVLSHAQF-SPPDGLNYDLFVSRRSDALLKLI---YASAQLK--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>bnToc34	
M-----------------------------------------------------------
-------------------AAL--QMSREWIGIQQFPPATQSKLLEILGKFKEEDVSSLT
VLVMGKGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPSLVSRSR-----S-GF
TLNIIDTPGLI----EGGYVNDQAVNLIK----RFLLN------MTID---------VLL
YVDRLDVYRVDDLDKQVVTAITDAFGK---------------------------------
---------EIWKKSALVLSHAQF-SPPDGLNYDLFVSRRSDALLKLI------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>boToc34	
M-----------------------------------------------------------
-------------------AAL--QVSREWIGIQQFPPATQSKLLEILGKFKEEDVSSLT
VLVMGKGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPSLVSRSR-----S-GF
TLNIIDTPGLI----EGGYVNGQAVNLIK----RFLLN------MTID---------VLL
YVDRLDVYRVDDLDKQVVTAITDAFGK---------------------------------
---------EIWKKSALVLSHAQF-SPRDG------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>atToc34	
M-----------------------------------------------------------
-------------------AAL--QTLREWIGIQQFPPATQSKLLEILGKYKEEDVSSLT
VLVMGKGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPTLVSRTR-----S-GF
TLNIIDTPGLI----EGGYVNDQAINIIK----RFLLN------MTID---------VLL
YVDRLDVYRVDDLDRQVVGAITDAFGK---------------------------------
---------EIWKKSALVLTHAQF-SPPDGLNYNHFVSKRSNALLKVI---QTGAQLKKQ
DLQGFSIPVI---------LVENSGRCH-KNESDEKILPCGTS-------WIPNLFNKIT
EISFNGNKAIHVDKKLVEGPNPNE--------------------------RGKKLIPLMF
AFQYLLVMKPLVRAIKSDVSR-ES--KLAWELRDSGLASR--------------------
--RS--------------------------------------------------------
-----------------------
>tsToc34	
P-----------------------------------------------------------
--------------------------------------------------TRPEDVSSLT
VLVRGKGGVGKSSTVNSVIGEKAAAVSTFQSEG--------LRPSLVSRSR-----S-GF
TLNIIDTPGLI----EGGYVNDGAVNLIK----GFLLN------KTID---------VLL
YVDRLDVYRVDDLDRQVVTAITDAFGK---------------------------------
---------EIWKKSALVLSHAQF-SPPDGL-YDLFVSRRSDS--SVI---CAGAQLKKQ
DLQGSSIPVI---------LVENSGRC---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>lsToc34	
------------------------------------------------------------
------------------------------------------------------------
-------------------GERAVTVSAFQSEA--------LRPTMVSRER-----S-GF
TLNIIDTPGIV----EGGYVNDQALEIIK----RFLLN------KTID---------VLL
YVDRLDAYRVDTLDGQIVKAISNSFGQ---------------------------------
---------QIWRKAIVVLTHAQL-SPPDCLSYDEFLAKRSEALLKVV---YRGARFRKL
DIENFPIPIG---------LVENSSRCN-KNEKDEKILPNGSA-------WIPSIVETIT
EVSLTESKSILVDQKLIDGPNPN---------------------------RGKLFIPFII
AFQYFFV-----------------------------------------------------
------------------------------------------------------------
-----------------------
>ptToc34-1
M-----------------------------------------------------------
--------------------GS---VLREWIGFQQFPTATQSKLVELFAKLKEEGVDKLT
ILVMGKGGVGKSSTVNSLFGERAVNVSSFQSEG--------FRPVMVSRNR-----A-GF
TLNIIDTPGLV----EGGYVSYQALDMIK----RFLLN------KTIH---------VLL
YVDRLDAYRVDDLDKQIIGAISDSFGK---------------------------------
---------EIWSKSLLVLTHAQL-SPPDDLSYDVFCARRSEAVLKTI---RMGARIRKR
DFEDSAIPVG---------LVENSGRCN-KNENDEKILPNGDA-------WIPSLVKEII
LVATNGKKLLLMRSWLVGLSQMTG---------------------------GKIFIPLIL
GI----------------------------------------------------------
------------------------------------------------------------
-----------------------
>ptToc34-3
M-----------------------------------------------------------
--------------------GS---VLREWIGFQQFPTATQSKLVELFAKLKEEGVDKLT
ILVMGKGGVGKSSTVNSLFGERAVNVSSFQSEG--------FRPVMVSRNR-----A-GF
TLNIIDTPGLV----EGGYVSYQALDMIK----RFLLN------KTIH---------VLL
YVDRLDAYRVDDLDKQIIGAISDSFGK---------------------------------
---------EIWSKSLLVLTHAQL-CPPDDLSYDVFCARRSEAVLKTI---RMGARIRKR
DFEDSAIPVG---------LVENSGRCN-KNENDEKILPSGDA-------WIPSLVKEII
LVATNGKKALVVDEKLVNGSESND--------------------------RGKIFIPLIL
GIQW-LLVKWIQREIKKDIAK-GG--KYL-------------------------------
------------------------------------------------------------
-----------------------
>ptToc34-2
G-----------------------------------------------------------
--------------------------------------------------------NKMT
ILVMGKGGVGKSSTVNSLLGERVVNVSSFQSEG--------LRPVMVSRDR-----A-GF
TLNIIDTPGLV----EGGYVNYQSLELIK----RFLLN------KTIN---------VLL
YVDRLDAYRVDDLDKQIISAITDSFGK---------------------------------
---------EIWNKSLLVLTHAQL-CPPDDLSYDVFCGRRSEAVLKTI---RMGAQI-KR
DFEDSAIP-G---------LVENSGGCN-KSENDEKILPNGDA-------WIPTLVK-IV
GVATNGKKSLLDQ-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>atToc33	
M-----------------------------------------------------------
--------------------GS---LVREWVGFQQFPAATQEKLIEFFGKLKQKDMNSMT
VLVLGKGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-----G-GF
TINIIDTPGLV----EAGYVNHQALELIK----GFLVN------RTID---------VLL
YVDRLDVYRVDELDKQVVIAITQTFGK---------------------------------
---------EIWCKTLLVLTHAQF-SPPDELSYETFSSKRSDSLLKTI---RAGSKMRKQ
EFEDSAIAVV---------YAENSGRCS-KNDKDEKALPNGEA-------WIPNLVKAIT
DVATNQRKAIHVDKKMVDGSYSDD--------------------------KGKKLIPLII
GAQY-LIVKMIQGAIRNDIKT-SG--KPL-------------------------------
------------------------------------------------------------
-----------------------
>bnToc33	
M-----------------------------------------------------------
--------------------GS---LVREWVGFQQFPAATQEKLIEFFAKLKQKDMNSLT
VVVMGKGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-----G-GF
TINIIDTPGLV----EAGYVNHQALELIK----GFLVN------RTID---------VLL
YVDRLDVYRVDELDKQVVQAITQTFGK---------------------------------
---------EIWCKTLLVLTHAQF-SPPDDLSYETFSSKRSDSLLKTI---RAGSKMGKQ
QFEDSAIEVV---------YAENSGRCS-KNDKEEKALPNGEA-------WIPNLVKAIT
DVATNQKKAIHVDKKMVDGSYSDD--------------------------KGKKLIPLII
AAQY-FVVKMIQGAIRSDIKT-SG--KPL-------------------------------
------------------------------------------------------------
-----------------------
>ovToc33	
M-----------------------------------------------------------
--------------------GS---LVREWVGFQQFPAATQEKLIGFFGKLKQKDMNSLT
VLVLGKGGVGKSSTANSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-----G-GF
TINIIDTPGLV----EAGYVNHQALELIK----GFLVN------RTID---------VFL
YVDRLDVYRVDELDKQVVQAITQTFGK---------------------------------
---------EIWCKTLLVLTHAQF-SPPDELSYETFSSKRSDSLFKTI---RAGSKMRKQ
QFEDSAIEVV---------YAENSGRCS-KNEKEEKALPNGEA-------WIPSLVKAIT
YVATNQRKAIHVDKKMVDGSYSDD--------------------------RGKKLIPLII
GAQW-FIVKMIQGAIRNDIKT-SG--KPL-------------------------------
------------------------------------------------------------
-----------------------
>ovToc33like
M-----------------------------------------------------------
--------------------GS---LVREWVGFQQFPAATQEKLIGFFGKLKQKDMNSLT
VLVLGKGGVGKSSTANSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-----G-GF
TINIIDTPGLV----EAGYVNHQALELIK----GFLVN------RTID---------VLL
YVDRLDVYRVDELDRQVVQAITQTFGK---------------------------------
---------EIWCKTLLVLTHAQF-SPPDELSYGTFSSKRSDSFLKTI---RTGSKMRKQ
QFEDSAIEVV---------YAENSGRCS-KNEKEEKALPNGEA-------WIPGLVKAIT
DVATNQRKAIHVDKKMVDGSYSDD--------------------------RGKKLIPLIM
AAQY-FIVEMIQGAIRNDIKT-SG--KPL-------------------------------
------------------------------------------------------------
-----------------------
>rrToc33	
M-----------------------------------------------------------
--------------------GS---LVREWVGFQQFPAATQEKLIEFFSKLKQKDMNSLT
VVVMGKGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-----G-GF
TINIIDTPDLV----EAGYVNHQALELIK----GFLVN------RTID---------VFL
YVDRLDVYRVDELDKQVVQAITQTFGK---------------------------------
---------EIWCKTLLVLTHAQF-SPPDDLSYETFSSKRSDSLLKTI---RAGSKMRKQ
QFEDSAIEVV---------YAENSGRCS-KNDKDEKALPNGEA-------WIPNLVKAIT
DVATIQKKAIHV------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>boToc33	
M-----------------------------------------------------------
--------------------GS---IVREWVGFQQFPAATQEKLIEFFAKLKQKDMNSLT
VVVMGKGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-----G-GF
TINIIDTPGLV----EAGYVNHQALELIK----GFLVN------RTID---------VLL
YVDRLDVYRVDELDKQVVQAITQTFGK---------------------------------
---------EIWCKTLLVLTHAQF-SPPDDLSYETFSSKRSDSLLKTI---RAGSKMGKQ
QFEDSAIEVV---------YAENSGRCS-KNDK---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>thToc33	
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------LDLIK----GFLVN------RTID---------VLL
YVDRLDVYRVDELDKQVVQAITQTFGK---------------------------------
---------EIWCKTLLVLTHAQF-SPPDELSYETFSSKRSDSLLTTI---RAGAKMRKQ
QFEDSAIAVV---------YAENSGRCS-KNEKEEKALPNGEA-------WIPNLVKSIT
DVATNQKKAIHVDNKMVDGSQSDD--------------------------KGKKLIPLII
GAQY-FIVKMIQGAIRNDIKI-SG--KPV-------------------------------
------------------------------------------------------------
-----------------------
>brToc33	
M-----------------------------------------------------------
--------------------GS---LVREWVGFQQFPAATQEKLIEFFTKLKQKDMNSLT
LVVMGKGGVGKSSTVNSLIGEQVVRVSPFQAEG--------LRPVMVSRTM-----G-GF
TINIIDTPGLV----EAGYVNHQALELIK----GFLVN------RTID---------VLL
YVDRLDVYRVDELDKQVVQAITQTFGK---------------------------------
---------EIWCKTLLVLTHAQF-SPPDDLSYETFSSKRSDSLLRTI---RAGSKMGET
TV----------------------GFCN--------------------------------
--------------GCVCGETVED------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>grToc34	
M-----------------------------------------------------------
--------------------GT--PLPREWLGLQQFPAATQTKLFELLGKLKQENVNTLT
IVVMGKGGVGKSSTINSLIGEQVVRVTAFQSEG--------LRPVMVSRSW-----A-GF
TLNVIDTPGLV----EAGYVNHQALELIK----GFLLN------KTID---------VLL
YVDRLDVYRVDNLDKQIIRAITNSFGK---------------------------------
---------EIWRKSLLVLTHAQL-CPPDGLNYDVFSSKRSEGVLKAI---RMGARIRKM
DLEDSVIPVV---------LVENTGRCN-KNDIDEKILPNGEA-------WVPNFGKSH-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>amToc34	
M-----------------------------------------------------------
--------------------AA--QLIKEWSAIQQFPAATQEKLVDLLGKLKNQDVNTLT
ILVMGKGGVGKSSTINSIIGERVVTVSAFQSET--------PRPVMVSRSR-----S-GF
TLNVIDTPGLV----EGGYVNDQVLETIKSFLGRFLMN------KTID---------VLL
YVDRLDAYRVDNLDKQIVKAITESFGK---------------------------------
---------EIWHKAVVVLTHAQL-SPPDALSYEEFFSRRSDSLLKFV---CQGAGINKK
DLKNFDIPVA---------LVEN-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>laToc34	
M-----------------------------------------------------------
--------------------TS--PITREWAGFNTFPPETQTKLLELLGRLKEKNVNKLT
ILVMGKCGVGKSSTVNSIIGERAVVINPFQSEG--------LRPVMVSRSR-----T-EF
TLNIIDTPGII----EGGCINNQALELIK----HFLLN------KTID---------ILL
YVDRLDTYRVDELDKMVVRAITNSFGK---------------------------------
---------EIWNRALIVLTHAQL-SPPDGLPYDEFVSKRSEALLKVV---HQGARLKKG
DLASS-IPSV--------------SRCN-KNDSGEK-GPNGTA-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>peToc34	
------------------------------------------------------------
------------------------------------------------------------
-----------------IVGERVAIVSAFQSEA--------MRPLICSRSR-----A-GF
TLNIIDTPGLI----EGGFVNDHALDLIK----RFLIN------KTID---------ILL
YVDRLDGYRVDDLDMQVTKAISKSFGQ---------------------------------
---------QIWRRGLVVLTHAQL-SPPDELRYADFVDRRSAILQAVV---RKAAGFKKS
ETQ---IPVV---------LVENSGRCN-TNSGGEKVLSDGTV-------WLPYLVEKIV
EVATNGSKPILIDKKLIEGPDANQ--------------------------WGKRWIPLFL
AFQYFFIVKPIRRGIQKDIQR-EKSERPAWEIYDETGDKTI-------------------
------------------------------------------------------------
-----------------------
>ppToc34-1
M-----------------------------------------------------------
--------------------AA--TPAREWTGLQQFPVATQTALHNILGTLRQQNKESLT
VLVVGKGGVGKSSTVNSIVGERVTIVSAFQSET--------LRPLQCARSR-----A-GF
TLNIIDTPGLV----EGGCINDQALDIIK----RFLLS------KTID---------VVL
YVDRLDGYRVDNLDRQVIRGLARSFGP---------------------------------
---------NFWRLAVIVLTHAQF-SPSDGVNYTEFVEKRSAALQAAI---RQEAGLKKD
EKE---VPYA---------LVENSGRCN-TNDGGEKILPNGTV-------WLPALVERIV
EVATGTTDSVFVDKKLIDGPNANE--------------------------WGKWWIPVLA
VAQYFLVVMPIRKAIEKDLAE-EKNQRPQWEIRAEEFRRN-TSLYDDDQVDEQAISQALE
QDDGLSGQPSSFVDEDDDDDEF--------------------------------------
-----------------------
>ppToc34-3
M-----------------------------------------------------------
--------------------AA--TQAREWTGLLQFPVATQTALHNILGKLRQQKKESLT
VLVVGKGGVGKSSTVNSIIGERVTVVSAFQSET--------LRPLQCARTR-----A-GF
TLNVIDTPGLI----EGGCINDQALDIIK----RFLLN------KTID---------VVL
YVDRLDGYRVDNLDKQVIRALARSFGP---------------------------------
---------NFWRIAIIALTHAQL-SPPDGVDYTEFVNNRSAALRAAI---RQEAGFKKS
EGE---ISYM---------LVENSGRCN-TNSEGEKVLPNGSV-------WLPALVDRIA
EVATGATPSIHVDQKLIDGPNANG--------------------------KGKWWIPLII
LAQYFLIVRPIRSAIEKDLIE-EEKQRPQWQIRAEEFVRPIASLYEDDQVDEQAIRQALK
Q-GALNDQMDSFVEDDEDDDEY--------------------------------------
-----------------------
>ppToc34-2
M-----------------------------------------------------------
--------------------AT--VSEKEWTGFQGLPAATQIILHTLLAKLRKQKVDKIT
IVLLGKGGVGKSSIVNSLFSERVAAVSAFRSET--------LRPRQYSRSK-----D-GF
KLTVIDTPGFV----EAGRV-DAALNSIR----RYLLG------KTIN---------VVL
YVDRLDGPREDKVDVKISRAISQAFGP---------------------------------
---------QIWPHVIVVFTHAEI-HLED-VTYSEFVSRRSAALRNII---LKESRFKTV
NTK---VPFV---------LVENCSRCS-ENGEHEKILPDGTV-------WLPVLFEALV
DLVLGSKKPILIDEKMIGIPKGNP--------------------------LGSIWMPLVL
LAQFVLIWRPIRKAIDRDLVE-EAQRHSP-------------------------------
------------------------------------------------------------
-----------------------
>olToc34
M----------------------------------------------SEEEYSEDEDYVS
SEGEGVEGTEEGGEGQPAQAAAPVLGPKEWVGLSSMPAATQSALLETLGKLRERNVNEMT
VIFIGKQGVGKSSTVNTLLNERVAPSSPFQPEN--------VRPLLAGRVA-----A-GF
TLNVLDTPGLL----EGDSVSARGLMALR----AALNG------RKVD---------AFV
FTDRLDTWRVDNADKAIFTSLAENFGA---------------------------------
---------ELWERTVLGFSHAQT-TPTDGRPYEEFVNARVEQYRKAI---RSTLNM---
--PNLALPFA---------LIENGSRCK-TNGNGEKVV-NDRP-------WLSDMVSTMV
EMACSKDGYEYDHGKAGKKLDPNN--------------------------KHKIWILPLF
LFQAFVLRPLVIGQIRRDIKK-ADEKKQRAAAAKH-------------------------
------------------------------------------------------------
-----------------------
>otToc34
M----------------------------------------------SDEEYSEDE-YVS
SEGEGAEGRDVEPQ---AQQAAPVLGPKEWVGLSSMPAATQQALLETLGKLRERNVNEMT
VIFIGKQGVGKSSTVNTLLNERVAPSSPFQPEN--------ARPLLAGRVA-----A-GF
TLNVLDTPGLL----DGDSISARGLMALR----AALNG------RKVD---------AFI
FTDRLDTWRVDNSDRAIFTALAENFGA---------------------------------
---------ELWERTVLGFSHAQT-TPPDGKPYEEFVNARVEQYRKAI---RQTLGM---
--PNLTLPFA---------LIENGSRCK-ANAAGEKVV-NERP-------WLTDMVGTMV
EMACAKESYEYDHKKAGKKLDPNN--------------------------KYKIWMLPLF
LFQAFVLRPLMIGQIRRDIRK-SDEDKKKKSARPAPKK----------------------
------------------------------------------------------------
-----------------------
>crToc34
M------------------------AQPPRPAEEYDDDVQEDEDELKEGELDDDESHEAA
SEGGEAAAGDEEAEDDEQDEEDGDEDSQPWAGLNRLP--ERDDMLDILNELRAEGRKQLT
VLLLGKSSVGKSSLINSLLGEAVVRVQAFKLQADTDITTTVVRQVAVGNSE-----VDGF
RLKLIDTCGLE-DPEAGDTVNLGALSKIA----EDVRG------VGID---------VVL
YCDRLDLYRVDPLDKAIIDAISSTFGR---------------------------------
---------GIWRRTVVALTHANLVQTPPGTDYDSFVNGRVRLIRGAV---RGPLFFR--
----PSLPVA---------LVENSETCPVSSESGFRVLPDGEP-------WLVALVSQLV
DMAAARRRPYKYHPRLSSKPSH----------------------------RFRWLLPVAI
AAEVLFYRRFLHPRLDDNQRRVEREEERVWALRGQQRRAL--------------------
------------------------GLHRPHRPDKDAAWRLEQMYDDD-------------
-----------------------
>pwToc34
V-----------------------------------------------------------
-------------------------------------------LALAECSGDRQRTGASR
CCCWEREAWARVATVNSLLGERAAVVSSFQATG--------LGVHMHTRTL-----PGGF
ALNLIDTPSLL----DQDSVSTSRLEQIG----SAIKG------VKID---------AVL
FLDRLDVYSTDTLDEQVVDGVTAYFGE---------------------------------
---------DMWDHAVLGLTRATSSAPPLSTDFGEWVVERSLQLQSLIAKARAQYAPRRR
RGEAPPLTPA---------GCRESQECP-RKLRGSGSSPATAP-------GSPTCMPRWR
SAATGAGQAWLHDAARR-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>F.cylindrus_4 jgi|Fracy1|190984|jgi|Fracy1|190984|e_gw1.11.73.1:28-347
M-----------------------------------------------------------
-------------------------------------NTNTTTITNVNNDDHQQQHRCGY
AGIVGAPNMGKSTLLNSLLKEDLCIATRRPQTT--------RHAILGVLSS-----P-TK
QCCLLDTPGVL----QGDGA--YQLQ-------ANMMEAVKGALTDSD---------MIV
VVTDLFSTPIPD-DNVFRRLS---------------------------------------
---------ETTKPVLVVVNKIDL-EGRAKRPDEATIQRKKDDEEEEEDEFEKTYT----
-------------------VVEAVEKWRLLLPNALAIIPLTAPIPGMFRNGVKSLTNDDV
KQLLPIGPPLYDDDFLSDRSVRFF------------------------------------
------CSELIREALLESRYL-KKELPYCCEVQITDYKEPR-----------------DD
NITRIEATIFVERDGQKAIIIGK-NGDVVKQVGIIAREKIERFLDGEKVFLQLRVKINKD
WRKREDQLAKFGYSN--------
>P-N.multiseries_3 jgi|Psemu1|253210|jgi|Psemu1|253210|estExt_Genewise1Plus.C_650095:87-387
M------------------------------------SPSQNENSKKQRSGKSKSKKNIE
KKRPADTLLILKQLDEKINSYEGRLPSKMPANLDTDNDRSSTGFADTNNIQH-EQHRCGF
VGIVGAPNMGKSTLLNGLLKEDLCIATRRPQTT--------RHAILGVLSS-----P-TR
QCCLLDTPGVL----QGDGA--YKLQ-------ANMMEAVKGALKDSD---------VLL
VVTDMFSTPIPN-DEIFRRLS---------------------------------------
---------LTNKPVLVVVNKIDL-EGRAQRPTETDGEEKKND-EDDEDEVEKTYT----
-------------------VAEAVAKWRMLLPDALAIIPMTAT-----------------
--LLPVGPPLYDDDFLSDRSVRFF------------------------------------
------CSELIREALLESRYL-KKELPYCCEVQITEYKEPR----------------KEK
DLTRIEATIFVERDGQKAIVVGK-NGSVIKQVGIVAREKIERFLDGEKIFLKLQVKVDKD
WRKKDDALTKFGYTNK-------
>P.tricornutum_3 gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217406280|gb|EEC46220.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
---MGAPNMGKSTLLNALLEEDLCIATARPQTT--------RHAILGLMST-----D-KC
QVCLVDTPGVI----E-DPA--YELQ-------EGMMEAVTGAVATSD---------VLL
VVTDVFSTPIPD-DELFLKVQ---------------------------------------
---------RTRKPVLVAINKIDL--------------AKKVN-KAAEENRDKTVT----
-------------------VEEAVAFWRAQLPNALCILPLSAS-QGINNVGVVAM-RRIL
TELLPISPPLYDPETLTDRPERFI------------------------------------
------ASEIVRSALFQ--VL-KKELPYCCEVRIREFKEPK----------------EEG
EVIRIAADVLVERDSQKVIVIGK-NGAQVKEIGVIAREKLEAFFR-HQIFLNLSVKVDKD
WRKNTRKLTEYGYMKPKR-----
>T.pseudonana_2 gi|224012853|ref|XP_002295079.1| predicted protein [Thalassiosira pseudonana CCMP1335] >gi|220969518|gb|EED87859.1| predicted protein [Thalassiosira pseudonana CCMP1335]
MLLPITFNGFVLIGCAVLRSTHLASSTNTVAFVPSASSIRSTSSTHHQHTVLFAESGNKY
AKEDKQTQQELLQTLESKFDYEGRIASKVGDGDNSSTDTSTTN----------PSHRCAL
VTILGKPNMGKSTLLNSLLSDNLAIATSRPQTT--------RHAILGVMTS-----D-HN
QLCLTDTPGII----D-KTA--YKLQ-------DGMMDVVKGAVKSAD---------LFL
VVTDEEDPYLGIGEDTVKMIK---------------------------------------
---------QMEKPVIVCVNKVDL-ASVDKSSV----------------YVNTPPL----
-------------------AVQTIGKWRALLPNAFAIIPTCAA----------------N
VDLLPIGPPLYHPDFFTDRTDRFC------------------------------------
------ASELIRETLFE--TL-GKELPYCCEVRVETFDESK-----RYLDEDSVGSGKNK
SMIRIGATILVERDSQKGIVVGK-GGQQIKDLGMNARKKLQVFFD-TKIFLDLRVKVDKN
WRNNAEKLKKYGYMQ--------
>NODE_3830936_27 [157 - 1101] length_3162_cov_13.956673
A-----------------------------------------------------------
-------------------------------------GCRRTGVEKTGAGMSIDKSYCGF
IAIVGRPNVGKSTLLNKLLGQKISITSRKAQTT--------RHRIVGIHTE-----G-AY
QAIYVDTPGLH-------MEEKRAIN-------RLMNKAASSSIGDVE---------LVI
FVVEGTRWTPDD-EMVLNKLR---------------------------------------
---------EGKAPVILAVNKVDN-VQEKADLLPHLQFLASQM-----------------
--------------------------------NFLDIVPISAE-----TGLNVDTIAAIV
RKHLPEATHHFPEDYITDRSQRFM------------------------------------
------ASEIIREKLMR--FL-GAELPYSVTVEIERFVSNE------------------R
GGYDINGLILVEREGQKKMVIGN-KGAKIKTIGIEARKDMQEMFE-APVHLELWVKVKSG
WADDERALRSLGYVDDL------
>F.cylindrus_2 jgi|Fracy1|187133|jgi|Fracy1|187133|e_gw1.7.947.1:43-377
M-------------------------------FKNAVLFPQRRARTWLWNNS--NTTTDA
CR--------ANLSYAIE-RCCSSSSSSSSSQSQSQSQSQSQSTLQQS--PSTIGRKRLD
VAIVGAPNAGKSQLVNILTQSPVAAVSRKRHTT--------RSDILGARTI-----G-NT
QIVFKDTPGFM----RIENAKEERLD-------RDLIATAASEMQDVD---------FTL
LVIDSARALSENYRHA--------------------------------------DDDANP
NSN------DGRGKFAIVLNKVDL-VKPKSTLIDLAMEIGAIADTCLEDHFTEHGK----
-----------------------TIDFEAMLEHSPIVFYVSAL----KEDGTDDLLDHLI
NLATPCKEWAVQSGQSTNMTELEQ------------------------------------
------VQEIIREKIYR--TC-HREVPHSVQQVNRMFRKIP------------------K
KGVIIHQDLVVFTKSHQKLVLGA-GGRTLERIRESAQTDLRKMFK-CEVSLHLHVK--KK
IGRRGDSGTEYKLGEASQTIL--
>F.cylindrus_1 jgi|Fracy1|226249|jgi|Fracy1|226249|fgenesh2_pm.7_#_308:48-420
M-------------------------------------QLEPVQRSIVQNQSLLLSIAAD
VMCFIARSIIAHTEYCIQYRCCSSSSSSSSSQSQSQSQSQSQSTLQQS--PSTIGRKRLD
VAIVGAPNAGKSQLVNILTQSPVAAVSRKRHTT--------RSDILGARTI-----G-NT
QIVFKDTPGFM----RIENAKEERLD-------RDLIATAASEMQDVD---------FTL
LVIDSARALSENYRHAFVQLMTGAINSKGRIEESFGDDNEIDDKSSIHNNNKSSDDDANP
NSN------DGRGKFAIVLNKVDL-VKPKSTLIDLAMEIGAIADTCLEDHFTEHGK----
-----------------------TIDFEAMLEHSPIVFYVSAL----KEDGTDDLLDHLI
NLATPCKEWAVQSGQSTNMTELEQ------------------------------------
------VQEIIREKIYR--TC-HREVPHSVQQVNRMFRKIP------------------K
KGVIIHQDLVVFTKSHQKLVLGA-GGRTLERIRESAQTDLRKMFK-CEVSLHLHVK--KK
IGRRGDSGTEYKLGEASQTIL--
>P-N.multiseries_2 jgi|Psemu1|8240|jgi|Psemu1|8240|gm1.8240_g:60-428
M------------------------RKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGW
LS--------SQASSRVK-FLSSSSPSSTRRQSPPASRPQAAAT------AQNRTRKRLD
VAIVGPPNAGKSQLVNVLTKSPIAAVSRKRHTT--------RSDLLGARTV-----G-NT
QIVFKDTPGFL----RIENAKEERLD-------RDLIATAASEMQDVD---------FTL
LVLDSARTLSDNYRHALVQLMVGAINSGGRIEDCDDDDDNNDRKTT-----RQSREDINP
SSKCDTAIPSDKSKFAIVLNKVDL-VKPKTDLISLAMDVGTMADTCLLDQFQKQGR----
-----------------------EFDFDAQMEQSPIVFYVSAL----KEDGTDDLLEHLL
GLATPSREWPVEPGKATNMTTLEQ------------------------------------
------VQEVIREKIYR--ST-HKEVPHAVQQVNRLFRRIP------------------N
KGVVIHQDLVVFTKSHQKLVLGSGGGKTLKRIQESARHDLQKLFG-CDVALQLHVKYRKS
KQQRGDSGAQYNLGEVSQSVY--
>P-N.multiseries_1 jgi|Psemu1|252849|jgi|Psemu1|252849|estExt_Genewise1Plus.C_570066:60-394
M------------------------RKIAGATVKEASLVLRRYHRPALGNSSIIGGNTGW
LS--------SQASSRVK-FLSSSSPSSTRRQSPPASRPQAAAT------AQNRTRKRLD
VAIVGPPNAGKSQLVNVLTKSPIAAVSRKRHTT--------RSDLLGARTV-----G-NT
QIVFKDTPGFL----RIENAKEERLD-------RDLIATAASEMQDVD---------FTL
LVLDSARTLSDNYRHAL---------------------------------------DINP
SSKCDTAIPSDKSKFAIVLNKVDL-VKPKTDLISLAMDVGTMADTCLLDQFQKQGR----
-----------------------EFDFDAQMEQSPIVFYVSAL----KEDGTDDLLEHLL
GLATPSREWPVEPGKATNMTTLEQ------------------------------------
------VQEVIREKIYR--ST-HKEVPHAVQQVNRLFRRIP------------------N
KGVVIHQDLVVFTKSHQKLVLGSGGGKTLKRIQESARHDLQKLFG-CDVALQLHVKYRKS
KQQRGDSGAQYNLGEVSQSVY--
>P.tricornutum_1 gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|217410895|gb|EEC50824.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------RPTFIRTALVTFRWSGGPKISRSDRVRLSSTTIGST--PSLEDRKRLD
VAIVGLPNAGKSQLLNVLTQSTVAAVSRKRHTT--------RDGILGARTV-----D-DT
QLYFVDTPGFL----RQSQAKKEGLN-------RDLVVTASSEMENVD---------FSL
LVVDAARRMTDDYEETLVALMLAALRSQGRLEFDVHSAEEVQSIRTPKGG----------
---------TNPAKFAVVLNKVDL-VHPKSNLMDLAVNIGTLAEQCIKFDAKESGK----
--------------------EELFLDSAYLQESLPMFFYISAL----KQRGVQDLLEFLL
ERATPSTSWEVEAGEATPMTMKER------------------------------------
------IEEVIREKIYR--CL-HKEVPHSIRQENRVLQQGK--------------DEDGN
IVLVIHQDLIVRSKSHQELVHGG-GGRTLERIRETAARGLEKIFF-CNVVLHLHVKLPRS
KNQRWSI----------------
>T.pseudonana_1 gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335] >gi|220973246|gb|EED91577.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
M-----------------------------AFFRRALLQGSLAVNNLTHDTW--------
----------HQTPRAIT-SLLNHQQSCSLHSTPITLNNPTSSSAATTQSDKPAPQKRLD
VAIVGAPNAGKSQLLNSLIGSKVAAVSRKRHTT--------RTGILGARTF-----D-DT
QLVFIDTPGFL----HHEMSVKEGV--------RKLLGEASSEMESAD---------FVL
LVVDAARKMEDDLRRTLVTLMFLALRSKGRNE----------------------------
--------------FAVVLNKVDL-VSPKEKLLMTAADVGSMAESCIRQFLNQRRSPSKV
KFGELVDTVLKNYANEDGFDGVHDDDIELFATLAPEFFFTSAI--VKDDEGVDDVLGLLL
ERATLSDQWIVDAGSATGMTPVEQ------------------------------------
------VEEIIREKIYR--CL-HREVPHSVQQQNRMFQLYKPNESKTKSTDGSDVDEDI-
KILRIRQDLIVRTKSHQRLVLGS-GGKTLERIRSTALKDLEESFD-CIVDLDLTVRVTKS
-NQHEAILDPESVGAVSLTPLEN
>T.oceanica_1 gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M-----------------------------FGIRRLVVGGSVRHGGHARGRP--------
----------LPCPACPT-GPDISSSASSLLSRTMTSYFDGGPSAPET--SRPKQQRRLD
IAIVGAPNAGKSQLLNSLVGSKVAAVSRKRHTT--------RSGILGARTF-----G-DT
QLVFIDTPGFL----HHSKGAREGV--------RNLLSEASAEMMNAD---------FAL
LVVDAAKTIDQDLKRTLVTLMMLALRSTGREEGSRVFSDQ--------------------
---------RHLGRFSVVLNKVDL-VKPKEKLLATAAEVGSLAESCVRRLLQQHRAPVRV
KMGELVDSVLERHEDEEGFAGVHEEDYETFASVVPEFLFTSAI--DPEDEGADDLLNVLL
SRATPSTEFVMDPS-----SNLEQ------------------------------------
------VEEIIREKIYR--CL-HREVPHHVQQTNRVFKLKQ------DQPPDHDVRADMG
DLLQIHQDLIVRTKSHHRLVLGS-GGKTLQRIQTTASKDLRELFG-CEVDLLLSVKLKKT
---NQGVLLDPEEEGARITTLHD
>NODE_3217431_10 [208 - 2] (REVERSE SENSE) length_180_cov_17.744444
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------DAR----SGEGVADIIGHLG
AMATPSQHWPVPAGLATNQSMEER------------------------------------
------IQEMIREKIYR--CL-HREVPYAVDQQNRLLK----------------------
------------------------------------------------------------
-----------------------
>NODE_5633892_22 [421 - 2] (REVERSE SENSE) length_391_cov_5.074169
R-----------------------------------------------------------
------------------QSISTEINLQDARSKQALPRPDAELM------ESITTKKRLD
VAIVGLPNAGKSQLLNVLTESTVSAVSRKRHTT--------REGILGARTIFPEPGE-GI
QFVFVDTPGFL----KHDPKNPERLE-------RKLVVSATVAMRTVD---------YTL
IVVDAARNLGNE------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
