>cmToc34
MDSETP----------------------TKNEAEQRASPDRTGQVTQRPVSLFRKNGTFA
-YPLEDSDVYEEQVLALEDVPEPTAQAILRLALAAERQGVPRLRFLVVGAPGVGKSSLIN
TLLNENLCSVSAWERGT--------KNAQVCARQV-DSVVIEFIDTPGIAPCRRSGLEAS
RRQVQRLR----KLLDARGADEHPYLRSFHAILYVMRLDDTRPDLVDYHNWKVLMEFFGA
EVLRHMMVVFTHGQS-L-PPDSLSYPEYVRGRRDYVYLLIERLT------GP-LKAVRFP
VFVAENSSKCP-VIEETGERKLPDDTPWITQLYDGIRRFVFPLEADLFGMETGPEDTQVL
VYIYDKRRSRADERYPRSPLQALIRNPWFLRAVQFCGAMLLRSYMIRQEHERF--NPKPH
HPEPIIRDANNAFAVASRRANDHRLFTPSIDEDEESFFRMNGNDDFVSRLRNRPGEVDLD
ELDVERIESPDGRFVEYWYTEKDNPEMVRMYRLEIRDD----------------------
---------PNEERESRQDRIPISK-----------------DQH
>acToc34	
------------------------------------------------------------
------MSFLTREWVGIQQFPAATQTKLHEILGKLKQENVNTMTILVMGKGGVGKSSTVN
SILGERVATVSAFQSEG--------LRPIMCSRTR-AGFTLNVIDTPGIVE----GGYVN
EQALEIIK----RFLLDKTID---------VLLYVDRLDSYRVDNLDKQVVKAITDFLGK
EIWQRGVVVLTHAQL-S-PPDGLNYDDYLEKRSDALLKYVRLGA---GIKKKELQGKGIP
VALVENSGRCK-T-NEDGEKILPNGTAWIPNLVQQSQT----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>asToc34	
------------------------------------------------------------
------------------------------------------------------------
----------SAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGLIE----GGYIN
EQAVEIIK----RFLLEKTID---------VLLYVDRLDTYRMDTLDEQVIRAITTSFGK
AIWRRTLVVLTHAQL-S-PPDGLDYNDFLTRRSESLLRYIRSGA---GIGKRESADYPLP
LALVENSGRCK-T-NENGAKILPDGTPWIPNLMKEITMVVSNGSKPIH------------
------------------------------------------------VDQKLIDGPNPN
--------------------NRWKKYIPLILAVQYFF-----------------------
--------------------------VVKGIRRAIHSD----IANGK--LDDWEQRYRDL
VG------SGNPVDQKVSSSRNPRPE----------------AGQ
>osToc34	
------------------------------------------------------------
----MSAAPIPREWVGLQQFPAATQTKLHELLGKLKEENVSTLTILVMGKGGVGKSSTVN
SIVGERVATVSAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGLIE----GGYIN
EQAVEIIK----RFLLGKTID---------VLLYVDRLDAYRMDTLDDQVIRAVTNSFGK
AIWRRTLVVLTHAQL-S-PPDGLDYNDFFTKRSESLLRYIRAGA---GVSKRELGDFPLP
IALVENSGRCK-T-NENGEKVLPDGTPWIPNLMKEITTVVSNGSKSIH------------
------------------------------------------------VDQKLIDGPNPN
--------------------NRWKMFIPLILMVEYFL-----------------------
--------------------------VVKGIRRAIHAD----ISNGK--LDDWEQRYRDL
VG------SKDPVDQKGSSSGNRKA--------------------
>brToc34	
------------------------------------------------------------
----MAALQMSREWIGIQQFPPATQSKLIEILNKFKEEDVSSLTVLVMGKGGVGKSSTVN
SVIGEKAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGLIE----GGYVN
DQAVNLIK----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>hvToc34	
------------------------------------------------------------
-----MAAPIPREWVGLQQFPAATQTKLHELLGKLKEENVSTLTILVMGKGGVGKSSTVN
SIVGERVANVSAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGLIE----GGYIN
EQAVEIIK----RFLLEKTID---------VLLYVDRLDTYRMDTLDEQVIRAITSSLGK
AIWRRTLVVLTHAQL-S-PPDGIDYNDFLARRSESLVRYIRSGA---GIGKREYADFPLP
IALAEDSGKGR-T-NENG--AILDGNSW--------------------------------
-------------------------------------------------DSKLE------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>sbToc34	
------------------------------------------------------------
-----MASPIPREWAGLQQFPAATQTKLHELLGKLKEEDVSTLTILVMGKGGVGKSSTVN
SIVGERVTTVSAFQSEG--------LRPTMCSRTR-AGFTLNIIDTPGLIE----GGYIN
EQAVDIIK----RFLLGKTID---------VLLYVDRLDAYRMDTLDEQVIRAITNSFGK
DIWRRSLVVLTHAQL-S-PPDGIDYNDFFTRRSEALLRYIRSGA---GINKREYGDFPLP
IALVENSGRCK-A-NEHGEKILPDGTPWVPNLM---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>zmToc34-1
------------------------------------------------------------
-----MASPIPREWVGLQQFPPATQTELHELLGKLKEEDVSTLTILVMGKGGVGKSSTVN
SIVGERIATVSAFQSEG--------LRPMMWSRTR-AGFTLNIIDTPGLIE----GGYIN
EQAVDIIK----RFLLGKTID---------VLLYVDRLDAYRMDTLDGQVIRAITNSFGK
DIWRRSLVVLTHAQL-S-PPDGIEYNDFFTRRSEALLRYIHSGA---GIKKREYGDFPLP
IALVENSGRCK-T-NEHGEKILPDGTPWVPKLMKEITVVISNGSKPIH------------
------------------------------------------------VDQKLIDGPNPN
--------------------NRWKMFIPIILAVEYFL-----------------------
--------------------------VVKGIRRAIHAD----IANGK--VDDWEQRYRDL
VG------SRDPVEQKGSTTRNRKA--------------------
>zmToc34-2
------------------------------------------------------------
-----MASPIPREWVGLQQFPAATQTKLHELLGKLKEEDVSTLTILVMGKGGVGKSSTVN
SIVGERVASVSAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGLIE----GGYIN
EQAVDIIK----RFLLGKTID---------VLLYVDRLDAYRMDTLDEQVIRAITNSFGK
DIWRRSLVVLTHAQL-S-PPDGIDYNDFFTRRSEALLRYIHSGA---GINKREYGDFPLP
IALVENSGRCK-T-NEHGEKILPDGTLWVPNLMKEITVVISNGSSPIH------------
------------------------------------------------VDQKLIDGPNPN
--------------------NRRKLFIPLILAVEYFL-----------------------
--------------------------VVKGIRRAIHAD----IANGK--VDDWEQRYRDL
VG------SRDLVEQKGSTSRNRKA--------------------
>soToc34	
------------------------------------------------------------
-----MASPIPREWVGLQQFPAATQTKLHELLGKLKEEDVSTLTILVMGKGGVGKSSTVN
SIVGERVTTVSAFQSEG--------LRPMMCSRTR-AGFTLNIIDTPGLIE----GGYIN
EQAVDIIK----RFLLGKTID---------VLLYVDRLDAYRMDTLDEQVIRAITNSFGK
DIWRRSLVVLTHAQL-S-PPDGIDYNDFFTRRSKALLPYIRSGA---GIQPTRIWGFPPC
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------Q--------------------
>peToc34	
------------------------------------------------------------
------------------------------------------------------------
-IVGERVAIVSAFQSEA--------MRPLICSRSR-AGFTLNIIDTPGLIE----GGFVN
DHALDLIK----RFLINKTID---------ILLYVDRLDGYRVDDLDMQVTKAISKSFGQ
QIWRRGLVVLTHAQL-S-PPDELRYADFVDRRSAILQAVVRKAA---GFKKSETQ---IP
VVLVENSGRCN-T-NSGGEKVLSDGTVWLPYLVEKIVEVATNGSKPIL------------
------------------------------------------------IDKKLIEGPDAN
--------------------QWGKRWIPLFLAFQYFF-----------------------
--------------------------IVKPIRRGIQKD----IQREKSERPAWEIYDE--
--------------------------------------TGDKT-I
>ppToc34-1
------------------------------------------------------------
---M--AATPAREWTGLQQFPVATQTALHNILGTLRQQNKESLTVLVVGKGGVGKSSTVN
SIVGERVTIVSAFQSET--------LRPLQCARSR-AGFTLNIIDTPGLVE----GGCIN
DQALDIIK----RFLLSKTID---------VVLYVDRLDGYRVDNLDRQVIRGLARSFGP
NFWRLAVIVLTHAQF-S-PSDGVNYTEFVEKRSAALQAAIRQEA---GLKKDEKE---VP
YALVENSGRCN-T-NDGGEKILPNGTVWLPALVERIVEVATGTTDSVF------------
------------------------------------------------VDKKLIDGPNAN
--------------------EWGKWWIPVLAVAQYFL-----------------------
--------------------------VVMPIRKAIEKD----LAEEKNQRPQWEIRAEEF
RR-NTSLYDDDQVDEQAISQALEQDDGLSGQPSSFVDEDDDDDEF
>ppToc34-3
------------------------------------------------------------
---M--AATQAREWTGLLQFPVATQTALHNILGKLRQQKKESLTVLVVGKGGVGKSSTVN
SIIGERVTVVSAFQSET--------LRPLQCARTR-AGFTLNVIDTPGLIE----GGCIN
DQALDIIK----RFLLNKTID---------VVLYVDRLDGYRVDNLDKQVIRALARSFGP
NFWRIAIIALTHAQL-S-PPDGVDYTEFVNNRSAALRAAIRQEA---GFKKSEGE---IS
YMLVENSGRCN-T-NSEGEKVLPNGSVWLPALVDRIAEVATGATPSIH------------
------------------------------------------------VDQKLIDGPNAN
--------------------GKGKWWIPLIILAQYFL-----------------------
--------------------------IVRPIRSAIEKD----LIEEEKQRPQWQIRAEEF
VRPIASLYEDDQVDEQAIRQALKQG-ALNDQMDSFVEDDEDDDEY
>amToc34	
------------------------------------------------------------
---M--AAQLIKEWSAIQQFPAATQEKLVDLLGKLKNQDVNTLTILVMGKGGVGKSSTIN
SIIGERVVTVSAFQSET--------PRPVMVSRSR-SGFTLNVIDTPGLVE----GGYVN
DQVLETIKSFLGRFLMNKTID---------VLLYVDRLDAYRVDNLDKQIVKAITESFGK
EIWHKAVVVLTHAQL-S-PPDALSYEEFFSRRSDSLLKFVCQGA---GINKKDLKNFDIP
VALVEN------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>vvtoc34	
------------------------------------------------------------
---M--ASQLIREWTGIQQFPPVTQTKLIELLGKLKQENVSTLTILVMGKGGVGKSSTVN
SIIGERAVAVSAFQSEG--------PRPVMVSRSR-AGFTLNIIDTPGLVE----GGYVN
DQALEIIK----RFLLNKTID---------VLLYVDRLDAYRVDNLDRQVVKAITDSFGK
EIWRRGVVVLTHAQL-S-PPDGLNYEDFFSKRSEALMKVVRSGA---RLRKQDIQDSGIP
VVLVENSGRCH-K-NESDEKILPNGTAWIPNLVKTITDAVSNGSKGIL------------
------------------------------------------------VDKKLIEGPNPN
--------------------ERGKLLIPFILAFQYFF-----------------------
--------------------------IVKRIQRAIKSD----MAKER--KAPWESREANR
YE------------------------------------------P
>stToc34-2
------------------------------------------------------------
---M--ASQIIREWAGIQQFPAATQSKLLELLGKLKQENVSTLTILVMGKGGVGKSSTVN
SIIWERAVAVSAFQSET--------PRPVMVSRSR-AGFTLNIIDTPGLVE----GGYVN
DQALDLIK----KFLLNKTID---------VLLYVDRLDAYRVDNLDKQIVKAITDSFGK
EIWRRGIVVLTHAQL-S-PPDGLTYDEFTSRRSEALLKIVRMGA---RIRKQDIQAASIP
VVLVENSGRCN-K-NESDEKILPSGTAWIPNLVQTITDAVLSGSKGIL------------
------------------------------------------------VDQKLIEGPNPN
--------------------NRGKVLIPFILAFQYFF-----------------------
--------------------------VVKRIQKSIKND----IARES--RPAWA------
---------------------------------------------
>leToc34-2
------------------------------------------------------------
---M--ASQIIREWAGIQQFPAATQSKLLELLGKLKQENVSTLTILVMGKGGVGKSSTVN
SIIGERAVAVSAFQSET--------PRPVMVSRSR-AGFTLNIIDTPGLVE----GGYVN
DQALDLIK----KFLLNKTID---------VLLYVDRLDAYRVDNLDKQIVKAITDIFGK
EMWCRGIVVLTHAQL-S-PPDGLTYEEFTSRRSEALLKIVRMGA---RIRKQDIQAASIP
VVLVENSGRCN-K-NESDEKILPSGIAWIPNLVQTITDAVLSGSKGIL------------
------------------------------------------------VDQKLIEGPNPN
--------------------NRGKVLIPFILAFQYFF-----------------------
--------------------------VVKRIQRSIKND----IARET--RPSWA------
---------------------------------------------
>leToc34-1
------------------------------------------------------------
---M--ASQVIREWVGFQQFPSATQSKLIELIRKLKQESVSTVTILVMGKGGVGKSSTVN
SILGERAVAVSAFQSET--------PRPVMVSRSW-AEFTLNIIDTPGLVE----GGYVN
DQALDLIK----RFLLNKTID---------VLLYVDRLDTYRVDNLDRQIVKAITDSFGK
GIWRRGLVVLTHAQV-S-PPDGLSYDEFTSRRSEALLKIVRLGA---RMKKQEIKAASIP
LVCVENSGRCN-K-NELDEKILPNGTAWIPSILQTITEVVVSQSKGIL------------
------------------------------------------------IDQKLIEGPNPN
--------------------NKGKLLIPLIATFQYFF-----------------------
--------------------------VVKRIQTWIKND----ISREN--RPSWA------
---------------------------------------------
>stToc34-1
------------------------------------------------------------
---M--ASQVIREWVGFQQFPSATQSKLIELIRKLKQESVSTLTILVMGKGGVGKSSTVN
SILGERAVAVSAFQSET--------PRPVMVSRSW-AEFTLNIIDTPGLVE----GGYVN
DQALDLIK----RFLLNKTID---------VLLYVDRLDTYRVDNLDRQIVKAITDSFGK
EIWHRGLVVLTHAQV-S-PPDGLSYDEFTSRRSEALSKIVRLGA---RIRKQEVKASSVP
IVCVENSGRCN-K-NELDEKILPNGTAWIPNLLQTITEVVASESKGIL------------
------------------------------------------------VDQKLIEGPNPN
--------------------NKGKLLIPLIAAFQYFF-----------------------
--------------------------VVKRIQKWIKND----IARET--RPSWA------
---------------------------------------------
>lsToc34	
------------------------------------------------------------
------------------------------------------------------------
---GERAVTVSAFQSEA--------LRPTMVSRER-SGFTLNIIDTPGIVE----GGYVN
DQALEIIK----RFLLNKTID---------VLLYVDRLDAYRVDTLDGQIVKAISNSFGQ
QIWRKAIVVLTHAQL-S-PPDCLSYDEFLAKRSEALLKVVYRGA---RFRKLDIENFPIP
IGLVENSSRCN-K-NEKDEKILPNGSAWIPSIVETITEVSLTESKSIL------------
------------------------------------------------VDQKLIDGPNPN
---------------------RGKLFIPFIIAFQYFF-----------------------
--------------------------V---------------------------------
---------------------------------------------
>ptToc34-1
------------------------------------------------------------
------MGSVLREWIGFQQFPTATQSKLVELFAKLKEEGVDKLTILVMGKGGVGKSSTVN
SLFGERAVNVSSFQSEG--------FRPVMVSRNR-AGFTLNIIDTPGLVE----GGYVS
YQALDMIK----RFLLNKTIH---------VLLYVDRLDAYRVDDLDKQIIGAISDSFGK
EIWSKSLLVLTHAQL-S-PPDDLSYDVFCARRSEAVLKTIRMGA---RIRKRDFEDSAIP
VGLVENSGRCN-K-NENDEKILPNGDAWIPSLVKEIILVATNGKKLLL------------
------------------------------------------------MRSWLV-GLSQM
--------------------TGGKIFIPLILGI---------------------------
------------------------------------------------------------
---------------------------------------------
>ptToc34-3
------------------------------------------------------------
------MGSVLREWIGFQQFPTATQSKLVELFAKLKEEGVDKLTILVMGKGGVGKSSTVN
SLFGERAVNVSSFQSEG--------FRPVMVSRNR-AGFTLNIIDTPGLVE----GGYVS
YQALDMIK----RFLLNKTIH---------VLLYVDRLDAYRVDDLDKQIIGAISDSFGK
EIWSKSLLVLTHAQL-C-PPDDLSYDVFCARRSEAVLKTIRMGA---RIRKRDFEDSAIP
VGLVENSGRCN-K-NENDEKILPSGDAWIPSLVKEIILVATNGKKALV------------
------------------------------------------------VDEKLVNGSESN
--------------------DRGKIFIPLILGIQWLL-----------------------
--------------------------V-KWIQREIKKD----IAKGG--KYL--------
---------------------------------------------
>atToc33	
------------------------------------------------------------
------MGSLVREWVGFQQFPAATQEKLIEFFGKLKQKDMNSMTVLVLGKGGVGKSSTVN
SLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGLVE----AGYVN
HQALELIK----GFLVNRTID---------VLLYVDRLDVYRVDELDKQVVIAITQTFGK
EIWCKTLLVLTHAQF-S-PPDELSYETFSSKRSDSLLKTIRAGS---KMRKQEFEDSAIA
VVYAENSGRCS-K-NDKDEKALPNGEAWIPNLVKAITDVATNQRKAIH------------
------------------------------------------------VDKKMVDGSYSD
--------------------DKGKKLIPLIIGAQYL------------------------
--------------------------IVKMIQGAIRND----IKTSG--KP---------
--------------------------------------------L
>bnToc33	
------------------------------------------------------------
------MGSLVREWVGFQQFPAATQEKLIEFFAKLKQKDMNSLTVVVMGKGGVGKSSTVN
SLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGLVE----AGYVN
HQALELIK----GFLVNRTID---------VLLYVDRLDVYRVDELDKQVVQAITQTFGK
EIWCKTLLVLTHAQF-S-PPDDLSYETFSSKRSDSLLKTIRAGS---KMGKQQFEDSAIE
VVYAENSGRCS-K-NDKEEKALPNGEAWIPNLVKAITDVATNQKKAIH------------
------------------------------------------------VDKKMVDGSYSD
--------------------DKGKKLIPLIIAAQYF------------------------
--------------------------VVKMIQGAIRSD----IKTSG--KP---------
--------------------------------------------L
>ovToc33	
------------------------------------------------------------
------MGSLVREWVGFQQFPAATQEKLIGFFGKLKQKDMNSLTVLVLGKGGVGKSSTAN
SLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGLVE----AGYVN
HQALELIK----GFLVNRTID---------VFLYVDRLDVYRVDELDKQVVQAITQTFGK
EIWCKTLLVLTHAQF-S-PPDELSYETFSSKRSDSLFKTIRAGS---KMRKQQFEDSAIE
VVYAENSGRCS-K-NEKEEKALPNGEAWIPSLVKAITYVATNQRKAIH------------
------------------------------------------------VDKKMVDGSYSD
--------------------DRGKKLIPLIIGAQWF------------------------
--------------------------IVKMIQGAIRND----IKTSG--KP---------
--------------------------------------------L
>thToc33	
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---LDLIK----GFLVNRTID---------VLLYVDRLDVYRVDELDKQVVQAITQTFGK
EIWCKTLLVLTHAQF-S-PPDELSYETFSSKRSDSLLTTIRAGA---KMRKQQFEDSAIA
VVYAENSGRCS-K-NEKEEKALPNGEAWIPNLVKSITDVATNQKKAIH------------
------------------------------------------------VDNKMVDGSQSD
--------------------DKGKKLIPLIIGAQYF------------------------
--------------------------IVKMIQGAIRND----IKISG--KP---------
--------------------------------------------V
>ovToc33like
------------------------------------------------------------
------MGSLVREWVGFQQFPAATQEKLIGFFGKLKQKDMNSLTVLVLGKGGVGKSSTAN
SLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGLVE----AGYVN
HQALELIK----GFLVNRTID---------VLLYVDRLDVYRVDELDRQVVQAITQTFGK
EIWCKTLLVLTHAQF-S-PPDELSYGTFSSKRSDSFLKTIRTGS---KMRKQQFEDSAIE
VVYAENSGRCS-K-NEKEEKALPNGEAWIPGLVKAITDVATNQRKAIH------------
------------------------------------------------VDKKMVDGSYSD
--------------------DRGKKLIPLIMAAQYF------------------------
--------------------------IVEMIQGAIRND----IKTSG--KP---------
--------------------------------------------L
>rrToc33	
------------------------------------------------------------
------MGSLVREWVGFQQFPAATQEKLIEFFSKLKQKDMNSLTVVVMGKGGVGKSSTVN
SLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPDLVE----AGYVN
HQALELIK----GFLVNRTID---------VFLYVDRLDVYRVDELDKQVVQAITQTFGK
EIWCKTLLVLTHAQF-S-PPDDLSYETFSSKRSDSLLKTIRAGS---KMRKQQFEDSAIE
VVYAENSGRCS-K-NDKDEKALPNGEAWIPNLVKAITDVATIQKKAIH------------
------------------------------------------------V-----------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>boToc33	
------------------------------------------------------------
------MGSIVREWVGFQQFPAATQEKLIEFFAKLKQKDMNSLTVVVMGKGGVGKSSTVN
SLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGLVE----AGYVN
HQALELIK----GFLVNRTID---------VLLYVDRLDVYRVDELDKQVVQAITQTFGK
EIWCKTLLVLTHAQF-S-PPDDLSYETFSSKRSDSLLKTIRAGS---KMGKQQFEDSAIE
VVYAENSGRCS-K-NDK-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>brToc33	
------------------------------------------------------------
------MGSLVREWVGFQQFPAATQEKLIEFFTKLKQKDMNSLTLVVMGKGGVGKSSTVN
SLIGEQVVRVSPFQAEG--------LRPVMVSRTM-GGFTINIIDTPGLVE----AGYVN
HQALELIK----GFLVNRTID---------VLLYVDRLDVYRVDELDKQVVQAITQTFGK
EIWCKTLLVLTHAQF-S-PPDDLSYETFSSKRSDSLLRTIRAGS---KMGETTV------
--GFCNGCVCG-E-TVED------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>grToc34	
------------------------------------------------------------
-----MGTPLPREWLGLQQFPAATQTKLFELLGKLKQENVNTLTIVVMGKGGVGKSSTIN
SLIGEQVVRVTAFQSEG--------LRPVMVSRSW-AGFTLNVIDTPGLVE----AGYVN
HQALELIK----GFLLNKTID---------VLLYVDRLDVYRVDNLDKQIIRAITNSFGK
EIWRKSLLVLTHAQL-C-PPDGLNYDVFSSKRSEGVLKAIRMGA---RIRKMDLEDSVIP
VVLVENTGRCN-K-NDIDEKILPNGEAWVPNFGKS-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------H
>atToc34	
------------------------------------------------------------
----MAALQTLREWIGIQQFPPATQSKLLEILGKYKEEDVSSLTVLVMGKGGVGKSSTVN
SVIGEKAAAVSTFQSEG--------LRPTLVSRTR-SGFTLNIIDTPGLIE----GGYVN
DQAINIIK----RFLLNMTID---------VLLYVDRLDVYRVDDLDRQVVGAITDAFGK
EIWKKSALVLTHAQF-S-PPDGLNYNHFVSKRSNALLKVIQTGA---QLKKQDLQGFSIP
VILVENSGRCH-K-NESDEKILPCGTSWIPNLFNKITEISFNGNKAIH------------
------------------------------------------------VDKKLVEGPNPN
--------------------ERGKKLIPLMFAFQYLL-----------------------
--------------------------VMKPLVRAIKSD----VSRES--KLAWELRDSGL
AS------RR----------------------------------S
>tsToc34	
------------------------------------------------------------
---------------------------------PTRPEDVSSLTVLVRGKGGVGKSSTVN
SVIGEKAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGLIE----GGYVN
DGAVNLIK----GFLLNKTID---------VLLYVDRLDVYRVDDLDRQVVTAITDAFGK
EIWKKSALVLSHAQF-S-PPDGL-YDLFVSRRSDS--SVICAGA---QLKKQDLQGSSIP
VILVENSGRC--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>rrToc34	
------------------------------------------------------------
----MAALQMSREWIGIQQFPPATQSKLLEILGKFEEEDVSSLTVLVMGKGGVGKSSTVN
SVIGERAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGLIE----GGYVN
DQAVNLIK----GFLPNKTID---------VLLYVDRLDVYRVDDLDKQVVTAITDAFGK
EIWKKSALVLSHAQF-S-PPDGLNYDLFVSRRSDALLKLIYASA---QLK----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>bnToc34	
------------------------------------------------------------
----MAALQMSREWIGIQQFPPATQSKLLEILGKFKEEDVSSLTVLVMGKGGVGKSSTVN
SVIGEKAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGLIE----GGYVN
DQAVNLIK----RFLLNMTID---------VLLYVDRLDVYRVDDLDKQVVTAITDAFGK
EIWKKSALVLSHAQF-S-PPDGLNYDLFVSRRSDALLKLI--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>boToc34	
------------------------------------------------------------
----MAALQVSREWIGIQQFPPATQSKLLEILGKFKEEDVSSLTVLVMGKGGVGKSSTVN
SVIGEKAAAVSTFQSEG--------LRPSLVSRSR-SGFTLNIIDTPGLIE----GGYVN
GQAVNLIK----RFLLNMTID---------VLLYVDRLDVYRVDDLDKQVVTAITDAFGK
EIWKKSALVLSHAQF-S-PRDG--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>laToc34	
------------------------------------------------------------
---M--TSPITREWAGFNTFPPETQTKLLELLGRLKEKNVNKLTILVMGKCGVGKSSTVN
SIIGERAVVINPFQSEG--------LRPVMVSRSR-TEFTLNIIDTPGIIE----GGCIN
NQALELIK----HFLLNKTID---------ILLYVDRLDTYRVDELDKMVVRAITNSFGK
EIWNRALIVLTHAQL-S-PPDGLPYDEFVSKRSEALLKVVHQGA---RLKKGDLAS-SIP
SV-----SRCN-K-NDSGEKG-PNGTA---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>mtToc34-1
------------------------------------------------------------
---MASQQQQVREWSGINTFAPATQTKLLELLGKLKQEDVNSLTILVMGKGGVGKSSTVN
SIIGERVVAISPFQSEG--------PRPVMVSRAR-AGFTLNIIDTPGLIE----GGYIN
DMALDIIK----RFLLDKTID---------VLLYVDRLDAYRVDNLDKLVAKAITDSFGK
GIWNKAIVALTHAQF-S-PPDALAYDEFFSKRSESLLQIIKSGA---SLKKDDAQASAIP
VVLIENSGRCN-K-NETDEKVLPNGIAWIPHLVHTITEIALNKSESIF------------
------------------------------------------------VDKNLIEGPNPN
--------------------QRGKLWIPVLFALEFLL-----------------------
--------------------------IMKPIEGLIKND----VANEK--KPSWETRDVGV
KK------ETREVGQKDMRKERRGGA----------------VRR
>psToc34	
------------------------------------------------------------
---MASQQQTVREWSGINTFAPATQTKLLELLGNLKQEDVNSLTILVMGKGGVGKSSTVN
SIIGERVVSISPFQSEG--------PRPVMVSRSR-AGFTLNIIDTPGLIE----GGYIN
DMALNIIK----SFLLDKTID---------VLLYVDRLDAYRVDNLDKLVAKAITDSFGK
GIWNKAIVALTHAQF-S-PPDGLPYDEFFSKRSEALLQVVRSGA---SLKK-DAQASDIP
VVLIENSGRCN-K-NDSDEKVLPNGIAWIPHLVQTITEVALNKSESIF------------
------------------------------------------------VDKNLIDGPNPN
--------------------QRGKLWIPLIFALQYLF-----------------------
--------------------------LAKPIEALIRRD----IATET--KPAWETRDVGD
R-------------------------------------------K
>pcToc34	
------------------------------------------------------------
---M--ASQIIREWSGINTFAPATQTKLLELLGKLKQENVNSLTILVMGKGGVGKSSTVN
SIIGERVVSISPLQSEG--------PRPVMVSRSR-AGFTLNIIDTPGLIE----GGYIN
DMALDIIK----RFLLNKTID---------VLLYVDRLDVYRVDNLDKLVAKAITDSFGK
GIWNKAIVALTHAQF-S-PPDGLPYEDFFSQRSEALLRVLRSGA---KIKKEVFQAASMP
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>ptToc34-2
------------------------------------------------------------
---------------------------------------GNKMTILVMGKGGVGKSSTVN
SLLGERVVNVSSFQSEG--------LRPVMVSRDR-AGFTLNIIDTPGLVE----GGYVN
YQSLELIK----RFLLNKTIN---------VLLYVDRLDAYRVDDLDKQIISAITDSFGK
EIWNKSLLVLTHAQL-C-PPDDLSYDVFCGRRSEAVLKTIRMGA---QI-KRDFEDSAIP
-GLVENSGGCN-K-SENDEKILPNGDAWIPTLVK-IVGVATNGKKSLL------------
------------------------------------------------DQ----------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>crToc34
MAQPPRPAEEYDDDVQEDEDE-LKEGELDDDESHEAASEGGEAAAGD-------EEAEDD
EQDEEDGDEDSQPWAGLNRLP--ERDDMLDILNELRAEGRKQLTVLLLGKSSVGKSSLIN
SLLGEAVVRVQAFKLQADTDITTTVVRQVAVGNSEVDGFRLKLIDTCGLEDP-EAGDTVN
LGALSKIA----EDVRGVGID---------VVLYCDRLDLYRVDPLDKAIIDAISSTFGR
GIWRRTVVALTHANLVQ-TPPGTDYDSFVNGRVRLIRGAVRGPL------FF---RPSLP
VALVENSETCPVS-SESGFRVLPDGEPWLVALVSQLVDMAAARRRPYK------------
------------------------------------------------YHPRL--SSKPS
--------------------HRFRWLLPVAIAAEVL------------------------
--------------------------FYRRFLHPRLDDNQRRVEREE--ERVWALRGQQR
--RALGLHRPHRPDKDAAWRLEQMY-----------------DDD
>olToc34
---------MSEEEYSEDEDYVSSEGEG-----VEGTEEGGEGQPAQ-------------
---AAAPVLGPKEWVGLSSMPAATQSALLETLGKLRERNVNEMTVIFIGKQGVGKSSTVN
TLLNERVAPSSPFQPEN--------VRPLLAGRVA-AGFTLNVLDTPGLLE----GDSVS
ARGLMALR----AALNGRKVD---------AFVFTDRLDTWRVDNADKAIFTSLAENFGA
ELWERTVLGFSHAQT-T-PTDGRPYEEFVNARVEQYRKAIRSTL------N--MPNLALP
FALIENGSRCK-T-NGNGEKVV-NDRPWLSDMVSTMVEMACSKDGYEY------------
------------------------------------------------DHGKAGKKLDPN
--------------------NKHKIWILPLFLFQAFV-----------------------
--------------------------LRPLVIGQIRRD----IKKAD-------------
--------------EKKQRAAAA--------------------KH
>otToc34
---------MSDEEYSEDE-YVSSEGEG-----AEGRDV--EPQ-AQ-------------
---QAAPVLGPKEWVGLSSMPAATQQALLETLGKLRERNVNEMTVIFIGKQGVGKSSTVN
TLLNERVAPSSPFQPEN--------ARPLLAGRVA-AGFTLNVLDTPGLLD----GDSIS
ARGLMALR----AALNGRKVD---------AFIFTDRLDTWRVDNSDRAIFTALAENFGA
ELWERTVLGFSHAQT-T-PPDGKPYEEFVNARVEQYRKAIRQTL------G--MPNLTLP
FALIENGSRCK-A-NAAGEKVV-NERPWLTDMVGTMVEMACAKESYEY------------
------------------------------------------------DHKKAGKKLDPN
--------------------NKYKIWMLPLFLFQAFV-----------------------
--------------------------LRPLMIGQIRRD----IRKSD-------------
--------------EDKKKKSARPA-----------------PKK
>ppToc34-2
------------------------------------------------------------
-----MATVSEKEWTGFQGLPAATQIILHTLLAKLRKQKVDKITIVLLGKGGVGKSSIVN
SLFSERVAAVSAFRSET--------LRPRQYSRSK-DGFKLTVIDTPGFVE----AGRV-
DAALNSIR----RYLLGKTIN---------VVLYVDRLDGPREDKVDVKISRAISQAFGP
QIWPHVIVVFTHAEI-H-LED-VTYSEFVSRRSAALRNIILKES------RFKTVNTKVP
FVLVENCSRCS-E-NGEHEKILPDGTVWLPVLFEALVDLVLGSKKPIL------------
------------------------------------------------IDEKMIGIPKGN
--------------------PLGSIWMPLVLLAQFVL-----------------------
--------------------------IWRPIRKAIDRD----LVEEA--QRHS-------
--------------------------------------------P
>pwToc34
------------------------------------------------------------
-------VLALAECSGDRQRTGASRCCCWE-------------------REAWARVATVN
SLLGERAAVVSSFQATG--------LGVHMHTRTLPGGFALNLIDTPSLLD----QDSVS
TSRLEQIG----SAIKGVKID---------AVLFLDRLDVYSTDTLDEQVVDGVTAYFGE
DMWDHAVLGLTRATS-SAPPLSTDFGEWVVERSLQLQSLIAKARAQYAPRRRRGEAPPLT
PAGCRESQECP-------------------------------------------------
-------------------------------------------------RKLRGSGSSP-
---------------------ATAPGSPTCMPRWRSAATGAGQA----------------
-----------------------------WLHDAARR-----------------------
---------------------------------------------
