>gi|295792212|gb|ADG29121.1| plastid Omp85-like protein [Phaeodactylum tricornutum]
---------------------------------MKTSSLVPLLLFALIVPECQAFLPPSN
SPRGRIGGLFSQPFTDGRNSGDNGVPPS------DDIGHLQAWDGFEGPTLLASIIRKND
TDAPSG-------------------LRGGGDVVKGTQATLS-STSSYWAKAFQSFRGAVV
KPLIEAKKKVANSF----KSKEVKKEEELLNQLKNMPIQRV-VVPNSTVLPNEVIQLAAN
RAGVVGHPLQSTSIQSFAKSLKEWYIRKGYILHSVTGATLQSE------T-----GTAII
TVQEPAV-------SKDPVGITFCKEMVVD----EETGNLLTFRQYKDKHQNR-------
----RTLGFDKITKADLNTTFVPTAGHTRPNRIASALGLSPGNPFQWDGIRWQQIAS---
---------SGIFAQVLRATPQPMQDG---TVQLHILATE-APTRHLEYGLGKSLYTGSW
EGELDFEHINLLGGGESLGLSVRRGTK-----------------------DAEPSIRLSF
TDSKFGLGGGYDLEVFSDFIGDQPEE-------------------MQEGELP--------
-----PDY--------DHDSILDRKGATVRLRNPISSR---IVRNSVASGSLERTA-T--
--KTGLHETIGSTTLAVGP------FVKRLPYDARSSIDAKCSLGTRLFAATSTAEE---
--ANALLPPLKLKPYTSATATTRQIFPL--LASFGPGGRPLILALKHSITTATPNLPRHE
AKAQGIAHNIRGSSLNGR----------------------------------------VA
SALTGTTELRVPIDIPVV------------QIRQDTNVVFFGDWLFAAKDSQSSFR----
-----RKSCVGVGVRKSVQGIPLKYDLCYSSDDGK-------------------------
--FQSA-------------------------FGLGA------------------------
------------------------------------------------------------
-DFDF-------------------------------------------------------
------------------------------------------------------------
-----------
>gi|219121419|ref|XP_002185934.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1] >gi|209582783|gb|ACI65404.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
---------------------------------MKTSSLVPLLLLALIVPECQAFLPPSN
SPRGRIGGLFSQPFTDGRNSGDNGVPPS------DDIGHLQAWDGFEGPTLLASIIRKND
TDAPSG-------------------LRGGGDVVKGTQATLS-ST----------------
-----AKKKVANSF----KSKEVKKEEELLHQLKNMPIQRV-VVPNSTVLPNEVIQLAAN
RAGVVGHPLQSTSIQSFAKSLKEWYIRKGYILHSVTGATLQSE------T-----GTAII
TVQEPAV-------SKDPVGITFCKEMVVD----EETGNLLTFRQYKDKHQNR-------
----RTLGFDKITKADLNTTFVPTAGHTRPNRIASALGLSPGNPFQWDGIRWQQIAS---
---------SGIFAQVLRATPQPMQDG---TVQLHILATE-APTRHLEYGLGKSLYTGSW
EGELDFEHINLLGGGESLGLSVRRGTK-----------------------DAEPSIRLSF
TDSKFGLGGGYDLEVFSDFIGDQPEE-------------------MQEGELP--------
-----PDY--------DHDSILDRKGATVRLRNPICSR---IVRNSVASGSLERTA-T--
--KTGLHETIGSTTLAVGP------FVKRLPYDARSSIDAKCSLGTRLFAASSTTEE---
--ANALLPPLKLKPYTSATATTRQIFPL--LASFGPGGRPLILALKHSITTATPNLPRHE
AKAQGIAHNIRGSSLNGR----------------------------------------VA
SALTGTTELRVPIDIPVV------------QIRQDTNVVFFGDWLFAAKDSQSSFR----
-----RKSCVGVGVRKSVQGIPLKYDLCYSSDDGK-------------------------
--FQSA-------------------------FGLGA------------------------
------------------------------------------------------------
-DFDF-------------------------------------------------------
------------------------------------------------------------
-----------
>a12s_contig_89707_23 [3 - 1100] No definition line found
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------IEYGLGTSRYTGSW
EGELDFEHGNLFGGGESFGVSVRRGAK-----------------------DVDPSVRVRF
SNDNFGLDGGYEIEAFSDFLAKEKQKKPKLSAEKNEDETEVNSALMAQGAASLATTDPDF
IEVTDPDY--------DKDMLVDRKGATFRLRNPFDES---VVSASAASCSFERTS-T--
--HTGLHENIGSCTLSLGP------FPRKLPLGARSNIDCKITTGTRI--QTKSQFN---
--ADELFDRFQLSPYATASATTRQTFPL--LPTRTADKRPVILALRHSLTTSTPTIPRHE
ATAQGIANTIRDSTENGR----------------------------------------VA
TALRGTTELRIPVDVPKI------------QTLQDGKIVLFGDWLFATPDYQSPIF----
-----KKSSVGVGLRKSVQGIPVRYDLCYTW-EGK-------------------------
--VRGS-------------------------VSLGR------------------------
------------------------------------------------------------
-DFEA-------------------------------------------------------
------------------------------------------------------------
-----------
>jgi|Fracy1|184808|jgi|Fracy1|184808|e_gw1.5.48.1:126-688
-----------------------------------------MCVKWSDQGGVTAYVSTPT
-----RYSSWSNPDRSGRNNGNLLNSTGFKDDIYDDIFCLEEDDTNGVGSSFAAVRRGGS
SYKQN--------------KSKNRIIDGGKNVISKASSFWS--------STVGG------
-----TITSVKSLF----QSKKSKKEQELLEQLQTMPVRRV-VLTNSTILPPDIVRTAVK
RAGLIGGPLRMDRVQELARTLKRWYVREGYVLNSVTGASLDPE------T-----ATASI
TVEEPVV-------SRLPVDIVFCKEMIID----DDTGELMTFKKYREKKQKELDDKSGG
LGRFQRLQEVKIDRKDLNTTFITTTGRTKATKIAQAMNLNPGQPFQYFDDRWNKIAS---
---------SGIFSKVLKKSPESASDG---GVCLQVFATE-PPPRHLEYGIGKSVWTNSW
EGEVDFDWRNVFGGGESAGVMVRRGTK-----------------------DPAPSVRLRF
GDDKFGLEGGYDVEAFTDFLGDTGKD-------------------TKEDNEN--------
-----DDDGPSSTLELDKDSLLSRRGATFRLRNPISPT---IITNSVASASLERTS-T--
--TTGQLENIGSATLTLGP------FRRLLPMEARSSISTTITGGTRL--QGKGDDDITV
LGSFTGASIGQLLPYTMASATTRQILPL-SLSSRDDGTSPITLALQHTASMSTPNLPRHE
AKAMGNSAQIRGASADCM----------------------------------------AS
STVKGTTEIRIPVAAPRV---------------GSGTVVLFGDWFCVQKDMNSPFH----
-----SKSSIGIGIRKSIQGLPLKYDLSYSS-EGK-------------------------
--FKPM-------------------------FGMGM------------------------
------------------------------------------------------------
-DFDV-------------------------------------------------------
------------------------------------------------------------
-----------
>jgi|Psemu1|64008|jgi|Psemu1|64008|estExt_Genemark1.C_470022:113-685
--------------------------------MLPAFLFITMCMKWGSQGGGGDAVPPHS
VPTLVTYSSWSHQDEFDENFA--LNNTGSDSQDFEDFLCTKDTPV----ESLLALRRGGS
SSK----------------SQNNGVIQGGKAVVMRSVSFWK--------STVGN------
-----AVESVKSKF----QSKESQKRQELMEALKVMPVRQV-VVPNSTVLPAEVIRTAVK
RSGMIGSPLKMDRVQELSRNLKRWYMRQGYILHSVTGASLNTD------T-----ATASI
SVEEPFV-------SALPVDIVVVKEMVID----DETGELITFKQYRSKKLSELEKKPGG
FGAFGRMPNLNIDRKDLNTTLVPTTGRTDAKKIAQAMKLRPGTPFKWMDTRWSKITS---
---------SGVFSKILKASPQPTTDG---GVCLQVYAME-PPPRHLEYGIGKSIWTNSW
EGEVDFDWRNIFGGGESVGVMVRRGTK-----------------------DSSPSVRVRY
GDDKFGLEGGYDIEAFSDFLGDTGSD-------------------KEEEKES--------
-----DDLSDSGS---DQDSLLSRRGATFRLRNPVSPS---FVTNSVASASLERTS-T--
--TTGQLENIGSASLTLGP------FRRFMPMDGKTSVSTTISGGARL--AGADTDE---
GGSISLAGTG-LLPYSSASATTKQVLP---ISSREKDKVPITLALQHTVSASTPNLPRHE
AKAMANSAQIRGASADNS----------------------------------------AT
TVVKGTTELRFPVAAPRI---------------GSGSVVLFGDWFCVQKDMNSPFY----
-----SKSSIGLGLRKNVQGLPLKYDVCYSS-EGK-------------------------
--IKTM-------------------------FGMGA------------------------
------------------------------------------------------------
-DFDV-------------------------------------------------------
------------------------------------------------------------
-----------
>jgi|Psemu1|318101|jgi|Psemu1|318101|estExt_fgenesh1_pm.C_470006:89-661
-----------------------------------------MCMKWGSQGGGGDAVPPHS
VPTLVTYSSWSHQDEFDENFA--LNNTGSDSQDFEDFL-------------------GGS
SSK----------------SQNNGVIQGGKAVVMRSVSFWK--------STVGN------
-----AVESVKSKF----QSKESQKRQELMEALKVMPVRQV-VVPNSTVLPAEVIRTAVK
RSGMIGSPLKMDRVQELSRNLKRWYMRQGYILHSVTGASLNTD------T-----ATASI
SVEEPFV-------SALPVDIVVVKEMVID----DETGELITFKQYRSKKLSELEKKPGG
FGAFGRMPNLNIDRKDLNTTLVPTTGRTDAKKIAQAMKLRPGTPFKWMDTRWSKITS---
---------SGVFSKILKASPQPTTDG---GVCLQVYAME-PPPRHLEYGIGKSIWTNSW
EGEVDFDWRNIFGGGESVGVMVRRGTK-----------------------DSSPSVRVRY
GDDKFGLEGGYDIEAFSDFLGDTGSD-------------------KEEEKES--------
-----DDLSDSGS---DQDSLLSRRGATFRLRNPVSPS---FVTNSVASASLERTS-T--
--TTGQLENIGSASLTLGP------FRRFMPMDGKTSVSTTISGGARL--AGADTDE---
GGSISLAGTG-LLPYSSASATTKQVLP---ISSREKDKVPITLALQHTVSASTPNLPRHE
AKAMANSAQIRGASADNS----------------------------------------AT
TVVKGTTELRFPVAAPRI---------------GSGSVVLFGDWFCVQKDMNSPFY----
-----SKSSIGLGLRKNVQGLPLKYDVCYSS-EGK-------------------------
--IKTM-------------------------FGMGA------------------------
------------------------------------------------------------
-DFDV-------------------------------------------------------
------------------------------------------------------------
-----------
>NODE_536174_6 [2 - 301] length_273_cov_29.391941
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------DGSRWRSVSN---
---------SGIFSRILKASPQPMEDG---TVQMLIVAQE-APARHIEYGLGTSRYTGSW
EGELDFEHGNLFGGGESFGVSVRRGAK-----------------------DVDPSVRVRF
SNDNFG------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>a12s_contig_40332_88 [1139 - 3] (REVERSE SENSE) No definition line found
SRPKCSSHRHTDRSLSMSIALYKHLSTMIYWMLLLSTYLLVSCRWADGFCVRGGSSFPPT
RPPSCRNLFDGSYD--------------------------------EDPVHECDIAAFSR
LDEPLDGEGVEKVKGVSRGGSTKKVPPPPDKLLSTTTTFWS--------RTFGKVGSTVT
APFRAGSKAVSNMF----RSKEKMMEEKLMEQLSTMPIEQISVVPSTTVLPSHVVEVAAR
RSGMLGSPLKPETVQEFARALKRWYTRNGYVLHAMTGATLKPE------T-----ATAEI
QLQEPVV-------NHKPVDIVFCKELIID----QETGALLTKRQYQDKQQNQR------
----RPGFRQKLSLEGANTTLVETNGRTRPGKIASALKLEPGKPFRWDGSRWRSVSN---
---------SGIFSRILKASPQPMEDG---TVQMLIVAQE-APARHIEYGL---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>NODE_5213026_4 [2 - 175] length_146_cov_29.630136
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------PVDIVFCKELIID----QETGALLTKRQYQDKQQNQR------
----RPGFRQKLSLEGANTTLVETNGRTR-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>NODE_4084741_12 [256 - 2] (REVERSE SENSE) length_227_cov_15.101321
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------LMEQLSTMPIEQISVVPSTTVLPSHVVEVAAR
RSGMLGSPLKPETVQEFARALKRWYTRNGYVLHAMTGATLKPE------T-----ATAEI
QLQE--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
>Surirella_toc75_Consensus100
SRPKCSSHRHTDRSLSMSIALYKHLSTMIYWMLLLSTYLLVSCRWADGFCVRGGSSFPPT
RPPSCRNLFDGSYD--------------------------------EDPVHECDIAAFSR
LDEPLDGEGVEKVKGVSRGGSTKKVPPPPDKLLSTTTTFWS--------RTFGKVGSTVT
APFRAGSKAVSNMF----RSKEKMMEEKLMEQLSTMPIEQISVVPSTTVLPSHVVEVAAR
RSGMLGSPLKPETVQEFARALKRWYTRNGYVLHAMTGATLKPE------T-----ATAEI
QLQEPVV-------NHKPVDIVFCKELIID----QETGALLTKRQYQDKQQNQR------
----RPGFRQKLSLEGANTTLVETNGRTRPGKIASALKLEPGKPFRWDGSRWRSVSN---
---------SGIFSRILKASPQPMEDG---TVQMLIVAQE-APARHIEYGLGTSRYTGSW
EGELDFEHGNLFGGGESFGVSVRRGAK-----------------------DVDPSVRVRF
SNDNFGLDGGYEIEAFSDFLAKEKQKKPKLSAEKNEDETEVNSALMAQGAASLATTDPDF
IEVTDPDY--------DKDMLVDRKGATFRLRNPFDES---VVSASAASCSFERTS-T--
--HTGLHENIGSCTLSLGP------FPRKLPLGARSNIDCKITTGTRI--QTKSQFN---
--ADELFDRFQLSPYATASATTRQTFPL--LPTRTADKRPVILALRHSLTTSTPTIPRHE
ATAQGIANTIRDSTENGR----------------------------------------VA
TALRGTTELRIPVDVPKI------------QTLQDGKIVLFGDWLFATPDYQSPIF----
-----KKSSVGVGLRKSVQGIPVRYDLCYTW-EGK-------------------------
--VRGS-------------------------VSLGR------------------------
------------------------------------------------------------
-DFEA-------------------------------------------------------
------------------------------------------------------------
-----------
>gi|295792214|gb|ADG29122.1| plastid Omp85-like protein [Thalassiosira pseudonana]
------MITFQTTRRKYPLLGGLACCLCLRAFVHISGDTSHPSIFANQHIGCDAFSLPPS
RLRHTRGVYRGGAFGRSGNAGGGNNGGRRPTLHFNHFYDDDSDSNGGVDMNVLQLLWMST
SSDNESNY----ISEHYTSSAACVNLRGGGGV---KETGNN-------------------
-PLQKLGSAVSRHIPFQQNKKEQSNLQEQEKLLSITHVTSV-CAPSSDLLPLEVITQSSK
QANLIGGTLTPETMERTASLINQWYWNQGYVMNSVTGATLVPGKANEG-G-----GKVEL
KVREVKLAKSRS-----SVDIRFVDRC--DNANTEAGVEIITLPAQTNDHQVQNSDSFPQ
YQK-----------------YKLTSGRTRPLKVARMVQLSPGSQFRILPERWSRLVALPG
GTFGGGGGKSAIFSAIHAVQPVPTKDGK-DTVNIEILASENKPYVSMEYGVTKSLYSDQW
EGELDLKHGNTFGGGEVATLNSFNDEKLGRSIDGGTFELEDEYQ------------RYAF
G----GGDSGYDVQIFRDHLGVSGMMNDVKDEQV--------------------------
----------------HEEDCPQRTGASIRLRLPKQ-----TLP-HAVSASFERINQSIS
APTASRTQSMASATMKIGPCRCGESFLKRSFHNVRSALSASITAGARWDAASTSS-----
---ETATVDTKTRPYATGTITSQHIIPLVSYPFGNRDNGTVNFAMRHVLSAASMHLPRHE
AIILGLASRVRGYKYNYQSHSLQPQKIVAKQVQRS------WKFLQGSSDGQTRPPIAVS
KAISGTMEIRVPLHPLSKRDESNLGTEGSLSSILSGDMVLFGDWSISQAQTQSSSHQDQY
DTSLLRHSSIGIGFRKRVQGIPLKMDACITE-HGA-------------------------
--RGVF-------------------------FGIGQ------------------------
------------------------------------------------------------
-DFGV-------------------------------------------------------
------------------------------------------------------------
-----------
>Sm_a12_contig_6799_275 [4537 - 2108] (REVERSE SENSE) No definition line found
------HLTKKIFIKSTSTHHDTMKQVRPRRPRPSVAGATFFLVVAYAASSCSALSVPPR
NPPRSFRNA-----GRGSDLGGGGKSPPPPWNRLNCHDSGDESNDNPSNFNLASIWILSL
SSDEDGEHILDIIDDQSTQDTTVLRTRGGDAAVKQKTTSSNKNIADSINDTLDSIQNIML
RPFQIVGQRIPSSL-LSKKKGDTSPAKDQEQVLRSTKIISV-SAPESALLPPDIITQSAT
DAELVGGTLNPEALELTATAINRWYADNGYVLNSVTGATLIPSATNDDNDANNTEGRVEL
KVKEVKLAKSSQ--NSFPVKLRLVQRVDSD-SDTNDQNSLITLPSQSGETSTL-------
--------------------FKSISGCTRPKKIARMTKLEPGRHLRILPDRWSRLVAFPG
GMFGAGGGRSAIFSNIHAVRPIPEESPQGNAVSVEIIASENKPYAALEYGVTKSLYSDKW
EGEFDLKHTNAFGGGEVATINVRKGQSNGRK-NGRNADRDDNNKWAQRLNDGPLSWRMSV
KDSY----AGYDLNLFHENVGAGGRRKKHQNTS---------------------------
-----NKEAEGGEHSGESGGNPMRVGGTMRLRLPSSMKR--KFKANAVSATFERIN----
------AQSIASASVGVGP------YQFNPFRSLYSSISASMTSGVTDGSAGAVT-----
--------------YAAGALTSHQSMPF--------KSSPVTLNVRHIASGGTKNLPRHE
AVSLGLSSKVRGYKYNYQGQKIDTSSIEEEEQQEHGTWQALRKLCSGGKGANVNPQIAIS
KALSGTVELRVPFQASSERGS---------QPILSGTFLLFGDWSLTQARTQSIATEEEN
RPA--RYSSAGVGLRKVVQGIPLKVDACVTE-HGS-------------------------
--KGIF-------------------------FGIGG------------------------
------------------------------------------------------------
HDF---------------------------------------------------------
------------------------------------------------------------
-----------
>gi|397569871|gb|EJK47026.1| hypothetical protein THAOC_34280 [Thalassiosira oceanica]
---------------------------MRMKAVTTAVIGVAILWETSQHKRCHALAPPSR
RLFGE---------SSFSDEGGGGPNNGAVALLLNFGSCSSSDDDEGVGYEESSL-----
-------------------TRHRLDLRGGRSA--RAATMSN-------------------
--LSTQLPSIIRNR-FSKQSKDRDTAKRQEELLSSTKVKSV-SAPGSA-IPQAFITQCAE
ECGLIGGTLTPEKLEHASSVINRWYLRNGFALNCVIGATLVPSEAEGSDD-----GTVVL
KVREVKLAKSSTKPNYTPLKLTFIDKVQGDDGGSSSLEDLLSIQEEDGSESV--------
--------------------YARSQGRTSPNKLARMLRMDPGSPLQLNPTLISELAAFPK
DK----RTQPALFSKIHAVRPVPTSKT--DEVEVEMVVSENKPYTSFEYGITKSLYTNEW
EGELNAKNTNAFGGGEVVTVNICKGRSNLGG---------DGEQNMRGLMNGQSTWRISL
RDDYLGDDSGYELDLFQGNIDEGLSCR---------------------------------
---------------------PIRTGSSMKVKVPRSLGERLMLPVRTISSRFEHIQET--
--DQRGAQCIASVDTELGQ-------FESAWGSVRSSTSVVAKLGGKMDIGMEES-----
----------RLEPYASCCAVNEQSTHL-------GKSRGMHLSLRNVVSTSSRHIPSHE
AYHIGLSSRVRGYGYNAKRNR--------NHSRPKNPVAMLRNTLEACQGELIHPPRSLS
SAVSGSLELRVPFDCLSQAAA---------RIIGDGSIVVFGDWCFASPTNTNAS-----
-----RYSSVGVGARKSLIGIPLKIDACLTE-HGT-------------------------
--KGVF-------------------------FGLGQ------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------
