>T.oceanica_gnl|BL_ORD_ID|24856 gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------FGIRRLVVGGSVRHGGH
ARGRPLPCPACPTGPDISSS----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---ASSLLSRTMTSYFDGGPSAPET--SRPKQQRRLDIAIVGAPNAGKSQLLNSLVGSK-
------VAAVSRKRHTTRSGILGAR-----TF--------GDTQLVFIDTPGFLH-HSKG
A---REGV---RNLLSEASAEMMNA-----------------------------------
----------------------------DFALLVVDAAKT-IDQDLKRTLVTLMMLALRS
TGREE------------GSRVFSDQRHL------------GRFSVVLNKVDLV-KPKEKL
LATAAEVGSLAESCVRRLLQQHRAPVRVKMGELVDSV-----LERHEDEEGFAGVHEEDY
ETFASVV-PEF--------------------------LFT--------------SAIDPE
DEGA---------DDLLNVLLSR----------ATPSTEFVMDPSSN-----L-------
--------EQVEEIIREKI------YR--CLHREVPHHVQQTNRVFKL------KQDQPP
DHDVRADMGDLLQIHQDLIVRTKSHHRLVLGS-GGKTLQRIQTTASKDLRELFG-CEVDL
LLSVKLKKT-NQ-GVLLDPEEEGA-RITTLHD
>T.pseudonana_gnl|BL_ORD_ID|10627 gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------AFFRRALLQGSLAVNNL
THDTWHQTPRAITSLLNHQQ----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---SCSLHSTPITLNNPTSSSAATTQSDKPAPQKRLDVAIVGAPNAGKSQLLNSLIGSK-
------VAAVSRKRHTTRTGILGAR-----TF--------DDTQLVFIDTPGFLH-HEMS
V---KEGV---RKLLGEASSEMESA-----------------------------------
----------------------------DFVLLVVDAARK-MEDDLRRTLVTLMFLALRS
KGRNE-------------------------------------FAVVLNKVDLV-SPKEKL
LMTAADVGSMAESCIRQFLNQRRSPSKVKFGELVDTV-----LKNYANEDGFDGVHDDDI
ELFATLA-PEF--------------------------FFT--------------SAIVKD
DEGV---------DDVLGLLLER----------ATLSDQWIVDAGSATGMTPV-------
--------EQVEEIIREKI------YR--CLHREVPHSVQQQNRMFQLYKPNESKTKSTD
GSDVDEDI-KILRIRQDLIVRTKSHQRLVLGS-GGKTLERIRSTALKDLEESFD-CIVDL
DLTVRVTKS-NQHEAILDPESVGAVSLTPLEN
>F.cylindrus_GMF1_gnl|BL_ORD_ID|11386 jgi|Fracy1|187133|e_gw1.7.947.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------FKNAVLFPQRRARTWLWNNS--NTT
TDACRANLSYAIERCCSSSS----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---SSSSSQSQSQSQSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILTQSP-
------VAAVSRKRHTTRSDILGAR-----TI--------GNTQIVFKDTPGFMR-IENA
K---EERLD--RDLIATAASEMQDV-----------------------------------
----------------------------DFTLLVIDSARA-LSENYRHA-----------
--------DDDANPNSNDGR--------------------GKFAIVLNKVDLV-KPKSTL
IDLAMEIGAIADTCLEDHFTEHGKTI--------------------------------DF
EAMLEHS-PIV--------------------------FYV--------------SAL--K
EDGT---------DDLLDHLINL----------ATPCKEWAVQSGQSTNMTEL-------
--------EQVQEIIREKI------YR--TCHREVPHSVQQVNRMFRKIPKKG-------
-----------VIIHQDLVVFTKSHQKLVLGA-GGRTLERIRESAQTDLRKMFK-CEVSL
HLHVK--KKIGRRGDSGTEYKLGEASQTIL--
>Pn.multiseries_gnl|BL_ORD_ID|138163 jgi|Psemu1|186266|e_gw1.57.139.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RKIAGATVKEASLVLRRYHRPALGNSSIIGGN
TGWLSSQASSRVKFLSSSSP----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---SSTRRQSPPASRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLTKSP-
------IAAVSRKRHTTRSDLLGAR-----TV--------GNTQIVFKDTPGFLR-IENA
K---EERLD--RDLIATAASEMQDV-----------------------------------
----------------------------DFTLLVLDSART-LSDNYRHALVQLMVGAINS
GGRIEDCDDDDDNNDRKTTRQSREDINPSSKCDTAIPSDKSKFAIVLNKVDLV-KPKTDL
ISLAMDVGTMADTCLLDQFQKQGREF--------------------------------DF
DAQMEQS-PIV--------------------------FYV--------------SAL--K
EDGT---------DDLLEHLLGL----------ATPSREWPVEPGKATNMTTL-------
--------EQVQEVIREKI------YR--STHKEVPHAVQQVNRLFRRIPNKG-------
-----------VVIHQDLVVFTKSHQKLVLGSGGGKTLKRIQESARHDLQKLFG-CDVAL
QLHVKYRKSKQQRGDSGAQYNLGEVSQSVY--
>P.tricornutum_gnl|BL_ORD_ID|6794 gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------RPTFIRTALVT
FRWSGGPKISRSDRVRLSSTTIGST--PSLEDRKRLDVAIVGLPNAGKSQLLNVLTQST-
------VAAVSRKRHTTRDGILGAR-----TV--------DDTQLYFVDTPGFLR-QSQA
K---KEGLN--RDLVVTASSEMENV-----------------------------------
----------------------------DFSLLVVDAARR-MTDDYEETLVALMLAALRS
QGRLE--FDVHSAEEVQSIRTPKGGTNP------------AKFAVVLNKVDLV-HPKSNL
MDLAVNIGTLAEQCIKFDAKESGKEELF------------------------------LD
SAYLQESLPMF--------------------------FYI--------------SAL--K
QRGV---------QDLLEFLLER----------ATPSTSWEVEAGEATPMTMK-------
--------ERIEEVIREKI------YR--CLHKEVPHSIRQENRVLQQGKDED-------
-------GNIVLVIHQDLIVRSKSHQELVHGG-GGRTLERIRETAARGLEKIFF-CNVVL
HLHVKLPRSKNQRWSI----------------
>F.cylindrus_GMF1_gnl|BL_ORD_ID|17946 jgi|Fracy1|190835|e_gw1.11.594.1
MNTNTTTITNV-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------NNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLLKED-
------LCIATRRPQTTRHAILGVL-----SS--------PTKQCCLLDTPGVLQGDGAY
QLQ--------ANMMEAVKGALTDS-----------------------------------
----------------------------DMIVVVTDLFSTPIPDD---------------
----------NVFRRLSETT--------------------KPVLVVVNKIDLE-GRAKRP
DE----------------------------------------------------------
ATIQRRPIP---------------------------------------------------
--GMFRNGVKSLTNDDVKQLLPI----------GPPLYDDDFLSDRSVRFF---------
----------CSELIREAL------LESRYLKKELPYCCEVQITDYKEPRDD--------
---------NITRIEATIFVERDGQKAIIIGK-NGDVVKQVGIIAREKIERFLDGEKVFL
QLRVKINKDWRKREDQLAKFGYSN--------
>P.tricornutum_gnl|BL_ORD_ID|696 gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------MGAPNMGKSTLLNALLEED-
------LCIATARPQTTRHAILGLM-----ST--------DKCQVCLVDTPGVIE-DPAY
ELQ--------EGMMEAVTGAVATS-----------------------------------
----------------------------DVLLVVTDVFSTPIPDD---------------
----------ELFLKVQRTR--------------------KPVLVAINKIDLA-KKVNKA
AEENRDKTVTVEEA----------------------------------------------
VAFWRAQLPNALC-----------------------------------------ILPLSA
SQGINNVGVVAM-RRILTELLPI----------SPPLYDPETLTDRPERFI---------
----------ASEIVRSAL--------FQVLKKELPYCCEVRIREFKEPKEEG-------
---------EVIRIAADVLVERDSQKVIVIGK-NGAQVKEIGVIAREKLEAFFR-HQIFL
NLSVKVDKDWRKNTRKLTEYGYMKPKR-----
>T.oceanica_gnl|BL_ORD_ID|14494 gi|397643422|gb|EJK75853.1| hypothetical protein THAOC_02405 [Thalassiosira oceanica]
MK-----------------GSIRMAHVGALMMFA-------TTACRGFRRSS---QSATP
KSTNRHITVLSQYCGIRDEVRRRNLIVGPSLQTVASRRRRATARLGPLHTPLQSTLYDLE
EKESTASTSDEDTVFALSSGSG---VTAVAVIRISGRNAFDALKQLLSPYSLEAGAEPPK
LPTPRMASLRILYDPLS----SSDHLNRM----RDPLDSALVLIFPGPRSFTGEDIVELH
CHGSRAVTSGVLKALSSLDS------VRPADPGEFTQR----------------------
------------------------------------------------------------
--------------------------------------------------AYGNGKLGLV
EVEALADLIVADT---------------------------------------SLQRKQAL
QQFDGRLSRLYLGWRKELIKGLAHAEAVIDFGDDEALGEE--DSSFD-------------
---------------S-SENDGGMSVWADVRPRISSLREAMDRHLE--------------
------------------------DASRGELLRDGLRIAIVGRPNAGKSSLLNLLAGRD-
------AAIVSSTPGTTRDVVEVVL-----DL--------DGVRCSLLDTAGVRE-EIED
GVDEIE-----IEGMKRARLAAQEA-----------------------------------
----------------------------HLIVGVVDCSDQKRGLEAVQELIRADGHSDSA
RS-SPH----------------------------------NNLLYVLNKRDLFEGEMEPC
G----V------------------------------------------------------
---------------------------------------------D----SETFAISCTT
NQGV---------DIFLAALSKRALAMISQEGDSSGDLSVV----GTEGAVITRARHR--
---------------------------------RHVEAASDALQRFEVLSSQGYMALDMA
AEELRLASSELGRVTGAIDVEDVLDVLFADFCIGK-------------------------
--------------------------------
>T.pseudonana_gnl|BL_ORD_ID|7596 gi|224013676|ref|XP_002296502.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
LPNARMASLRTLYDPTADAKGTSDDEEEMQQQKRDPLDSALVLTFEGPNSFTGEDIVELH
CHGSRAVVHGVLSALSSLSSRAIPLQLRPADPGEFTQR----------------------
------------------------------------------------------------
--------------------------------------------------AYAHGKLGLV
EVEALADLIVADT---------------------------------------SLQRKQAL
QQFDGRLSRLYGGWREELIKGLAHAEAVIDFGDDEALDAH--DEFDD-------------
---------------GLNANDGGMSIWGTIAPRIRSLRQAMNRHLA--------------
------------------------DASRGELLRDGLRIAIVGRPNAGKSSLLNLLAGRD-
------AAIVSSSPGTTRDVVEVML-----DL--------GGVRCTLLDTAGVRE-EKEE
GVNEIE-----VEGMKRARRAARDA-----------------------------------
----------------------------HIIVGVVDATDLSRGLEAVDELIRVESESDES
SSLLNR----------------------------------DNVLYVLNKLDLVEGNENSI
NSKEQS------------------------------------------------------
---------------------------------------------N----SPKFGISCTT
SEGV---------DDFLSSLTQQALSLVSGDRDE--------------GAVITRARHR--
---------------------------------RHVEAASDALERFEELSGQGYMALDMA
AEELRLASSELGRVTGAIDVEDVLDVLFADFCIGK-------------------------
--------------------------------
>P.tricornutum_gnl|BL_ORD_ID|9918 gi|219114453|ref|XP_002176397.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MRMTTQRCYSTQHSRHFSFQSIRIPHVLLAMVVSAWFGSQPTRTVRAFPLTQWRCHSVRR
NTNCRHVSHLS---------FQRN--------TVFKEHTRTKRVLIPSTTRRYSSVNDVD
MTTTVATTSSQDTIFALSSGAATGQATAVAVIRLSGPQA-GVILQRLTP------GRP--
LPKPRTAALRKLHD--------LDDPKVV-------LDQALVLYFSGPNSFTGDDVVELQ
VHGSRAVVTAVLETLGTA--------ARLAEPGEFTQR----------------------
------------------------------------------------------------
--------------------------------------------------AWLAGKLDAL
QVEALADLLTADT---------------------------------------ATQRQQAL
AQLDGQLSAVYDTWRDMLVAGLAHAEAVIDFGDDERLDDALLDEEDQ-------------
---------------QLAQD----NVWGGVVGNMEVLERSMRRQLQ--------------
------------------------DARRGELVRQGLQIAIVGPPNAGKSSLFNILADRD-
------AAIVSPTAGTTRDVLELSL-----NL--------GGVKCVLQDTAGVRT-FTDD
A---IE-----MEGIARATRAAAQA-----------------------------------
----------------------------DLVLAMVDSSDVESGLEILTTIL-------QN
SPNLDR----------------------------------QHVLLLLNKSDLREEKHQTI
EVPGKD------------------------------------------------------
---------------------------------------------VVELIGGQYEISCAT
QNGV---------DTFLESLTRICVARVSNTDASDRDKTSIVDRETSEGTLITRARHR--
---------------------------------QHVQAAVEALERFQTLSQQGTMSVDLA
AEELRLAASELGRITGAVDVEDVLDKLFADFCIGK-------------------------
--------------------------------
>F.cylindrus_GMF2_gnl|BL_ORD_ID|3483 jgi|Fracy1|196010|e_gw1.26.139.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
PTPISTQPIRRYRS----------------------LKKEPLVAILGRPNVGKSAFVNRI
C--------GTQNGGAIVADEEGITRDRTYRDANFLGE----------------------
--------------NFQVVDT---------------------------------------
-----GGLV-------------------------FADDESTLFA-------------REI
REQAMVAIDESSGVVLVVDGKIGMTAMDQQIAEFLRKDVLSR----------NLPVILAV
NKCES-------------------ETVGALNAAEFWNLGL--------------------
---------------------------------GEPIPVSALHGVGTAEVLERLFEEIKQ
KQSAALPGFGTKDALA--------AFDEL-ERPEEINVAIVGRPNVGKSSLLNALFGDQ-
------RAIVSKMAGTTRDSIDAVM-----ER-PGDNEGDLPTIYRFVDTAGIRR-RAKV
EYGPE------FFMVNRALRAIRRA-----------------------------------
----------------------------DVVLLVMDATAG-VTEQ---------------
--------DRILAQKIADDG--------------------RACAIICNKWDAVVDKDSST
YDKSVK------------------------------------------------------
--YIRAEMPQIRWAP---------------------ILFI--------------SAE--T
GQRV---------GKIYNVVDD--------------------AIGAHRKRIST-------
--------SVLNEVLRDAILWQPPPARRNGAQAKIYYCNQVSTR----------------
-------PPTIVVFCNDPKLVNDNYKRYL----DRKFRESLDGFEATPVRWIFRGRRARD
IMRAKDMNGNPGDGGKGVSYPFPHAD------
>P.tricornutum_gnl|BL_ORD_ID|7302 gi|219109543|ref|XP_002176526.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MKSVLCGVTLACGGIWQANSFTFRPLPVTRPVIGLLATLDRVNEKSTVEPS---------
------------------------------------------------------------
------------------------------------------------------------
SGDPQLQPIRRLRQ----------------------NKKEPLIAIVGRPNVGKSALVNRI
A--------GSQSGGAIVADESGITRDRTYRPAEFLGE----------------------
--------------RFMIVDT---------------------------------------
-----GGLV-------------------------FDDDESTLFA-------------KEI
REQAMVAIEESAAVIMVVDGQTGLTGMDLMIAEFLRKEV-------------DIPVHVAV
NKCES-------------------EKTGAMSAADFWGLGL--------------------
---------------------------------GEPFPVSALHGVGTAEIMETIFDSIAE
KK----------------------TFDAE-DRPEEINIAIIGRPNVGKSSLLNSIFGDT-
------RAIVSEMAGTTRDSIDAVM-----ERPPPPGSDDLSTIYRFVDTAGIRR-KGKV
DFGPE------FFMVNRALRAIRRA-----------------------------------
----------------------------DVVLLILDATSG-VAEQ---------------
--------DRVLAQKIADDG--------------------RACVIVCNKWDAVVDKDSTT
YDKSVQ------------------------------------------------------
--YFREELPMIRWAP---------------------ILFI--------------SAA--T
GQRV---------GKIYSAIDG--------------------AIEAHRKRIST-------
--------AILNEVLRDAILWQPPPTRRNGSQAKIYYCNQVSTR----------------
-------PPTVVVFCNDPKLVNDNYRRYL----DRKFRESLDGFEATPIRWIFRGRRVRD
VMRNRSMNGDPGDGGTGVSFPFPHAD------
>T.pseudonana_gnl|BL_ORD_ID|5653 gi|223994975|ref|XP_002287171.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------PLIAVVGRPNVGKSALVNRL
A--------GTQSGGAIVADEEGITRDRTYRNAEFLGE----------------------
--------------AFQLVDT---------------------------------------
-----GGLV-------------------------FDDNDA-LFA-------------KEI
REQAMIAIEESAGVILVVDGQMGPTSMDEQLAIFLRKEVLK-----------KMPVILAV
NKCES-------------------DKNGAYLASQFWNLGL--------------------
---------------------------------GEPFAVSALHGVGTAEVMEKMFDDIAK
------------------------PLDGEDDTDEEINVAIIGRPNVGKSSLINTIFGSN-
------RAIVSDVAGTTRDSIDAIM-----ER-PSSDPEGLPTIYRFVDTAGIRR-KGKI
EFGPE------FFMVNRALRAIRRA-----------------------------------
----------------------------DVVLLVLDATAG-VTEQ---------------
--------DRVLAQKISDDG--------------------RACVILCNKWDAVIDKDSST
YDQSVK------------------------------------------------------
--YFREELPQIRWAP---------------------ILFV--------------SAA--T
GQRV---------GKIYEAVDS--------------------AVNAHRRRIST-------
--------SVLNEVLRDATLWQPPPARRNGAQAKIYYGSQVSTR----------------
-------PPTIVVFVNDPNLINDNYKRYL----DRKMRESLDGFESTPIRWMFRGRRVRD
VTRNM---------------------------
>F.cylindrus_GMF2_gnl|BL_ORD_ID|13890 jgi|Fracy1|147902|gw1.4.359.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SNFTVSILGPPNAGKSTLFNRL
QCKERNRAKHTSKGNAIVSSIAGTTRDRRECWGRIGGT----------------------
--------------EFTLMDT---------------------------------------
-----AGI---------------------------DGDRIQALAGKSKSEKHA--LERAM
MEQTLEAAKKSDLVLLLWDARIGVSQDLLITARWLRKLGK------------HSNVSLIA
NKLEG------------DSWAHDEDSIVMENLRDVLRLGL--------------------
---------------------------------GNAIPISALQGDGLADIAILIEKLKTE
KEAKYNQENYSTDT--TTANEISENNSGKDGDQKPLQIAIIGRQNVGKSTLVNRLLKSD-
------RVLTGSTPGLTRDAIAVEW-----DW--------DGQLVQLVDTAGIRK-LTKR
MQMDDDSIE--DQSVADALRAMKVA-----------------------------------
----------------------------EVAVLVLDAKELFIQRQELAICNAVLNEG---
----------------------------------------RALVIAANKMDLIEMSSTYT
SRDFAN----------------------------------------------------SV
REQIESRIPILRNIP---------------------IVPM--------------SCI--S
GKGI---------EHVLPAALD--------------------ARNRWARTIST-------
--------GLLNRWLAEVVTGLQPPYVAGVRAK------------------------LKY
IIQTKGRPPTFIIFSNVKSFPEPYLRYLTRQFQDSFELYGMPVRL---------------
--------------------------------
>P.tricornutum_gnl|BL_ORD_ID|5109 gi|219124383|ref|XP_002182484.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SRIVVSILGPPNAGKSTLFNRL
LDKAANRA-----GTAIVSNVPGTTRDRRECVGRIGGT----------------------
--------------LFRLVDT---------------------------------------
-----AGV---------------------------DGERLELLAQSRRNQNGEGILMKFM
MGQTLEAARQADLVFLMFDARVGVTADLLETARWLRKISQREQDPAAQTALPDRQIFLLA
NKLEG------------DFWNFD-GSIVLDHLTEATRLGF--------------------
---------------------------------GEAIPISAHHGEGLADIAVLIEQAAVA
KRQSLGILDDDTD--------LASNDSDKD---KPLQLAILGRQNVGKSTLVNALLKQD-
------RVIVGATPGLTRDAIAVEW-----TW--------KNRPVQIVDTAGIRK-RSQR
NH--EDAIE--DLSVEDALRAMKVA-----------------------------------
----------------------------DVAVLVLDAEARKLQRQELAIADAVLKEG---
----------------------------------------RALVVAANKMDLI-VERGYS
KKDFAE----------------------------------------------------DV
RAQLEARYPILRKTP---------------------IVPM--------------SSL--T
GDSV---------HKLMPVVFR--------------------ARERWSRKIST-------
--------GELNRWIAEVMDGKPPPPVSGRKAR------------------------IKY
VMQTKGRPPTFLLFCNVASLPENYLRFLTRNFQDTFEMFGMEVRM---------------
--------------------------------
>F.cylindrus_GMF1_gnl|BL_ORD_ID|25599 jgi|Fracy1|214794|estExt_Genewise1Plus.C_700009
MSEDIV------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------AEFSSKAGGGYNRPGVQWYPGHIAKA
ERQLSETLKAVDVVVEVRDARACKATSHPRVGEWCA----------------GRPRIVVL
THLDMIPKAAANSWRKAYEKFGAEDMDDAPIN----------------------------
---------------------------------RQVLFVNAKQGQGIHALHRAIFK----
-----------------AGSHVQERRERRGLNPRALRVGIIGYPNVGKSALINKILGRK-
------RAKTANTPGVTRSLQWIR-------------------EFELLDSPGIIP-AKMV
DQS--------DALLLAACNCIGQAAYDNQAVAAYLYEWLKAVYLMDKQALTAPNWRDKC
IDRYGFDPLEKVQRDEDDIVQDEYLTGEDMLFKVADDL----------------------
-----------------------------------------------CRGDAE-DAARKM
LQDFRQ------------------------------------------------------
------------------------------------------------------------
------------------------------GRMGPISLQMAPESEEDGGMLSVSVGDGTI
LGRQSMR--------------------------GSENGGFDAEYQQQIQDE----RARIA
LETAKERGLELPPIVDDPERA------------KEEAEADVGKGMFDGW-----------
--------------------------------
>T.oceanica_gnl|BL_ORD_ID|10226 gi|397601583|gb|EJK57948.1| hypothetical protein THAOC_21972 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------EDPNSFSLSGYQRPKVNWYPGHIAKA
ERQLAETLKSVDVVIEVRDSRAPKATAHPSVGKWAA----------------GRPRVVVL
TRVDTVTTRSRETWRQAYERLGADRWQEKLAGDERNRNAQFETERRK-------------
---------------YVDGEDGDSVKLRGADGVEEVLFVDAKRGQGTHAITRAVYR----
-----------------AGRHVNERRKRRGLNDRSLRVGIIGFPNVGKSALINRLLGRK-
------RAKTANTPGITRSLQWMRVAADKSTSASGSGSANAKKGFELLDSPGIIP-SDML
DQN--------DALLLAACNSVGVGA---KIAARWGSESTDGSARSWLDFAAKNADRMPS
GE--------------------------DMLFIVADNT----------------------
-----------------------------------------------CKGDPE-NAARKI
LQDFRN------------------------------------------------------
------------------------------------------------------------
------------------------------GRMGPVSLQLAPESETDEGQVHVENMRSDG
LDVRIVA--------------------------SPTNLKRATEEHEKRQKEEIQQRAKAA
MVAAKQKGLDLPPVVESIDVDDTEQVAAGGGADSKPSESEIGKGLFDGW-----------
--------------------------------
>T.pseudonana_gnl|BL_ORD_ID|2716 gi|223994459|ref|XP_002286913.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PKVNWYPGHIAKA
ERQLSETLKSVDVVIEVRDSRAPKATAHPSVGKWTA----------------GRPRVVVL
TRMDTVTSRSRDSWREAYERLGADRWEDSLV-----------------------------
---------------------------------EEILFVDAKRGQGTHAISRAVYK----
-----------------AGRHVNERRKRRGLNDRPLRVGIIGFPNVGKSALINRLLGKK-
------RARTANTPGITRSLQWIR------------------SGFELLDSPGIIP-SDML
DQS--------DALLLAACNSIGVGAYDNQAVAAYLCERIQSLVIMEKDYIAAPLWRNRC
IERYGFDPL-------------------DMLFIVADNT----------------------
-----------------------------------------------CKGDPE-NAARKI
LQDFRM------------------------------------------------------
------------------------------------------------------------
------------------------------GRMGPISLQL--------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>P.tricornutum_gnl|BL_ORD_ID|9646 gi|219116036|ref|XP_002178813.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------PRSQGTSRKGKPGKKDRDAGMGKSLQRAQVQRYRPRADGKSRRGDGGMHMQA
GVDSIGLEEAQQDQLKTRSVLEMQDLDDFLLQADMANREFVSEKEGLVVVDQTGQAYRPP
AVQWADQKSSFLFTELSVPRRPAWDDTTTAVELDMNERKSFLEWRRA-------------
----------------------------------IAIKEEELARTSSLAAATPFEKNLEV
WRQLWRVLERSACLLQLVDARNPMFYLSDDLRDYASTL--------------GKPMMVLV
NKSDYLSPSQRASWREYLMEKGWDPVFFSAVKEQQKLDAMANRKRIQVQLGTGHDNSLDH
LGEETDVSIDAHDQIEEPEDERGVSVPLSRERLMETMLSFARQH----------------
------------------------NCQPDPRYDNRIQFGMVGFPNVGKSSVINVLFGSSK
HEHGVVRVAVASQPGKTKHFQTLML-----P---------DAEEMMLCDCPGLVF-PSFV
SNT--------ADLIAAGVYPIAQM-----------------------------------
----------------------------RDHWPVTNLICQRIPREVINAHYGIVLPKPSQ
LEMNERGLTKLPPPSGEEFLGTFCIAR-------------GMLAASSGVPDYT-RAARTI
IKDYAD------------------------------------------------------
-----GKLLYCHPPPS--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>F.cylindrus_GMF1_gnl|BL_ORD_ID|22594 jgi|Fracy1|214636|estExt_Genewise1Plus.C_650061
M----------------------AP------KYQNKTKRRENAIPRTGASSKI--GKGRD
NAKGG-------------------------------------------------------
------------------------------------------------------------
HRSAETIKRLNLYKS-RAIRNKKGTIIGGDFMMGDRAGDRDITGETGRIAPDRRWFGNTR
VVDPKQLDTFRQEMTEKVADPYSVVLKRKKLPMGLLREAAEREA-----PPSQALLGQEP
FSQVFGSKSRRKKVKLDQLML-----------------------ARSDVDPNKDEDED--
-----GAPI-------------------------KKGG-----RAEVKADLFNKGQSKRI
WGEFFKVVDCSDVVLHIIDARNVPGTRCNMIERHIRDNAS------------HKHLVFVL
NKIDLVPNWVAKRWMGELAKDRPTIAFHASMTHAFGKGALISLLR---------------
------------------------------------------------------------
------------------------QFGKLHGDKKQISVGVIGYPNVGKSSVINTLISQK-
------SCKVAPIPGETKIWQYITL-----F-----------KRISLIDCPGVVV-DTAG
DTE--------TESVLKGVVRAERL-----------------------------------
----------------------------ETPEDFIQPIVDMVKREHIAGQYKFTKEESNK
WTTPTELLETIATK--------------------------AGRLLKGGEPCLR-SASITM
INDFQR------------------------------------------------------
-----GRLPHFVAPP---------------------ELKE--------------------
------------------------------------------------------------
------------------------------------------------------------
-DDVEENQGNMGGSTAVIEGVKPEAQELDKI----GEENTKSDGTVDGESDQKEG-----
---------KETGSSGVVADEPVAIAEGEWDD
>P.tricornutum_gnl|BL_ORD_ID|6857 gi|219112187|ref|XP_002177845.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M----------------------AKTGWKSGISNTSSAGKTNRTPKGNASSKLTQGRRRD
KQPGS-------------------------------------------------------
------------------------------------------------------------
ERSAETIQRLKMYSNGKAIRNKAGKIVAGTFMMQDRAGDRKIEASTGRIQPDRRWFGNTR
VVGATELDRFRQEMTEKVADPYSVVLKRKKLPMGLLQDAAEYKA----GNQKAALLEQEP
FDQAFGKNSRRKRVKLDQLFV-----------------------QRAAESADSKEDIKTG
E----GEAI-------------------------RSEGEGIDWRHEKKDDLFLKGQSKRI
WGEFFKVVDCSDVVLHIIDARNVPGTRCTMIERHIAKNAS------------HKHLVFVL
NKIDLVPNWVAKRWMGELAAVRPTIAFHASLTNAFGKGALISLLR---------------
------------------------------------------------------------
------------------------QFGKLHEDKKQISVGVIGYPNVGKSSVINTLISKK-
------SCKVAPIPGETKIWQYVTL-----F-----------KRISLIDCPGVVV-DTAG
DTE--------EDSVLKGVVRAERL-----------------------------------
----------------------------ENPEDFIDAIMGKVKREHIAAQYKLPKDGEET
WSSSGELMEMIARR--------------------------SGRLLKGGDPCIR-TAALMI
INDFQR------------------------------------------------------
-----GRLPHFIPPP---------------------ELKV--------------------
------------------------------------------------------------
------------------------------------------------------------
-EEDQKTVATE-------QAIQIEEQNLDDVVVVEKEMEQDEEGVETKTNDHAAI-----
---------ADTET--VIDTSSILIGDGKWDE
>T.oceanica_gnl|BL_ORD_ID|1577 gi|397642458|gb|EJK75246.1| hypothetical protein THAOC_03037 [Thalassiosira oceanica]
M----------------------VKTGYKF-TKQQPNKGSRNMLKNSAASSRPNRTAPKR
GDNGN-------------------------------------------------------
------------------------------------------------------------
MRSNQTIARLKMYNNGKAIRNKEGKVVGGQFMMGDRAGDTKITAATGRIAPDRRWFGNTR
VVNPTELDRFREEMTSSMADPYSVVVKRKQLPMGLLRDAAELE-KAGRNNS--GLLANEP
FEHTFGGKSRRKRVKMEQYMVGRTSKIDDVEDKDEEDDQKPYRGGEAETVNDMPSDDKSG
YAALLAAAQKSQDTYSKVNNRVGIVPWGKDSNLTKTSGEGVDWVHSKKDDLFLKGQSKRI
WGEFYKVVDCSDVILHVIDARNVPGTRCTMIEKHIAKNAP------------HKHLVFVL
NKIDLVPNWVAKRWIGELAQIRPTIAFHASMTHAFGKGALISLLR---------------
------------------------------------------------------------
------------------------QFGKLNSDKKQISVGVIGYPNVGKSSVINTLISKK-
------SCKVAPIPGETKIWQYITL-----F-----------RNIYLIDCPGVVV-DTAG
DSE--------TDSVLKGVVRSERL-----------------------------------
----------------------------ETPEDYVDAIQDAVKREHIAAMYGLPRSGEDT
WKSSEELCEKIAIK--------------------------CGRLRKGGEPCLR-SAAIMI
INDFQR------------------------------------------------------
-----GRLPHYVAPP---------------------ELKE--------------------
------------------------------------------------------------
------------------------------------------------------------
-EDSGEGAAAV-ADTANIEGVELAAQNLDEVTRDRAEDSAEGQRSDTKEETSEKIEKKDG
IAEDAGDVEADEDA--GSDDDEVVIGDGDWE-
>T.pseudonana_gnl|BL_ORD_ID|4381 gi|224003191|ref|XP_002291267.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
KADSN-------------------------------------------------------
------------------------------------------------------------
MRSSATIARLKMYNNGKAIRNKEGKVVGGQFMMADRAGDSKITAATGRIAPDRRWFGNTR
VVAPTELDAFREEMTQSMADPYSVVIKRKQLPMGLLKDAAELQAKHGGTNSSAGLLLNEP
FEHAFGTKSRRKRVKVEQFMV-----------------------GNAETLANLPDDDATG
YKSLLAAAQ-------------------------KTSGEGVDWRTEKKDDLFLKGQSKRI
WGEFYKVLDCSDVILHIIDARNVPGTRCTMIEKHIAKNAP------------HKHLVFVL
NKIDLVPNWVAKRWIGELAQIRPTIAFHASMTHAFGKGALISLLR---------------
------------------------------------------------------------
------------------------QFGKLASDKKQISVGVIGYPNVGKSSVINTLISKK-
------SCKVAPVPGETKIWQYITL-----F-----------RNIYLIDCPGVVV-DTAG
DTE--------IDSVLKGDVRAERL-----------------------------------
----------------------------ECPEDFIDAIQAAVKREHIAAMYGVPKSGDDT
WSTSIELLEKISIK--------------------------CGRLKKGGEPCLR-SSAITL
INDFQR------------------------------------------------------
-----GRLPHYVAPP---------------------E-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>T.oceanica_gnl|BL_ORD_ID|33149 gi|397569214|gb|EJK46603.1| hypothetical protein THAOC_34725 [Thalassiosira oceanica]
M---------------------------------------------------------VK
KKGKS-------------------------------------------------------
------------------------------------------------------------
KRITLKDKYKIQRRVVETHRKNRKQAKRDAKAGIVRHDKKKDPGIPNSWPFKQELLQSIQ
REKERAENRKLEEKERRVNKNGAANLEELVKQANQKKSEFDAKT----------------
------------------------------------------------------------
----------------------------------GSSSAASDDGIKIVTTSHGQQSRRAY
LRSLKTVIESSDVILQVLDARDPLGTRISSGIEASILSHF------------DKRMVLVM
NKIDLIPKKNVSEWLTYLRRSHPTVALKAGTTQSRSNEGGRSSGVGQ-------------
---------------TKGENALSSSMAVGVDGLLQLLKNYA-------------------
------------------------RANGEKKSKTSITVGIIGYPNVGKSSILNSLKRFR-
------AVGVSSRPGFTTTLQEVVL-----D-----------KNIRLIDSPGVVF-DDDA
SRDG-------ANAMLRNGVDADSV-----------------------------------
----------------------------SDPLPAIAELLGRCTSESLMMTYSVPAFPPGP
EGVLTFLAMVARS---------------------------KGRVLKGGIPDKM-MAARLV
MRDWNQ------------------------------------------------------
-----GKIPYFSTPP---------------------VTEVEM------------------
------------------------------------------------------------
---------------------------------GDTSAGSTHAKIVSKFSEEFDVSKIMA
AHDKELMNGLEDVDEMDFVQMTSSSRPRGEGS-ADKVVKYLHEGGDQNSDSEMEGDDDAV
ALNTRMEEAEDFFGE-----------------
>F.cylindrus_GMF2_gnl|BL_ORD_ID|13155 jgi|Fracy1|162596|gw1.1.2020.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------EVAFLGRSNVGKSSLINAIMRKN-
------LCITSKSPGRTQLPYYYGN-----PS--------GQPQGFIVDLPGYGF-AKKP
MSITEDWQKDTQDLLLHRRHEAKVL-----------------------------------
----------------------------KRLFLLMDARRG-VQGPNEH------------
--------DRIVMRWLEDAE--------------------IPFTVVLTKADRV-S-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3128 _gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
MDSETPT-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KNEAEQRASPDRTGQVTQRPVSLFRK
NGTFAYPLEDSDV---------------------------------------YEEQVLAL
EDVPEPTAQAILRL----------------------------------------------
------------------------------------------------------------
------------------------ALAAERQGVPRLRFLVVGAPGVGKSSLINTLLNEN-
------LCSVSAWERGTKNAQVCAR-----QV--------DSVVIEFIDTPGIAP-CR--
-----------RSGLEASRRQVQRL-----------------------------------
----------------------------RKLLDARGADEHPYLRSFHAILYVMRLDD---
-----------------------------------------------TRPDLVDYHNWKV
LMEFFGAEVLRHMMVVFTHGQSLPPDSLSYPEYVRGRRDYVYLLIERLTGPLKAVRFPVF
VAENSSKCPVIEETGERKLPDDTPWITQLYDGIRRFVFPLEADLFGMETGPEDTQVLVYI
YDKRRSRADERYPRSPLQALIRNPWFLRAVQFCGAMLLRSYMIRQEHERFNPK-------
-------PHHPEPIIRDANNAFAVASRRANDHRLFTPSIDEDEESFFRMNGN-----DDF
VSRLRNRPGEVDLDELDVERIESPDGRFVEYWYTEKDNPEMVRMYRLEIRDDPNEERESR
QDRIPISKDQH---------------------
