>Toc159_T.oceanica_gnl|BL_ORD_ID|24856 gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------FGIRRLVVGGSVRHGGH
ARGRPLPCPACPTGPDISSS----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---ASSLLSRTMTSYFDGGPSAPET--SRPKQQRRLDIAIVGAPNAGKSQLLNSLVGSK-
------VAAVSRKRHTTRSGILGAR-----TF--------GDTQLVFIDTPGFLH-HSKG
A---REGV---RNLLSEASAEMMNA-----------------------------------
----------------------------DFALLVVDAAKT-IDQDLKRTLVTLMMLALRS
TGREE------------GSRVFSDQRHL------------GRFSVVLNKVDLV-KPKEKL
LATAAEVGSLAESCVRRLLQQHRAPVRVKMGELVDSV-----LERHEDEEGFAGVHEEDY
ETFASVV-PEF--------------------------LFT--------------SAIDPE
DEGA---------DDLLNVLLSR----------ATPSTEFVMDPSSN-----L-------
--------EQVEEIIREKI------YR--CLHREVPHHVQQTNRVFKL------KQDQPP
DHDVRADMGDLLQIHQDLIVRTKSHHRLVLGS-GGKTLQRIQTTASKDLRELFG-CEVDL
LLSVKLKKT-NQ-GVLLDPEEEGA-RITTLHD
>Toc159_T.pseudonana_gnl|BL_ORD_ID|10627 gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------AFFRRALLQGSLAVNNL
THDTWHQTPRAITSLLNHQQ----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---SCSLHSTPITLNNPTSSSAATTQSDKPAPQKRLDVAIVGAPNAGKSQLLNSLIGSK-
------VAAVSRKRHTTRTGILGAR-----TF--------DDTQLVFIDTPGFLH-HEMS
V---KEGV---RKLLGEASSEMESA-----------------------------------
----------------------------DFVLLVVDAARK-MEDDLRRTLVTLMFLALRS
KGRNE-------------------------------------FAVVLNKVDLV-SPKEKL
LMTAADVGSMAESCIRQFLNQRRSPSKVKFGELVDTV-----LKNYANEDGFDGVHDDDI
ELFATLA-PEF--------------------------FFT--------------SAIVKD
DEGV---------DDVLGLLLER----------ATLSDQWIVDAGSATGMTPV-------
--------EQVEEIIREKI------YR--CLHREVPHSVQQQNRMFQLYKPNESKTKSTD
GSDVDEDI-KILRIRQDLIVRTKSHQRLVLGS-GGKTLERIRSTALKDLEESFD-CIVDL
DLTVRVTKS-NQHEAILDPESVGAVSLTPLEN
>Toc159_F.cylindrus_GMF1_gnl|BL_ORD_ID|11386 jgi|Fracy1|187133|e_gw1.7.947.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------FKNAVLFPQRRARTWLWNNS--NTT
TDACRANLSYAIERCCSSSS----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---SSSSSQSQSQSQSQSQSTLQQS--PSTIGRKRLDVAIVGAPNAGKSQLVNILTQSP-
------VAAVSRKRHTTRSDILGAR-----TI--------GNTQIVFKDTPGFMR-IENA
K---EERLD--RDLIATAASEMQDV-----------------------------------
----------------------------DFTLLVIDSARA-LSENYRHA-----------
--------DDDANPNSNDGR--------------------GKFAIVLNKVDLV-KPKSTL
IDLAMEIGAIADTCLEDHFTEHGKTI--------------------------------DF
EAMLEHS-PIV--------------------------FYV--------------SAL--K
EDGT---------DDLLDHLINL----------ATPCKEWAVQSGQSTNMTEL-------
--------EQVQEIIREKI------YR--TCHREVPHSVQQVNRMFRKIPKKG-------
-----------VIIHQDLVVFTKSHQKLVLGA-GGRTLERIRESAQTDLRKMFK-CEVSL
HLHVK--KKIGRRGDSGTEYKLGEASQTIL--
>Toc159_Pn.multiseries_gnl|BL_ORD_ID|138163 jgi|Psemu1|186266|e_gw1.57.139.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------RKIAGATVKEASLVLRRYHRPALGNSSIIGGN
TGWLSSQASSRVKFLSSSSP----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---SSTRRQSPPASRPQAAATAQNR------TRKRLDVAIVGPPNAGKSQLVNVLTKSP-
------IAAVSRKRHTTRSDLLGAR-----TV--------GNTQIVFKDTPGFLR-IENA
K---EERLD--RDLIATAASEMQDV-----------------------------------
----------------------------DFTLLVLDSART-LSDNYRHALVQLMVGAINS
GGRIEDCDDDDDNNDRKTTRQSREDINPSSKCDTAIPSDKSKFAIVLNKVDLV-KPKTDL
ISLAMDVGTMADTCLLDQFQKQGREF--------------------------------DF
DAQMEQS-PIV--------------------------FYV--------------SAL--K
EDGT---------DDLLEHLLGL----------ATPSREWPVEPGKATNMTTL-------
--------EQVQEVIREKI------YR--STHKEVPHAVQQVNRLFRRIPNKG-------
-----------VVIHQDLVVFTKSHQKLVLGSGGGKTLKRIQESARHDLQKLFG-CDVAL
QLHVKYRKSKQQRGDSGAQYNLGEVSQSVY--
>Toc159_P.tricornutum_gnl|BL_ORD_ID|6794 gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------RPTFIRTALVT
FRWSGGPKISRSDRVRLSSTTIGST--PSLEDRKRLDVAIVGLPNAGKSQLLNVLTQST-
------VAAVSRKRHTTRDGILGAR-----TV--------DDTQLYFVDTPGFLR-QSQA
K---KEGLN--RDLVVTASSEMENV-----------------------------------
----------------------------DFSLLVVDAARR-MTDDYEETLVALMLAALRS
QGRLE--FDVHSAEEVQSIRTPKGGTNP------------AKFAVVLNKVDLV-HPKSNL
MDLAVNIGTLAEQCIKFDAKESGKEELF------------------------------LD
SAYLQESLPMF--------------------------FYI--------------SAL--K
QRGV---------QDLLEFLLER----------ATPSTSWEVEAGEATPMTMK-------
--------ERIEEVIREKI------YR--CLHKEVPHSIRQENRVLQQGKDED-------
-------GNIVLVIHQDLIVRSKSHQELVHGG-GGRTLERIRETAARGLEKIFF-CNVVL
HLHVKLPRSKNQRWSI----------------
>Toc159_F.cylindrus_GMF1_gnl|BL_ORD_ID|17946 jgi|Fracy1|190835|e_gw1.11.594.1
MNTNTTTITNV-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------NNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLLKED-
------LCIATRRPQTTRHAILGVL-----SS--------PTKQCCLLDTPGVLQGDGAY
QLQ--------ANMMEAVKGALTDS-----------------------------------
----------------------------DMIVVVTDLFSTPIPDD---------------
----------NVFRRLSETT--------------------KPVLVVVNKIDLE-GRAKRP
DE----------------------------------------------------------
ATIQRRPIP---------------------------------------------------
--GMFRNGVKSLTNDDVKQLLPI----------GPPLYDDDFLSDRSVRFF---------
----------CSELIREAL------LESRYLKKELPYCCEVQITDYKEPRDD--------
---------NITRIEATIFVERDGQKAIIIGK-NGDVVKQVGIIAREKIERFLDGEKVFL
QLRVKINKDWRKREDQLAKFGYSN--------
>Toc159_P.tricornutum_gnl|BL_ORD_ID|696 gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------MGAPNMGKSTLLNALLEED-
------LCIATARPQTTRHAILGLM-----ST--------DKCQVCLVDTPGVIE-DPAY
ELQ--------EGMMEAVTGAVATS-----------------------------------
----------------------------DVLLVVTDVFSTPIPDD---------------
----------ELFLKVQRTR--------------------KPVLVAINKIDLA-KKVNKA
AEENRDKTVTVEEA----------------------------------------------
VAFWRAQLPNALC-----------------------------------------ILPLSA
SQGINNVGVVAM-RRILTELLPI----------SPPLYDPETLTDRPERFI---------
----------ASEIVRSAL--------FQVLKKELPYCCEVRIREFKEPKEEG-------
---------EVIRIAADVLVERDSQKVIVIGK-NGAQVKEIGVIAREKLEAFFR-HQIFL
NLSVKVDKDWRKNTRKLTEYGYMKPKR-----
>Toc159_T.oceanica_gnl|BL_ORD_ID|14494 gi|397643422|gb|EJK75853.1| hypothetical protein THAOC_02405 [Thalassiosira oceanica]
MK-----------------GSIRMAHVGALMMFA-------TTACRGFRRSS---QSATP
KSTNRHITVLSQYCGIRDEVRRRNLIVGPSLQTVASRRRRATARLGPLHTPLQSTLYDLE
EKESTASTSDEDTVFALSSGSG---VTAVAVIRISGRNAFDALKQLLSPYSLEAGAEPPK
LPTPRMASLRILYDPLS----SSDHLNRM----RDPLDSALVLIFPGPRSFTGEDIVELH
CHGSRAVTSGVLKALSSLDS------VRPADPGEFTQR----------------------
------------------------------------------------------------
--------------------------------------------------AYGNGKLGLV
EVEALADLIVADT---------------------------------------SLQRKQAL
QQFDGRLSRLYLGWRKELIKGLAHAEAVIDFGDDEALGEE--DSSFD-------------
---------------S-SENDGGMSVWADVRPRISSLREAMDRHLE--------------
------------------------DASRGELLRDGLRIAIVGRPNAGKSSLLNLLAGRD-
------AAIVSSTPGTTRDVVEVVL-----DL--------DGVRCSLLDTAGVRE-EIED
GVDEIE-----IEGMKRARLAAQEA-----------------------------------
----------------------------HLIVGVVDCSDQKRGLEAVQELIRADGHSDSA
RS-SPH----------------------------------NNLLYVLNKRDLFEGEMEPC
G----V------------------------------------------------------
---------------------------------------------D----SETFAISCTT
NQGV---------DIFLAALSKRALAMISQEGDSSGDLSVV----GTEGAVITRARHR--
---------------------------------RHVEAASDALQRFEVLSSQGYMALDMA
AEELRLASSELGRVTGAIDVEDVLDVLFADFCIGK-------------------------
--------------------------------
>Toc159_T.pseudonana_gnl|BL_ORD_ID|7596 gi|224013676|ref|XP_002296502.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
LPNARMASLRTLYDPTADAKGTSDDEEEMQQQKRDPLDSALVLTFEGPNSFTGEDIVELH
CHGSRAVVHGVLSALSSLSSRAIPLQLRPADPGEFTQR----------------------
------------------------------------------------------------
--------------------------------------------------AYAHGKLGLV
EVEALADLIVADT---------------------------------------SLQRKQAL
QQFDGRLSRLYGGWREELIKGLAHAEAVIDFGDDEALDAH--DEFDD-------------
---------------GLNANDGGMSIWGTIAPRIRSLRQAMNRHLA--------------
------------------------DASRGELLRDGLRIAIVGRPNAGKSSLLNLLAGRD-
------AAIVSSSPGTTRDVVEVML-----DL--------GGVRCTLLDTAGVRE-EKEE
GVNEIE-----VEGMKRARRAARDA-----------------------------------
----------------------------HIIVGVVDATDLSRGLEAVDELIRVESESDES
SSLLNR----------------------------------DNVLYVLNKLDLVEGNENSI
NSKEQS------------------------------------------------------
---------------------------------------------N----SPKFGISCTT
SEGV---------DDFLSSLTQQALSLVSGDRDE--------------GAVITRARHR--
---------------------------------RHVEAASDALERFEELSGQGYMALDMA
AEELRLASSELGRVTGAIDVEDVLDVLFADFCIGK-------------------------
--------------------------------
>Toc159_P.tricornutum_gnl|BL_ORD_ID|9918 gi|219114453|ref|XP_002176397.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MRMTTQRCYSTQHSRHFSFQSIRIPHVLLAMVVSAWFGSQPTRTVRAFPLTQWRCHSVRR
NTNCRHVSHLS---------FQRN--------TVFKEHTRTKRVLIPSTTRRYSSVNDVD
MTTTVATTSSQDTIFALSSGAATGQATAVAVIRLSGPQA-GVILQRLTP------GRP--
LPKPRTAALRKLHD--------LDDPKVV-------LDQALVLYFSGPNSFTGDDVVELQ
VHGSRAVVTAVLETLGTA--------ARLAEPGEFTQR----------------------
------------------------------------------------------------
--------------------------------------------------AWLAGKLDAL
QVEALADLLTADT---------------------------------------ATQRQQAL
AQLDGQLSAVYDTWRDMLVAGLAHAEAVIDFGDDERLDDALLDEEDQ-------------
---------------QLAQD----NVWGGVVGNMEVLERSMRRQLQ--------------
------------------------DARRGELVRQGLQIAIVGPPNAGKSSLFNILADRD-
------AAIVSPTAGTTRDVLELSL-----NL--------GGVKCVLQDTAGVRT-FTDD
A---IE-----MEGIARATRAAAQA-----------------------------------
----------------------------DLVLAMVDSSDVESGLEILTTIL-------QN
SPNLDR----------------------------------QHVLLLLNKSDLREEKHQTI
EVPGKD------------------------------------------------------
---------------------------------------------VVELIGGQYEISCAT
QNGV---------DTFLESLTRICVARVSNTDASDRDKTSIVDRETSEGTLITRARHR--
---------------------------------QHVQAAVEALERFQTLSQQGTMSVDLA
AEELRLAASELGRITGAVDVEDVLDKLFADFCIGK-------------------------
--------------------------------
>Toc159_F.cylindrus_GMF2_gnl|BL_ORD_ID|3483 jgi|Fracy1|196010|e_gw1.26.139.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
PTPISTQPIRRYRS----------------------LKKEPLVAILGRPNVGKSAFVNRI
C--------GTQNGGAIVADEEGITRDRTYRDANFLGE----------------------
--------------NFQVVDT---------------------------------------
-----GGLV-------------------------FADDESTLFA-------------REI
REQAMVAIDESSGVVLVVDGKIGMTAMDQQIAEFLRKDVLSR----------NLPVILAV
NKCES-------------------ETVGALNAAEFWNLGL--------------------
---------------------------------GEPIPVSALHGVGTAEVLERLFEEIKQ
KQSAALPGFGTKDALA--------AFDEL-ERPEEINVAIVGRPNVGKSSLLNALFGDQ-
------RAIVSKMAGTTRDSIDAVM-----ER-PGDNEGDLPTIYRFVDTAGIRR-RAKV
EYGPE------FFMVNRALRAIRRA-----------------------------------
----------------------------DVVLLVMDATAG-VTEQ---------------
--------DRILAQKIADDG--------------------RACAIICNKWDAVVDKDSST
YDKSVK------------------------------------------------------
--YIRAEMPQIRWAP---------------------ILFI--------------SAE--T
GQRV---------GKIYNVVDD--------------------AIGAHRKRIST-------
--------SVLNEVLRDAILWQPPPARRNGAQAKIYYCNQVSTR----------------
-------PPTIVVFCNDPKLVNDNYKRYL----DRKFRESLDGFEATPVRWIFRGRRARD
IMRAKDMNGNPGDGGKGVSYPFPHAD------
>Toc159_P.tricornutum_gnl|BL_ORD_ID|7302 gi|219109543|ref|XP_002176526.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MKSVLCGVTLACGGIWQANSFTFRPLPVTRPVIGLLATLDRVNEKSTVEPS---------
------------------------------------------------------------
------------------------------------------------------------
SGDPQLQPIRRLRQ----------------------NKKEPLIAIVGRPNVGKSALVNRI
A--------GSQSGGAIVADESGITRDRTYRPAEFLGE----------------------
--------------RFMIVDT---------------------------------------
-----GGLV-------------------------FDDDESTLFA-------------KEI
REQAMVAIEESAAVIMVVDGQTGLTGMDLMIAEFLRKEV-------------DIPVHVAV
NKCES-------------------EKTGAMSAADFWGLGL--------------------
---------------------------------GEPFPVSALHGVGTAEIMETIFDSIAE
KK----------------------TFDAE-DRPEEINIAIIGRPNVGKSSLLNSIFGDT-
------RAIVSEMAGTTRDSIDAVM-----ERPPPPGSDDLSTIYRFVDTAGIRR-KGKV
DFGPE------FFMVNRALRAIRRA-----------------------------------
----------------------------DVVLLILDATSG-VAEQ---------------
--------DRVLAQKIADDG--------------------RACVIVCNKWDAVVDKDSTT
YDKSVQ------------------------------------------------------
--YFREELPMIRWAP---------------------ILFI--------------SAA--T
GQRV---------GKIYSAIDG--------------------AIEAHRKRIST-------
--------AILNEVLRDAILWQPPPTRRNGSQAKIYYCNQVSTR----------------
-------PPTVVVFCNDPKLVNDNYRRYL----DRKFRESLDGFEATPIRWIFRGRRVRD
VMRNRSMNGDPGDGGTGVSFPFPHAD------
>Toc159_T.pseudonana_gnl|BL_ORD_ID|5653 gi|223994975|ref|XP_002287171.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------PLIAVVGRPNVGKSALVNRL
A--------GTQSGGAIVADEEGITRDRTYRNAEFLGE----------------------
--------------AFQLVDT---------------------------------------
-----GGLV-------------------------FDDNDA-LFA-------------KEI
REQAMIAIEESAGVILVVDGQMGPTSMDEQLAIFLRKEVLK-----------KMPVILAV
NKCES-------------------DKNGAYLASQFWNLGL--------------------
---------------------------------GEPFAVSALHGVGTAEVMEKMFDDIAK
------------------------PLDGEDDTDEEINVAIIGRPNVGKSSLINTIFGSN-
------RAIVSDVAGTTRDSIDAIM-----ER-PSSDPEGLPTIYRFVDTAGIRR-KGKI
EFGPE------FFMVNRALRAIRRA-----------------------------------
----------------------------DVVLLVLDATAG-VTEQ---------------
--------DRVLAQKISDDG--------------------RACVILCNKWDAVIDKDSST
YDQSVK------------------------------------------------------
--YFREELPQIRWAP---------------------ILFV--------------SAA--T
GQRV---------GKIYEAVDS--------------------AVNAHRRRIST-------
--------SVLNEVLRDATLWQPPPARRNGAQAKIYYGSQVSTR----------------
-------PPTIVVFVNDPNLINDNYKRYL----DRKMRESLDGFESTPIRWMFRGRRVRD
VTRNM---------------------------
>Toc159_F.cylindrus_GMF2_gnl|BL_ORD_ID|13890 jgi|Fracy1|147902|gw1.4.359.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SNFTVSILGPPNAGKSTLFNRL
QCKERNRAKHTSKGNAIVSSIAGTTRDRRECWGRIGGT----------------------
--------------EFTLMDT---------------------------------------
-----AGI---------------------------DGDRIQALAGKSKSEKHA--LERAM
MEQTLEAAKKSDLVLLLWDARIGVSQDLLITARWLRKLGK------------HSNVSLIA
NKLEG------------DSWAHDEDSIVMENLRDVLRLGL--------------------
---------------------------------GNAIPISALQGDGLADIAILIEKLKTE
KEAKYNQENYSTDT--TTANEISENNSGKDGDQKPLQIAIIGRQNVGKSTLVNRLLKSD-
------RVLTGSTPGLTRDAIAVEW-----DW--------DGQLVQLVDTAGIRK-LTKR
MQMDDDSIE--DQSVADALRAMKVA-----------------------------------
----------------------------EVAVLVLDAKELFIQRQELAICNAVLNEG---
----------------------------------------RALVIAANKMDLIEMSSTYT
SRDFAN----------------------------------------------------SV
REQIESRIPILRNIP---------------------IVPM--------------SCI--S
GKGI---------EHVLPAALD--------------------ARNRWARTIST-------
--------GLLNRWLAEVVTGLQPPYVAGVRAK------------------------LKY
IIQTKGRPPTFIIFSNVKSFPEPYLRYLTRQFQDSFELYGMPVRL---------------
--------------------------------
>Toc159_P.tricornutum_gnl|BL_ORD_ID|5109 gi|219124383|ref|XP_002182484.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SRIVVSILGPPNAGKSTLFNRL
LDKAANRA-----GTAIVSNVPGTTRDRRECVGRIGGT----------------------
--------------LFRLVDT---------------------------------------
-----AGV---------------------------DGERLELLAQSRRNQNGEGILMKFM
MGQTLEAARQADLVFLMFDARVGVTADLLETARWLRKISQREQDPAAQTALPDRQIFLLA
NKLEG------------DFWNFD-GSIVLDHLTEATRLGF--------------------
---------------------------------GEAIPISAHHGEGLADIAVLIEQAAVA
KRQSLGILDDDTD--------LASNDSDKD---KPLQLAILGRQNVGKSTLVNALLKQD-
------RVIVGATPGLTRDAIAVEW-----TW--------KNRPVQIVDTAGIRK-RSQR
NH--EDAIE--DLSVEDALRAMKVA-----------------------------------
----------------------------DVAVLVLDAEARKLQRQELAIADAVLKEG---
----------------------------------------RALVVAANKMDLI-VERGYS
KKDFAE----------------------------------------------------DV
RAQLEARYPILRKTP---------------------IVPM--------------SSL--T
GDSV---------HKLMPVVFR--------------------ARERWSRKIST-------
--------GELNRWIAEVMDGKPPPPVSGRKAR------------------------IKY
VMQTKGRPPTFLLFCNVASLPENYLRFLTRNFQDTFEMFGMEVRM---------------
--------------------------------
>Toc159_F.cylindrus_GMF1_gnl|BL_ORD_ID|25599 jgi|Fracy1|214794|estExt_Genewise1Plus.C_700009
MSEDIV------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------AEFSSKAGGGYNRPGVQWYPGHIAKA
ERQLSETLKAVDVVVEVRDARACKATSHPRVGEWCA----------------GRPRIVVL
THLDMIPKAAANSWRKAYEKFGAEDMDDAPIN----------------------------
---------------------------------RQVLFVNAKQGQGIHALHRAIFK----
-----------------AGSHVQERRERRGLNPRALRVGIIGYPNVGKSALINKILGRK-
------RAKTANTPGVTRSLQWIR-------------------EFELLDSPGIIP-AKMV
DQS--------DALLLAACNCIGQAAYDNQAVAAYLYEWLKAVYLMDKQALTAPNWRDKC
IDRYGFDPLEKVQRDEDDIVQDEYLTGEDMLFKVADDL----------------------
-----------------------------------------------CRGDAE-DAARKM
LQDFRQ------------------------------------------------------
------------------------------------------------------------
------------------------------GRMGPISLQMAPESEEDGGMLSVSVGDGTI
LGRQSMR--------------------------GSENGGFDAEYQQQIQDE----RARIA
LETAKERGLELPPIVDDPERA------------KEEAEADVGKGMFDGW-----------
--------------------------------
>Toc159_T.oceanica_gnl|BL_ORD_ID|10226 gi|397601583|gb|EJK57948.1| hypothetical protein THAOC_21972 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------EDPNSFSLSGYQRPKVNWYPGHIAKA
ERQLAETLKSVDVVIEVRDSRAPKATAHPSVGKWAA----------------GRPRVVVL
TRVDTVTTRSRETWRQAYERLGADRWQEKLAGDERNRNAQFETERRK-------------
---------------YVDGEDGDSVKLRGADGVEEVLFVDAKRGQGTHAITRAVYR----
-----------------AGRHVNERRKRRGLNDRSLRVGIIGFPNVGKSALINRLLGRK-
------RAKTANTPGITRSLQWMRVAADKSTSASGSGSANAKKGFELLDSPGIIP-SDML
DQN--------DALLLAACNSVGVGA---KIAARWGSESTDGSARSWLDFAAKNADRMPS
GE--------------------------DMLFIVADNT----------------------
-----------------------------------------------CKGDPE-NAARKI
LQDFRN------------------------------------------------------
------------------------------------------------------------
------------------------------GRMGPVSLQLAPESETDEGQVHVENMRSDG
LDVRIVA--------------------------SPTNLKRATEEHEKRQKEEIQQRAKAA
MVAAKQKGLDLPPVVESIDVDDTEQVAAGGGADSKPSESEIGKGLFDGW-----------
--------------------------------
>Toc159_T.pseudonana_gnl|BL_ORD_ID|2716 gi|223994459|ref|XP_002286913.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PKVNWYPGHIAKA
ERQLSETLKSVDVVIEVRDSRAPKATAHPSVGKWTA----------------GRPRVVVL
TRMDTVTSRSRDSWREAYERLGADRWEDSLV-----------------------------
---------------------------------EEILFVDAKRGQGTHAISRAVYK----
-----------------AGRHVNERRKRRGLNDRPLRVGIIGFPNVGKSALINRLLGKK-
------RARTANTPGITRSLQWIR------------------SGFELLDSPGIIP-SDML
DQS--------DALLLAACNSIGVGAYDNQAVAAYLCERIQSLVIMEKDYIAAPLWRNRC
IERYGFDPL-------------------DMLFIVADNT----------------------
-----------------------------------------------CKGDPE-NAARKI
LQDFRM------------------------------------------------------
------------------------------------------------------------
------------------------------GRMGPISLQL--------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Toc159_P.tricornutum_gnl|BL_ORD_ID|9646 gi|219116036|ref|XP_002178813.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------PRSQGTSRKGKPGKKDRDAGMGKSLQRAQVQRYRPRADGKSRRGDGGMHMQA
GVDSIGLEEAQQDQLKTRSVLEMQDLDDFLLQADMANREFVSEKEGLVVVDQTGQAYRPP
AVQWADQKSSFLFTELSVPRRPAWDDTTTAVELDMNERKSFLEWRRA-------------
----------------------------------IAIKEEELARTSSLAAATPFEKNLEV
WRQLWRVLERSACLLQLVDARNPMFYLSDDLRDYASTL--------------GKPMMVLV
NKSDYLSPSQRASWREYLMEKGWDPVFFSAVKEQQKLDAMANRKRIQVQLGTGHDNSLDH
LGEETDVSIDAHDQIEEPEDERGVSVPLSRERLMETMLSFARQH----------------
------------------------NCQPDPRYDNRIQFGMVGFPNVGKSSVINVLFGSSK
HEHGVVRVAVASQPGKTKHFQTLML-----P---------DAEEMMLCDCPGLVF-PSFV
SNT--------ADLIAAGVYPIAQM-----------------------------------
----------------------------RDHWPVTNLICQRIPREVINAHYGIVLPKPSQ
LEMNERGLTKLPPPSGEEFLGTFCIAR-------------GMLAASSGVPDYT-RAARTI
IKDYAD------------------------------------------------------
-----GKLLYCHPPPS--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Toc159_F.cylindrus_GMF1_gnl|BL_ORD_ID|22594 jgi|Fracy1|214636|estExt_Genewise1Plus.C_650061
M----------------------AP------KYQNKTKRRENAIPRTGASSKI--GKGRD
NAKGG-------------------------------------------------------
------------------------------------------------------------
HRSAETIKRLNLYKS-RAIRNKKGTIIGGDFMMGDRAGDRDITGETGRIAPDRRWFGNTR
VVDPKQLDTFRQEMTEKVADPYSVVLKRKKLPMGLLREAAEREA-----PPSQALLGQEP
FSQVFGSKSRRKKVKLDQLML-----------------------ARSDVDPNKDEDED--
-----GAPI-------------------------KKGG-----RAEVKADLFNKGQSKRI
WGEFFKVVDCSDVVLHIIDARNVPGTRCNMIERHIRDNAS------------HKHLVFVL
NKIDLVPNWVAKRWMGELAKDRPTIAFHASMTHAFGKGALISLLR---------------
------------------------------------------------------------
------------------------QFGKLHGDKKQISVGVIGYPNVGKSSVINTLISQK-
------SCKVAPIPGETKIWQYITL-----F-----------KRISLIDCPGVVV-DTAG
DTE--------TESVLKGVVRAERL-----------------------------------
----------------------------ETPEDFIQPIVDMVKREHIAGQYKFTKEESNK
WTTPTELLETIATK--------------------------AGRLLKGGEPCLR-SASITM
INDFQR------------------------------------------------------
-----GRLPHFVAPP---------------------ELKE--------------------
------------------------------------------------------------
------------------------------------------------------------
-DDVEENQGNMGGSTAVIEGVKPEAQELDKI----GEENTKSDGTVDGESDQKEG-----
---------KETGSSGVVADEPVAIAEGEWDD
>Toc159_P.tricornutum_gnl|BL_ORD_ID|6857 gi|219112187|ref|XP_002177845.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M----------------------AKTGWKSGISNTSSAGKTNRTPKGNASSKLTQGRRRD
KQPGS-------------------------------------------------------
------------------------------------------------------------
ERSAETIQRLKMYSNGKAIRNKAGKIVAGTFMMQDRAGDRKIEASTGRIQPDRRWFGNTR
VVGATELDRFRQEMTEKVADPYSVVLKRKKLPMGLLQDAAEYKA----GNQKAALLEQEP
FDQAFGKNSRRKRVKLDQLFV-----------------------QRAAESADSKEDIKTG
E----GEAI-------------------------RSEGEGIDWRHEKKDDLFLKGQSKRI
WGEFFKVVDCSDVVLHIIDARNVPGTRCTMIERHIAKNAS------------HKHLVFVL
NKIDLVPNWVAKRWMGELAAVRPTIAFHASLTNAFGKGALISLLR---------------
------------------------------------------------------------
------------------------QFGKLHEDKKQISVGVIGYPNVGKSSVINTLISKK-
------SCKVAPIPGETKIWQYVTL-----F-----------KRISLIDCPGVVV-DTAG
DTE--------EDSVLKGVVRAERL-----------------------------------
----------------------------ENPEDFIDAIMGKVKREHIAAQYKLPKDGEET
WSSSGELMEMIARR--------------------------SGRLLKGGDPCIR-TAALMI
INDFQR------------------------------------------------------
-----GRLPHFIPPP---------------------ELKV--------------------
------------------------------------------------------------
------------------------------------------------------------
-EEDQKTVATE-------QAIQIEEQNLDDVVVVEKEMEQDEEGVETKTNDHAAI-----
---------ADTET--VIDTSSILIGDGKWDE
>Toc159_T.oceanica_gnl|BL_ORD_ID|1577 gi|397642458|gb|EJK75246.1| hypothetical protein THAOC_03037 [Thalassiosira oceanica]
M----------------------VKTGYKF-TKQQPNKGSRNMLKNSAASSRPNRTAPKR
GDNGN-------------------------------------------------------
------------------------------------------------------------
MRSNQTIARLKMYNNGKAIRNKEGKVVGGQFMMGDRAGDTKITAATGRIAPDRRWFGNTR
VVNPTELDRFREEMTSSMADPYSVVVKRKQLPMGLLRDAAELE-KAGRNNS--GLLANEP
FEHTFGGKSRRKRVKMEQYMVGRTSKIDDVEDKDEEDDQKPYRGGEAETVNDMPSDDKSG
YAALLAAAQKSQDTYSKVNNRVGIVPWGKDSNLTKTSGEGVDWVHSKKDDLFLKGQSKRI
WGEFYKVVDCSDVILHVIDARNVPGTRCTMIEKHIAKNAP------------HKHLVFVL
NKIDLVPNWVAKRWIGELAQIRPTIAFHASMTHAFGKGALISLLR---------------
------------------------------------------------------------
------------------------QFGKLNSDKKQISVGVIGYPNVGKSSVINTLISKK-
------SCKVAPIPGETKIWQYITL-----F-----------RNIYLIDCPGVVV-DTAG
DSE--------TDSVLKGVVRSERL-----------------------------------
----------------------------ETPEDYVDAIQDAVKREHIAAMYGLPRSGEDT
WKSSEELCEKIAIK--------------------------CGRLRKGGEPCLR-SAAIMI
INDFQR------------------------------------------------------
-----GRLPHYVAPP---------------------ELKE--------------------
------------------------------------------------------------
------------------------------------------------------------
-EDSGEGAAAV-ADTANIEGVELAAQNLDEVTRDRAEDSAEGQRSDTKEETSEKIEKKDG
IAEDAGDVEADEDA--GSDDDEVVIGDGDWE-
>Toc159_T.pseudonana_gnl|BL_ORD_ID|4381 gi|224003191|ref|XP_002291267.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
KADSN-------------------------------------------------------
------------------------------------------------------------
MRSSATIARLKMYNNGKAIRNKEGKVVGGQFMMADRAGDSKITAATGRIAPDRRWFGNTR
VVAPTELDAFREEMTQSMADPYSVVIKRKQLPMGLLKDAAELQAKHGGTNSSAGLLLNEP
FEHAFGTKSRRKRVKVEQFMV-----------------------GNAETLANLPDDDATG
YKSLLAAAQ-------------------------KTSGEGVDWRTEKKDDLFLKGQSKRI
WGEFYKVLDCSDVILHIIDARNVPGTRCTMIEKHIAKNAP------------HKHLVFVL
NKIDLVPNWVAKRWIGELAQIRPTIAFHASMTHAFGKGALISLLR---------------
------------------------------------------------------------
------------------------QFGKLASDKKQISVGVIGYPNVGKSSVINTLISKK-
------SCKVAPVPGETKIWQYITL-----F-----------RNIYLIDCPGVVV-DTAG
DTE--------IDSVLKGDVRAERL-----------------------------------
----------------------------ECPEDFIDAIQAAVKREHIAAMYGVPKSGDDT
WSTSIELLEKISIK--------------------------CGRLKKGGEPCLR-SSAITL
INDFQR------------------------------------------------------
-----GRLPHYVAPP---------------------E-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Toc159_T.oceanica_gnl|BL_ORD_ID|33149 gi|397569214|gb|EJK46603.1| hypothetical protein THAOC_34725 [Thalassiosira oceanica]
M---------------------------------------------------------VK
KKGKS-------------------------------------------------------
------------------------------------------------------------
KRITLKDKYKIQRRVVETHRKNRKQAKRDAKAGIVRHDKKKDPGIPNSWPFKQELLQSIQ
REKERAENRKLEEKERRVNKNGAANLEELVKQANQKKSEFDAKT----------------
------------------------------------------------------------
----------------------------------GSSSAASDDGIKIVTTSHGQQSRRAY
LRSLKTVIESSDVILQVLDARDPLGTRISSGIEASILSHF------------DKRMVLVM
NKIDLIPKKNVSEWLTYLRRSHPTVALKAGTTQSRSNEGGRSSGVGQ-------------
---------------TKGENALSSSMAVGVDGLLQLLKNYA-------------------
------------------------RANGEKKSKTSITVGIIGYPNVGKSSILNSLKRFR-
------AVGVSSRPGFTTTLQEVVL-----D-----------KNIRLIDSPGVVF-DDDA
SRDG-------ANAMLRNGVDADSV-----------------------------------
----------------------------SDPLPAIAELLGRCTSESLMMTYSVPAFPPGP
EGVLTFLAMVARS---------------------------KGRVLKGGIPDKM-MAARLV
MRDWNQ------------------------------------------------------
-----GKIPYFSTPP---------------------VTEVEM------------------
------------------------------------------------------------
---------------------------------GDTSAGSTHAKIVSKFSEEFDVSKIMA
AHDKELMNGLEDVDEMDFVQMTSSSRPRGEGS-ADKVVKYLHEGGDQNSDSEMEGDDDAV
ALNTRMEEAEDFFGE-----------------
>Toc159_F.cylindrus_GMF2_gnl|BL_ORD_ID|13155 jgi|Fracy1|162596|gw1.1.2020.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------EVAFLGRSNVGKSSLINAIMRKN-
------LCITSKSPGRTQLPYYYGN-----PS--------GQPQGFIVDLPGYGF-AKKP
MSITEDWQKDTQDLLLHRRHEAKVL-----------------------------------
----------------------------KRLFLLMDARRG-VQGPNEH------------
--------DRIVMRWLEDAE--------------------IPFTVVLTKADRV-S-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Toc159_Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3128 _gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
MDSETPT-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------KNEAEQRASPDRTGQVTQRPVSLFRK
NGTFAYPLEDSDV---------------------------------------YEEQVLAL
EDVPEPTAQAILRL----------------------------------------------
------------------------------------------------------------
------------------------ALAAERQGVPRLRFLVVGAPGVGKSSLINTLLNEN-
------LCSVSAWERGTKNAQVCAR-----QV--------DSVVIEFIDTPGIAP-CR--
-----------RSGLEASRRQVQRL-----------------------------------
----------------------------RKLLDARGADEHPYLRSFHAILYVMRLDD---
-----------------------------------------------TRPDLVDYHNWKV
LMEFFGAEVLRHMMVVFTHGQSLPPDSLSYPEYVRGRRDYVYLLIERLTGPLKAVRFPVF
VAENSSKCPVIEETGERKLPDDTPWITQLYDGIRRFVFPLEADLFGMETGPEDTQVLVYI
YDKRRSRADERYPRSPLQALIRNPWFLRAVQFCGAMLLRSYMIRQEHERFNPK-------
-------PHHPEPIIRDANNAFAVASRRANDHRLFTPSIDEDEESFFRMNGN-----DDF
VSRLRNRPGEVDLDELDVERIESPDGRFVEYWYTEKDNPEMVRMYRLEIRDDPNEERESR
QDRIPISKDQH---------------------
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|11386 jgi|Fracy1|187133|e_gw1.7.947.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------F-KNAVLFPQRRART
WLWNNS--NTTTDACRANLSYAIERCCSSSS-----------------------------
--------------SSSSSQSQSQSQSQSQST----------------------------
------------------------------------------------------------
------LQQSPSTIGRKRLDVAIVGAPNAGKSQLVNILTQSP-------VAAVSRKRHTT
RSDILGARTIGN-------------TQIVFKDTPGFMRIENAK---EERLD--RDLIATA
ASEMQDVDFTLLVIDSARA--LSENYRHA-------------------DDDANPNSNDGR
--------------------GKFAIVLNK----------VDLV-KPKSTLID----LAME
--IGAIADTCLEDHFTEHGKT--I-------------------------DFEAMLEHS-P
IV-----FYVSAL--KEDGT---------DDLLDHLINLATPCKE---------------
----------------------------------------------------WAVQSGQS
TNMTELEQVQEIIR-----------------------EKI------YR--TCHREVPHSV
QQVNRMF----RKIP--------------KKG----VIIHQDLVVFTKSHQKLVLGA-GG
RTLERIRESAQTDLRKMFK-CEVS-LHLHVK--KKIGRRGDSGTEYKLG-EASQT-----
-IL
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|20621 jgi|Fracy1|254023|fgenesh2_pg.52_#_25
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------FKNAVLFPQRRART
WLWNNS------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------NTTTLDVAIVGAPNAGKSQLVNILTQSP-------VAAVSRKRHTT
RSDILGARTIGN-------------TQIVFKDTPGFMRIENAK---EERLD--RDLIATA
ASEMQDVDFTLLVIDSARA--LSENYRHAFVELK--------------------------
----------------------------------------NLL-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------GMIR----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--D
>Toc34_Pn.multiseries_gnl|BL_ORD_ID|138163 jgi|Psemu1|186266|e_gw1.57.139.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------RKIAGATV-KEASLVLRRYHRP
ALGNSSIIGGNTGWLSSQASSRVKFLSSSSP-----------------------------
--------------SSTRRQSPPASRPQAAAT----------------------------
------------------------------------------------------------
------AQNR----TRKRLDVAIVGPPNAGKSQLVNVLTKSP-------IAAVSRKRHTT
RSDLLGARTVGN-------------TQIVFKDTPGFLRIENAK---EERLD--RDLIATA
ASEMQDVDFTLLVLDSART--LSDNYRHALVQLMVGAINSGGRIEDCDDDDDNNDRKTTR
QSREDINPSSKCDTAIPSDKSKFAIVLNK----------VDLV-KPKTDLIS----LAMD
--VGTMADTCLLDQFQKQGRE--F-------------------------DFDAQMEQS-P
IV-----FYVSAL--KEDGT---------DDLLEHLLGLATPSRE---------------
----------------------------------------------------WPVEPGKA
TNMTTLEQVQEVIR-----------------------EKI------YR--STHKEVPHAV
QQVNRLF----RRIP--------------NKG----VVIHQDLVVFTKSHQKLVLGSGGG
KTLKRIQESARHDLQKLFG-CDVA-LQLHVKYRKSKQQRGDSGAQYNLG-EVSQS-----
-VY
>Toc34_P.tricornutum_gnl|BL_ORD_ID|6794 gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------RP
TF---------------IRTALVTFRWSGGP-----------------------------
--------------KISRSDRVRLSSTTIGST----------------------------
------------------------------------------------------------
------PSLE----DRKRLDVAIVGLPNAGKSQLLNVLTQST-------VAAVSRKRHTT
RDGILGARTVDD-------------TQLYFVDTPGFLRQSQAK---KEGLN--RDLVVTA
SSEMENVDFSLLVVDAARR--MTDDYEETLVALMLAALRSQGRLE--FDVHSAEEVQSIR
TPKGGTNP------------AKFAVVLNK----------VDLV-HPKSNLMD----LAVN
--IGTLAEQCIKFDAKESGKEELF-------------------------LDSAYLQESLP
MF-----FYISAL--KQRGV---------QDLLEFLLERATPSTS---------------
----------------------------------------------------WEVEAGEA
TPMTMKERIEEVIR-----------------------EKI------YR--CLHKEVPHSI
RQENRVL----QQGK--------------DEDGNIVLVIHQDLIVRSKSHQELVHGG-GG
RTLERIRETAARGLEKIFF-CNVV-LHLHVKLPRSKNQRWS-------------------
--I
>Toc34_T.oceanica_gnl|BL_ORD_ID|24856 gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------FGIRRL
VVGGSVRHGGHARGRPLPCPACPTGPDISSS-----------------------------
--------------ASSLLSRTMTSYFDGGPS----------------------------
------------------------------------------------------------
APET--SRPK----QQRRLDIAIVGAPNAGKSQLLNSLVGSK-------VAAVSRKRHTT
RSGILGARTFGD-------------TQLVFIDTPGFLHHSKGA---REGV---RNLLSEA
SAEMMNADFALLVVDAAKT--IDQDLKRTLVTLMMLALRSTGREE------------GSR
VFSDQRHL------------GRFSVVLNK----------VDLV-KPKEKLLA----TAAE
--VGSLAESCVRRLLQQHRAPVRVKMGELVDSVLERHEDEEGFAGVHEEDYETFASVV-P
EF-----LFTSAIDPEDEGA---------DDLLNVLLSRATPSTE---------------
----------------------------------------------------FVMDPSSN
-----LEQVEEIIR-----------------------EKI------YR--CLHREVPHHV
QQTNRVF----KL------KQDQPPDHDVRADMGDLLQIHQDLIVRTKSHHRLVLGS-GG
KTLQRIQTTASKDLRELFG-CEVD-LLLSVKLKKTNQ-GVLLDPEEEGA-RITTL-----
-HD
>Toc34_T.pseudonana_gnl|BL_ORD_ID|10627 gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------AFFRRA
LLQGSLAVNNLTHDTWHQTPRAITSLLNHQQ-----------------------------
--------------SCSLHSTPITLNNPTSSS----------------------------
------------------------------------------------------------
AATTQSDKPA----PQKRLDVAIVGAPNAGKSQLLNSLIGSK-------VAAVSRKRHTT
RTGILGARTFDD-------------TQLVFIDTPGFLHHEMSV---KEGV---RKLLGEA
SSEMESADFVLLVVDAARK--MEDDLRRTLVTLMFLALRSKGRNE---------------
----------------------FAVVLNK----------VDLV-SPKEKLLM----TAAD
--VGSMAESCIRQFLNQRRSPSKVKFGELVDTVLKNYANEDGFDGVHDDDIELFATLA-P
EF-----FFTSAIVKDDEGV---------DDVLGLLLERATLSDQ---------------
----------------------------------------------------WIVDAGSA
TGMTPVEQVEEIIR-----------------------EKI------YR--CLHREVPHSV
QQQNRMF----QLYKPNESKTKSTDGSDVDEDI-KILRIRQDLIVRTKSHQRLVLGS-GG
KTLERIRSTALKDLEESFD-CIVD-LDLTVRVTKSNQHEAILDPESVGAVSLTPL-----
-EN
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|17946 jgi|Fracy1|190835|e_gw1.11.594.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------NTN----------------------------
------------------------------------------------------------
TTTITNVNNDDHQQQHRCGYAGIVGAPNMGKSTLLNSLLKED-------LCIATRRPQTT
RHAILGVLSSPT-------------KQCCLLDTPGVLQGDGAY---Q--LQ--ANMMEAV
KGALTDSDMIVVVTDLFSTPIPDDNVFRRLSETT--------------------------
--------------------KPVLVVVNK----------IDLE-GRAKRPDE--------
----------A-----------------------------------------TIQRRPIP
------------------GMFRNGVKSLTNDDVKQLLPIGPPLYD---------------
----------------------------------------------------DDFLSDRS
VRFF----CSELIR-----------------------EAL------LESRYLKKELPYCC
EVQITDY----KEPR--------------DD---NITRIEATIFVERDGQKAIIIGK-NG
DVVKQVGIIAREKIERFLDGEKVF-LQLRVKINKDWRKREDQLAKF----GY--------
-SN
>Toc34_P.tricornutum_gnl|BL_ORD_ID|696 gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------MGAPNMGKSTLLNALLEED-------LCIATARPQTT
RHAILGLMSTDK-------------CQVCLVDTPGVIE-DPAY---E--LQ--EGMMEAV
TGAVATSDVLLVVTDVFSTPIPDDELFLKVQRTR--------------------------
--------------------KPVLVAINK----------IDLA-KKVNKAAE----ENRD
--KTVTVEEAV-----------------------------------------AFWRAQLP
NA-----LCILPL-SASQGINNVGVVAM-RRILTELLPISPPLYD---------------
----------------------------------------------------PETLTDRP
ERFI----ASEIVR-----------------------SAL------FQ--VLKKELPYCC
EVRIREF----KEPK--------------EEG--EVIRIAADVLVERDSQKVIVIGK-NG
AQVKEIGVIAREKLEAFFR-HQIF-LNLSVKVDKDWRKNTRKLTEY----GYMKP-----
-KR
>Toc34_P.tricornutum_gnl|BL_ORD_ID|9918 gi|219114453|ref|XP_002176397.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MRMTTQRCYSTQHSRHFSFQSIRIPHVLLAMVVSAWFGSQPTRTVRAFPLTQWRCHSVRR
NTNCRHVSHLSFQ-----------------RNTVFKEH----------------------
-----TRTKRVLIPSTTRRYSSVNDVDMTTTVATTSSQDTIFALSSGAATGQATAVAVIR
LSGPQAGVILQRLTPGRP-----------LPKPRTA------------------------
------------------------------------------------------------
--------------ALRKLHD-------------------LDDPKVVLDQALVLYFSGPN
SFTGDDVVELQVHGSRAVVTAVLETLGTAAR--------LAEPGEFTQRAWLA----GKL
DALQVEALADLLTADTATQRQQALAQLDGQLSAVYDTWRDMLVAGLAHAEAVIDFGDD--
--------ERLDDALLDEEDQQLAQDN-------------------VWGGVVGNMEVLER
SMRRQLQDARRGELVRQGLQIAIVGPPNAGKSSLFNILADRD-------AAIVSPTAGTT
RDVLELSLNLGG-------------VKCVLQDTAGVRTFTDDA------IE--MEGIARA
TRAAAQADLVLAMVDSS-------DVESGLEILTTILQNSPNLDR---------------
--------------------QHVLLLLNK----------SDLR-EEKHQTIEVPGKDVVE
LIGGQYEISCA-------------------------------------------------
---------------TQNGV---------DTFLESLTRICVARVS---------------
----------------------------------------------------NTDASDRD
KTSIVDRETSEG-------------------------TLI------TR--ARHRQHVQAA
VEALERF----QTLS--------------QQGTMSVDLAAEELRL-------------AA
SELGRI--TGAVDVEDVLD--KLF-ADFCIG-----------------------------
--K
>Toc34_T.oceanica_gnl|BL_ORD_ID|14494 gi|397643422|gb|EJK75853.1| hypothetical protein THAOC_02405 [Thalassiosira oceanica]
MK-----------------GSIRMAHVGALMMFA-------TTACRGFRRSS---QSATP
KSTNRHITVLSQYCGIRDEVRRRNLIVGPSLQTVASRR----------------------
-----RRATARLGPLHTPLQSTLYDLEEKESTASTSDEDTVFALSSGSG---VTAVAVIR
ISGRNAFDALKQLL--SPYSLEAGAEPPKLPTPRMA------------------------
------------------------------------------------------------
--------------SLRILYDPLS----SSDH----LNRM----RDPLDSALVLIFPGPR
SFTGEDIVELHCHGSRAVTSGVLKALSSLDS------VRPADPGEFTQRAYGN----GKL
GLVEVEALADLIVADTSLQRKQALQQFDGRLSRLYLGWRKELIKGLAHAEAVIDFGDD--
--------EALGEE--DSSFDS-SENDGGMS---------------VWADVRPRISSLRE
AMDRHLEDASRGELLRDGLRIAIVGRPNAGKSSLLNLLAGRD-------AAIVSSTPGTT
RDVVEVVLDLDG-------------VRCSLLDTAGVREEIEDG---VDEIE--IEGMKRA
RLAAQEAHLIVGVVDCS-------DQKRGLEAVQELIRADGHSDSARS-SPH--------
--------------------NNLLYVLNK----------RDLF-EGEMEPCG--------
VDSETFAISCT-------------------------------------------------
---------------TNQGV---------DIFLAALSKRALAMIS---------------
----------------------------------------------------QEGDSSGD
LSVV----GTE--G-----------------------AVI------TR--ARHRRHVEAA
SDALQRF----EVLS--------------SQGYMALDMAAEELRL-------------AS
SELGRV--TGAIDVEDVLD--VLF-ADFCIG-----------------------------
--K
>Toc34_T.pseudonana_gnl|BL_ORD_ID|7596 gi|224013676|ref|XP_002296502.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------LPNARMA------------------------
------------------------------------------------------------
--------------SLRTLYDPTADAKGTSDD----EEEMQQQKRDPLDSALVLTFEGPN
SFTGEDIVELHCHGSRAVVHGVLSALSSLSSRAIPLQLRPADPGEFTQRAYAH----GKL
GLVEVEALADLIVADTSLQRKQALQQFDGRLSRLYGGWREELIKGLAHAEAVIDFGDD--
--------EALDAH--DEFDDGLNANDGGMS---------------IWGTIAPRIRSLRQ
AMNRHLADASRGELLRDGLRIAIVGRPNAGKSSLLNLLAGRD-------AAIVSSSPGTT
RDVVEVMLDLGG-------------VRCTLLDTAGVREEKEEG---VNEIE--VEGMKRA
RRAARDAHIIVGVVDAT-------DLSRGLEAVDELIRVESESDESSSLLNR--------
--------------------DNVLYVLNK----------LDLV-EGNENSIN----SKEQ
SNSPKFGISCT-------------------------------------------------
---------------TSEGV---------DDFLSSLTQQALSLVS---------------
----------------------------------------------------GDRDEG--
-------------------------------------AVI------TR--ARHRRHVEAA
SDALERF----EELS--------------GQGYMALDMAAEELRL-------------AS
SELGRV--TGAIDVEDVLD--VLF-ADFCIG-----------------------------
--K
>Toc34_F.cylindrus_GMF2_gnl|BL_ORD_ID|3483 jgi|Fracy1|196010|e_gw1.26.139.1
M-----------------------------------------------------------
---------------------PTPISTQPIRRYRSLKK----------------------
-----EPLVAILGRPNVGKSAFVNRI--------CGTQNGGAIVADEEGITRDRTYRDAN
FLGENFQVVDTGGLVFADDESTLFA-----------------------------------
------------------------------------------------------------
----------------REIREQAMVAIDESSG----VVLVVDGKIGMTAMDQQIAEFLRK
DVLSR----------NLPVILAVNKCESETV-------GALNAAEFWNLGLGEPIPVSAL
HGVGTAEVLERLFEEIKQKQSAALPGFGTKDA----------------------------
------------------------------------------------------------
------LAAFDELERPEEINVAIVGRPNVGKSSLLNALFGDQ-------RAIVSKMAGTT
RDSIDAVMERPG-DNEGDLP-----TIYRFVDTAGIRRRAKVEYGPE------FFMVNRA
LRAIRRADVVLLVMDATAG-VTEQDRILAQKIADDG------------------------
--------------------RACAIICNK----------WDAV-VDKDSSTY----DKSV
----------------------------------------------------KYIRAEMP
QIRWAPILFISAE--TGQRV---------GKIYNV-------------------------
----------------------------------------------------VDDAIGAH
RKRISTSVLNEVLR-----------------------DAILWQPPPARRNGAQAKIYYCN
QVSTR-------------------------------------------PPTIVVFCNDPK
LVNDNYKRYLDRKFRESLDGFEATPVRWIFRGRRARDIMRAKDMNGNPGDGGKGVSYPFP
HAD
>Toc34_P.tricornutum_gnl|BL_ORD_ID|7302 gi|219109543|ref|XP_002176526.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MKSVLCGVTLACGGIWQANSFTFRPLPVTRPVIGLLATLDRVNEKSTV------------
------------------EPSSGDPQLQPIRRLRQNKK----------------------
-----EPLIAIVGRPNVGKSALVNRI--------AGSQSGGAIVADESGITRDRTYRPAE
FLGERFMIVDTGGLVFDDDESTLFA-----------------------------------
------------------------------------------------------------
----------------KEIREQAMVAIEESAA----VIMVVDGQTGLTGMDLMIAEFLRK
EV-------------DIPVHVAVNKCESEKT-------GAMSAADFWGLGLGEPFPVSAL
HGVGTAEIMETIFDSIAEKKT---------------------------------------
------------------------------------------------------------
---------FDAEDRPEEINIAIIGRPNVGKSSLLNSIFGDT-------RAIVSEMAGTT
RDSIDAVMERPPPPGSDDLS-----TIYRFVDTAGIRRKGKVDFGPE------FFMVNRA
LRAIRRADVVLLILDATSG-VAEQDRVLAQKIADDG------------------------
--------------------RACVIVCNK----------WDAV-VDKDSTTY----DKSV
----------------------------------------------------QYFREELP
MIRWAPILFISAA--TGQRV---------GKIYSA-------------------------
----------------------------------------------------IDGAIEAH
RKRISTAILNEVLR-----------------------DAILWQPPPTRRNGSQAKIYYCN
QVSTR-------------------------------------------PPTVVVFCNDPK
LVNDNYRRYLDRKFRESLDGFEATPIRWIFRGRRVRDVMRNRSMNGDPGDGGTGVSFPFP
HAD
>Toc34_F.cylindrus_GMF2_gnl|BL_ORD_ID|13890 jgi|Fracy1|147902|gw1.4.359.1
S-----------------------------------------------------------
------------------------------------------------------------
-----NFTVSILGPPNAGKSTLFNRLQCKERNRAKHTSKGNAIVSSIAGTTRDRRECWGR
IGGTEFTLMDTAGI--DGDRIQALAGKSKSEKHA--------------------------
------------------------------------------------------------
--------------LERAMMEQTLEAAKKSDL----VLLLWDARIGVSQDLLITARWLRK
LGKHS------------NVSLIANKLEGDSWAHDEDSIVMENLRDVLRLGLGNAIPISAL
QG-DGLADIAILIEKLKTEKEAKYNQENYSTD----------------------------
----------------------------------------------------------TT
TANEISENNSGKDGDQKPLQIAIIGRQNVGKSTLVNRLLKSD-------RVLTGSTPGLT
RDAIAVEWDWDG-------------QLVQLVDTAGIRKLTKRMQMDDDSIE--DQSVADA
LRAMKVAEVAVLVLDAKELFIQRQELAICNAVLNEG------------------------
--------------------RALVIAANK----------MDLIEMSSTYTSR----DFAN
-------------------------------------------------SVREQIESRIP
ILRNIPIVPMSCI--SGKGI---------EHVLPA-------------------------
----------------------------------------------------ALDARNRW
ARTISTGLLNRWLA-----------------------EVVTGLQPPYVA-GVRAKLKYII
QTKGR-------------------------------------------PPTFIIFSN-VK
SFPEPYLRYLTRQFQDSFE------------------------------------LYGMP
VRL
>Toc34_P.tricornutum_gnl|BL_ORD_ID|5109 gi|219124383|ref|XP_002182484.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
S-----------------------------------------------------------
------------------------------------------------------------
-----RIVVSILGPPNAGKSTLFNRLLDKAANRA-----GTAIVSNVPGTTRDRRECVGR
IGGTLFRLVDTAGV--DGERLELLAQSRRNQNGEGI------------------------
------------------------------------------------------------
--------------LMKFMMGQTLEAARQADL----VFLMFDARVGVTADLLETARWLRK
ISQREQDPAAQTALPDRQIFLLANKLEGDFWNFD-GSIVLDHLTEATRLGFGEAIPISAH
HG-EGLADIAVLIEQAAVAKRQSLGILDDDTD----------------------------
------------------------------------------------------------
----LASNDSDKD---KPLQLAILGRQNVGKSTLVNALLKQD-------RVIVGATPGLT
RDAIAVEWTWKN-------------RPVQIVDTAGIRKRSQRNH--EDAIE--DLSVEDA
LRAMKVADVAVLVLDAEARKLQRQELAIADAVLKEG------------------------
--------------------RALVVAANK----------MDLI-VERGYSKK----DFAE
-------------------------------------------------DVRAQLEARYP
ILRKTPIVPMSSL--TGDSV---------HKLMPV-------------------------
----------------------------------------------------VFRARERW
SRKISTGELNRWIA-----------------------EVMDGKPPPPVS-GRKARIKYVM
QTKGR-------------------------------------------PPTFLLFCN-VA
SLPENYLRFLTRNFQDTFE------------------------------------MFGME
VRM
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|25599 jgi|Fracy1|214794|estExt_Genewise1Plus.C_700009
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------SE------------------DIVAEFSSKA
GGGYNRPGVQWYPGHIAKAERQLSETLKAVDV----VVEVRDARACKATSHPRVGEWCA-
---------------GRPRIVVLTHLDMIPK-----------------------------
--------------AAANSWRKAYEKFGAEDMDDAP------------------------
----------------------INRQVLFVNAKQGQG-------------IHALHRAIFK
AGSHVQERRERRGLNPRALRVGIIGYPNVGKSALINKILGRK-------RAKTANTPGVT
RSLQWIR-------------------EFELLDSPGIIPAKMVD---QSDALLLAACNCIG
QAAYDNQAVAAYLYEWLKAVYLMDKQALTAPNWRDKCIDRYGFDPLEKVQRDEDDIVQDE
YLTGE---------------DMLFKVADD-------LCRGDAE-DAARKMLQ----DFRQ
------------------------------------------------------------
-----------------------------GRMGPISLQMAPESEEDGGMLSVSVGDGTIL
GRQSMRGSENGGFDAEYQQQIQDE----RARIALETAKERGLELPPI-----VDDPERA-
------KEEAEADV----------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GKGMF
DGW
>Toc34_T.oceanica_gnl|BL_ORD_ID|10226 gi|397601583|gb|EJK57948.1| hypothetical protein THAOC_21972 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------EDPNSFS
LSGYQRPKVNWYPGHIAKAERQLAETLKSVDV----VIEVRDSRAPKATAHPSVGKWAA-
---------------GRPRVVVLTRVDTVTT-----------------------------
--------------RSRETWRQAYERLGADRWQEKLAGDERNRNAQFETERRKYVDGE--
--------DGDSVKLRGAD---GVEEVLFVDAKRGQG-------------THAITRAVYR
AGRHVNERRKRRGLNDRSLRVGIIGFPNVGKSALINRLLGRK-------RAKTANTPGIT
RSLQWMRVAADKSTSASGSGSANAKKGFELLDSPGIIPSDMLD---QNDALLLAACNSVG
VGA---KIAARWGSESTDGSARSWLDFAAKNADRMPSGE---------------------
--------------------DMLFIVADN-------TCKGDPE-NAARKILQ----DFRN
------------------------------------------------------------
-----------------------------GRMGPVSLQLAPESETDEGQVHVENMRSDGL
DVRIVASPTNLKRATEEHEKRQKEEIQQRAKAAMVAAKQKGLDLPPVVESIDVDDTEQVA
AGGGADSKPSESEI----------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GKGLF
DGW
>Toc34_T.pseudonana_gnl|BL_ORD_ID|2716 gi|223994459|ref|XP_002286913.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------PKVNWYPGHIAKAERQLSETLKSVDV----VIEVRDSRAPKATAHPSVGKWTA-
---------------GRPRVVVLTRMDTVTS-----------------------------
--------------RSRDSWREAYERLGADRWEDSL------------------------
-----------------------VEEILFVDAKRGQG-------------THAISRAVYK
AGRHVNERRKRRGLNDRPLRVGIIGFPNVGKSALINRLLGKK-------RARTANTPGIT
RSLQWIR------------------SGFELLDSPGIIPSDMLD---QSDALLLAACNSIG
VGAYDNQAVAAYLCERIQSLVIMEKDYIAAPLWRNRCIERYGFDPL--------------
--------------------DMLFIVADN-------TCKGDPE-NAARKILQ----DFRM
------------------------------------------------------------
-----------------------------GRMGPISLQL---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>Toc34_P.tricornutum_gnl|BL_ORD_ID|9646 gi|219116036|ref|XP_002178813.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MPRSQGTSRKGKPGKKDRDAGMGKSLQRAQVQRYRPRADGKSRRGDGGMHMQAGVDSIGL
EEAQQDQLKTRSVLEMQDLDDFLLQADMANREFVSEKEGLVVVDQTGQAYRPPAVQWADQ
KSSFLFTELSVPRRPAWDDTTTAVELDMNERKSFLEWRRAIAIKEEELARTSSLAAATPF
E-----------------------------------------------------------
------------------------------------------------------------
--------------KNLEVWRQLWRVLERSAC----LLQLVDARNPMFYLSDDLRDYAST
L--------------GKPMMVLVNKSDYLSP-----------------------------
--------------SQRASWREYLMEKGWDPVFFSAVKEQQKLDAMANRKRIQVQLGTGH
DNSLDHLGEETDVSIDAHDQIEEPEDERGVSVPLSRERLMETMLSFARQ-----------
------HNCQPDPRYDNRIQFGMVGFPNVGKSSVINVLFGSSKHEHGVVRVAVASQPGKT
KHFQTLMLPDA--------------EEMMLCDCPGLVFPSFVS----NTADLIAAGVYPI
AQMRDHWPVTNLICQRIPREVINAHYGIVLPKPSQLEMNERGLTKLPPPSGE--------
--------------------EFLGTFCIARGMLAASSGVPDYT-RAARTIIK----DYAD
------------------------------------------------------------
-----------------------------GKLLYCHPPP---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--S
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|22594 jgi|Fracy1|214636|estExt_Genewise1Plus.C_650061
MAP------KYQNKTKRRENAIPRTGASSKI--GKGRDNAKGGHRSAETIKRLNLYKS-R
AIRNKKGTIIGGDFMMGDRAGDRDITGETGRIAPDRRW----------------------
-----FGNTRVVDP---------KQLDTFRQEMTEKVADPYSVVLKRKKLPMGLLREAAE
REA-----PPSQALLGQEPFSQVFGSKSRRKKVKLDQLMLAR------------------
-----SDVDPNKDEDED-------GAPI-------------------------KKGG---
--RAEVKADLFNKGQSKRIWGEFFKVVDCSDV----VLHIIDARNVPGTRCNMIERHIRD
NAS------------HKHLVFVLNKIDLVPN-----------------------------
--------------WVAKRWMGELAKDRPTIAFHASMT----------------------
-------------------------------HAFGKGALISLLRQFGKLHG---------
--------------DKKQISVGVIGYPNVGKSSVINTLISQK-------SCKVAPIPGET
KIWQYITLF----------------KRISLIDCPGVVVDTAGD----TETESVLKGVVRA
ERLETPEDFIQPIVDMVKREHIAGQYKFTKEESNKWTTPT--------------------
--------------------ELLETIATKAGRL-LKGGEPCLR-SASITMIN----DFQR
------------------------------------------------------------
-----------------------------GRLPHFVAPPELKEDDVEENQGNMGGSTAVI
EGVKPEAQELDKI---------------------------------------GEENTKSD
GTVDGESDQKEG--------------KETGSSGVVADEPVAIAEGEWD------------
------------------------------------------------------------
------------------------------------------------------------
--D
>Toc34_P.tricornutum_gnl|BL_ORD_ID|6857 gi|219112187|ref|XP_002177845.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MAKTGWKSGISNTSSAGKTNRTPKGNASSKLTQGRRRDKQPGSERSAETIQRLKMYSNGK
AIRNKAGKIVAGTFMMQDRAGDRKIEASTGRIQPDRRW----------------------
-----FGNTRVVGA---------TELDRFRQEMTEKVADPYSVVLKRKKLPMGLLQDAAE
YKA----GNQKAALLEQEPFDQAFGKNSRRKRVKLDQLFVQR------------------
-----AAESADSKEDIKTGE----GEAI-------------------------RSEGEGI
DWRHEKKDDLFLKGQSKRIWGEFFKVVDCSDV----VLHIIDARNVPGTRCTMIERHIAK
NAS------------HKHLVFVLNKIDLVPN-----------------------------
--------------WVAKRWMGELAAVRPTIAFHASLT----------------------
-------------------------------NAFGKGALISLLRQFGKLHE---------
--------------DKKQISVGVIGYPNVGKSSVINTLISKK-------SCKVAPIPGET
KIWQYVTLF----------------KRISLIDCPGVVVDTAGD----TEEDSVLKGVVRA
ERLENPEDFIDAIMGKVKREHIAAQYKLPKDGEETWSSSG--------------------
--------------------ELMEMIARRSGRL-LKGGDPCIR-TAALMIIN----DFQR
------------------------------------------------------------
-----------------------------GRLPHFIPPPELKVEEDQKTVATE-------
QAIQIEEQNLDDVVVVE-----------------------------------KEMEQDEE
GVETKTNDHAAI--------------ADTET--VIDTSSILIGDGKWD------------
------------------------------------------------------------
------------------------------------------------------------
--E
>Toc34_T.oceanica_gnl|BL_ORD_ID|1577 gi|397642458|gb|EJK75246.1| hypothetical protein THAOC_03037 [Thalassiosira oceanica]
MVKTGYKF-TKQQPNKGSRNMLKNSAASSRPNRTAPKRGDNGNMRSNQTIARLKMYNNGK
AIRNKEGKVVGGQFMMGDRAGDTKITAATGRIAPDRRW----------------------
-----FGNTRVVNP---------TELDRFREEMTSSMADPYSVVVKRKQLPMGLLRDAAE
LEK---AGRNNSGLLANEPFEHTFGGKSRRKRVKMEQYMVGRTSKIDDVEDKDEEDDQKP
YRGGEAETVNDMPSDDKSGYAALLAAAQKSQDTYSKVNNRVGIVPWGKDSNLTKTSGEGV
DWVHSKKDDLFLKGQSKRIWGEFYKVVDCSDV----ILHVIDARNVPGTRCTMIEKHIAK
NAP------------HKHLVFVLNKIDLVPN-----------------------------
--------------WVAKRWIGELAQIRPTIAFHASMT----------------------
-------------------------------HAFGKGALISLLRQFGKLNS---------
--------------DKKQISVGVIGYPNVGKSSVINTLISKK-------SCKVAPIPGET
KIWQYITLF----------------RNIYLIDCPGVVVDTAGD----SETDSVLKGVVRS
ERLETPEDYVDAIQDAVKREHIAAMYGLPRSGEDTWKSSE--------------------
--------------------ELCEKIAIKCGRL-RKGGEPCLR-SAAIMIIN----DFQR
------------------------------------------------------------
-----------------------------GRLPHYVAPPELKEEDSGEGAAAV-ADTANI
EGVELAAQNLDEVTRDR-----------------------------------AEDSAEGQ
RSDTKEETSEKIEKKDGIAEDAGDVEADEDA--GSDDDEVVIGDGDWE------------
------------------------------------------------------------
------------------------------------------------------------
---
>Toc34_T.pseudonana_gnl|BL_ORD_ID|4381 gi|224003191|ref|XP_002291267.1| predicted protein [Thalassiosira pseudonana CCMP1335]
--------------------------------------KADSNMRSSATIARLKMYNNGK
AIRNKEGKVVGGQFMMADRAGDSKITAATGRIAPDRRW----------------------
-----FGNTRVVAP---------TELDAFREEMTQSMADPYSVVIKRKQLPMGLLKDAAE
LQAKHGGTNSSAGLLLNEPFEHAFGTKSRRKRVKVEQFMVGN------------------
-----AETLANLPDDDATGYKSLLAAAQ-------------------------KTSGEGV
DWRTEKKDDLFLKGQSKRIWGEFYKVLDCSDV----ILHIIDARNVPGTRCTMIEKHIAK
NAP------------HKHLVFVLNKIDLVPN-----------------------------
--------------WVAKRWIGELAQIRPTIAFHASMT----------------------
-------------------------------HAFGKGALISLLRQFGKLAS---------
--------------DKKQISVGVIGYPNVGKSSVINTLISKK-------SCKVAPVPGET
KIWQYITLF----------------RNIYLIDCPGVVVDTAGD----TEIDSVLKGDVRA
ERLECPEDFIDAIQAAVKREHIAAMYGVPKSGDDTWSTSI--------------------
--------------------ELLEKISIKCGRL-KKGGEPCLR-SSAITLIN----DFQR
------------------------------------------------------------
-----------------------------GRLPHYVAPPE--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>Toc34_T.oceanica_gnl|BL_ORD_ID|33149 gi|397569214|gb|EJK46603.1| hypothetical protein THAOC_34725 [Thalassiosira oceanica]
M--------------------VKKKGKSKRITLKDKYKIQRRVVETHRKNRKQAKRDAKA
GIVRHDKKKDPGIPNSWPFKQELLQSIQREKERAENRK------------------LEEK
ERRVNKNGAANLEELVKQANQKKSEFDAKTGSSSAASDDGIKIVTTSHGQQ---------
------------------------------------------------------------
------------------------------------------------------------
--------------SRRAYLRSLKTVIESSDV----ILQVLDARDPLGTRI---------
---SSGIEASILSHFDKRMVLVMNKIDLIPK-----------------------------
--------------KNVSEWLTYLRRSHPTVALKAGTTQSRSNEGGRSSGVGQTKG----
------------------------ENALSSSMAVGVDGLLQLLKNY--------------
------ARANGEKKSKTSITVGIIGYPNVGKSSILNSLKRFR-------AVGVSSRPGFT
TTLQEVVLD----------------KNIRLIDSPGVVFDDDAS---RDGANAMLRNGVDA
DSVSDPLPAIAELLGRCTSESLMMTYSVPAFPPGPEGVL---------------------
--------------------TFLAMVARSKGRV-LKGGIPDKM-MAARLVMR----DWNQ
------------------------------------------------------------
-----------------------------GKIPYFSTPPVTEVEM---------------
----------------------------------------------------GDTSAGST
HAKIVSKFSEEFDVSKIMAAHDKELMNGLEDVDEMDFVQMTSSSRPRGEGSADKVVKYLH
EGGDQNSDSEM-----------------------------------------------EG
DDDAVALNTRMEEAEDFFG-----------------------------------------
--E
>Toc34_F.cylindrus_GMF2_gnl|BL_ORD_ID|13155 jgi|Fracy1|162596|gw1.1.2020.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------EVAFLGRSNVGKSSLINAIMRKN-------LCITSKSPGRT
QLPYYYGNPSGQ-------------PQGFIVDLPGYGFAKKPMSITEDWQKDTQDLLLHR
RHEAKVLKRLFLLMDARRG--VQGPNEHDRIVMRWLEDAE--------------------
--------------------IPFTVVLTK----------ADRV-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--S
>Toc34_C.merolae gi|449018483|dbj|BAM81885.1| similar to chloroplast outer membrane protein Toc34 [Cyanidioschyzon merolae strain 10D]
M-----------------------------------------------------------
------------------------------------------------------------
----------------------DSETPTKNEAEQRASPDRTGQVTQRPV-----------
------------------------------------------------------------
------------------------------------------------------------
--------------SLFRKNGTFAYPLEDSDVYEEQVLALEDVPEPTAQAILRLA-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------LAAERQGVPRLRFLVVGAPGVGKSSLINTLLNEN-------LCSVSAWERGT
KNAQVCARQVDS-------------VVIEFIDTPGIAPCRRSG-------------LEAS
RRQVQRLRKLLDARGADEHPYLRSF-----------------------------------
--------------------HAILYVMRL------DDTRPDLVDYHNWKVLM----EFFG
----------------------------------------------------------AE
VLRHMMVVFTHGQSLPPDSLSYPEYVRGRRDYVYLLIERLTGPLKAVRFPVFVAENSSKC
PVIEETGERKLPDDTPWITQLYDGIRRFVFPLEADLFGMETGPEDTQVLVYIYDKRRSRA
DERYPRSPLQALIRNPWFLRAVQFCGAMLLRSYMIRQEHERFNPKPHHPEPIIRDANNAF
AVASRRANDHRLFTPSIDEDEESFFRMNGNDDFVSRLRNRPGEVDLDELDVERIESPDGR
FVEYWYTEKDNPEMVRMYR------LEIRDDPNEERESRQDRIPISKDQ-----------
--H
