>Toc159_T.oceanica_gnl|BL_ORD_ID|24856 gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------FGIRRLVVGGSVRHGGHARGRPLPCPACPTGPDI
SSSASSLLSRTMTSYFDGGPSAPET--SRPK----QQRRLDIAIVGAPNAGKSQLLNSLV
GSK-------VAAVSRKRHTTRSGILGARTFGD-------------TQLVFIDTPGFLHH
SKGAREGV------RNLLSEASAE-----MMNAD----FALLVVDAAKT---IDQDLKRT
LVTLMMLALRSTGREE------------GSRVFSDQRHL------------GRFSVVLNK
VDLV-KPKEKLLATAAEVGSLAESCVRRLLQQHRAPVRVKMGELVDSVLERHEDEEGFAG
VHEEDYETFASVV-PEFLFTSAIDPEDEGA---------DDLLNVLLSRATPSTEFVMDP
SSN-----LEQVEEIIREKI----------------YRCLHREVPHHVQQTNRVFKL---
---KQDQPPDHDVRADMGDLLQIHQDLI--------------------------------
VRTKSHHRLVLGS-GGKTLQRIQTTASKDLRELF-------GCE----------------
--------------------------VDLLLSVKLKKTNQ-GVLLDPEEEGA-RITTLHD
----
>Toc34_T.oceanica_gnl|BL_ORD_ID|24856 gi|397590707|gb|EJK55129.1| hypothetical protein THAOC_25171 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------FGIRRLVVGGSVRHGGHARGRPLPCPACPTGPDI
SSSASSLLSRTMTSYFDGGPSAPET--SRPK----QQRRLDIAIVGAPNAGKSQLLNSLV
GSK-------VAAVSRKRHTTRSGILGARTFGD-------------TQLVFIDTPGFLHH
SKGAREGV------RNLLSEASAE-----MMNAD----FALLVVDAAKT---IDQDLKRT
LVTLMMLALRSTGREE------------GSRVFSDQRHL------------GRFSVVLNK
VDLV-KPKEKLLATAAEVGSLAESCVRRLLQQHRAPVRVKMGELVDSVLERHEDEEGFAG
VHEEDYETFASVV-PEFLFTSAIDPEDEGA---------DDLLNVLLSRATPSTEFVMDP
SSN-----LEQVEEIIREKI----------------YRCLHREVPHHVQQTNRVFKL---
---KQDQPPDHDVRADMGDLLQIHQDLI--------------------------------
VRTKSHHRLVLGS-GGKTLQRIQTTASKDLRELF-------GCE----------------
--------------------------VDLLLSVKLKKTNQ-GVLLDPEEEGA-RITTLHD
----
>Toc159_T.pseudonana_gnl|BL_ORD_ID|10627 gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------AFFRRALLQGSLAVNNLTHDTWHQTPRAITSLLN
HQQSCSLHSTPITLNNPTSSSAATTQSDKPA----PQKRLDVAIVGAPNAGKSQLLNSLI
GSK-------VAAVSRKRHTTRTGILGARTFDD-------------TQLVFIDTPGFLHH
EMSVKEGV------RKLLGEASSE-----MESAD----FVLLVVDAARK---MEDDLRRT
LVTLMFLALRSKGRNE-------------------------------------FAVVLNK
VDLV-SPKEKLLMTAADVGSMAESCIRQFLNQRRSPSKVKFGELVDTVLKNYANEDGFDG
VHDDDIELFATLA-PEFFFTSAIVKDDEGV---------DDVLGLLLERATLSDQWIVDA
GSATGMTPVEQVEEIIREKI----------------YRCLHREVPHSVQQQNRMFQLYKP
NESKTKSTDGSDVDEDI-KILRIRQDLI--------------------------------
VRTKSHQRLVLGS-GGKTLERIRSTALKDLEESF-------DCI----------------
--------------------------VDLDLTVRVTKSNQHEAILDPESVGAVSLTPLEN
----
>Toc34_T.pseudonana_gnl|BL_ORD_ID|10627 gi|224003597|ref|XP_002291470.1| gtp-binding protein [Thalassiosira pseudonana CCMP1335]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------AFFRRALLQGSLAVNNLTHDTWHQTPRAITSLLN
HQQSCSLHSTPITLNNPTSSSAATTQSDKPA----PQKRLDVAIVGAPNAGKSQLLNSLI
GSK-------VAAVSRKRHTTRTGILGARTFDD-------------TQLVFIDTPGFLHH
EMSVKEGV------RKLLGEASSE-----MESAD----FVLLVVDAARK---MEDDLRRT
LVTLMFLALRSKGRNE-------------------------------------FAVVLNK
VDLV-SPKEKLLMTAADVGSMAESCIRQFLNQRRSPSKVKFGELVDTVLKNYANEDGFDG
VHDDDIELFATLA-PEFFFTSAIVKDDEGV---------DDVLGLLLERATLSDQWIVDA
GSATGMTPVEQVEEIIREKI----------------YRCLHREVPHSVQQQNRMFQLYKP
NESKTKSTDGSDVDEDI-KILRIRQDLI--------------------------------
VRTKSHQRLVLGS-GGKTLERIRSTALKDLEESF-------DCI----------------
--------------------------VDLDLTVRVTKSNQHEAILDPESVGAVSLTPLEN
----
>Toc159_F.cylindrus_GMF1_gnl|BL_ORD_ID|11386 jgi|Fracy1|187133|e_gw1.7.947.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------F-KNAVLFPQRRARTWLWNNS--NTTTDACRANLSYAIERCCS
SSSSSSSSQSQSQ----SQSQSQST--LQQSPSTIGRKRLDVAIVGAPNAGKSQLVNILT
QSP-------VAAVSRKRHTTRSDILGARTIGN-------------TQIVFKDTPGFMRI
ENAKEERLD-----RDLIATAASE-----MQDVD----FTLLVIDSARA---LSENYRHA
-------------------DDDANPNSNDGR--------------------GKFAIVLNK
VDLV-KPKSTLIDLAMEIGAIADTCLEDHFTEH-------------------GKT--I--
----DFEAMLEHS-PIVFYVSAL--KEDGT---------DDLLDHLINLATPCKEWAVQS
GQSTNMTELEQVQEIIREKI----------------YRTCHREVPHSVQQVNRMFRKIP-
-------------KKG----VIIHQDLV--------------------------------
VFTKSHQKLVLGA-GGRTLERIRESAQTDLRKMF-------KCE----------------
--------------------------VSLHLHVK--KKIGRRGDSGTEYKLG-EASQTIL
----
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|11386 jgi|Fracy1|187133|e_gw1.7.947.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------F-KNAVLFPQRRARTWLWNNS--NTTTDACRANLSYAIERCCS
SSSSSSSSQSQSQ----SQSQSQST--LQQSPSTIGRKRLDVAIVGAPNAGKSQLVNILT
QSP-------VAAVSRKRHTTRSDILGARTIGN-------------TQIVFKDTPGFMRI
ENAKEERLD-----RDLIATAASE-----MQDVD----FTLLVIDSARA---LSENYRHA
-------------------DDDANPNSNDGR--------------------GKFAIVLNK
VDLV-KPKSTLIDLAMEIGAIADTCLEDHFTEH-------------------GKT--I--
----DFEAMLEHS-PIVFYVSAL--KEDGT---------DDLLDHLINLATPCKEWAVQS
GQSTNMTELEQVQEIIREKI----------------YRTCHREVPHSVQQVNRMFRKIP-
-------------KKG----VIIHQDLV--------------------------------
VFTKSHQKLVLGA-GGRTLERIRESAQTDLRKMF-------KCE----------------
--------------------------VSLHLHVK--KKIGRRGDSGTEYKLG-EASQTIL
----
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|20621 jgi|Fracy1|254023|fgenesh2_pg.52_#_25
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------FKNAVLFPQRRARTWLWNNS----------------------
-----------------------------------NTTTLDVAIVGAPNAGKSQLVNILT
QSP-------VAAVSRKRHTTRSDILGARTIGN-------------TQIVFKDTPGFMRI
ENAKEERLD-----RDLIATAASE-----MQDVD----FTLLVIDSARA---LSENYRHA
FVELK-------------------------------------------------------
---------NLLGMIRD-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc159_Pn.multiseries_gnl|BL_ORD_ID|138163 jgi|Psemu1|186266|e_gw1.57.139.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------RKIAGATV-KEASLVLRRYHRPALGNSSIIGGNTGWLSSQASSRVKFLSS
SSPSSTRRQSPPA----SRPQAAAT--AQNR----TRKRLDVAIVGPPNAGKSQLVNVLT
KSP-------IAAVSRKRHTTRSDLLGARTVGN-------------TQIVFKDTPGFLRI
ENAKEERLD-----RDLIATAASE-----MQDVD----FTLLVLDSART---LSDNYRHA
LVQLMVGAINSGGRIEDCDDDDDNNDRKTTRQSREDINPSSKCDTAIPSDKSKFAIVLNK
VDLV-KPKTDLISLAMDVGTMADTCLLDQFQKQ-------------------GRE--F--
----DFDAQMEQS-PIVFYVSAL--KEDGT---------DDLLEHLLGLATPSREWPVEP
GKATNMTTLEQVQEVIREKI----------------YRSTHKEVPHAVQQVNRLFRRIP-
-------------NKG----VVIHQDLV--------------------------------
VFTKSHQKLVLGSGGGKTLKRIQESARHDLQKLF-------GCD----------------
--------------------------VALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
----
>Toc34_Pn.multiseries_gnl|BL_ORD_ID|138163 jgi|Psemu1|186266|e_gw1.57.139.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------RKIAGATV-KEASLVLRRYHRPALGNSSIIGGNTGWLSSQASSRVKFLSS
SSPSSTRRQSPPA----SRPQAAAT--AQNR----TRKRLDVAIVGPPNAGKSQLVNVLT
KSP-------IAAVSRKRHTTRSDLLGARTVGN-------------TQIVFKDTPGFLRI
ENAKEERLD-----RDLIATAASE-----MQDVD----FTLLVLDSART---LSDNYRHA
LVQLMVGAINSGGRIEDCDDDDDNNDRKTTRQSREDINPSSKCDTAIPSDKSKFAIVLNK
VDLV-KPKTDLISLAMDVGTMADTCLLDQFQKQ-------------------GRE--F--
----DFDAQMEQS-PIVFYVSAL--KEDGT---------DDLLEHLLGLATPSREWPVEP
GKATNMTTLEQVQEVIREKI----------------YRSTHKEVPHAVQQVNRLFRRIP-
-------------NKG----VVIHQDLV--------------------------------
VFTKSHQKLVLGSGGGKTLKRIQESARHDLQKLF-------GCD----------------
--------------------------VALQLHVKYRKSKQQRGDSGAQYNLG-EVSQSVY
----
>Toc159_P.tricornutum_gnl|BL_ORD_ID|6794 gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RPTFIRTALVTFRWSGGPKISRSDRV
RLSSTTIGST-----------------PSLE----DRKRLDVAIVGLPNAGKSQLLNVLT
QST-------VAAVSRKRHTTRDGILGARTVDD-------------TQLYFVDTPGFLRQ
SQAKKEGLN-----RDLVVTASSE-----MENVD----FSLLVVDAARR---MTDDYEET
LVALMLAALRSQGRLE--FDVHSAEEVQSIRTPKGGTNP------------AKFAVVLNK
VDLV-HPKSNLMDLAVNIGTLAEQCIKFDAKES-------------------GKEELF--
----LDSAYLQESLPMFFYISAL--KQRGV---------QDLLEFLLERATPSTSWEVEA
GEATPMTMKERIEEVIREKI----------------YRCLHKEVPHSIRQENRVLQQGK-
-------------DEDGNIVLVIHQDLI--------------------------------
VRSKSHQELVHGG-GGRTLERIRETAARGLEKIF-------FCN----------------
--------------------------VVLHLHVKLPRSKNQRWSI---------------
----
>Toc34_P.tricornutum_gnl|BL_ORD_ID|6794 gi|219112517|ref|XP_002178010.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RPTFIRTALVTFRWSGGPKISRSDRV
RLSSTTIGST-----------------PSLE----DRKRLDVAIVGLPNAGKSQLLNVLT
QST-------VAAVSRKRHTTRDGILGARTVDD-------------TQLYFVDTPGFLRQ
SQAKKEGLN-----RDLVVTASSE-----MENVD----FSLLVVDAARR---MTDDYEET
LVALMLAALRSQGRLE--FDVHSAEEVQSIRTPKGGTNP------------AKFAVVLNK
VDLV-HPKSNLMDLAVNIGTLAEQCIKFDAKES-------------------GKEELF--
----LDSAYLQESLPMFFYISAL--KQRGV---------QDLLEFLLERATPSTSWEVEA
GEATPMTMKERIEEVIREKI----------------YRCLHKEVPHSIRQENRVLQQGK-
-------------DEDGNIVLVIHQDLI--------------------------------
VRSKSHQELVHGG-GGRTLERIRETAARGLEKIF-------FCN----------------
--------------------------VVLHLHVKLPRSKNQRWSI---------------
----
>Toc159_F.cylindrus_GMF1_gnl|BL_ORD_ID|17946 jgi|Fracy1|190835|e_gw1.11.594.1
MNTNTTTITNVNNDDHQQ------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------QHRCGYAGIVGAPNMGKSTLLNSLL
KED-------LCIATRRPQTTRHAILGVLSSPT-------------KQCCLLDTPGVLQG
DGAYQLQ-------ANMMEAVKGA-----LTDSD----MIVVVTDLFST-PIPDDNVFRR
LSETT----------------------------------------------KPVLVVVNK
IDLE-GRAKRPDE------------ATIQRRP----------------------------
--------------IP------------GMFRNGVKSLTNDDVKQLLPIGPPLYDDDFLS
DRSVRFFCSELIREALLESR------------------YLKKELPYCCEVQITDYKE---
-------------PRDD-NITRIEATIF--------------------------------
VERDGQKAIIIGK-NGDVVKQVGIIAREKIERFL------DGEK----------------
--------------------------VFLQLRVKINKDWRKREDQLAKFGY---SN----
----
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|17946 jgi|Fracy1|190835|e_gw1.11.594.1
MNTNTTTITNVNNDDHQQ------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------QHRCGYAGIVGAPNMGKSTLLNSLL
KED-------LCIATRRPQTTRHAILGVLSSPT-------------KQCCLLDTPGVLQG
DGAYQLQ-------ANMMEAVKGA-----LTDSD----MIVVVTDLFST-PIPDDNVFRR
LSETT----------------------------------------------KPVLVVVNK
IDLE-GRAKRPDE------------ATIQRRP----------------------------
--------------IP------------GMFRNGVKSLTNDDVKQLLPIGPPLYDDDFLS
DRSVRFFCSELIREALLESR------------------YLKKELPYCCEVQITDYKE---
-------------PRDD-NITRIEATIF--------------------------------
VERDGQKAIIIGK-NGDVVKQVGIIAREKIERFL------DGEK----------------
--------------------------VFLQLRVKINKDWRKREDQLAKFGY---SN----
----
>Toc159_P.tricornutum_gnl|BL_ORD_ID|696 gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MGAPNMGKSTLLNALL
EED-------LCIATARPQTTRHAILGLMSTDK-------------CQVCLVDTPGVIE-
DPAYELQ-------EGMMEAVTGA-----VATSD----VLLVVTDVFST-PIPDDELFLK
VQRTR----------------------------------------------KPVLVAINK
IDLA-KKVNKAAEENRDKTVTVEEAVAFWRAQ----------------------------
--------------LPNALCILPLSASQGINNVGVVAM-RRILTELLPISPPLYDPETLT
DRPERFIASEIVRSALFQ--------------------VLKKELPYCCEVRIREFKE---
-------------PKEEGEVIRIAADVL--------------------------------
VERDSQKVIVIGK-NGAQVKEIGVIAREKLEAFF------R-HQ----------------
--------------------------IFLNLSVKVDKDWRKNTRKLTEYGYMKPKR----
----
>Toc34_P.tricornutum_gnl|BL_ORD_ID|696 gi|219124036|ref|XP_002182319.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MGAPNMGKSTLLNALL
EED-------LCIATARPQTTRHAILGLMSTDK-------------CQVCLVDTPGVIE-
DPAYELQ-------EGMMEAVTGA-----VATSD----VLLVVTDVFST-PIPDDELFLK
VQRTR----------------------------------------------KPVLVAINK
IDLA-KKVNKAAEENRDKTVTVEEAVAFWRAQ----------------------------
--------------LPNALCILPLSASQGINNVGVVAM-RRILTELLPISPPLYDPETLT
DRPERFIASEIVRSALFQ--------------------VLKKELPYCCEVRIREFKE---
-------------PKEEGEVIRIAADVL--------------------------------
VERDSQKVIVIGK-NGAQVKEIGVIAREKLEAFF------R-HQ----------------
--------------------------IFLNLSVKVDKDWRKNTRKLTEYGYMKPKR----
----
>Toc159_T.oceanica_gnl|BL_ORD_ID|14494 gi|397643422|gb|EJK75853.1| hypothetical protein THAOC_02405 [Thalassiosira oceanica]
MK-----------------GSIRMAHVGALMMFA-------TTACRGFRRSS---QSATP
KSTNRHITVLSQYCGIRDEVRRRNLIVGPSLQTVASRRRRATARLGPLHTPLQSTLYDLE
EKESTASTSDEDTVFALSSGSG---VTAVAVIRISGRNAFDALKQLLSPYSLEAGAEPPK
LPTPRMASLRILYDPLS----SSDHLNRM----RDPLDSALVLIFPGPRSFTGEDIVELH
CHGSRAVTSGVLKALSSLDS------VRPADPGEFTQRAYGN-------GKLGLVEVEAL
ADLIVADTSLQRKQALQQFDG-----------------------RLSRLYLGWR------
------------------------------------------------------------
-KELIKGLAHAEA----VIDFGDDEALGEE--DS--------------------------
------------------------------------------------------------
---------------------------------SFDS-SENDGGMSVWADVRPRISSLRE
AMDRHLEDASRGEL---------------------LRDGLRIAIVGRPNAGKSSLLNLLA
GRD-------AAIVSSTPGTTRDVVEVVLDLDG-------------VRCSLLDTAGVREE
IEDGVDEIE-----IEGMKRARLA-----AQEAH----LIVGVVDCSDQ-KRGLEAVQEL
IRADGHSDSARS-SPH-----------------------------------NNLLYVLNK
RDLF-EGEMEPCG-----------------------------------------------
----------VD----SETFAISCTTNQGV---------DIFLAALSKRALAM----ISQ
EGDSSGDLSVV----GTEGA--------------VITRARHRRHVEAASDALQRFEVLSS
QGYMALDMAAEELRLASSELGRVTGAID--------------------------------
VEDVLDVLFADFCIGK--------------------------------------------
------------------------------------------------------------
----
>Toc34_T.oceanica_gnl|BL_ORD_ID|14494 gi|397643422|gb|EJK75853.1| hypothetical protein THAOC_02405 [Thalassiosira oceanica]
MK-----------------GSIRMAHVGALMMFA-------TTACRGFRRSS---QSATP
KSTNRHITVLSQYCGIRDEVRRRNLIVGPSLQTVASRRRRATARLGPLHTPLQSTLYDLE
EKESTASTSDEDTVFALSSGSG---VTAVAVIRISGRNAFDALKQLLSPYSLEAGAEPPK
LPTPRMASLRILYDPLS----SSDHLNRM----RDPLDSALVLIFPGPRSFTGEDIVELH
CHGSRAVTSGVLKALSSLDS------VRPADPGEFTQRAYGN-------GKLGLVEVEAL
ADLIVADTSLQRKQALQQFDG-----------------------RLSRLYLGWR------
------------------------------------------------------------
-KELIKGLAHAEA----VIDFGDDEALGEE--DS--------------------------
------------------------------------------------------------
---------------------------------SFDS-SENDGGMSVWADVRPRISSLRE
AMDRHLEDASRGEL---------------------LRDGLRIAIVGRPNAGKSSLLNLLA
GRD-------AAIVSSTPGTTRDVVEVVLDLDG-------------VRCSLLDTAGVREE
IEDGVDEIE-----IEGMKRARLA-----AQEAH----LIVGVVDCSDQ-KRGLEAVQEL
IRADGHSDSARS-SPH-----------------------------------NNLLYVLNK
RDLF-EGEMEPCG-----------------------------------------------
----------VD----SETFAISCTTNQGV---------DIFLAALSKRALAM----ISQ
EGDSSGDLSVV----GTEGA--------------VITRARHRRHVEAASDALQRFEVLSS
QGYMALDMAAEELRLASSELGRVTGAID--------------------------------
VEDVLDVLFADFCIGK--------------------------------------------
------------------------------------------------------------
----
>Toc159_T.pseudonana_gnl|BL_ORD_ID|7596 gi|224013676|ref|XP_002296502.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
LPNARMASLRTLYDPTADAKGTSDDEEEMQQQKRDPLDSALVLTFEGPNSFTGEDIVELH
CHGSRAVVHGVLSALSSLSSRAIPLQLRPADPGEFTQRAYAH-------GKLGLVEVEAL
ADLIVADTSLQRKQALQQFDG-----------------------RLSRLYGGWR------
------------------------------------------------------------
-EELIKGLAHAEA----VIDFGDDEALDAH--DE--------------------------
------------------------------------------------------------
---------------------------------FDDGLNANDGGMSIWGTIAPRIRSLRQ
AMNRHLADASRGEL---------------------LRDGLRIAIVGRPNAGKSSLLNLLA
GRD-------AAIVSSSPGTTRDVVEVMLDLGG-------------VRCTLLDTAGVREE
KEEGVNEIE-----VEGMKRARRA-----ARDAH----IIVGVVDATDL-SRGLEAVDEL
IRVESESDESSSLLNR-----------------------------------DNVLYVLNK
LDLV-EGNENSINSKEQ-------------------------------------------
----------SN----SPKFGISCTTSEGV---------DDFLSSLTQQALSL----VSG
DRD--------------EGA--------------VITRARHRRHVEAASDALERFEELSG
QGYMALDMAAEELRLASSELGRVTGAID--------------------------------
VEDVLDVLFADFCIGK--------------------------------------------
------------------------------------------------------------
----
>Toc34_T.pseudonana_gnl|BL_ORD_ID|7596 gi|224013676|ref|XP_002296502.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
LPNARMASLRTLYDPTADAKGTSDDEEEMQQQKRDPLDSALVLTFEGPNSFTGEDIVELH
CHGSRAVVHGVLSALSSLSSRAIPLQLRPADPGEFTQRAYAH-------GKLGLVEVEAL
ADLIVADTSLQRKQALQQFDG-----------------------RLSRLYGGWR------
------------------------------------------------------------
-EELIKGLAHAEA----VIDFGDDEALDAH--DE--------------------------
------------------------------------------------------------
---------------------------------FDDGLNANDGGMSIWGTIAPRIRSLRQ
AMNRHLADASRGEL---------------------LRDGLRIAIVGRPNAGKSSLLNLLA
GRD-------AAIVSSSPGTTRDVVEVMLDLGG-------------VRCTLLDTAGVREE
KEEGVNEIE-----VEGMKRARRA-----ARDAH----IIVGVVDATDL-SRGLEAVDEL
IRVESESDESSSLLNR-----------------------------------DNVLYVLNK
LDLV-EGNENSINSKEQ-------------------------------------------
----------SN----SPKFGISCTTSEGV---------DDFLSSLTQQALSL----VSG
DRD--------------EGA--------------VITRARHRRHVEAASDALERFEELSG
QGYMALDMAAEELRLASSELGRVTGAID--------------------------------
VEDVLDVLFADFCIGK--------------------------------------------
------------------------------------------------------------
----
>Toc159_P.tricornutum_gnl|BL_ORD_ID|9918 gi|219114453|ref|XP_002176397.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MRMTTQRCYSTQHSRHFSFQSIRIPHVLLAMVVSAWFGSQPTRTVRAFPLTQWRCHSVRR
NTNCRHVSHLS---------FQRN--------TVFKEHTRTKRVLIPSTTRRYSSVNDVD
MTTTVATTSSQDTIFALSSGAATGQATAVAVIRLSGPQA-GVILQRLTP------GRP--
LPKPRTAALRKLHD--------LDDPKVV-------LDQALVLYFSGPNSFTGDDVVELQ
VHGSRAVVTAVLETLGTA--------ARLAEPGEFTQRAWLA-------GKLDALQVEAL
ADLLTADTATQRQQALAQLDG-----------------------QLSAVYDTWR------
------------------------------------------------------------
-DMLVAGLAHAEA----VIDFGDDERLDDALLDE--------------------------
------------------------------------------------------------
---------------------------------EDQQLAQD----NVWGGVVGNMEVLER
SMRRQLQDARRGEL---------------------VRQGLQIAIVGPPNAGKSSLFNILA
DRD-------AAIVSPTAGTTRDVLELSLNLGG-------------VKCVLQDTAGVRTF
TDDA---IE-----MEGIARATRA-----AAQAD----LVLAMVDSSDV-ESGLEILTTI
L-------QNSPNLDR-----------------------------------QHVLLLLNK
SDLR-EEKHQTIEVPGK-------------------------------------------
----------DVVELIGGQYEISCATQNGV---------DTFLESLTRICVAR----VSN
TDASDRDKTSIVDRETSEGT--------------LITRARHRQHVQAAVEALERFQTLSQ
QGTMSVDLAAEELRLAASELGRITGAVD--------------------------------
VEDVLDKLFADFCIGK--------------------------------------------
------------------------------------------------------------
----
>Toc34_P.tricornutum_gnl|BL_ORD_ID|9918 gi|219114453|ref|XP_002176397.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MRMTTQRCYSTQHSRHFSFQSIRIPHVLLAMVVSAWFGSQPTRTVRAFPLTQWRCHSVRR
NTNCRHVSHLS---------FQRN--------TVFKEHTRTKRVLIPSTTRRYSSVNDVD
MTTTVATTSSQDTIFALSSGAATGQATAVAVIRLSGPQA-GVILQRLTP------GRP--
LPKPRTAALRKLHD--------LDDPKVV-------LDQALVLYFSGPNSFTGDDVVELQ
VHGSRAVVTAVLETLGTA--------ARLAEPGEFTQRAWLA-------GKLDALQVEAL
ADLLTADTATQRQQALAQLDG-----------------------QLSAVYDTWR------
------------------------------------------------------------
-DMLVAGLAHAEA----VIDFGDDERLDDALLDE--------------------------
------------------------------------------------------------
---------------------------------EDQQLAQD----NVWGGVVGNMEVLER
SMRRQLQDARRGEL---------------------VRQGLQIAIVGPPNAGKSSLFNILA
DRD-------AAIVSPTAGTTRDVLELSLNLGG-------------VKCVLQDTAGVRTF
TDDA---IE-----MEGIARATRA-----AAQAD----LVLAMVDSSDV-ESGLEILTTI
L-------QNSPNLDR-----------------------------------QHVLLLLNK
SDLR-EEKHQTIEVPGK-------------------------------------------
----------DVVELIGGQYEISCATQNGV---------DTFLESLTRICVAR----VSN
TDASDRDKTSIVDRETSEGT--------------LITRARHRQHVQAAVEALERFQTLSQ
QGTMSVDLAAEELRLAASELGRITGAVD--------------------------------
VEDVLDKLFADFCIGK--------------------------------------------
------------------------------------------------------------
----
>Toc159_F.cylindrus_GMF2_gnl|BL_ORD_ID|3483 jgi|Fracy1|196010|e_gw1.26.139.1
M-----------------------PTPIS-------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------TQPIRRYRSLKKEPLVAILGRPNVGKSAFVNRI
C--------GTQNGGAIVADEEGITRDRTYRDANFLGENFQV-------VDTGGLVFADD
ESTLFAREI------------------------------------R--------------
------------------------------------------------------------
-EQAMVAIDESSG----VVLVVDGKIGMTAMDQQ-IAEFLRKDVLSR----------NLP
VILAVNKCESETVGALNA-------------------AEFWNLGL---------------
----------GEPIPVSALHGV-----------------------GTAEVLERLFEEIKQ
KQSAALPGFGTKDALAAFD--------EL-E----RPEEINVAIVGRPNVGKSSLLNALF
GDQ-------RAIVSKMAGTTRDSIDAVMER-PGDNEGDLP-----TIYRFVDTAGIRRR
AKV----EYGPE--FFMVNRALRA-----IRRAD----VVLLVMDATAG--VTEQDRILA
QKIADDG--------------------------------------------RACAIICNK
WDAV-VDKDSSTYDKSV------------------KYIRAEMPQIRW-------------
--------------APILFISAE--TGQRV---------GKIYNVVD----------DAI
GAHRKRISTSVLNEVLRDAILWQPPPA--------RRNGAQAKIYYCNQVSTR-------
-----------------------PPTIV--------------------------------
VFCNDPKL------VNDNYKRYLDRKFRESLDGF------EATP----------------
--------------------------VRWIFRGRRARDIMRAKDMNGNPGDGGKGVSYPF
PHAD
>Toc34_F.cylindrus_GMF2_gnl|BL_ORD_ID|3483 jgi|Fracy1|196010|e_gw1.26.139.1
M-----------------------PTPIS-------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------TQPIRRYRSLKKEPLVAILGRPNVGKSAFVNRI
C--------GTQNGGAIVADEEGITRDRTYRDANFLGENFQV-------VDTGGLVFADD
ESTLFAREI------------------------------------R--------------
------------------------------------------------------------
-EQAMVAIDESSG----VVLVVDGKIGMTAMDQQ-IAEFLRKDVLSR----------NLP
VILAVNKCESETVGALNA-------------------AEFWNLGL---------------
----------GEPIPVSALHGV-----------------------GTAEVLERLFEEIKQ
KQSAALPGFGTKDALAAFD--------EL-E----RPEEINVAIVGRPNVGKSSLLNALF
GDQ-------RAIVSKMAGTTRDSIDAVMER-PGDNEGDLP-----TIYRFVDTAGIRRR
AKV----EYGPE--FFMVNRALRA-----IRRAD----VVLLVMDATAG--VTEQDRILA
QKIADDG--------------------------------------------RACAIICNK
WDAV-VDKDSSTYDKSV------------------KYIRAEMPQIRW-------------
--------------APILFISAE--TGQRV---------GKIYNVVD----------DAI
GAHRKRISTSVLNEVLRDAILWQPPPA--------RRNGAQAKIYYCNQVSTR-------
-----------------------PPTIV--------------------------------
VFCNDPKL------VNDNYKRYLDRKFRESLDGF------EATP----------------
--------------------------VRWIFRGRRARDIMRAKDMNGNPGDGGKGVSYPF
PHAD
>Toc159_P.tricornutum_gnl|BL_ORD_ID|7302 gi|219109543|ref|XP_002176526.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MKSVLCGVTLACGGIWQANSFTFRPLPVTRPVIGLLATLDRVNEKSTVEPS---------
------------------------------------------------------------
------------------------------------------------------------
----------------------SGDPQLQPIRRLRQNKKEPLIAIVGRPNVGKSALVNRI
A--------GSQSGGAIVADESGITRDRTYRPAEFLGERFMI-------VDTGGLVFDDD
ESTLFAKEI------------------------------------R--------------
------------------------------------------------------------
-EQAMVAIEESAA----VIMVVDGQTGLTGMDLM-IAEFLRKEV-------------DIP
VHVAVNKCESEKTGAMSA-------------------ADFWGLGL---------------
----------GEPFPVSALHGV-----------------------GTAEIMETIFDSIAE
KKT--------------FD--------AE-D----RPEEINIAIIGRPNVGKSSLLNSIF
GDT-------RAIVSEMAGTTRDSIDAVMERPPPPGSDDLS-----TIYRFVDTAGIRRK
GKV----DFGPE--FFMVNRALRA-----IRRAD----VVLLILDATSG--VAEQDRVLA
QKIADDG--------------------------------------------RACVIVCNK
WDAV-VDKDSTTYDKSV------------------QYFREELPMIRW-------------
--------------APILFISAA--TGQRV---------GKIYSAID----------GAI
EAHRKRISTAILNEVLRDAILWQPPPT--------RRNGSQAKIYYCNQVSTR-------
-----------------------PPTVV--------------------------------
VFCNDPKL------VNDNYRRYLDRKFRESLDGF------EATP----------------
--------------------------IRWIFRGRRVRDVMRNRSMNGDPGDGGTGVSFPF
PHAD
>Toc34_P.tricornutum_gnl|BL_ORD_ID|7302 gi|219109543|ref|XP_002176526.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
MKSVLCGVTLACGGIWQANSFTFRPLPVTRPVIGLLATLDRVNEKSTVEPS---------
------------------------------------------------------------
------------------------------------------------------------
----------------------SGDPQLQPIRRLRQNKKEPLIAIVGRPNVGKSALVNRI
A--------GSQSGGAIVADESGITRDRTYRPAEFLGERFMI-------VDTGGLVFDDD
ESTLFAKEI------------------------------------R--------------
------------------------------------------------------------
-EQAMVAIEESAA----VIMVVDGQTGLTGMDLM-IAEFLRKEV-------------DIP
VHVAVNKCESEKTGAMSA-------------------ADFWGLGL---------------
----------GEPFPVSALHGV-----------------------GTAEIMETIFDSIAE
KKT--------------FD--------AE-D----RPEEINIAIIGRPNVGKSSLLNSIF
GDT-------RAIVSEMAGTTRDSIDAVMERPPPPGSDDLS-----TIYRFVDTAGIRRK
GKV----DFGPE--FFMVNRALRA-----IRRAD----VVLLILDATSG--VAEQDRVLA
QKIADDG--------------------------------------------RACVIVCNK
WDAV-VDKDSTTYDKSV------------------QYFREELPMIRW-------------
--------------APILFISAA--TGQRV---------GKIYSAID----------GAI
EAHRKRISTAILNEVLRDAILWQPPPT--------RRNGSQAKIYYCNQVSTR-------
-----------------------PPTVV--------------------------------
VFCNDPKL------VNDNYRRYLDRKFRESLDGF------EATP----------------
--------------------------IRWIFRGRRVRDVMRNRSMNGDPGDGGTGVSFPF
PHAD
>Toc159_T.pseudonana_gnl|BL_ORD_ID|5653 gi|223994975|ref|XP_002287171.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------PLIAVVGRPNVGKSALVNRL
A--------GTQSGGAIVADEEGITRDRTYRNAEFLGEAFQL-------VDTGGLVFDDN
DA-LFAKEI------------------------------------R--------------
------------------------------------------------------------
-EQAMIAIEESAG----VILVVDGQMGPTSMDEQ-LAIFLRKEVL-K----------KMP
VILAVNKCESDKNGAYLA-------------------SQFWNLGL---------------
----------GEPFAVSALHGV-----------------------GTAEVMEKMFDDIA-
-KP--------------LD--------GEDD----TDEEINVAIIGRPNVGKSSLINTIF
GSN-------RAIVSDVAGTTRDSIDAIMER-PSSDPEGLP-----TIYRFVDTAGIRRK
GKI----EFGPE--FFMVNRALRA-----IRRAD----VVLLVLDATAG--VTEQDRVLA
QKISDDG--------------------------------------------RACVILCNK
WDAV-IDKDSSTYDQSV------------------KYFREELPQIRW-------------
--------------APILFVSAA--TGQRV---------GKIYEAVD----------SAV
NAHRRRISTSVLNEVLRDATLWQPPPA--------RRNGAQAKIYYGSQVSTR-------
-----------------------PPTIV--------------------------------
VFVNDPNL------INDNYKRYLDRKMRESLDGF------ESTP----------------
--------------------------IRWMFRGRRVRDVTRNM-----------------
----
>Toc159_F.cylindrus_GMF2_gnl|BL_ORD_ID|13890 jgi|Fracy1|147902|gw1.4.359.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SNFTVSILGPPNAGKSTLFNRL
QCKERNRAKHTSKGNAIVSSIAGTTRDRRECWGRIGGTEFTL-------MDTAGI--DGD
RIQALAGKSKSEKHA--LERA-----------------------MM--------------
------------------------------------------------------------
-EQTLEAAKKSDL----VLLLWDARIGVSQDLLI-TARWLRKLGKHS------------N
VSLIANKLEGDSWAHDEDSIVMENLRDVLRLGL---------------------------
----------GNAIPISALQGD------------------------GLADIAILIEKLKT
EKEAKYNQENYSTDTTTAN-EISENNSGKDG----DQKPLQIAIIGRQNVGKSTLVNRLL
KSD-------RVLTGSTPGLTRDAIAVEWDWDG-------------QLVQLVDTAGIRKL
TKRMQMDDDSIE--DQSVADALRA-----MKVAE----VAVLVLDAKEL-FIQRQELAIC
NAVLNEG--------------------------------------------RALVIAANK
MDLIEMSSTYTSRDFAN---------------SVREQIESRIPILRN-------------
--------------IPIVPMSCI--SGKGI---------EHVLPAAL----------DAR
NRWARTISTGLLNRWLAEVVTGLQPPY---------VAGVRAKLKYIIQTKGR-------
-----------------------PPTFI--------------------------------
IFSNVKS-------FPEPYLRYLTRQFQDSFELYGMPVRL--------------------
------------------------------------------------------------
----
>Toc34_F.cylindrus_GMF2_gnl|BL_ORD_ID|13890 jgi|Fracy1|147902|gw1.4.359.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SNFTVSILGPPNAGKSTLFNRL
QCKERNRAKHTSKGNAIVSSIAGTTRDRRECWGRIGGTEFTL-------MDTAGI--DGD
RIQALAGKSKSEKHA--LERA-----------------------MM--------------
------------------------------------------------------------
-EQTLEAAKKSDL----VLLLWDARIGVSQDLLI-TARWLRKLGKHS------------N
VSLIANKLEGDSWAHDEDSIVMENLRDVLRLGL---------------------------
----------GNAIPISALQGD------------------------GLADIAILIEKLKT
EKEAKYNQENYSTDTTTAN-EISENNSGKDG----DQKPLQIAIIGRQNVGKSTLVNRLL
KSD-------RVLTGSTPGLTRDAIAVEWDWDG-------------QLVQLVDTAGIRKL
TKRMQMDDDSIE--DQSVADALRA-----MKVAE----VAVLVLDAKEL-FIQRQELAIC
NAVLNEG--------------------------------------------RALVIAANK
MDLIEMSSTYTSRDFAN---------------SVREQIESRIPILRN-------------
--------------IPIVPMSCI--SGKGI---------EHVLPAAL----------DAR
NRWARTISTGLLNRWLAEVVTGLQPPY---------VAGVRAKLKYIIQTKGR-------
-----------------------PPTFI--------------------------------
IFSNVKS-------FPEPYLRYLTRQFQDSFELYGMPVRL--------------------
------------------------------------------------------------
----
>Toc159_P.tricornutum_gnl|BL_ORD_ID|5109 gi|219124383|ref|XP_002182484.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SRIVVSILGPPNAGKSTLFNRL
LDKAANRA-----GTAIVSNVPGTTRDRRECVGRIGGTLFRL-------VDTAGV--DGE
RLELLAQSRRNQNGEGILMKF-----------------------MM--------------
------------------------------------------------------------
-GQTLEAARQADL----VFLMFDARVGVTADLLE-TARWLRKISQREQDPAAQTALPDRQ
IFLLANKLEGDFWNFD-GSIVLDHLTEATRLGF---------------------------
----------GEAIPISAHHGE------------------------GLADIAVLIEQAAV
AKRQSLGILDDDTD-------LASNDSD-------KDKPLQLAILGRQNVGKSTLVNALL
KQD-------RVIVGATPGLTRDAIAVEWTWKN-------------RPVQIVDTAGIRKR
SQRNH--EDAIE--DLSVEDALRA-----MKVAD----VAVLVLDAEAR-KLQRQELAIA
DAVLKEG--------------------------------------------RALVVAANK
MDLI-VERGYSKKDFAE---------------DVRAQLEARYPILRK-------------
--------------TPIVPMSSL--TGDSV---------HKLMPVVF----------RAR
ERWSRKISTGELNRWIAEVMDGKPPPP---------VSGRKARIKYVMQTKGR-------
-----------------------PPTFL--------------------------------
LFCNVAS-------LPENYLRFLTRNFQDTFEMFGMEVRM--------------------
------------------------------------------------------------
----
>Toc34_P.tricornutum_gnl|BL_ORD_ID|5109 gi|219124383|ref|XP_002182484.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SRIVVSILGPPNAGKSTLFNRL
LDKAANRA-----GTAIVSNVPGTTRDRRECVGRIGGTLFRL-------VDTAGV--DGE
RLELLAQSRRNQNGEGILMKF-----------------------MM--------------
------------------------------------------------------------
-GQTLEAARQADL----VFLMFDARVGVTADLLE-TARWLRKISQREQDPAAQTALPDRQ
IFLLANKLEGDFWNFD-GSIVLDHLTEATRLGF---------------------------
----------GEAIPISAHHGE------------------------GLADIAVLIEQAAV
AKRQSLGILDDDTD-------LASNDSD-------KDKPLQLAILGRQNVGKSTLVNALL
KQD-------RVIVGATPGLTRDAIAVEWTWKN-------------RPVQIVDTAGIRKR
SQRNH--EDAIE--DLSVEDALRA-----MKVAD----VAVLVLDAEAR-KLQRQELAIA
DAVLKEG--------------------------------------------RALVVAANK
MDLI-VERGYSKKDFAE---------------DVRAQLEARYPILRK-------------
--------------TPIVPMSSL--TGDSV---------HKLMPVVF----------RAR
ERWSRKISTGELNRWIAEVMDGKPPPP---------VSGRKARIKYVMQTKGR-------
-----------------------PPTFL--------------------------------
LFCNVAS-------LPENYLRFLTRNFQDTFEMFGMEVRM--------------------
------------------------------------------------------------
----
>Toc159_F.cylindrus_GMF1_gnl|BL_ORD_ID|25599 jgi|Fracy1|214794|estExt_Genewise1Plus.C_700009
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------SEDIVAEFS
SKAGGGYNRPGVQWYPGHIAK-----------------------AE--------------
------------------------------------------------------------
-RQLSETLKAVDV----VVEVRDARACKATSHPR-----------------VGEWCAGRP
RIVVLTHLDMIPKAAANSWRKAYEKFGAEDMDDAPIN-----------------------
----------RQVLFVNAKQGQ-----------------GIHALHRAIFKAGSHVQERRE
RRGL-------------------------------NPRALRVGIIGYPNVGKSALINKIL
GRK-------RAKTANTPGVTRSLQWIR-------------------EFELLDSPGIIPA
KMVDQS--------DALLLAACNC-----IGQAA----YDNQAVAAYLY-EWLKAVYLMD
KQALTAPNWRDKCIDRYGFDPLEKVQRDEDDIVQDEYLTGEDMLFKVADD-------LCR
GDAE-DAARKMLQDFRQ-------------------------------------------
---------------------------------------GRMGPISLQMAPESEEDG---
---------------------------GMLSVSVGDGTILGRQSMRGSENGGFDAEYQQQ
IQDE----RARIALETAKERGLELPPIV--------------------------------
-----DDPERA-------KEEAEADVGKGMFDGW--------------------------
------------------------------------------------------------
----
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|25599 jgi|Fracy1|214794|estExt_Genewise1Plus.C_700009
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------SEDIVAEFS
SKAGGGYNRPGVQWYPGHIAK-----------------------AE--------------
------------------------------------------------------------
-RQLSETLKAVDV----VVEVRDARACKATSHPR-----------------VGEWCAGRP
RIVVLTHLDMIPKAAANSWRKAYEKFGAEDMDDAPIN-----------------------
----------RQVLFVNAKQGQ-----------------GIHALHRAIFKAGSHVQERRE
RRGL-------------------------------NPRALRVGIIGYPNVGKSALINKIL
GRK-------RAKTANTPGVTRSLQWIR-------------------EFELLDSPGIIPA
KMVDQS--------DALLLAACNC-----IGQAA----YDNQAVAAYLY-EWLKAVYLMD
KQALTAPNWRDKCIDRYGFDPLEKVQRDEDDIVQDEYLTGEDMLFKVADD-------LCR
GDAE-DAARKMLQDFRQ-------------------------------------------
---------------------------------------GRMGPISLQMAPESEEDG---
---------------------------GMLSVSVGDGTILGRQSMRGSENGGFDAEYQQQ
IQDE----RARIALETAKERGLELPPIV--------------------------------
-----DDPERA-------KEEAEADVGKGMFDGW--------------------------
------------------------------------------------------------
----
>Toc159_T.oceanica_gnl|BL_ORD_ID|10226 gi|397601583|gb|EJK57948.1| hypothetical protein THAOC_21972 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------EDPN
SFSLSGYQRPKVNWYPGHIAK-----------------------AE--------------
------------------------------------------------------------
-RQLAETLKSVDV----VIEVRDSRAPKATAHPS-----------------VGKWAAGRP
RVVVLTRVDTVTTRSRETWRQAYERLGADRWQEKLAGDERNRNAQFETERRKYVDGEDGD
SVKLRGADGVEEVLFVDAKRGQ-----------------GTHAITRAVYRAGRHVNERRK
RRGL-------------------------------NDRSLRVGIIGFPNVGKSALINRLL
GRK-------RAKTANTPGITRSLQWMRVAADKSTSASGSGSANAKKGFELLDSPGIIPS
DMLDQN--------DALLLAACNS-----VGVGA-------KIAARWGS-ESTDGSARSW
LDFAAKNADRMPSGE--------------------------DMLFIVADN-------TCK
GDPE-NAARKILQDFRN-------------------------------------------
---------------------------------------GRMGPVSLQLAPESETDE---
---------------------------GQVHVENMRSDGLDVRIVASPTNLKRATEEHEK
RQKEEIQQRAKAAMVAAKQKGLDLPPVV--------------------------------
ESIDVDDTEQVAAGGGADSKPSESEIGKGLFDGW--------------------------
------------------------------------------------------------
----
>Toc34_T.oceanica_gnl|BL_ORD_ID|10226 gi|397601583|gb|EJK57948.1| hypothetical protein THAOC_21972 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------EDPN
SFSLSGYQRPKVNWYPGHIAK-----------------------AE--------------
------------------------------------------------------------
-RQLAETLKSVDV----VIEVRDSRAPKATAHPS-----------------VGKWAAGRP
RVVVLTRVDTVTTRSRETWRQAYERLGADRWQEKLAGDERNRNAQFETERRKYVDGEDGD
SVKLRGADGVEEVLFVDAKRGQ-----------------GTHAITRAVYRAGRHVNERRK
RRGL-------------------------------NDRSLRVGIIGFPNVGKSALINRLL
GRK-------RAKTANTPGITRSLQWMRVAADKSTSASGSGSANAKKGFELLDSPGIIPS
DMLDQN--------DALLLAACNS-----VGVGA-------KIAARWGS-ESTDGSARSW
LDFAAKNADRMPSGE--------------------------DMLFIVADN-------TCK
GDPE-NAARKILQDFRN-------------------------------------------
---------------------------------------GRMGPVSLQLAPESETDE---
---------------------------GQVHVENMRSDGLDVRIVASPTNLKRATEEHEK
RQKEEIQQRAKAAMVAAKQKGLDLPPVV--------------------------------
ESIDVDDTEQVAAGGGADSKPSESEIGKGLFDGW--------------------------
------------------------------------------------------------
----
>Toc159_T.pseudonana_gnl|BL_ORD_ID|2716 gi|223994459|ref|XP_002286913.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------PKVNWYPGHIAK-----------------------AE--------------
------------------------------------------------------------
-RQLSETLKSVDV----VIEVRDSRAPKATAHPS-----------------VGKWTAGRP
RVVVLTRMDTVTSRSRDSWREAYERLGADRWEDSLV------------------------
----------EEILFVDAKRGQ-----------------GTHAISRAVYKAGRHVNERRK
RRGL-------------------------------NDRPLRVGIIGFPNVGKSALINRLL
GKK-------RARTANTPGITRSLQWIR------------------SGFELLDSPGIIPS
DMLDQS--------DALLLAACNS-----IGVGA----YDNQAVAAYLC-ERIQSLVIME
KDYIAAPLWRNRCIERYGFDPL-------------------DMLFIVADN-------TCK
GDPE-NAARKILQDFRM-------------------------------------------
---------------------------------------GRMGPISLQL-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc34_T.pseudonana_gnl|BL_ORD_ID|2716 gi|223994459|ref|XP_002286913.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------PKVNWYPGHIAK-----------------------AE--------------
------------------------------------------------------------
-RQLSETLKSVDV----VIEVRDSRAPKATAHPS-----------------VGKWTAGRP
RVVVLTRMDTVTSRSRDSWREAYERLGADRWEDSLV------------------------
----------EEILFVDAKRGQ-----------------GTHAISRAVYKAGRHVNERRK
RRGL-------------------------------NDRPLRVGIIGFPNVGKSALINRLL
GKK-------RARTANTPGITRSLQWIR------------------SGFELLDSPGIIPS
DMLDQS--------DALLLAACNS-----IGVGA----YDNQAVAAYLC-ERIQSLVIME
KDYIAAPLWRNRCIERYGFDPL-------------------DMLFIVADN-------TCK
GDPE-NAARKILQDFRM-------------------------------------------
---------------------------------------GRMGPISLQL-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc159_P.tricornutum_gnl|BL_ORD_ID|9646 gi|219116036|ref|XP_002178813.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------PRSQGTSRKGKPGKKDRDAGMGKSLQRAQVQRYRPRADGKSRRGDGGMHMQA
GVDSIGLEEAQQDQLKTRSVLEMQDLDDFLLQADMANREFVS-------EKEGLVVVDQT
GQAYRPPAVQWADQKSSFLFT-----------------------ELSVPRRPAWDDTTTA
VELDMNERKSFLEWRRA-----------------IAIKEEELARTSSLAAATPFEKNLEV
WRQLWRVLERSAC----LLQLVDARNPMFY-----LSDDLRDYASTL----------GKP
MMVLVNKSDYLSPSQRASWREYLMEKGWDPVFFSAVKEQQKLDAMA--------------
---------NRKRIQVQLGTGH------------DNSLDHLGEETDVSIDAHDQIEEPED
ERGVSVPLSRERLMETMLSFARQHNCQPDPR----YDNRIQFGMVGFPNVGKSSVINVLF
GSSKHEHGVVRVAVASQPGKTKHFQTLMLPDA--------------EEMMLCDCPGLVFP
SFVSNT--------ADLIAAGVYP-----IAQMRDHWPVTNLICQRIPR-EVINAHYGIV
LPKPSQLEMNERGLTK------------------LPPPSGEEFLGTFCIARGMLAASSGV
PDYT-RAARTIIKDYAD-------------------------------------------
---------------------------------------GKLLYCHPPPS----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc34_P.tricornutum_gnl|BL_ORD_ID|9646 gi|219116036|ref|XP_002178813.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------PRSQGTSRKGKPGKKDRDAGMGKSLQRAQVQRYRPRADGKSRRGDGGMHMQA
GVDSIGLEEAQQDQLKTRSVLEMQDLDDFLLQADMANREFVS-------EKEGLVVVDQT
GQAYRPPAVQWADQKSSFLFT-----------------------ELSVPRRPAWDDTTTA
VELDMNERKSFLEWRRA-----------------IAIKEEELARTSSLAAATPFEKNLEV
WRQLWRVLERSAC----LLQLVDARNPMFY-----LSDDLRDYASTL----------GKP
MMVLVNKSDYLSPSQRASWREYLMEKGWDPVFFSAVKEQQKLDAMA--------------
---------NRKRIQVQLGTGH------------DNSLDHLGEETDVSIDAHDQIEEPED
ERGVSVPLSRERLMETMLSFARQHNCQPDPR----YDNRIQFGMVGFPNVGKSSVINVLF
GSSKHEHGVVRVAVASQPGKTKHFQTLMLPDA--------------EEMMLCDCPGLVFP
SFVSNT--------ADLIAAGVYP-----IAQMRDHWPVTNLICQRIPR-EVINAHYGIV
LPKPSQLEMNERGLTK------------------LPPPSGEEFLGTFCIARGMLAASSGV
PDYT-RAARTIIKDYAD-------------------------------------------
---------------------------------------GKLLYCHPPPS----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc159_F.cylindrus_GMF1_gnl|BL_ORD_ID|22594 jgi|Fracy1|214636|estExt_Genewise1Plus.C_650061
M-----------------------------------------------------------
------------------------------------------------------------
------------------AP------KYQNKTKRRENAIPRTGASSKI--GKGRDNAKGG
HRSAETIKRLNLYKS-RAIRNKKGTIIGGDFMMGDRAGDRDITGETGRIAPDRRWFGNTR
VVDPKQLDTFRQEMTEKVADPYSVVLKRKKLPMGLLREAAEREA-----PPSQALLGQEP
FSQVFGSKSRRKKVKLDQLML-----------------------ARSDVDPNKDEDED--
-----GAPI-------------------------KKGG-----RAEVKADLFNKGQSKRI
WGEFFKVVDCSDV----VLHIIDARNVPGTRCNM-------------IERHIRDNASHKH
LVFVLNKIDLVPNWVAKRWMGELAKD----------------------------------
----------RPTIAFHASMTH-------------------------AFGKGALISLLRQ
FGKLHG-----------------------------DKKQISVGVIGYPNVGKSSVINTLI
SQK-------SCKVAPIPGETKIWQYITLF----------------KRISLIDCPGVVVD
TAGDTETESV----LKGVVRAERL-----ETPED----FIQPIVDMVKR-EHIAGQYKFT
KE------------------------------ESNKWTTPTELLETIATK-AGRLLKGGE
PCLR-SASITMINDFQR-------------------------------------------
---------------------------------------GRLPHFVAPPELKEDDVEENQ
GNMGGSTAVIEGVKPEAQEL-----------DKI----GEENTKSDGTVDGESDQKEG--
------------KETGSSGVVADEPVAIAEGEWDD-------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc34_F.cylindrus_GMF1_gnl|BL_ORD_ID|22594 jgi|Fracy1|214636|estExt_Genewise1Plus.C_650061
M-----------------------------------------------------------
------------------------------------------------------------
------------------AP------KYQNKTKRRENAIPRTGASSKI--GKGRDNAKGG
HRSAETIKRLNLYKS-RAIRNKKGTIIGGDFMMGDRAGDRDITGETGRIAPDRRWFGNTR
VVDPKQLDTFRQEMTEKVADPYSVVLKRKKLPMGLLREAAEREA-----PPSQALLGQEP
FSQVFGSKSRRKKVKLDQLML-----------------------ARSDVDPNKDEDED--
-----GAPI-------------------------KKGG-----RAEVKADLFNKGQSKRI
WGEFFKVVDCSDV----VLHIIDARNVPGTRCNM-------------IERHIRDNASHKH
LVFVLNKIDLVPNWVAKRWMGELAKD----------------------------------
----------RPTIAFHASMTH-------------------------AFGKGALISLLRQ
FGKLHG-----------------------------DKKQISVGVIGYPNVGKSSVINTLI
SQK-------SCKVAPIPGETKIWQYITLF----------------KRISLIDCPGVVVD
TAGDTETESV----LKGVVRAERL-----ETPED----FIQPIVDMVKR-EHIAGQYKFT
KE------------------------------ESNKWTTPTELLETIATK-AGRLLKGGE
PCLR-SASITMINDFQR-------------------------------------------
---------------------------------------GRLPHFVAPPELKEDDVEENQ
GNMGGSTAVIEGVKPEAQEL-----------DKI----GEENTKSDGTVDGESDQKEG--
------------KETGSSGVVADEPVAIAEGEWDD-------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc159_P.tricornutum_gnl|BL_ORD_ID|6857 gi|219112187|ref|XP_002177845.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------AKTGWKSGISNTSSAGKTNRTPKGNASSKLTQGRRRDKQPGS
ERSAETIQRLKMYSNGKAIRNKAGKIVAGTFMMQDRAGDRKIEASTGRIQPDRRWFGNTR
VVGATELDRFRQEMTEKVADPYSVVLKRKKLPMGLLQDAAEYKAG----NQKAALLEQEP
FDQAFGKNSRRKRVKLDQLFV-----------------------QRAAESADSKEDIKTG
E----GEAI-------------------------RSEGEGIDWRHEKKDDLFLKGQSKRI
WGEFFKVVDCSDV----VLHIIDARNVPGTRCTM-------------IERHIAKNASHKH
LVFVLNKIDLVPNWVAKRWMGELAAV----------------------------------
----------RPTIAFHASLTN-------------------------AFGKGALISLLRQ
FGKLHE-----------------------------DKKQISVGVIGYPNVGKSSVINTLI
SKK-------SCKVAPIPGETKIWQYVTLF----------------KRISLIDCPGVVVD
TAGDTEEDSV----LKGVVRAERL-----ENPED----FIDAIMGKVKR-EHIAAQYKLP
KD------------------------------GEETWSSSGELMEMIARR-SGRLLKGGD
PCIR-TAALMIINDFQR-------------------------------------------
---------------------------------------GRLPHFIPPPELKVEEDQ---
----KTVATEQAIQIEEQNL-----------DDVVVVEKEMEQDEEGVETKTNDHAAI--
------------ADTET--VIDTSSILIGDGKWDE-------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc34_P.tricornutum_gnl|BL_ORD_ID|6857 gi|219112187|ref|XP_002177845.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------AKTGWKSGISNTSSAGKTNRTPKGNASSKLTQGRRRDKQPGS
ERSAETIQRLKMYSNGKAIRNKAGKIVAGTFMMQDRAGDRKIEASTGRIQPDRRWFGNTR
VVGATELDRFRQEMTEKVADPYSVVLKRKKLPMGLLQDAAEYKAG----NQKAALLEQEP
FDQAFGKNSRRKRVKLDQLFV-----------------------QRAAESADSKEDIKTG
E----GEAI-------------------------RSEGEGIDWRHEKKDDLFLKGQSKRI
WGEFFKVVDCSDV----VLHIIDARNVPGTRCTM-------------IERHIAKNASHKH
LVFVLNKIDLVPNWVAKRWMGELAAV----------------------------------
----------RPTIAFHASLTN-------------------------AFGKGALISLLRQ
FGKLHE-----------------------------DKKQISVGVIGYPNVGKSSVINTLI
SKK-------SCKVAPIPGETKIWQYVTLF----------------KRISLIDCPGVVVD
TAGDTEEDSV----LKGVVRAERL-----ENPED----FIDAIMGKVKR-EHIAAQYKLP
KD------------------------------GEETWSSSGELMEMIARR-SGRLLKGGD
PCIR-TAALMIINDFQR-------------------------------------------
---------------------------------------GRLPHFIPPPELKVEEDQ---
----KTVATEQAIQIEEQNL-----------DDVVVVEKEMEQDEEGVETKTNDHAAI--
------------ADTET--VIDTSSILIGDGKWDE-------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc159_T.oceanica_gnl|BL_ORD_ID|1577 gi|397642458|gb|EJK75246.1| hypothetical protein THAOC_03037 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------VKTGYKF-TKQQPNKGSRNMLKNSAASSRPNRTAPKRGDNGN
MRSNQTIARLKMYNNGKAIRNKEGKVVGGQFMMGDRAGDTKITAATGRIAPDRRWFGNTR
VVNPTELDRFREEMTSSMADPYSVVVKRKQLPMGLLRDAAELE-KAGRNNS--GLLANEP
FEHTFGGKSRRKRVKMEQYMVGRTSKIDDVEDKDEEDDQKPYRGGEAETVNDMPSDDKSG
YAALLAAAQKSQDTYSKVNNRVGIVPWGKDSNLTKTSGEGVDWVHSKKDDLFLKGQSKRI
WGEFYKVVDCSDV----ILHVIDARNVPGTRCTM-------------IEKHIAKNAPHKH
LVFVLNKIDLVPNWVAKRWIGELAQI----------------------------------
----------RPTIAFHASMTH-------------------------AFGKGALISLLRQ
FGKLNS-----------------------------DKKQISVGVIGYPNVGKSSVINTLI
SKK-------SCKVAPIPGETKIWQYITLF----------------RNIYLIDCPGVVVD
TAGDSETDSV----LKGVVRSERL-----ETPED----YVDAIQDAVKR-EHIAAMYGLP
RS------------------------------GEDTWKSSEELCEKIAIK-CGRLRKGGE
PCLR-SAAIMIINDFQR-------------------------------------------
---------------------------------------GRLPHYVAPPELKEEDSGEGA
AAV-ADTANIEGVELAAQNL-----------DEVTRDRAEDSAEGQRSDTKEETSEKIEK
KDGIAEDAGDVEADEDA--GSDDDEVVIGDGDWE--------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc34_T.oceanica_gnl|BL_ORD_ID|1577 gi|397642458|gb|EJK75246.1| hypothetical protein THAOC_03037 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
------------------VKTGYKF-TKQQPNKGSRNMLKNSAASSRPNRTAPKRGDNGN
MRSNQTIARLKMYNNGKAIRNKEGKVVGGQFMMGDRAGDTKITAATGRIAPDRRWFGNTR
VVNPTELDRFREEMTSSMADPYSVVVKRKQLPMGLLRDAAELE-KAGRNNS--GLLANEP
FEHTFGGKSRRKRVKMEQYMVGRTSKIDDVEDKDEEDDQKPYRGGEAETVNDMPSDDKSG
YAALLAAAQKSQDTYSKVNNRVGIVPWGKDSNLTKTSGEGVDWVHSKKDDLFLKGQSKRI
WGEFYKVVDCSDV----ILHVIDARNVPGTRCTM-------------IEKHIAKNAPHKH
LVFVLNKIDLVPNWVAKRWIGELAQI----------------------------------
----------RPTIAFHASMTH-------------------------AFGKGALISLLRQ
FGKLNS-----------------------------DKKQISVGVIGYPNVGKSSVINTLI
SKK-------SCKVAPIPGETKIWQYITLF----------------RNIYLIDCPGVVVD
TAGDSETDSV----LKGVVRSERL-----ETPED----YVDAIQDAVKR-EHIAAMYGLP
RS------------------------------GEDTWKSSEELCEKIAIK-CGRLRKGGE
PCLR-SAAIMIINDFQR-------------------------------------------
---------------------------------------GRLPHYVAPPELKEEDSGEGA
AAV-ADTANIEGVELAAQNL-----------DEVTRDRAEDSAEGQRSDTKEETSEKIEK
KDGIAEDAGDVEADEDA--GSDDDEVVIGDGDWE--------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc159_T.pseudonana_gnl|BL_ORD_ID|4381 gi|224003191|ref|XP_002291267.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------KADSN
MRSSATIARLKMYNNGKAIRNKEGKVVGGQFMMADRAGDSKITAATGRIAPDRRWFGNTR
VVAPTELDAFREEMTQSMADPYSVVIKRKQLPMGLLKDAAELQAKHGGTNSSAGLLLNEP
FEHAFGTKSRRKRVKVEQFMV-----------------------GNAETLANLPDDDATG
YKSLLAAAQ-------------------------KTSGEGVDWRTEKKDDLFLKGQSKRI
WGEFYKVLDCSDV----ILHIIDARNVPGTRCTM-------------IEKHIAKNAPHKH
LVFVLNKIDLVPNWVAKRWIGELAQI----------------------------------
----------RPTIAFHASMTH-------------------------AFGKGALISLLRQ
FGKLAS-----------------------------DKKQISVGVIGYPNVGKSSVINTLI
SKK-------SCKVAPVPGETKIWQYITLF----------------RNIYLIDCPGVVVD
TAGDTEIDSV----LKGDVRAERL-----ECPED----FIDAIQAAVKR-EHIAAMYGVP
KS------------------------------GDDTWSTSIELLEKISIK-CGRLKKGGE
PCLR-SSAITLINDFQR-------------------------------------------
---------------------------------------GRLPHYVAPPE----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc34_T.pseudonana_gnl|BL_ORD_ID|4381 gi|224003191|ref|XP_002291267.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------KADSN
MRSSATIARLKMYNNGKAIRNKEGKVVGGQFMMADRAGDSKITAATGRIAPDRRWFGNTR
VVAPTELDAFREEMTQSMADPYSVVIKRKQLPMGLLKDAAELQAKHGGTNSSAGLLLNEP
FEHAFGTKSRRKRVKVEQFMV-----------------------GNAETLANLPDDDATG
YKSLLAAAQ-------------------------KTSGEGVDWRTEKKDDLFLKGQSKRI
WGEFYKVLDCSDV----ILHIIDARNVPGTRCTM-------------IEKHIAKNAPHKH
LVFVLNKIDLVPNWVAKRWIGELAQI----------------------------------
----------RPTIAFHASMTH-------------------------AFGKGALISLLRQ
FGKLAS-----------------------------DKKQISVGVIGYPNVGKSSVINTLI
SKK-------SCKVAPVPGETKIWQYITLF----------------RNIYLIDCPGVVVD
TAGDTEIDSV----LKGDVRAERL-----ECPED----FIDAIQAAVKR-EHIAAMYGVP
KS------------------------------GDDTWSTSIELLEKISIK-CGRLKKGGE
PCLR-SSAITLINDFQR-------------------------------------------
---------------------------------------GRLPHYVAPPE----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc159_T.oceanica_gnl|BL_ORD_ID|33149 gi|397569214|gb|EJK46603.1| hypothetical protein THAOC_34725 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------VKKKGKSKRI
TLKDKYKIQRRVVETHRKNRKQAKRDAKAGIVRHDKKKD---------PGIPNSWPFKQE
LLQSIQREKERAENRKLEEKERRVNKNGAANLEELVKQANQKKSEFDAKTGSSSAASDDG
IKIVTTSHGQQSRRAYL-------------------------------------------
------------------------------------------------------------
-RSLKTVIESSDV----ILQVLDARDPLGTRISSGIEASILSHF-------------DKR
MVLVMNKIDLIPKKNVSEWLTYLRRS----------------------------------
----------HPTVALKAGTTQSRSNEGGRSSGVGQTKGENALSSSMAVGVDGLLQLLKN
YARANGEKK--------------------------SKTSITVGIIGYPNVGKSSILNSLK
RFR-------AVGVSSRPGFTTTLQEVVLD----------------KNIRLIDSPGVVFD
DDASRDGA------NAMLRNGVDA-----DSVSD-PLPAIAELLGRCTS-ESLMMTYSVP
A-------------------------------FPPGPEGVLTFLAMVARS-KGRVLKGGI
PDKM-MAARLVMRDWNQ-------------------------------------------
---------------------------------------GKIPYFSTPPVTEVEMGDTSA
GSTHAKIVSKFSEEFDVSKI----------------MAAHDKELMNGLEDVDEMDFVQMT
SSSRPRGEGSADKVVK--------------------------------------------
YLHEGGDQNSDSEMEGDDDAVALNTRMEEAEDFFGE------------------------
------------------------------------------------------------
----
>Toc34_T.oceanica_gnl|BL_ORD_ID|33149 gi|397569214|gb|EJK46603.1| hypothetical protein THAOC_34725 [Thalassiosira oceanica]
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------VKKKGKSKRI
TLKDKYKIQRRVVETHRKNRKQAKRDAKAGIVRHDKKKD---------PGIPNSWPFKQE
LLQSIQREKERAENRKLEEKERRVNKNGAANLEELVKQANQKKSEFDAKTGSSSAASDDG
IKIVTTSHGQQSRRAYL-------------------------------------------
------------------------------------------------------------
-RSLKTVIESSDV----ILQVLDARDPLGTRISSGIEASILSHF-------------DKR
MVLVMNKIDLIPKKNVSEWLTYLRRS----------------------------------
----------HPTVALKAGTTQSRSNEGGRSSGVGQTKGENALSSSMAVGVDGLLQLLKN
YARANGEKK--------------------------SKTSITVGIIGYPNVGKSSILNSLK
RFR-------AVGVSSRPGFTTTLQEVVLD----------------KNIRLIDSPGVVFD
DDASRDGA------NAMLRNGVDA-----DSVSD-PLPAIAELLGRCTS-ESLMMTYSVP
A-------------------------------FPPGPEGVLTFLAMVARS-KGRVLKGGI
PDKM-MAARLVMRDWNQ-------------------------------------------
---------------------------------------GKIPYFSTPPVTEVEMGDTSA
GSTHAKIVSKFSEEFDVSKI----------------MAAHDKELMNGLEDVDEMDFVQMT
SSSRPRGEGSADKVVK--------------------------------------------
YLHEGGDQNSDSEMEGDDDAVALNTRMEEAEDFFGE------------------------
------------------------------------------------------------
----
>Toc159_F.cylindrus_GMF2_gnl|BL_ORD_ID|13155 jgi|Fracy1|162596|gw1.1.2020.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EVAFLGRSNVGKSSLINAIM
RKN-------LCITSKSPGRTQLPYYYGNPSGQ-------------PQGFIVDLPGYGFA
KKPMSITEDWQKDTQDLLLHRRHE-----AKVLK----RLFLLMDARRGVQGPNEHDRIV
MRWLEDAE-------------------------------------------IPFTVVLTK
ADRV-S------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc34_F.cylindrus_GMF2_gnl|BL_ORD_ID|13155 jgi|Fracy1|162596|gw1.1.2020.1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EVAFLGRSNVGKSSLINAIM
RKN-------LCITSKSPGRTQLPYYYGNPSGQ-------------PQGFIVDLPGYGFA
KKPMSITEDWQKDTQDLLLHRRHE-----AKVLK----RLFLLMDARRGVQGPNEHDRIV
MRWLEDAE-------------------------------------------IPFTVVLTK
ADRV-S------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Toc159_Cyanidioschyzon_merolae_gnl|BL_ORD_ID|3128 _gnl|CMER|CMP284C similar to chloroplast outer membrane protein Toc34
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------DSETPTKNEA
EQRASPDRTGQVTQRPVSLFR-----------------------KN--------------
------------------------------------------------------------
-GTFAYPLEDSDVYEEQVLALEDVPEPTAQAILRLALAAERQ------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------GVPRLRFLVVGAPGVGKSSLINTLL
NEN-------LCSVSAWERGTKNAQVCARQVDS-------------VVIEFIDTPGIAPC
RRSGLEASRRQVQRLRKLLDARGADEHPYLRSFH----AILYVMRLDDT-----------
-----------------------------------------------------------R
PDLVDYHNWKVLMEFFGAEVLRHMMVVFTHGQSLPPDSLSYPEYVRGRR-----------
---------------------------------------DYVYLLIERLTGPLKAVRFPV
FVAENSSKCPVIEETGERKLPDDTPWITQLYDGIRRFVFPLEADLFGMETGPEDTQVLVY
IYDKRRSRADERYPRSPLQALIRNPWFLRAVQFCGAMLLRSYMIRQEHERFNPKPHHPEP
IIRDANNAFAVASRRANDHRLFTPSIDEDEESFFRMNGNDDFVSRLRNRPGEVDLDELDV
ERIESPDGRFVEYWYTEKDNPEMVRMYRLEIRDDPNEERESRQDRIPISKDQH-------
----
>Toc34_C.merolae gi|449018483|dbj|BAM81885.1| similar to chloroplast outer membrane protein Toc34 [Cyanidioschyzon merolae strain 10D]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------DSETPTKNEA
EQRASPDRTGQVTQRPVSLFR-----------------------KN--------------
------------------------------------------------------------
-GTFAYPLEDSDVYEEQVLALEDVPEPTAQAILRLALAAERQ------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------GVPRLRFLVVGAPGVGKSSLINTLL
NEN-------LCSVSAWERGTKNAQVCARQVDS-------------VVIEFIDTPGIAPC
RRSGLEASRRQVQRLRKLLDARGADEHPYLRSFH----AILYVMRLDDT-----------
-----------------------------------------------------------R
PDLVDYHNWKVLMEFFGAEVLRHMMVVFTHGQSLPPDSLSYPEYVRGRR-----------
---------------------------------------DYVYLLIERLTGPLKAVRFPV
FVAENSSKCPVIEETGERKLPDDTPWITQLYDGIRRFVFPLEADLFGMETGPEDTQVLVY
IYDKRRSRADERYPRSPLQALIRNPWFLRAVQFCGAMLLRSYMIRQEHERFNPKPHHPEP
IIRDANNAFAVASRRANDHRLFTPSIDEDEESFFRMNGNDDFVSRLRNRPGEVDLDELDV
ERIESPDGRFVEYWYTEKDNPEMVRMYRLEIRDDPNEERESRQDRIPISKDQH-------
----
